== fun_type.move ========================================================
-- test 0 -------------------
use line: 2, use_ndx: 0
Use Def: start: 14, end: 23, def line: 2, def char: 14, no ty info
Def Info: entry fun Macros::fun_type::entry_fun()

-- test 1 -------------------
use line: 5, use_ndx: 0
Use Def: start: 14, end: 23, def line: 5, def char: 14, no ty info
Def Info: macro fun Macros::fun_type::macro_fun()

-- test 2 -------------------
use line: 9, use_ndx: 0
Use Def: start: 8, end: 17, def line: 2, def char: 14, no ty info
Def Info: entry fun Macros::fun_type::entry_fun()

-- test 3 -------------------
use line: 10, use_ndx: 0
Use Def: start: 8, end: 17, def line: 5, def char: 14, no ty info
Def Info: macro fun Macros::fun_type::macro_fun()

== macros.move ========================================================
-- test 0 -------------------
use line: 6, use_ndx: 0
Use Def: start: 14, end: 17, def line: 6, def char: 14, no ty info
Def Info: macro fun Macros::macros::foo($i: u64, $body: |u64| -> u64): u64

-- test 1 -------------------
use line: 6, use_ndx: 1
Use Def: start: 18, end: 20, def line: 6, def char: 18, no ty info
Def Info: $i: u64

-- test 2 -------------------
use line: 6, use_ndx: 2
Use Def: start: 27, end: 32, def line: 6, def char: 27, no ty info
Def Info: $body: |u64| -> u64

-- test 3 -------------------
use line: 14, use_ndx: 0
Use Def: start: 14, end: 17, def line: 14, def char: 14, no ty info
Def Info: macro fun Macros::macros::bar($i: Macros::macros::SomeStruct, $body: |Macros::macros::SomeStruct| -> Macros::macros::SomeStruct): Macros::macros::SomeStruct

-- test 4 -------------------
use line: 14, use_ndx: 1
Use Def: start: 18, end: 20, def line: 14, def char: 18, ty def line: 2, ty def char: 18, 
Def Info: $i: Macros::macros::SomeStruct

-- test 5 -------------------
use line: 14, use_ndx: 2
Use Def: start: 22, end: 32, def line: 2, def char: 18, ty def line: 2, ty def char: 18, 
Def Info: public struct Macros::macros::SomeStruct has drop {
	some_field: u64
}

-- test 6 -------------------
use line: 14, use_ndx: 3
Use Def: start: 34, end: 39, def line: 14, def char: 34, no ty info
Def Info: $body: |Macros::macros::SomeStruct| -> Macros::macros::SomeStruct

-- test 7 -------------------
use line: 14, use_ndx: 4
Use Def: start: 42, end: 52, def line: 2, def char: 18, ty def line: 2, ty def char: 18, 
Def Info: public struct Macros::macros::SomeStruct has drop {
	some_field: u64
}

-- test 8 -------------------
use line: 14, use_ndx: 5
Use Def: start: 57, end: 67, def line: 2, def char: 18, ty def line: 2, ty def char: 18, 
Def Info: public struct Macros::macros::SomeStruct has drop {
	some_field: u64
}

-- test 9 -------------------
use line: 14, use_ndx: 6
Use Def: start: 70, end: 80, def line: 2, def char: 18, ty def line: 2, ty def char: 18, 
Def Info: public struct Macros::macros::SomeStruct has drop {
	some_field: u64
}

-- test 10 -------------------
use line: 18, use_ndx: 0
Use Def: start: 14, end: 22, def line: 18, def char: 14, no ty info
Def Info: macro fun Macros::macros::for_each<$T>($v: &vector<$T>, $body: |&$T| -> ())

-- test 11 -------------------
use line: 18, use_ndx: 1
Use Def: start: 23, end: 25, def line: 18, def char: 23, no ty info
Def Info: $T

-- test 12 -------------------
use line: 18, use_ndx: 2
Use Def: start: 27, end: 29, def line: 18, def char: 27, no ty info
Def Info: let $v: &vector<u64>

-- test 13 -------------------
use line: 18, use_ndx: 3
Use Def: start: 39, end: 41, def line: 18, def char: 23, no ty info
Def Info: $T

-- test 14 -------------------
use line: 18, use_ndx: 4
Use Def: start: 44, end: 49, def line: 18, def char: 44, no ty info
Def Info: $body: |&$T| -> ()

-- test 15 -------------------
use line: 18, use_ndx: 5
Use Def: start: 53, end: 55, def line: 18, def char: 23, no ty info
Def Info: $T

-- test 16 -------------------
use line: 32, use_ndx: 0
Use Def: start: 16, end: 22, def line: 0, def char: 15, no ty info
Def Info: module Macros::macros

-- test 17 -------------------
use line: 32, use_ndx: 1
Use Def: start: 24, end: 27, def line: 6, def char: 14, no ty info
Def Info: macro fun Macros::macros::foo($i: u64, $body: |u64| -> u64): u64

-- test 18 -------------------
use line: 32, use_ndx: 2
Use Def: start: 29, end: 30, def line: 31, def char: 12, no ty info
Def Info: let p: u64

-- test 19 -------------------
use line: 32, use_ndx: 3
Use Def: start: 33, end: 34, def line: 32, def char: 33, no ty info
Def Info: let x: u64

-- test 20 -------------------
use line: 32, use_ndx: 4
Use Def: start: 36, end: 37, def line: 32, def char: 33, no ty info
Def Info: let x: u64

-- test 21 -------------------
use line: 37, use_ndx: 5
Use Def: start: 49, end: 50, def line: 37, def char: 49, no ty info
Def Info: let y: u64

-- test 22 -------------------
use line: 37, use_ndx: 7
Use Def: start: 68, end: 71, def line: 6, def char: 14, no ty info
Def Info: macro fun Macros::macros::foo($i: u64, $body: |u64| -> u64): u64

-- test 23 -------------------
use line: 37, use_ndx: 8
Use Def: start: 73, end: 74, def line: 37, def char: 49, no ty info
Def Info: let y: u64

-- test 24 -------------------
use line: 37, use_ndx: 9
Use Def: start: 77, end: 78, def line: 37, def char: 77, no ty info
Def Info: let z: u64

-- test 25 -------------------
use line: 37, use_ndx: 10
Use Def: start: 80, end: 81, def line: 37, def char: 77, no ty info
Def Info: let z: u64

-- test 26 -------------------
use line: 43, use_ndx: 4
Use Def: start: 48, end: 51, def line: 42, def char: 16, no ty info
Def Info: let mut sum: u64

-- test 27 -------------------
use line: 44, use_ndx: 0
Use Def: start: 8, end: 10, def line: 41, def char: 12, no ty info
Def Info: let es: vector<u64>

-- test 28 -------------------
use line: 44, use_ndx: 1
Use Def: start: 11, end: 16, def line: 18, def char: 14, no ty info
Def Info: macro fun Macros::macros::for_each<$T>($v: &vector<$T>, $body: |&$T| -> ())

-- test 29 -------------------
use line: 51, use_ndx: 2
Use Def: start: 34, end: 44, def line: 2, def char: 18, ty def line: 2, ty def char: 18, 
Def Info: public struct Macros::macros::SomeStruct has drop {
	some_field: u64
}

