error[Sui E02007]: invalid object declaration
   ┌─ tests/sui_mode/linter/no_trigger_lint_missing_key.move:13:9
   │
12 │     struct FP1_HasKeyButDifferentFieldName has key {
   │                                                --- The 'key' ability is used to declare objects in Sui
13 │         uid: UID,
   │         ^^^ Invalid object 'FP1_HasKeyButDifferentFieldName'. Structs with the 'key' ability must have 'id: sui::object::UID' as their first field

error[Sui E02007]: invalid object declaration
   ┌─ tests/sui_mode/linter/no_trigger_lint_missing_key.move:18:9
   │
17 │     struct FP2_HasKeyUIDNotFirst has key {
   │                                      --- The 'key' ability is used to declare objects in Sui
18 │         point: u64,
   │         ^^^^^ Invalid object 'FP2_HasKeyUIDNotFirst'. Structs with the 'key' ability must have 'id: sui::object::UID' as their first field

error[Sui E02007]: invalid object declaration
   ┌─ tests/sui_mode/linter/no_trigger_lint_missing_key.move:24:9
   │
23 │     struct FP3_HasKeyButIDNotUID has key {
   │                                      --- The 'key' ability is used to declare objects in Sui
24 │         id: address,
   │         ^^  ------- But found type: 'address'
   │         │    
   │         Invalid object 'FP3_HasKeyButIDNotUID'. Structs with the 'key' ability must have 'id: sui::object::UID' as their first field

warning[Lint W99007]: The struct's first field is 'id' of type 'sui::object::UID' but is missing the 'key' ability.
   ┌─ tests/sui_mode/linter/no_trigger_lint_missing_key.move:34:5
   │  
34 │ ╭     struct FP5_HasAbilityButNotKey has store, copy, drop {
35 │ │         id: UID,
36 │ │     }
   │ ╰─────^ Struct's first field has an 'id' field of type 'sui::object::UID' but is missing the 'key' ability.
   │  
   = This warning can be suppressed with '#[allow(lint(missing_key))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

error[E05001]: ability constraint not satisfied
   ┌─ tests/sui_mode/linter/no_trigger_lint_missing_key.move:35:13
   │
35 │         id: UID,
   │             ^^^
   │             │
   │             Invalid field type. The struct was declared with the ability 'copy' so all fields require the ability 'copy'
   │             The type 'sui::object::UID' does not have the ability 'copy'
   ·
40 │     struct UID has store {
   │            --- To satisfy the constraint, the 'copy' ability would need to be added here

error[E05001]: ability constraint not satisfied
   ┌─ tests/sui_mode/linter/no_trigger_lint_missing_key.move:35:13
   │
35 │         id: UID,
   │             ^^^
   │             │
   │             Invalid field type. The struct was declared with the ability 'drop' so all fields require the ability 'drop'
   │             The type 'sui::object::UID' does not have the ability 'drop'
   ·
40 │     struct UID has store {
   │            --- To satisfy the constraint, the 'drop' ability would need to be added here

