warning[Lint W00001]: possible owned object share
   ┌─ tests/sui_mode/linter/share_owned.move:15:9
   │
13 │     public entry fun arg_object(o: Obj) {
   │                                 - A potentially owned object coming from here
14 │         let arg = o;
15 │         transfer::public_share_object(arg);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                             │
   │         │                             Creating a fresh object and sharing it within the same function will ensure this does not abort.
   │         Potential abort from a (potentially) owned object created by a different transaction.
   │
   = This warning can be suppressed with '#[allow(lint(share_owned))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W00001]: possible owned object share
   ┌─ tests/sui_mode/linter/share_owned.move:35:9
   │
34 │         let Wrapper { id, i: _, o } = w;
   │                                 - A potentially owned object coming from here
35 │         transfer::public_share_object(o);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                             │
   │         │                             Creating a fresh object and sharing it within the same function will ensure this does not abort.
   │         Potential abort from a (potentially) owned object created by a different transaction.
   │
   = This warning can be suppressed with '#[allow(lint(share_owned))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09008]: unused function
   ┌─ tests/sui_mode/linter/share_owned.move:48:9
   │
48 │     fun private_fun_should_not_be_suppressed() {}
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The non-'public', non-'entry' function 'private_fun_should_not_be_suppressed' is never called. Consider removing it.
   │
   = This warning can be suppressed with '#[allow(unused_function)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09008]: unused function
   ┌─ tests/sui_mode/linter/share_owned.move:52:9
   │
52 │     fun another_private_fun_should_not_be_suppressed() {}
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The non-'public', non-'entry' function 'another_private_fun_should_not_be_suppressed' is never called. Consider removing it.
   │
   = This warning can be suppressed with '#[allow(unused_function)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09009]: unused struct field
   ┌─ tests/sui_mode/linter/share_owned.move:57:9
   │
57 │         id: address,
   │         ^^ The 'id' field of the 'UID' type is unused
   │
   = This warning can be suppressed with '#[allow(unused_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

