processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-55:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8474000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 57-57:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 59-59:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 4 'run'. lines 61-61:
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8664000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'view-object'. lines 63-63:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 6 'run'. lines 65-65:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8664000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'view-object'. lines 67-67:
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 8 'run'. lines 69-69:
mutated: object(0,0), object(2,0)
deleted: object(4,0), object(4,1), object(4,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 8577360, non_refundable_storage_fee: 86640

task 9 'run'. lines 71-71:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 10 'create-checkpoint'. lines 73-73:
Checkpoint created: 1

task 11 'run-graphql'. lines 75-138:
Response: {
  "data": {
    "latest": {
      "version": 6,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDve1Ab2c1fYbmGadpom7ao3qAredUZ7LNuO6Ci7/UDwAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IJ7RuOEv7VxWHIzZpdWX872yQb4iDGq5uGMxvcWO1ZzsAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IMcFM1h6jtqVoSQyhWRQygyPjkUFGTyjB3q7bK67cDqUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df123_removed": {
      "version": 5,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDve1Ab2c1fYbmGadpom7ao3qAredUZ7LNuO6Ci7/UDwAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IJ7RuOEv7VxWHIzZpdWX872yQb4iDGq5uGMxvcWO1ZzsAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IMcFM1h6jtqVoSQyhWRQygyPjkUFGTyjB3q7bK67cDqUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df456_added": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDve1Ab2c1fYbmGadpom7ao3qAredUZ7LNuO6Ci7/UDwAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IHiMzS7DmrXh1WuxA4M603OwMBLG1UQYnL/ltpi9llE/AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw=="
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IIf8W/33wau6FjgMjs5osDb8GPYKDgmHIvvx04PFMsWuAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg=="
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IJ7RuOEv7VxWHIzZpdWX872yQb4iDGq5uGMxvcWO1ZzsAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IMcFM1h6jtqVoSQyhWRQygyPjkUFGTyjB3q7bK67cDqUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IP0BJ68aixVY+x5azuc+CXoy/Ilv3pCk32dD3+cSEWZlAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ=="
              },
              "value": {
                "json": "df1"
              }
            }
          }
        ]
      },
      "df1": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1"
        }
      },
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}

task 12 'run-graphql'. lines 140-178:
Response: {
  "data": {
    "latest_owner": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDve1Ab2c1fYbmGadpom7ao3qAredUZ7LNuO6Ci7/UDwAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IJ7RuOEv7VxWHIzZpdWX872yQb4iDGq5uGMxvcWO1ZzsAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IMcFM1h6jtqVoSQyhWRQygyPjkUFGTyjB3q7bK67cDqUAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}
