processed 10 tasks

init:
A: object(0,0)

task 1 'publish'. lines 18-60:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7600000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 62-65:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4924800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 67-67:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 4 'run'. lines 69-69:
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6004152, non_refundable_storage_fee: 60648

task 5 'run'. lines 71-71:
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,2)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 6 'run'. lines 73-73:
mutated: object(0,0), object(2,0), object(2,2)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6004152, non_refundable_storage_fee: 60648

task 7 'run'. lines 75-75:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 8 'create-checkpoint'. lines 77-77:
Checkpoint created: 1

task 9 'run-graphql'. lines 79-159:
Response: {
  "data": {
    "latest": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IHdS7iKaPvl/tfQdHQqs0gjKUAwXwmSF1Cr5UUQ5X/UPAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IHdS7iKaPvl/tfQdHQqs0gjKUAwXwmSF1Cr5UUQ5X/UPAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
              "count": "0"
            }
          }
        }
      }
    },
    "v2": {
      "version": 2,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "v3": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IHdS7iKaPvl/tfQdHQqs0gjKUAwXwmSF1Cr5UUQ5X/UPAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
              "count": "0"
            }
          }
        }
      }
    },
    "v4": {
      "version": 4,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "v7": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IHdS7iKaPvl/tfQdHQqs0gjKUAwXwmSF1Cr5UUQ5X/UPAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xa205527e1a9c3bec2ad44285a1fd3a54b6af44fe8381cd60041d60cd14129ca6",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
