processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 19-58:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7600000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 60-62:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 64-64:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 4 'create-checkpoint'. lines 66-66:
Checkpoint created: 1

task 5 'run-graphql'. lines 68-130:
Response: {
  "data": {
    "latest": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IL1UnJ4tEMbcRfNVxJ2raKarUdPXhW9vuUUOe+8FfSlYAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x3a30ed78d68480f4647031c12f33823162bb54acf1b9b8abe282c42ed034ed41",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3a30ed78d68480f4647031c12f33823162bb54acf1b9b8abe282c42ed034ed41",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IL1UnJ4tEMbcRfNVxJ2raKarUdPXhW9vuUUOe+8FfSlYAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x3a30ed78d68480f4647031c12f33823162bb54acf1b9b8abe282c42ed034ed41",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3a30ed78d68480f4647031c12f33823162bb54acf1b9b8abe282c42ed034ed41",
              "count": "0"
            }
          }
        }
      }
    },
    "dof_added": {
      "version": 3,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IL1UnJ4tEMbcRfNVxJ2raKarUdPXhW9vuUUOe+8FfSlYAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x3a30ed78d68480f4647031c12f33823162bb54acf1b9b8abe282c42ed034ed41",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3a30ed78d68480f4647031c12f33823162bb54acf1b9b8abe282c42ed034ed41",
              "count": "0"
            }
          }
        }
      }
    },
    "before_dof_added": {
      "version": 2,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    }
  }
}

task 6 'run'. lines 132-132:
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6004152, non_refundable_storage_fee: 60648

task 7 'create-checkpoint'. lines 134-134:
Checkpoint created: 2

task 8 'run-graphql'. lines 136-186:
Response: {
  "data": {
    "latest": {
      "version": 4,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "owner_view": {
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "before_reclaim_and_transfer_dof": {
      "version": 3,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x3a30ed78d68480f4647031c12f33823162bb54acf1b9b8abe282c42ed034ed41",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
