processed 35 tasks

init:
A: object(0,0)

task 1 'publish'. lines 12-85:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 11012400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 87-89:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3549200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 91-91:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 4 'view-object'. lines 93-93:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 5 'programmable'. lines 95-97:
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6004000,  storage_rebate: 3513708, non_refundable_storage_fee: 35492

task 6 'view-object'. lines 99-99:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 7 'view-object'. lines 101-101:
Owner: Object ID: ( fake(5,0) )
Version: 3
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 1u64}

task 8 'create-checkpoint'. lines 103-103:
Checkpoint created: 1

task 9 'run-graphql'. lines 105-167:
Response: {
  "data": {
    "parent_version_2_no_dof": {
      "address": "0xe27d0e22b0728aeaa5bddec4ec90c8538497fe3556e1422ba187e88750aa5fbd",
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_3_has_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "child_version_2_no_parent": {
      "address": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
      "owner": {}
    },
    "child_version_3_has_parent": {
      "owner": {
        "parent": {
          "address": "0xfb350bf843940806d6a8ef06dd4529ad62351080729fedfc3079f4d8ca7a301d"
        }
      }
    }
  }
}

task 10 'programmable'. lines 169-171:
created: object(10,0), object(10,1), object(10,2)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 9910400,  storage_rebate: 3513708, non_refundable_storage_fee: 35492

task 11 'view-object'. lines 173-173:
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 12 'view-object'. lines 175-175:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 2u64}

task 13 'create-checkpoint'. lines 177-177:
Checkpoint created: 2

task 14 'run-graphql'. lines 179-239:
Response: {
  "data": {
    "parent_version_4_show_dof_and_dfs": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBiLsfGk2eWOMGRYrwLQK9QRhyTGHB7+VrCyZESZzJq6AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IDPNwjHa9MG6rkRehqU2Un1/ObzrEgw+R253i5SJVxTnAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IH5t26wpE1znt3HYl/c/YqQ+xUiBonEkigNoHn1/Z1MWAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_3_only_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_3_cursor_at_parent_version_3": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_version_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 15 'run-graphql'. lines 241-278:
Response: {
  "data": {
    "parent_version_3": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
              "count": "1"
            }
          }
        }
      },
      "dfNotAvailableYet": null
    },
    "parent_version_4": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
              "count": "1"
            }
          }
        }
      },
      "dfAddedHere": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    }
  }
}

task 16 'programmable'. lines 281-282:
created: object(16,0), object(16,1), object(16,2)
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 8603200,  storage_rebate: 2219580, non_refundable_storage_fee: 22420

task 17 'view-object'. lines 284-284:
Owner: Account Address ( A )
Version: 5
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 18 'view-object'. lines 286-286:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 2u64}

task 19 'create-checkpoint'. lines 288-288:
Checkpoint created: 3

task 20 'run-graphql'. lines 290-340:
Response: {
  "data": {
    "parent_version_4_has_4_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBiLsfGk2eWOMGRYrwLQK9QRhyTGHB7+VrCyZESZzJq6AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IDPNwjHa9MG6rkRehqU2Un1/ObzrEgw+R253i5SJVxTnAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IH5t26wpE1znt3HYl/c/YqQ+xUiBonEkigNoHn1/Z1MWAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_5_has_7_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBiLsfGk2eWOMGRYrwLQK9QRhyTGHB7+VrCyZESZzJq6AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IDPNwjHa9MG6rkRehqU2Un1/ObzrEgw+R253i5SJVxTnAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IFQfgw9TwuRaUyhfhCS3WWodvt0yTPB4vL6nqNFccGLJAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IH5t26wpE1znt3HYl/c/YqQ+xUiBonEkigNoHn1/Z1MWAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IM4rToHokZXnRNcJtJj9QlP20q6UypNM6rdyn3lmVC96AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IO0/kFtArFm6X6WavpnOeqGmXCzw+IXiOv3hELfPUb26AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_5_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 21 'programmable'. lines 342-343:
mutated: object(0,0), object(2,1)
deleted: object(10,0), object(10,1), object(10,2)
gas summary: computation_cost: 1000000, storage_cost: 2242000,  storage_rebate: 8517168, non_refundable_storage_fee: 86032

task 22 'view-object'. lines 345-345:
Owner: Account Address ( A )
Version: 6
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 23 'view-object'. lines 347-347:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 2u64}

task 24 'create-checkpoint'. lines 349-349:
Checkpoint created: 4

task 25 'run-graphql'. lines 351-401:
Response: {
  "data": {
    "parent_version_4_has_df1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBiLsfGk2eWOMGRYrwLQK9QRhyTGHB7+VrCyZESZzJq6BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IDPNwjHa9MG6rkRehqU2Un1/ObzrEgw+R253i5SJVxTnBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IH5t26wpE1znt3HYl/c/YqQ+xUiBonEkigNoHn1/Z1MWBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IFQfgw9TwuRaUyhfhCS3WWodvt0yTPB4vL6nqNFccGLJBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IM4rToHokZXnRNcJtJj9QlP20q6UypNM6rdyn3lmVC96BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IO0/kFtArFm6X6WavpnOeqGmXCzw+IXiOv3hELfPUb26BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd0226926da31fdaabc243522c7cc49eaf3cd23f10648ae2ec9ea4ba90b476657",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 26 'run-graphql'. lines 403-434:
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}

task 28 'create-checkpoint'. lines 438-438:
Checkpoint created: 5

task 30 'create-checkpoint'. lines 442-442:
Checkpoint created: 6

task 31 'force-object-snapshot-catchup'. lines 444-444:
Objects snapshot updated to [0 to 5)

task 32 'create-checkpoint'. lines 446-446:
Checkpoint created: 7

task 33 'run-graphql'. lines 448-498:
Response: {
  "data": {
    "parent_version_4_outside_consistent_range": null,
    "parent_version_4_paginated_outside_consistent_range": null,
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IFQfgw9TwuRaUyhfhCS3WWodvt0yTPB4vL6nqNFccGLJBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IM4rToHokZXnRNcJtJj9QlP20q6UypNM6rdyn3lmVC96BwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IO0/kFtArFm6X6WavpnOeqGmXCzw+IXiOv3hELfPUb26BwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IPs1C/hDlAgG1qjvBt1FKa1iNRCAcp/t/DB59NjKejAdBwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": null
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 34 'run-graphql'. lines 500-531:
Response: {
  "data": {
    "parent_version_4": null,
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}
