processed 17 tasks

init:
A: object(0,0)

task 1 'publish'. lines 20-68:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8770400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 70-70:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 72-72:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 74-74:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 76-76:
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 6 'run'. lines 78-78:
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 7 'run'. lines 80-80:
mutated: object(0,0), object(2,0), object(3,0)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6004152, non_refundable_storage_fee: 60648

task 8 'create-checkpoint'. lines 82-82:
Checkpoint created: 1

task 9 'run-graphql'. lines 84-114:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x6b7e8ee3f855e9c484caf53b5fef5fe958d7266d8a3a12577f4a17830e213983",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x6b7e8ee3f855e9c484caf53b5fef5fe958d7266d8a3a12577f4a17830e213983",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 116-146:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x6b7e8ee3f855e9c484caf53b5fef5fe958d7266d8a3a12577f4a17830e213983",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x6b7e8ee3f855e9c484caf53b5fef5fe958d7266d8a3a12577f4a17830e213983",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x4198a12c0cd01da21a6cd35cc5e986d855c532676233d004105dbaa77bdfda77",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x4198a12c0cd01da21a6cd35cc5e986d855c532676233d004105dbaa77bdfda77",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 148-178:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 12 'run-graphql'. lines 180-210:
Response: {
  "data": {
    "object": null
  }
}

task 13 'run-graphql'. lines 212-239:
Response: {
  "data": {
    "object": {
      "owner": {
        "parent": {
          "address": "0x14c69bfdef30d74f3cb7e305aead3f5d2558ca8d4a32c96b01936c7cfbb36af0"
        }
      },
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 14 'run-graphql'. lines 241-258:
Response: {
  "data": {
    "object": null
  }
}

task 15 'run-graphql'. lines 260-287:
Response: {
  "data": {
    "object": {
      "owner": {
        "_": null
      },
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x4198a12c0cd01da21a6cd35cc5e986d855c532676233d004105dbaa77bdfda77",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x4198a12c0cd01da21a6cd35cc5e986d855c532676233d004105dbaa77bdfda77",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 16 'run-graphql'. lines 289-316:
Response: {
  "data": {
    "object": {
      "owner": {
        "_": null
      },
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x4198a12c0cd01da21a6cd35cc5e986d855c532676233d004105dbaa77bdfda77",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x4198a12c0cd01da21a6cd35cc5e986d855c532676233d004105dbaa77bdfda77",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
