processed 17 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-48:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7828000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 50-50:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 52-52:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 4 'run'. lines 54-54:
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8664000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'view-object'. lines 56-56:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 6 'run'. lines 58-58:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'view-object'. lines 60-60:
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 42u64}

task 8 'create-checkpoint'. lines 62-62:
Checkpoint created: 1

task 9 'run-graphql'. lines 64-112:
Response: {
  "data": {
    "latest": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDPo1pIVqwlth0mybyRuVKQezD2u2Q2vK21/6ai+zRCdAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw=="
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IEqnqubr5EyKB7R4yqT0Q4+xBB+qGg0SVlB9yS4qMm93AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg=="
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IGFqsGHSG3Ky9WH9T4FytMvHV/0IqfGfxazQclAuX/4QAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ=="
              },
              "value": {
                "json": "df1"
              }
            }
          }
        ]
      },
      "dynamicField": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "df_added": {
      "version": 3,
      "dynamicField": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "before_df_added": {
      "version": 2,
      "dynamicField": null
    }
  }
}

task 10 'view-object'. lines 114-114:
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 42u64}

task 11 'run'. lines 116-116:
mutated: object(0,0), object(2,0), object(4,2)
gas summary: computation_cost: 1000000, storage_cost: 4484000,  storage_rebate: 4378968, non_refundable_storage_fee: 44232

task 12 'view-object'. lines 118-118:
Owner: Account Address ( A )
Version: 5
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 42u64}

task 13 'run'. lines 120-120:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 14 'view-object'. lines 122-122:
Owner: Account Address ( A )
Version: 6
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 84u64}

task 15 'create-checkpoint'. lines 124-124:
Checkpoint created: 2

task 16 'run-graphql'. lines 126-174:
Response: {
  "data": {
    "latest": {
      "version": 6,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IDPo1pIVqwlth0mybyRuVKQezD2u2Q2vK21/6ai+zRCdAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw=="
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IEqnqubr5EyKB7R4yqT0Q4+xBB+qGg0SVlB9yS4qMm93AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg=="
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IGFqsGHSG3Ky9WH9T4FytMvHV/0IqfGfxazQclAuX/4QAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ=="
              },
              "value": {
                "json": "df1_mutated"
              }
            }
          }
        ]
      },
      "dynamicField": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1_mutated"
        }
      }
    },
    "df1_mutated": {
      "version": 5,
      "dynamicField": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1_mutated"
        }
      }
    },
    "before_df1_mutated": {
      "version": 4,
      "dynamicField": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1"
        }
      }
    }
  }
}
