processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 15-65:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8390400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 67-69:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 71-71:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 4 'run'. lines 73-73:
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 75-75:
Checkpoint created: 1

task 6 'run-graphql'. lines 77-134:
Response: {
  "data": {
    "latest": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICV96n8b3rV4RYYOcL0iKUkUmz552bFWZStViqxU1UteAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
              "count": "0"
            }
          }
        }
      }
    },
    "owner_view": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICV96n8b3rV4RYYOcL0iKUkUmz552bFWZStViqxU1UteAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
                    "count": "0"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
              "count": "0"
            }
          }
        }
      }
    },
    "dof_added": {
      "version": 3,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
              "count": "0"
            }
          }
        }
      }
    },
    "before_dof_added": {
      "version": 2,
      "dynamicObjectField": null
    }
  }
}

task 7 'run'. lines 136-136:
mutated: object(0,0), object(2,0), object(2,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 6004152, non_refundable_storage_fee: 60648

task 8 'create-checkpoint'. lines 138-138:
Checkpoint created: 2

task 9 'run-graphql'. lines 140-191:
Response: {
  "data": {
    "latest": {
      "version": 5,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "owner_view": {
      "version": 5,
      "dynamicFields": {
        "edges": []
      },
      "dynamicObjectField": null
    },
    "before_reclaim_dof": {
      "version": 4,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
              "count": "0"
            }
          }
        }
      }
    }
  }
}

task 10 'run'. lines 193-193:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 2272248, non_refundable_storage_fee: 22952

task 11 'run'. lines 195-195:
created: object(3,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 12 'create-checkpoint'. lines 197-197:
Checkpoint created: 3

task 13 'run-graphql'. lines 199-262:
Response: {
  "data": {
    "latest": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICV96n8b3rV4RYYOcL0iKUkUmz552bFWZStViqxU1UteAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
              "count": "1"
            }
          }
        }
      }
    },
    "owner_view": {
      "version": 7,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ICV96n8b3rV4RYYOcL0iKUkUmz552bFWZStViqxU1UteAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "KgAAAAAAAAA="
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      },
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
              "count": "1"
            }
          }
        }
      }
    },
    "parent_version_6": null,
    "parent_version_5": {
      "version": 5,
      "dynamicObjectField": null
    },
    "parent_version_4": {
      "version": 4,
      "dynamicObjectField": {
        "name": {
          "bcs": "KgAAAAAAAAA="
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x0128e728671d63409410e8bd7359bbff050af12bc7a4022734d129d3434e3e4f",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
