processed 17 tasks

init:
A: object(0,0)

task 1 'publish'. lines 24-78:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8960400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 80-80:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 82-82:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 84-84:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 86-86:
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 6 'run'. lines 88-88:
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 7 'run'. lines 90-90:
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 8 'run'. lines 92-92:
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 9 'create-checkpoint'. lines 94-94:
Checkpoint created: 1

task 10 'run-graphql'. lines 96-126:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 128-158:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 160-190:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 13 'run-graphql'. lines 192-222:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0x3339e48e778ce18dc56e656f46e0883d9f934fbc19041846359693eb6fcb0257",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
                      "version": 8,
                      "contents": {
                        "json": {
                          "id": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
                          "count": "1"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 14 'run-graphql'. lines 224-241:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 15 'run-graphql'. lines 243-260:
Response: {
  "data": {
    "object": null
  }
}

task 16 'run-graphql'. lines 262-279:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x977fc319ef9186cecd87789c9f57bf47de053aa259d041e3ccae0566f595637b",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
