processed 17 tasks

init:
A: object(0,0)

task 1 'publish'. lines 24-75:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8960400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 77-77:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 79-79:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 81-81:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2295200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 83-83:
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 6 'run'. lines 85-85:
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6064800,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 7 'run'. lines 87-87:
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 8 'run'. lines 89-89:
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 3610000,  storage_rebate: 3573900, non_refundable_storage_fee: 36100

task 9 'create-checkpoint'. lines 91-91:
Checkpoint created: 1

task 10 'run-graphql'. lines 93-123:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 125-155:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 157-187:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 13 'run-graphql'. lines 189-219:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0x73f7e04f424045e449ed940a29a191045a40089fab972a4d83d7715d06c7ecf4",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
                      "version": 8,
                      "contents": {
                        "json": {
                          "id": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
                          "count": "1"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 14 'run-graphql'. lines 221-238:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 15 'run-graphql'. lines 240-257:
Response: {
  "data": {
    "object": null
  }
}

task 16 'run-graphql'. lines 259-276:
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0xc01dbc5bc85403c91054fc00aceffde453d176eecd91c216cace519337f3880b",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
