error[E01018]: invalid 'match'
  ┌─ tests/development/enums/matching/invalid_empty_match.move:7:9
  │  
7 │ ╭         match (e) {
8 │ │         }
  │ ╰─────────^ Invalid 'match' form. 'match' must have at least one arm

error[E01018]: invalid 'match'
   ┌─ tests/development/enums/matching/invalid_empty_match.move:17:9
   │  
17 │ ╭         match (e) {
18 │ │         }
   │ ╰─────────^ Invalid 'match' form. 'match' must have at least one arm

