processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-55:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8709600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 56-56:
Checkpoint created: 1

task 3 'programmable'. lines 58-64:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'programmable'. lines 66-74:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'create-checkpoint'. lines 75-77:
Checkpoint created: 2

task 6 'advance-epoch'. lines 78-78:
Epoch advanced: 0

task 7 'programmable'. lines 80-83:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'programmable'. lines 85-88:
Error: Transaction Effects Status: Invalid command argument at 0. The argument cannot be deserialized into a value of the specified type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidBCSBytes }, source: Some("Function expects std::string::String but provided argument's value does not match"), command: Some(0) } }

task 9 'programmable'. lines 90-96:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 10 'create-checkpoint'. lines 97-100:
Checkpoint created: 4

task 11 'advance-epoch'. lines 101-103:
Epoch advanced: 1

task 12 'advance-epoch'. lines 104-104:
Epoch advanced: 2

task 13 'view-checkpoint'. lines 106-106:
CheckpointSummary { epoch: 2, seq: 6, content_digest: GyYwMWrjkzGwSBxo3LsRqXZ8nM6w5RJU28zKbjjcZEQ4,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}
