--- tests/move_2024/migration/friend_decl.move
+++ tests/move_2024/migration/friend_decl.move
@@ -3,1 +3,1 @@
-    friend a::n1;
+    /* friend a::n1; */
@@ -4,1 +4,1 @@
-    friend /* nested */ a::n2;
+    /* friend /* nested */ a::n2; */
@@ -5,1 +5,1 @@
-    /* stays */friend /* nested */ a::n3; // stays
+    /* stays *//* friend /* nested */ a::n3; */ // stays
@@ -6,1 +6,1 @@
-    /* stays */friend/* nested */a::n4;// stays
+    /* stays *//* friend/* nested */a::n4; */// stays
