--- tests/move_2024/migration/let_mut_migrate.move
+++ tests/move_2024/migration/let_mut_migrate.move
@@ -3,1 +3,1 @@
-    public fun t(x: u64, yip: u64, s: S): u64  {
+    public fun t(mut x: u64, mut yip: u64, s: S): u64  {
@@ -4,1 +4,1 @@
-        let yes = 0;
+        let mut yes = 0;
@@ -5,1 +5,1 @@
-        let S { f: fin } = s;
+        let S { f: mut fin } = s;
@@ -15,1 +15,1 @@
-        let x = 5; let y = 10;
+        let mut x = 5; let mut y = 10;
