--- tests/move_2024/migration/match_okay.move
+++ tests/move_2024/migration/match_okay.move
@@ -3,2 +3,2 @@
-    fun t(t: u64, match: u64): bool {
-        t == match
+    fun t(t: u64, `match`: u64): bool {
+        t == `match`
@@ -7,2 +7,2 @@
-    fun t(t: u64, match: u64): bool {
-        if (t == match) { true } else { false }
+    fun t(t: u64, `match`: u64): bool {
+        if (t == `match`) { true } else { false }
