error[E13002]: feature is deprecated in specified edition
  ┌─ tests/move_2024/migration/multiline.move:3:5
  │  
3 │ ╭     friend // why
4 │ │     a::n;
  │ ╰─────────^ 'friend's are deprecated. Use 'public(package)' instead

error[E13002]: feature is deprecated in specified edition
  ┌─ tests/move_2024/migration/multiline.move:5:5
  │  
5 │ ╭     public( // why folks, why
6 │ │         friend
7 │ │     ) fun t() {}
  │ ╰─────^ 'friend's are deprecated. Use 'public(package)' instead

