processed 8 tasks

init:
A: object(0,0)

task 1 'run-graphql'. lines 6-10:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 2 'run-graphql'. lines 12-42:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 1,
          "column": 28
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 3 'run-graphql'. lines 44-50:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 1,
          "column": 24
        }
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 4 'run-graphql'. lines 52-56:
Response: {
  "data": {}
}

task 5 'run-graphql'. lines 58-62:
Response: {
  "data": {
    "chainIdentifier": "3989ac57"
  }
}

task 6 'run-graphql'. lines 64-68:
Response: {
  "data": {
    "chainIdentifier": "3989ac57"
  }
}

task 7 'run-graphql'. lines 70-74:
Response: {
  "data": {}
}
