processed 7 tasks

init:
A: object(0,0)

task 1 'run-graphql'. lines 6-10:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 2,
          "column": 19
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

task 2 'run-graphql'. lines 12-42:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Directive `@deprecated` is not supported. Supported directives are `@include`, `@skip`",
      "locations": [
        {
          "line": 1,
          "column": 29
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

task 3 'run-graphql'. lines 44-48:
Response: {
  "data": {}
}

task 4 'run-graphql'. lines 50-54:
Response: {
  "data": {
    "chainIdentifier": "e5efa03d"
  }
}

task 5 'run-graphql'. lines 56-60:
Response: {
  "data": {
    "chainIdentifier": "e5efa03d"
  }
}

task 6 'run-graphql'. lines 62-66:
Response: {
  "data": {}
}
