processed 16 tasks

task 1 'run-graphql'. lines 6-14:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasPreviousPage": false
      }
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 3,
      "outputNodes": 3,
      "depth": 3,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 254
    }
  }
}

task 2 'run-graphql'. lines 16-26:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "node": {
            "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 42,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 359
    }
  }
}

task 3 'run-graphql'. lines 28-42:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "transactionBlocks": {
            "edges": [
              {
                "txns": {
                  "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 6,
      "outputNodes": 842,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 484
    }
  }
}

task 4 'run-graphql'. lines 44-65:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "notOne": {
            "edges": [
              {
                "txns": {
                  "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
                }
              }
            ]
          },
          "isOne": {
            "edges": [
              {
                "txns": {
                  "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 10,
      "outputNodes": 922,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 735
    }
  }
}

task 5 'run-graphql'. lines 67-88:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "notZero": {
            "edges": [
              {
                "txns": {
                  "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
                }
              }
            ]
          },
          "isZero": {
            "edges": []
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 10,
      "outputNodes": 882,
      "depth": 6,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 733
    }
  }
}

task 6 'run-graphql'. lines 90-100:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 4,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 323
    }
  }
}

task 7 'run-graphql'. lines 102-112:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 4,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 322
    }
  }
}

task 8 'run-graphql'. lines 114-142:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH",
            "first": null,
            "last": null
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 14,
      "outputNodes": 1762,
      "depth": 8,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 1077
    }
  }
}

task 9 'run-graphql'. lines 144-171:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH",
          "first": null,
          "last": null
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 13,
      "outputNodes": 1742,
      "depth": 7,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 1030
    }
  }
}

task 10 'run-graphql'. lines 173-222:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "txns": {
            "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH",
            "a": null,
            "b": null
          }
        }
      ]
    },
    "events": {
      "edges": []
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 24,
      "outputNodes": 46424,
      "depth": 11,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 2093
    }
  }
}

task 11 'run-graphql'. lines 224-249:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "node": {
            "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH",
            "a": null
          }
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 12,
      "outputNodes": 17302,
      "depth": 11,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 1029
    }
  }
}

task 12 'run-graphql'. lines 251-272:
Response: {
  "data": {
    "fragmentSpread": {
      "nodes": [
        {
          "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
        }
      ]
    },
    "inlineFragment": {
      "nodes": [
        {
          "digest": "EoFwLKRy23XKLkWZbBLiqjTV2vsKPsmpW6dV2caK8ZDH"
        }
      ]
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 8,
      "outputNodes": 44,
      "depth": 4,
      "variables": 0,
      "fragments": 1,
      "queryPayload": 562
    }
  }
}

task 13 'run-graphql'. lines 274-286:
Response: {
  "data": null,
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 62,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 394
    }
  },
  "errors": [
    {
      "message": "'first' and 'last' must not be used together",
      "locations": [
        {
          "line": 4,
          "column": 3
        }
      ],
      "path": [
        "transactionBlocks"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 14 'run-graphql'. lines 288-298:
Response: {
  "data": null,
  "extensions": {
    "usage": {
      "inputNodes": 4,
      "outputNodes": 42,
      "depth": 4,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 141
    }
  },
  "errors": [
    {
      "message": "Invalid value for argument \"first\", expected type \"Int\"",
      "locations": [
        {
          "line": 3,
          "column": 21
        }
      ]
    }
  ]
}

task 15 'run-graphql'. lines 300-310:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Estimated output nodes exceeds 100000",
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
