
# Generated on Tue, 21 May 2024 20:02:41 +0000
# !buckify
# code within the buckify block will be auto-replaced when buckify is run
deps = [
  "//external-crates/move/crates/move-abstract-interpreter:move-abstract-interpreter",
  "//external-crates/move/crates/move-abstract-stack:move-abstract-stack",
  "//external-crates/move/crates/move-binary-format:move-binary-format",
  "//external-crates/move/crates/move-borrow-graph:move-borrow-graph",
  "//external-crates/move/crates/move-bytecode-verifier-meter:move-bytecode-verifier-meter",
  "//external-crates/move/crates/move-core-types:move-core-types",
  "//external-crates/move/crates/move-vm-config:move-vm-config",
  "//third-party:petgraph_0_5_1"
]
# buckify!

rust_library(
    name = "move-bytecode-verifier",
    srcs = glob(["**/*"]),
    deps = deps,
    env = {
        "CARGO_MANIFEST_DIR": "",
        "CARGO_PKG_VERSION": "0.1.0",
        "OUT_DIR": "",
        "CARGO_PKG_DESCRIPTION": "Move bytecode verifier",
        "CARGO_PKG_NAME": "move-bytecode-verifier",
        "CARGO_PKG_AUTHORS": "[Diem Association <opensource@diem.com>]",
    },
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["PUBLIC"],
)

