processed 6 tasks

task 1 'publish'. lines 6-33:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6756400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 35-35:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'programmable'. lines 37-40:
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3420000,  storage_rebate: 3385800, non_refundable_storage_fee: 34200

task 4 'programmable'. lines 41-44:
Error: Error checking transaction input objects: DuplicateObjectRefInput

task 5 'programmable'. lines 45-46:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object 0x6b7c4000d7f46a0cf15aeab3134157cbdecc6d25aa828d74c8bd36f91314a17e is owned by account address 0xacc3895100e62eddf620872c5c762488afac12c37c4e1141ca0a88052738a9e1, but given owner/signer address is 0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e" }
