processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-38:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7835600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 40-40:
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3541600,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'view-object'. lines 42-42:
Owner: Account Address ( _ )
Version: 3
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 4 'view-object'. lines 44-44:
Owner: Account Address ( fake(2,0) )
Version: 3
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 5 'run'. lines 46-46:
created: object(5,0), object(5,1), object(5,2)
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 9728000,  storage_rebate: 3506184, non_refundable_storage_fee: 35416

task 6 'view-object'. lines 48-48:
Owner: Account Address ( _ )
Version: 4
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 7 'view-object'. lines 50-50:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, value: 100u64}

task 8 'view-object'. lines 52-52:
Owner: Object ID: ( fake(2,0) )
Version: 4
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(5,0)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(2,1)}}

task 9 'view-object'. lines 54-54:
Owner: Object ID: ( fake(2,1) )
Version: 4
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(5,1)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(5,2)}}

task 10 'view-object'. lines 56-56:
Owner: Object ID: ( fake(5,1) )
Version: 4
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(5,2)}}, value: 100u64}
