processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-36:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7843200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 38-38:
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7273200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 40-40:
Owner: Object ID: ( fake(2,1) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(2,2)}}

task 4 'view-object'. lines 42-42:
Owner: Account Address ( fake(2,3) )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 5 'view-object'. lines 44-44:
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 6 'view-object'. lines 46-46:
Owner: Account Address ( A )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,3)}}, value: 0u64}

task 7 'run'. lines 48-48:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object 0x65f4bb16cb1ee14b473a0cce5df659a664c4b9c1e1d8698c76f0453e83c42c51 is owned by account address 0xfca3004fdc6e9507f2ecc9d58a180b11fc1b534ca3a1aa119d0c68d4e4f4ea8d, but given owner/signer address is 0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e" }

task 8 'view-object'. lines 50-50:
Owner: Object ID: ( fake(2,1) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(2,2)}}

task 9 'view-object'. lines 52-52:
Owner: Account Address ( fake(2,3) )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, value: 0u64}

task 10 'view-object'. lines 54-54:
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 11 'view-object'. lines 56-56:
Owner: Account Address ( A )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,3)}}, value: 0u64}
