Command `test -t 1 --trace-execution new_traces`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING tracing_unit_tests
Running Move unit tests
[ PASS    ] 0x1::calls::test_call_order
[ PASS    ] 0x1::calls::test_call_return_order
[ PASS    ] 0x1::calls::test_complex_nested_calls
[ PASS    ] 0x1::calls::test_return_order
[ PASS    ] 0x1::errors::aborter
[ PASS    ] 0x1::errors::bad_cast
[ PASS    ] 0x1::errors::div_0
[ PASS    ] 0x1::errors::fail_during_abort
[ PASS    ] 0x1::errors::fail_in_native
[ PASS    ] 0x1::errors::overshift_l
[ PASS    ] 0x1::errors::overshift_r
[ PASS    ] 0x1::errors::underflow
[ PASS    ] 0x1::natives::get_orig_type_name_test
[ PASS    ] 0x1::natives::get_type_name_test
[ PASS    ] 0x1::packs::test_gen_pack_order
[ PASS    ] 0x1::packs::test_gen_unpack_order
[ PASS    ] 0x1::packs::test_pack_order
[ PASS    ] 0x1::packs::test_unpack_order
[ PASS    ] 0x1::references::nested_struct_reference_mutation
[ PASS    ] 0x1::references::pass_mut_assign_in_other_fn
[ PASS    ] 0x1::references::test_struct_borrow
[ PASS    ] 0x1::references::test_vector_mut_borrow
[ PASS    ] 0x1::references::test_vector_mut_borrow_pop
Test result: OK. Total tests: 23; passed: 23; failed: 0
External Command `diff -qr new_traces saved_traces`:
