processed 3 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-11:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3898800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 13-14:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Can only call `entry` or `public` functions"), command: Some(0) } }
