processed 3 tasks

init:
A: object(103)

task 1 'publish'. lines 8-11:
created: object(105)
mutated: object(104)

task 2 'programmable'. lines 13-14:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Can only call `entry` or `public` functions"), command: Some(0) } }
