processed 9 tasks

init:
A: object(103)

task 1 'publish'. lines 8-24:
created: object(105)
mutated: object(104)

task 2 'programmable'. lines 25-26:
mutated: object(106)

task 3 'programmable'. lines 28-29:
mutated: object(107)

task 4 'programmable'. lines 31-32:
mutated: object(108)

task 5 'programmable'. lines 34-35:
mutated: object(109)

task 6 'programmable'. lines 37-38:
mutated: object(110)

task 7 'programmable'. lines 40-43:
mutated: object(111)

task 8 'programmable'. lines 44-46:
mutated: object(112)
