processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-16:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4681600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 18-19:
Error: Transaction Effects Status: Invalid public Move function signature. Unsupported return type for return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidPublicFunctionReturnType { idx: 0 }, source: None, command: Some(0) } }

task 3 'programmable'. lines 21-22:
Error: Transaction Effects Status: Invalid public Move function signature. Unsupported return type for return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidPublicFunctionReturnType { idx: 0 }, source: None, command: Some(0) } }

task 4 'programmable'. lines 24-25:
Error: Transaction Effects Status: Invalid public Move function signature. Unsupported return type for return value 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidPublicFunctionReturnType { idx: 1 }, source: None, command: Some(0) } }
