processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-27:
created: object(1,0)
mutated: object(0,1)

task 2 'programmable'. lines 29-34:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 2, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 2, secondary_idx: 0 }, source: None, command: None } }

task 3 'programmable'. lines 35-43:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: Some("The value has copy, but not drop. Its last usage must be by-value so it can be taken."), command: None } }

task 4 'programmable'. lines 44-47:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 2, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 2, secondary_idx: 0 }, source: Some("The value has copy, but not drop. Its last usage must be by-value so it can be taken."), command: None } }
