processed 4 tasks

task 2 'run'. lines 25-25:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(9223372105574252543),
    location: 0x42::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'run'. lines 27-27:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(9223372118459154431),
    location: 0x42::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(1), 1)],
}
