processed 35 tasks

task 6 'run'. lines 182-188:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x7::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 7 'run'. lines 190-196:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x8::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 8 'run'. lines 198-204:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x9::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 9 'run'. lines 206-212:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0xa::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 10 'run'. lines 214-220:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0xb::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 11 'run'. lines 222-228:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0xc::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 12 'run'. lines 230-236:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0xd::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 13 'run'. lines 238-244:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0xe::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 14 'run'. lines 246-252:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0xf::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 15 'run'. lines 254-262:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x10::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 16 'run'. lines 263-269:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x11::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 17 'run'. lines 271-277:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x12::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 18 'run'. lines 279-285:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x13::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 19 'run'. lines 287-293:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x14::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 20 'run'. lines 295-301:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x15::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 21 'run'. lines 303-309:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x16::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 22 'run'. lines 311-317:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x17::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 23 'run'. lines 319-325:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x18::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 24 'run'. lines 327-335:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x19::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 25 'run'. lines 336-342:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x1a::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 27 'run'. lines 352-358:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x1c::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 28 'run'. lines 360-366:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x1d::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 29 'run'. lines 368-374:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x1e::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 30 'run'. lines 376-382:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x1f::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 31 'run'. lines 384-392:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x20::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 32 'run'. lines 393-399:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x21::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 33 'run'. lines 401-407:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x22::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 34 'run'. lines 409-415:
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x23::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}
