processed 16 tasks

task 0, lines 1-8:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x1::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 1, lines 10-16:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x2::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2, lines 18-24:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x3::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 3, lines 26-32:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x4::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4, lines 34-40:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x5::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 5, lines 42-48:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x6::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 6, lines 50-56:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x7::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7, lines 58-64:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x8::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8, lines 66-72:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x9::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 9, lines 74-83:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0xa::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
