current frame stack:
  function: test (m.move:12)
    scope 0 :
line breakpoints
  m2.mvb
    12
current frame stack:
  function: test (m.move:12)
    scope 0 :
  function: foo (m2.mvb:8)
    scope 0 :
      p : 42
      type: u64

line breakpoints
  m2.mvb
    12
current frame stack:
  function: test (m.move:12)
    scope 0 :
  function: foo (m2.mvb:11)
    scope 0 :
  function: bar (m3.move:4)
    scope 0 :
      p : 84
      type: u64

line breakpoints
  m2.mvb
    12
current frame stack:
  function: test (m.move:12)
    scope 0 :
  function: foo (m2.mvb:12)
    scope 0 :
line breakpoints
  m2.mvb
    12
