current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 17)
    scope 0 :
      p : 42
      type: u64

current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 18)
    scope 0 :
      p : 42
      type: u64

      v1 : 210
      type: u64

current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 19)
    scope 0 :
      p : 42
      type: u64

      v1 : 210
      type: u64

      v2 : 84
      type: u64

current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 19)
    scope 0 :
      v1 : 210
      type: u64

      v2 : 84
      type: u64

current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 20)
    scope 0 :
      v1 : 210
      type: u64

      v2 : 84
      type: u64

      v3 : 84
      type: u64

