processed 5 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-11:
//# programmable --sender A --inputs 1000000 @B
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 13-15:
//# programmable --sender B --inputs 2000000 @A
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 17:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 19-87:
//# run-graphql
Response: {
  "data": {
    "bySentAddress": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "inputState": null,
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "1000000"
                      }
                    }
                  }
                },
                {
                  "inputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "300000000000000"
                      }
                    }
                  },
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "299999996024000"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "bySignAddress": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "inputState": null,
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "1000000"
                      }
                    }
                  }
                },
                {
                  "inputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "300000000000000"
                      }
                    }
                  },
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "299999996024000"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "bothAddresses": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "inputState": null,
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "1000000"
                      }
                    }
                  }
                },
                {
                  "inputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "300000000000000"
                      }
                    }
                  },
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "299999996024000"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "differentAddresses": {
      "nodes": []
    },
    "compoundBySentAddress": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "inputState": null,
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "1000000"
                      }
                    }
                  }
                },
                {
                  "inputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "300000000000000"
                      }
                    }
                  },
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "299999996024000"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "compoundBySignAddress": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "inputState": null,
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "1000000"
                      }
                    }
                  }
                },
                {
                  "inputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "300000000000000"
                      }
                    }
                  },
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "299999996024000"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "compoundBothAddresses": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "inputState": null,
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "1000000"
                      }
                    }
                  }
                },
                {
                  "inputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "300000000000000"
                      }
                    }
                  },
                  "outputState": {
                    "asMoveObject": {
                      "asCoin": {
                        "coinBalance": "299999996024000"
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "compoundDifferentAddresses": {
      "nodes": []
    },
    "sentViaAddress": {
      "transactionBlocks": {
        "nodes": [
          {
            "effects": {
              "objectChanges": {
                "nodes": [
                  {
                    "inputState": null,
                    "outputState": {
                      "asMoveObject": {
                        "asCoin": {
                          "coinBalance": "1000000"
                        }
                      }
                    }
                  },
                  {
                    "inputState": {
                      "asMoveObject": {
                        "asCoin": {
                          "coinBalance": "300000000000000"
                        }
                      }
                    },
                    "outputState": {
                      "asMoveObject": {
                        "asCoin": {
                          "coinBalance": "299999996024000"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    },
    "signViaAddress": {
      "transactionBlocks": {
        "nodes": [
          {
            "effects": {
              "objectChanges": {
                "nodes": [
                  {
                    "inputState": null,
                    "outputState": {
                      "asMoveObject": {
                        "asCoin": {
                          "coinBalance": "1000000"
                        }
                      }
                    }
                  },
                  {
                    "inputState": {
                      "asMoveObject": {
                        "asCoin": {
                          "coinBalance": "300000000000000"
                        }
                      }
                    },
                    "outputState": {
                      "asMoveObject": {
                        "asCoin": {
                          "coinBalance": "299999996024000"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}
