// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// @generated by scripts/verus-expand.sh — DO NOT EDIT.
// Plain Rust with the verus! macro evaluated (all proof and spec code
// stripped). Checked in for review only; this file is never compiled.

//! Code from `sui-types` whose correctness is formally verified by Verus.
//!
//! This crate lives at `crates/sui-types/verified/`. The `verus!` macro is
//! a no-op under stable `cargo build`; CI runs `cargo verus check` via
//! scripts/verus-check.sh.
//!
//! To review only the executable code (proof and spec stripped), see the
//! checked-in plain-code artifact `expanded/sui-types-verified.rs`, regenerated
//! by scripts/verus-expand.sh.

pub mod signature_verification {
    //! Formally verified signature verification for user-signed transactions.
    //!
    //! [`verify_signatures`] handles only user transactions: intent checking and
    //! the system-transaction bypass are the caller's responsibility.
    //!
    //! The function is generic over the signature and address types so that this
    //! crate has no dependency on `sui-types`. The concrete instantiation
    //! (`GenericSignature`, `SuiAddress`) lives in `sui-types`.
    //!
    //! Informal spec: `crates/sui-types/verify_sig_spec.md`
    use crate::utils::{
        clone_and_set, copy_eq, nonempty_index, nonempty_len, nonempty_to_vec, prepend_u8,
        slice_contains,
    };
    use nonempty::NonEmpty;
    use vstd::prelude::*;
    /// Verification failure reasons, kept intentionally small.
    ///
    /// Callers in `sui-types` convert these variants into the appropriate
    /// `SuiError` / `SuiErrorKind` variants.
    pub enum SigVerifyError {
        /// `|tx_signatures| ≠ |required_signers|`.
        SignerCountMismatch { actual: usize, expected: usize },

        /// A signature's address cannot be derived (malformed bytes).
        AddressDerivationFailed,

        /// A required signer has no matching signature (including via aliases).
        ///
        /// Note: crypto failures inside `scan_first_valid` are absorbed here —
        /// if all candidate signatures for a signer fail cryptographic verification
        /// the error that surfaces at the `verify_signatures` boundary is
        /// `SignerAbsent`, not `CryptoVerificationFailed`.
        SignerAbsent,

        /// A signature failed cryptographic verification.
        ///
        /// Used by `SignatureVerifiable::verify_for_address` implementations and
        /// caught internally by `scan_first_valid`.  **Never returned directly by
        /// `verify_signatures`** — crypto failures are folded into `SignerAbsent`
        /// after all candidate aliases have been exhausted.
        CryptoVerificationFailed,
    }
    /// The two operations the verified algorithm needs from a concrete signature.
    ///
    /// Implemented in `sui-types` for `GenericSignature` (wrapped with its
    /// verification context). The verified module never sees the concrete type.
    pub trait SignatureVerifiable<Addr>: Sized {
        /// Derive all addresses this signature is associated with.
        ///
        /// A single signature may yield more than one address (e.g. a zklogin
        /// signature with legacy-address support). Returns
        /// `Err(SigVerifyError::AddressDerivationFailed)` for malformed input.
        fn try_derive_addresses(&self) -> Result<Vec<Addr>, SigVerifyError>;
        /// Cryptographically verify this signature as proof of authorization by
        /// `addr` at `epoch`. Returns `Err(CryptoVerificationFailed)` on failure.
        fn verify_for_address(&self, addr: &Addr, epoch: u64) -> Result<(), SigVerifyError>;
    }
    /// Derive addresses for every signature in one pass.
    /// Returns `Err` if any signature is malformed, otherwise `Ok(sig_addrs)`
    /// where `sig_addrs[i]@.to_set() == spec_addresses(tx_signatures, i)`.
    fn derive_all_addresses<S: SignatureVerifiable<Addr>, Addr: PartialEq + Eq + Copy>(
        tx_signatures: &[S],
    ) -> Result<Vec<Vec<Addr>>, SigVerifyError> {
        let n = tx_signatures.len();
        let mut sig_addrs: Vec<Vec<Addr>> = Vec::with_capacity(n);
        for i in 0..n {
            match tx_signatures[i].try_derive_addresses() {
                Ok(addrs) => {
                    {}
                    sig_addrs.push(addrs);
                    {}
                }
                Err(_) => {
                    {}
                    return Err(SigVerifyError::AddressDerivationFailed);
                }
            }
        }
        {}
        Ok(sig_addrs)
    }
    /// Find the first unused position j where sig j's address set intersects `aliases`
    /// AND the signature is cryptographically valid for the matching address.
    /// Returns `None` iff `spec_first_valid_unused` returns `None`.
    ///
    /// Correctness note: we iterate over ALL aliases for each position (not just
    /// the first common address) so that if one alias fails crypto another may
    /// succeed.  This is necessary for signatures with multiple addresses (e.g.
    /// zklogin legacy + canonical) and makes the proof tractable.
    fn scan_first_valid<S: SignatureVerifiable<Addr>, Addr: PartialEq + Eq + Copy>(
        tx_signatures: &[S],
        sig_addrs: &[Vec<Addr>],
        aliases: &Vec<Addr>,
        epoch: u64,
        visited: &[bool],
        _ghost_used: Ghost<Set<int>>,
    ) -> Option<(u8, Addr)> {
        let n = tx_signatures.len();
        for j in 0..n {
            if !visited[j] {
                let mut ai = 0usize;
                let mut found_addr: Option<Addr> = None;
                while ai < aliases.len() && found_addr.is_none() {
                    let a = aliases[ai];
                    ai += 1;
                    if slice_contains(&sig_addrs[j], a) {
                        match tx_signatures[j].verify_for_address(&a, epoch) {
                            Ok(()) => {
                                {}
                                found_addr = Some(a);
                            }
                            Err(_) => {}
                        }
                    } else {
                        {}
                    }
                }
                match found_addr {
                    Some(addr) => {
                        {}
                        return Some((j as u8, addr));
                    }
                    None => {}
                }
            }
        }
        {}
        None
    }
    /// Recursive core of the greedy verification algorithm.
    ///
    /// Processes `signers` one at a time.  `taken` (exec) / `used` (ghost) track
    /// which signature positions have already been assigned to earlier senders.
    /// Directly mirrors `spec_greedy_helper` so the proof is by structural induction.
    fn verify_sigs_rec<S: SignatureVerifiable<Addr>, Addr: PartialEq + Eq + Copy>(
        tx_signatures: &[S],
        sig_addrs: &[Vec<Addr>],
        signers: &[(Addr, Vec<Addr>)],
        epoch: u64,
        visited: &[bool],
        used: Ghost<Set<int>>,
    ) -> Result<Vec<u8>, SigVerifyError> {
        if signers.is_empty() {
            return Ok(::alloc::vec::Vec::new());
        }
        let (_, aliases) = &signers[0];
        let scan_result = scan_first_valid(tx_signatures, sig_addrs, aliases, epoch, visited, used);
        let (j, _addr) = match scan_result {
            None => {
                {}
                return Err(SigVerifyError::SignerAbsent);
            }
            Some(pair) => pair,
        };
        let visited_new = clone_and_set(visited, j as usize, true);
        {}
        let rest = verify_sigs_rec(
            tx_signatures,
            sig_addrs,
            &signers[1..signers.len()],
            epoch,
            &visited_new,
            Ghost::assume_new_fallback(|| {
                ::core::panicking::panic("internal error: entered unreachable code")
            }),
        )?;
        let result = prepend_u8(j, &rest);
        {}
        Ok(result)
    }
    /// Look up the alias set for `signer` in `aliased_addresses`.
    /// Returns `[signer]` if no entry matches (the typical case).
    ///
    /// Uses `copy_eq` to bridge exec `PartialEq::eq` to spec `==`.
    fn find_aliases_for_signer<Addr: PartialEq + Eq + Copy>(
        signer: Addr,
        aliased_addresses: &[(Addr, NonEmpty<Addr>)],
    ) -> Vec<Addr> {
        let n = aliased_addresses.len();
        let mut i = 0usize;
        while i < n {
            if copy_eq(aliased_addresses[i].0, signer) {
                let result = nonempty_to_vec(&aliased_addresses[i].1);
                {}
                return result;
            }
            {}
            i += 1;
        }
        {}
        <[_]>::into_vec(::alloc::boxed::box_new([signer]))
    }
    /// Build the `(canonical_sender, aliases)` pairs that `verify_signatures` expects.
    ///
    /// For each signer, looks up its alias set in `aliased_addresses`; if absent,
    /// the alias set defaults to `[signer]`.
    pub fn build_required_signers<Addr: PartialEq + Eq + Copy>(
        signers: &NonEmpty<Addr>,
        aliased_addresses: &[(Addr, NonEmpty<Addr>)],
    ) -> Vec<(Addr, Vec<Addr>)> {
        let n = nonempty_len(signers);
        let mut result: Vec<(Addr, Vec<Addr>)> = Vec::with_capacity(n);
        let mut i = 0usize;
        while i < n {
            let signer = nonempty_index(signers, i);
            let aliases = find_aliases_for_signer(signer, aliased_addresses);
            result.push((signer, aliases));
            i += 1;
        }
        result
    }
    /// Verify signatures on a user-signed transaction.
    ///
    /// The caller is responsible for:
    /// - Checking that the transaction intent is `SUI_TRANSACTION_INTENT`.
    /// - Skipping this call for system transactions (which are unconditionally valid).
    ///
    /// # Parameters
    /// - `tx_signatures` — ordered sequence of authenticators.
    /// - `required_signers` — each entry is `(canonical_sender, aliases)` where
    ///   `aliases` is the non-empty set of addresses that may sign for this sender.
    ///   The typical case is `aliases = vec![canonical_sender]`.
    /// - `epoch` — current epoch for cryptographic verification.
    ///
    /// # Preconditions
    /// - The signer-count ≤ 255 precondition is now checked at runtime (E0).
    /// - **Disjoint address sets** — distinct signatures must have disjoint derived
    ///   address sets (excluding signatures with failed derivation).  This is the
    ///   project-level trust boundary: the precondition is expressed as a `requires`
    ///   clause and satisfied by convention in the unverified caller
    ///   (`verify_sender_signed_data_message_signatures`), not by a Verus proof.
    ///   Violating it degrades correctness (the greedy algorithm may miss a valid
    ///   assignment) but does not create a security hole — all crypto checks still
    ///   run on every returned index.
    ///
    /// # Contract
    ///
    /// See `crates/sui-types/verify_sig_spec.md`.
    pub fn verify_signatures<S: SignatureVerifiable<Addr>, Addr: PartialEq + Eq + Copy>(
        tx_signatures: &[S],
        required_signers: &[(Addr, Vec<Addr>)],
        epoch: u64,
    ) -> Result<Vec<u8>, SigVerifyError> {
        if required_signers.len() > u8::MAX as usize {
            return Err(SigVerifyError::SignerCountMismatch {
                actual: required_signers.len(),
                expected: u8::MAX as usize,
            });
        }
        {}
        let n = tx_signatures.len();
        if n != required_signers.len() {
            return Err(SigVerifyError::SignerCountMismatch {
                actual: n,
                expected: required_signers.len(),
            });
        }
        let sig_addrs = match derive_all_addresses(tx_signatures) {
            Ok(a) => a,
            Err(e) => return Err(e),
        };
        {}
        let visited_init = ::alloc::vec::from_elem(false, n);
        let rec_result = verify_sigs_rec(
            tx_signatures,
            &sig_addrs,
            required_signers,
            epoch,
            &visited_init,
            Ghost::assume_new_fallback(|| {
                ::core::panicking::panic("internal error: entered unreachable code")
            }),
        );
        {}
        rec_result
    }
}
pub mod utils {
    //! Small utility functions with Verus specifications.
    use nonempty::NonEmpty;
    use vstd::prelude::*;
    pub struct ExNonEmpty<T>(NonEmpty<T>);
    /// Number of elements in a `NonEmpty<T>`.
    pub fn nonempty_len<T>(ne: &NonEmpty<T>) -> usize {
        ne.len()
    }
    /// Get the element at index `i`.
    pub fn nonempty_index<T: Copy>(ne: &NonEmpty<T>, i: usize) -> T {
        ne[i]
    }
    /// Clone a `NonEmpty<T>`'s elements into a fresh `Vec<T>`.
    ///
    /// Trusted (`external_body`) — `NonEmpty::iter` and collection are not specced
    /// in vstd. The ensures ties the result directly to `nonempty_view`.
    pub fn nonempty_to_vec<T: Clone>(ne: &NonEmpty<T>) -> Vec<T> {
        ne.iter().cloned().collect()
    }
    /// Compare two `Copy + Eq` values, bridging exec `PartialEq::eq` to spec `==`.
    ///
    /// Trusted (`external_body`) — Verus does not automatically axiomatize that
    /// `PartialEq::eq` agrees with spec equality for generic types.  This is
    /// sound for any well-behaved `Eq` implementation (the `Eq` laws require it).
    pub fn copy_eq<A: PartialEq + Eq + Copy>(a: A, b: A) -> bool {
        a == b
    }
    /// Check whether a slice contains an element.
    ///
    /// Trusted (`external_body`) — neither `Iterator::any` nor `slice::contains`
    /// is specced in vstd. The spec is straightforward: true iff the element
    /// appears in the slice's ghost sequence view.
    pub fn slice_contains<T: PartialEq + Eq + Copy>(v: &[T], elem: T) -> bool {
        v.iter().any(|a| *a == elem)
    }
    /// Clone a boolean slice and set position `pos` to `true`.
    ///
    /// Trusted (`external_body`) — `slice::to_vec` and indexing assignment
    /// are not specced in vstd. The spec captures what callers need for the proof.
    pub fn clone_and_set<T: Clone>(v: &[T], pos: usize, val: T) -> Vec<T> {
        let mut r = v.to_vec();
        r[pos] = val;
        r
    }
    /// Prepend a single `u8` to a slice, returning a new `Vec`.
    ///
    /// Trusted (`external_body`) — `extend_from_slice` is not specced in vstd.
    pub fn prepend_u8(x: u8, v: &[u8]) -> Vec<u8> {
        let mut r = Vec::with_capacity(1 + v.len());
        r.push(x);
        r.extend_from_slice(v);
        r
    }
}
