processed 17 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-62:
created: object(105)
written: object(104)

task 2 'run'. lines 64-64:
created: object(107)
written: object(106)

task 3 'view-object'. lines 66-66:
Owner: Account Address ( A )
Version: 1
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 4 'run'. lines 68-68:
created: object(109), object(110)
written: object(107), object(108)

task 5 'run'. lines 70-70:
written: object(107), object(109), object(111)
deleted: object(110)

task 6 'view-object'. lines 72-76:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 7 'run'. lines 78-78:
created: object(113)
written: object(112)

task 8 'view-object'. lines 80-80:
Owner: Account Address ( A )
Version: 1
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(113)}}}

task 9 'run'. lines 82-82:
created: object(115), object(116)
written: object(113), object(114)

task 10 'run'. lines 84-84:
written: object(113), object(115), object(116), object(117)

task 11 'view-object'. lines 86-90:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(113)}}}

task 12 'run'. lines 92-92:
created: object(119)
written: object(118)

task 13 'view-object'. lines 94-94:
Owner: Account Address ( A )
Version: 1
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(119)}}}

task 14 'run'. lines 96-96:
created: object(121), object(122)
written: object(119), object(120)

task 15 'run'. lines 98-98:
created: object(124)
written: object(119), object(121), object(123)
deleted: object(122)

task 16 'view-object'. lines 100-100:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(119)}}}
