processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-58:
created: object(105)
written: object(104)

task 2 'run'. lines 60-60:
created: object(107)
written: object(106)

task 3 'run'. lines 62-62:
created: object(109), object(110)
written: object(107), object(108)

task 4 'view-object'. lines 64-64:
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 5 'run'. lines 66-66:
written: object(111)
deleted: object(107)
