processed 12 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-42:
created: object(105)
written: object(104)

task 2 'run'. lines 44-44:
created: object(107)
written: object(106)

task 3 'run'. lines 46-46:
created: object(109)
written: object(108)

task 4 'run'. lines 48-48:
written: object(107), object(109), object(110)

task 5 'view-object'. lines 50-50:
Owner: Account Address ( A )
Version: 2
Child Count: Some(1)
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 6 'run'. lines 52-56:
written: object(111)
deleted: object(107), object(109)

task 7 'run'. lines 58-58:
created: object(113)
written: object(112)

task 8 'run'. lines 60-60:
created: object(115)
written: object(114)

task 9 'run'. lines 62-62:
written: object(113), object(115), object(116)

task 10 'view-object'. lines 64-64:
Owner: Account Address ( A )
Version: 2
Child Count: Some(1)
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(113)}}}

task 11 'run'. lines 66-66:
written: object(117)
deleted: object(113), object(115)
