processed 7 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-43:
created: object(105)
written: object(104)

task 2 'run'. lines 45-45:
created: object(107)
written: object(106)

task 3 'run'. lines 47-47:
created: object(109)
written: object(108)

task 4 'run'. lines 49-49:
written: object(107), object(109), object(110)

task 5 'view-object'. lines 51-51:
Owner: Account Address ( A )
Version: 2
Child Count: Some(1)
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(109)}}}

task 6 'run'. lines 53-53:
Error: Transaction Effects Status: Invalid Deletion of Parent Object with Children. Parent object fake(109) was wrapped in another object before its children were deleted or transferred.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidParentDeletion { parent: fake(109), kind: Some(Wrap) }, source: None } }
