processed 3 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-30:
created: object(105)
written: object(104)

task 2 'run'. lines 32-32:
Error: Transaction Effects Status: Invalid Deletion of Parent Object with Children. Parent object _ was wrapped in another object before its children were deleted or transferred.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidParentDeletion { parent: _, kind: Some(Wrap) }, source: None } }
