processed 6 tasks

init:
A: object(103), B: object(104)

task 1 'publish'. lines 9-38:
created: object(106)
mutated: object(105)

task 2 'run'. lines 40-40:
created: object(108)
mutated: object(107)

task 3 'run'. lines 42-42:
created: object(110), object(111)
mutated: object(108), object(109)

task 4 'view-object'. lines 44-44:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}

task 5 'run'. lines 46-46:
created: object(113)
mutated: object(112)
wrapped: object(108)
