processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-33:
created: object(105)
written: object(104)

task 2 'run'. lines 35-35:
created: object(107)
written: object(106)

task 3 'run'. lines 37-37:
created: object(109), object(110)
written: object(107), object(108)

task 4 'view-object'. lines 39-39:
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 5 'run'. lines 41-41:
written: object(111)
deleted: object(107)
