processed 7 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-33:
created: object(105)
written: object(104)

task 2 'run'. lines 35-35:
created: object(107)
written: object(106)

task 3 'run'. lines 37-37:
created: object(109)
written: object(108)

task 4 'run'. lines 39-39:
written: object(107), object(109), object(110)

task 5 'view-object'. lines 41-41:
Owner: Account Address ( A )
Contents: test::m::S {info: sui::object::Info {id: sui::object::ID {bytes: fake(107)}, version: 2u64, child_count: std::option::Option<u64> {vec: vector[1u64]}}}

task 6 'run'. lines 43-43:
Error: Transaction Effects Status: Invalid Freezing of Parent Object with Children. Invalid freezing of parent object fake(107) before its children were deleted or transferred.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidParentFreezing(InvalidParentFreezing { object: fake(107) }), source: None } }
