processed 6 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-65:
created: object(1,0)
mutated: object(0,2)

task 2 'run'. lines 67-67:
created: object(2,0)
mutated: object(0,0)

task 3 'run'. lines 69-69:
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)

task 4 'view-object'. lines 71-71:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 5 'run'. lines 73-73:
mutated: object(0,0), object(2,0)
deleted: object(3,0), object(3,1)
