processed 7 tasks

init:
A: object(103), B: object(104)

task 1 'publish'. lines 9-62:
created: object(106)
mutated: object(105)

task 2 'run'. lines 64-64:
created: object(108)
mutated: object(107)

task 3 'run'. lines 66-66:
created: object(110), object(111)
mutated: object(108), object(109)

task 4 'view-object'. lines 68-68:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}

task 5 'run'. lines 70-70:
mutated: object(108), object(112)
deleted: object(110), object(111)

task 6 'run'. lines 72-72:
mutated: object(108), object(113)
