processed 7 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-34:
created: object(105)
written: object(104)

task 2 'run'. lines 36-36:
created: object(107)
written: object(106)

task 3 'run'. lines 38-38:
created: object(109)
written: object(108)

task 4 'run'. lines 40-40:
written: object(107), object(109), object(110)

task 5 'view-object'. lines 42-42:
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 6 'run'. lines 44-44:
written: object(107), object(111)
