processed 8 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-27:
created: object(105)
written: object(104)

task 2 'run'. lines 29-29:
created: object(107), object(108)
written: object(106)

task 3 'view-object'. lines 31-31:
Owner: Account Address ( A )
Contents: test::m::S {info: sui::object::Info {id: sui::object::ID {bytes: fake(107)}, version: 1u64, child_count: std::option::Option<u64> {vec: vector[1u64]}}}

task 4 'view-object'. lines 33-33:
Owner: Object ID: ( fake(107) )
Contents: test::m::S {info: sui::object::Info {id: sui::object::ID {bytes: fake(108)}, version: 1u64, child_count: std::option::Option<u64> {vec: vector[]}}}

task 5 'run'. lines 35-35:
written: object(107), object(108), object(109)

task 6 'view-object'. lines 37-37:
Owner: Account Address ( A )
Contents: test::m::S {info: sui::object::Info {id: sui::object::ID {bytes: fake(107)}, version: 2u64, child_count: std::option::Option<u64> {vec: vector[1u64]}}}

task 7 'view-object'. lines 39-39:
Owner: Object ID: ( fake(107) )
Contents: test::m::S {info: sui::object::Info {id: sui::object::ID {bytes: fake(108)}, version: 2u64, child_count: std::option::Option<u64> {vec: vector[]}}}
