processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 10-51:
created: object(105)
written: object(104)

task 2 'run'. lines 53-53:
created: object(107)
written: object(106)

task 3 'run'. lines 55-60:
created: object(109), object(110)
written: object(107), object(108)

task 4 'run'. lines 62-66:
created: object(112), object(113)
written: object(111)

task 5 'run'. lines 68-68:
created: object(115), object(116)
written: object(114)
