processed 7 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-64:
created: object(105)
written: object(104)

task 2 'run'. lines 66-66:
created: object(107)
written: object(106)

task 3 'run'. lines 68-73:
created: object(109), object(110)
written: object(107), object(108)

task 4 'run'. lines 75-79:
created: object(112), object(113)
written: object(111)

task 5 'run'. lines 81-85:
created: object(115), object(116)
written: object(114)

task 6 'run'. lines 87-87:
created: object(118), object(119)
written: object(117)
