processed 10 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-46:
created: object(106)
written: object(105)

task 2 'run'. lines 48-48:
created: object(108), object(109), object(110)
written: object(107)

task 3 'view-object'. lines 50-54:
Owner: Object ID: ( fake(108) )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(109)}}}

task 4 'run'. lines 56-56:
created: object(112), object(113), object(114)
written: object(111)

task 5 'run'. lines 58-58:
Error: Object 0x4ed62609e80f1a882d16311822ec560fbc1d81a2ab0bcb4fd6358910dee9573f is owned by object 0x0e1963f04364076254e2239b46ad24cccf0ce9c4adec48c942e5180ff59ed753. Objects owned by other objects cannot be used as input arguments.

task 6 'view-object'. lines 60-64:
Owner: Object ID: ( fake(112) )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(113)}}}

task 7 'run'. lines 66-66:
created: object(117), object(118), object(119)
written: object(116)

task 8 'transfer-object'. lines 68-68:
Error: Object 0x2fa713550aa15a388199f0a2a6e7dd56e3d2d1876c732a6f1b8d3a0148a3dab8 is owned by object 0xe3fa1ef69b72a69ab91b6dfdfbf386e4cded35c28274d88d10ac4e023472f1ca. Objects owned by other objects cannot be used as input arguments.

task 9 'view-object'. lines 70-70:
Owner: Object ID: ( fake(117) )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(119)}}}
