processed 10 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-46:
created: object(106)
written: object(105)

task 2 'run'. lines 48-48:
created: object(108), object(109), object(110)
written: object(107)

task 3 'view-object'. lines 50-54:
Owner: Shared
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(109)}}}

task 4 'run'. lines 56-56:
created: object(112), object(113), object(114)
written: object(111)

task 5 'run'. lines 58-58:
written: object(113), object(115)

task 6 'view-object'. lines 60-64:
Owner: Account Address ( B )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(113)}}}

task 7 'run'. lines 66-66:
created: object(117), object(118), object(119)
written: object(116)

task 8 'transfer-object'. lines 68-68:
written: object(119), object(120)

task 9 'view-object'. lines 70-70:
Owner: Account Address ( B )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(119)}}}
