processed 9 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-48:
created: object(105)
written: object(104)

task 2 'run'. lines 50-50:
created: object(107), object(108)
written: object(106)

task 3 'view-object'. lines 52-52:
Owner: Account Address ( A )
Version: 1
Child Count: Some(1)
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 4 'run'. lines 54-54:
created: object(110)
written: object(109)
deleted: object(107), object(108)

task 5 'view-object'. lines 56-56:
Owner: Account Address ( A )
Version: 1
Child Count: None
Contents: test::m::R {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}, s: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}}

task 6 'run'. lines 58-58:
written: object(111)
deleted: object(107), object(110)

task 7 'view-object'. lines 60-60:
No object at id 107

task 8 'view-object'. lines 62-62:
No object at id 110
