processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-42:
created: object(105)
written: object(104)

task 2 'run'. lines 44-44:
created: object(107)
written: object(106)

task 3 'run'. lines 46-46:
created: object(109)
written: object(108)

task 4 'run'. lines 48-48:
written: object(107), object(109), object(110)

task 5 'run'. lines 50-50:
Error: Transaction Effects Status: Invalid Deletion of Parent Object with Children. Parent object fake(107) was wrapped in another object before its children were deleted or transferred.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidParentDeletion { parent: fake(107), kind: Some(Wrap) }, source: None } }
