processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 9-43:
created: object(105)
written: object(104)

task 2 'run'. lines 45-45:
created: object(107)
written: object(106)

task 3 'run'. lines 47-47:
created: object(109)
written: object(108)

task 4 'run'. lines 49-49:
written: object(107), object(109), object(110)

task 5 'run'. lines 51-51:
created: object(112)
written: object(111)
deleted: object(107)
