
# Generated on Mon, 29 Jul 2024 21:00:34 +0000
# !buckify
# code within the buckify block will be auto-replaced when buckify is run
deps = [
  "//buck/third-party:atomic_float_0_1_0",
  "//buck/third-party:bytes-varint_1_0_3",
  "//buck/third-party:bytes_1_5_0",
  "//buck/third-party:clap_4_5_4",
  "//buck/third-party:crossterm_0_25_0",
  "//buck/third-party:futures_0_3_29",
  "//buck/third-party:once_cell_1_19_0",
  "//buck/third-party:opentelemetry-otlp_0_13_0",
  "//buck/third-party:opentelemetry-proto_0_3_0",
  "//buck/third-party:opentelemetry_0_20_0",
  "//buck/third-party:opentelemetry_api_0_20_0",
  "//buck/third-party:prometheus_0_13_3",
  "//buck/third-party:prost_0_11_9",
  "//buck/third-party:tokio_1_36_0",
  "//buck/third-party:tonic_0_9_2",
  "//buck/third-party:tracing-appender_0_2_2",
  "//buck/third-party:tracing-opentelemetry_0_21_0",
  "//buck/third-party:tracing-subscriber_0_3_17",
  "//buck/third-party:tracing_0_1_40"
]
# buckify!

rust_library(
    name = "telemetry-subscribers",
    srcs = glob(["**/*"]),
    deps = deps,
    env = {
        "CARGO_PKG_NAME": "telemetry-subscribers",
        "CARGO_MANIFEST_DIR": "",
        "CARGO_PKG_VERSION": "0.2.0",
        "CARGO_PKG_DESCRIPTION": "Library for common telemetry and observability functionality",
        "CARGO_PKG_AUTHORS": "[Evan Chan <echan@mystenlabs.com>]",
        "OUT_DIR": "",
    },
    crate_root = "src/lib.rs",
    features = [
        "opentelemetry",
        "opentelemetry-otlp",
        "opentelemetry-proto",
        "opentelemetry_api",
        "otlp",
        "tracing-opentelemetry",
    ],
    edition = "2021",
    visibility = ["PUBLIC"],
)


rust_binary(
    name = "import-trace",
    srcs = glob(["**/*"]),
    deps = deps,
    named_deps = {
        "import-trace": ":import-trace",
    },
    env = {
        "OUT_DIR": "",
        "CARGO_MANIFEST_DIR": "",
        "CARGO_PKG_DESCRIPTION": "Library for common telemetry and observability functionality",
        "CARGO_PKG_BIN": "telemetry-subscribers",
        "CARGO_PKG_NAME": "telemetry-subscribers",
        "CARGO_PKG_VERSION": "0.2.0",
        "CARGO_PKG_AUTHORS": "[Evan Chan <echan@mystenlabs.com>]",
        "CARGO_BIN_NAME": "telemetry-subscribers",
    },
    crate_root = "src/bin/import-trace.rs",
    features = [
        "opentelemetry",
        "opentelemetry-otlp",
        "opentelemetry-proto",
        "opentelemetry_api",
        "otlp",
        "tracing-opentelemetry",
    ],
    edition = "2021",
    visibility = ["PUBLIC"],
)

