Command `new --path . Foo`:
Command `build`:
BUILDING Foo
Command `docgen --template template.md --exclude-private-fun --no-collapsed-sections --output-directory doc --references-file template.md --section-level-start 3 --toc-depth 3`:
BUILDING Foo
Generated "doc/template.md"
Generated "doc/Foo/Foo.md"

Documentation generation successful!
External Command `grep documentation doc/Foo/Foo.md`:
External Command `cat doc/template.md`:
This is a test template


This is a test template
