Command `migrate`:
Package toml does not specify an edition. As of 2024, Move requires all packages to define a language edition.

Please select one of the following editions:

1) 2024
2) legacy

Selection (default=1): 

Would you like the Move compiler to migrate your code to Move 2024? (Y/n) 
Generated changes . . .
INCLUDING DEPENDENCY MoveStdlib
BUILDING A

The following changes will be made.
============================================================

--- ./sources/mod0.move
+++ ./sources/mod0.move
@@ -5,5 +5,5 @@
-    fun t0(type: u64, enum: S, mut: bool, match: u64, for: u64): u64 {
-        if (type == match) {
-            type
-        } else if (mut) {
-            match
+    fun t0(`type`: u64, `enum`: S, `mut`: bool, `match`: u64, `for`: u64): u64 {
+        if (`type` == `match`) {
+            `type`
+        } else if (`mut`) {
+            `match`
@@ -11 +11 @@
-            enum.n + for
+            `enum`.n + `for`
--- ./sources/mod_intermodule_errors.move
+++ ./sources/mod_intermodule_errors.move
@@ -5,5 +5,5 @@
-    public fun t0(type: u64, enum: S, mut: bool, match: u64, for: u64): u64 {
-        if (type == match) {
-            type
-        } else if (mut) {
-            match
+    public fun t0(`type`: u64, `enum`: S, `mut`: bool, `match`: u64, `for`: u64): u64 {
+        if (`type` == `match`) {
+            `type`
+        } else if (`mut`) {
+            `match`
@@ -11 +11 @@
-            enum.n + for
+            `enum`.n + `for`
--- ./sources/mod_let.move
+++ ./sources/mod_let.move
@@ -6,6 +6,6 @@
-        let type = 0;
-        let enum = 1;
-        let mut = 2;
-        let match = 3;
-        let for = 3;
-        type + enum + mut + match + for
+        let `type` = 0;
+        let `enum` = 1;
+        let `mut` = 2;
+        let `match` = 3;
+        let `for` = 3;
+        `type` + `enum` + `mut` + `match` + `for`
--- ./sources/mod_let_errors.move
+++ ./sources/mod_let_errors.move
@@ -6,6 +6,6 @@
-        let type = 0;
-        let enum = 1;
-        let mut = 2;
-        let match = 3;
-        let for = 3;
-        type + enum + mut + match + for
+        let `type` = 0;
+        let `enum` = 1;
+        let `mut` = 2;
+        let `match` = 3;
+        let `for` = 3;
+        `type` + `enum` + `mut` + `match` + `for`


============================================================
Apply changes? (Y/n) 
Updating "./sources/mod0.move" . . .
Updating "./sources/mod_intermodule_errors.move" . . .
Updating "./sources/mod_let.move" . . .
Updating "./sources/mod_let_errors.move" . . .

Changes complete
Wrote patchfile out to: ./migration.patch

Recorded edition in 'Move.toml'
External Command `diff -r -s sources migration_sources`:
Files sources/mod0.move and migration_sources/mod0.move are identical
Files sources/mod_intermodule_errors.move and migration_sources/mod_intermodule_errors.move are identical
Files sources/mod_let.move and migration_sources/mod_let.move are identical
Files sources/mod_let_errors.move and migration_sources/mod_let_errors.move are identical
External Command `diff -s Move.toml Move.toml.expected`:
Files Move.toml and Move.toml.expected are identical
