Running Move unit tests
[ PASS    ] 0x42::m::t0
[ PASS    ] 0x42::m::t1
[ PASS    ] 0x42::m::t2
[ PASS    ] 0x42::m::t3
[ PASS    ] 0x42::m::t4
0x42::m::t0
Output: Ok(ChangeSet { accounts: {} })
0x42::m::t1
Output: Ok(ChangeSet { accounts: {} })
0x42::m::t2
Output: Ok(ChangeSet { accounts: {} })
0x42::m::t3
Output: Ok(ChangeSet { accounts: {} })
0x42::m::t4
Output: Ok(ChangeSet { accounts: {} })
Test result: OK. Total tests: 5; passed: 5; failed: 0
