processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 6-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# create-checkpoint
Checkpoint created: 1

task 3, line 31:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 33:
//# run Test::M1::create --args 1 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5, line 35:
//# run Test::M1::create --args 2 @B --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6, line 37:
//# run Test::M1::create --args 3 @B --sender B
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7, line 39:
//# run Test::M1::create --args 4 @B --sender B
created: object(7,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8, line 41:
//# create-checkpoint
Checkpoint created: 2

task 9, line 43:
//# run Test::M1::create --args 100 @B --sender B
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10, line 45:
//# run Test::M1::create --args 101 @B --sender B
created: object(10,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 11, line 47:
//# run Test::M1::create --args 102 @B --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12, line 49:
//# run Test::M1::create --args 103 @B --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13, line 51:
//# run Test::M1::create --args 104 @B --sender A
created: object(13,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 14, line 53:
//# create-checkpoint
Checkpoint created: 3

task 15, line 55:
//# run Test::M1::create --args 100 @B --sender B
created: object(15,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 16, line 57:
//# create-checkpoint
Checkpoint created: 4

task 17, lines 59-82:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
        "startCursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "CReUjLynvpq4dD4w6zekGxvSyBBQF2e3KG3K2Rs7oD8L",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 18, lines 84-106:
//# run-graphql --cursors {"c":4,"t":2,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": true,
        "endCursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
        "startCursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "BB6bMUxrBJX9wANzzptKnJM3bMVFKnD4xtY8DGWthaH9",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 19, lines 108-129:
//# run-graphql --cursors {"c":4,"t":3,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
        "startCursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "CReUjLynvpq4dD4w6zekGxvSyBBQF2e3KG3K2Rs7oD8L",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 20, lines 131-156:
//# run-graphql --cursors {"c":4,"t":4,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
        "startCursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "CReUjLynvpq4dD4w6zekGxvSyBBQF2e3KG3K2Rs7oD8L",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "BB6bMUxrBJX9wANzzptKnJM3bMVFKnD4xtY8DGWthaH9",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 21, lines 158-182:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjo0LCJ0Ijo2LCJpIjp0cnVlfQ",
        "startCursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "digest": "CReUjLynvpq4dD4w6zekGxvSyBBQF2e3KG3K2Rs7oD8L",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "digest": "BB6bMUxrBJX9wANzzptKnJM3bMVFKnD4xtY8DGWthaH9",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "digest": "BbHDa5U8CfAk95yFLTVTaeKwCAXhLrcpqEeG3T8z7Sii",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 2
              }
            }
          }
        }
      ]
    }
  }
}

task 22, lines 184-208:
//# run-graphql --cursors {"c":4,"t":6,"i":true}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": true,
        "endCursor": "eyJjIjo0LCJ0IjoxMSwiaSI6ZmFsc2V9",
        "startCursor": "eyJjIjo0LCJ0Ijo3LCJpIjp0cnVlfQ"
      },
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0Ijo5LCJpIjpmYWxzZX0",
          "node": {
            "digest": "Bw31PqH9Z7W1PtaGAqPtvErMbTPZeeu5Ru3cXqCtDhns",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxMCwiaSI6ZmFsc2V9",
          "node": {
            "digest": "AjdVaGXpAZmyhskAZKXzxk5zaMvaaMfmVDFVu6ApzBA9",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxMSwiaSI6ZmFsc2V9",
          "node": {
            "digest": "8f9P48WkmU8jQchKFeC6dM9WCeibp5JKdPkzJVrSGtfN",
            "effects": {
              "checkpoint": {
                "sequenceNumber": 3
              }
            }
          }
        }
      ]
    }
  }
}

task 23, lines 211-234:
//# run-graphql --cursors {"c":4,"t":11,"i":false}
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": true,
        "endCursor": null,
        "startCursor": "eyJjIjo0LCJ0IjoxMiwiaSI6dHJ1ZX0"
      },
      "edges": []
    }
  }
}
