processed 3 tasks

task 0 'print-bytecode'. lines 3-34:
// Move bytecode v7
module 1.MonomorphicEnums {


enum EnumWithTwoVariants has drop {
	One { x: u64 },
	Two { x: u64, y: u64 }
}

public f(Arg0: u64): EnumWithTwoVariants {
B0:
	0: MoveLoc[0](Arg0: u64)
	1: PackVariant(EnumDefinitionIndex(0), 0)
	2: Ret

}
public mutate(Arg0: &mut EnumWithTwoVariants, Arg1: u64, Arg2: u64) {
B0:
	0: MoveLoc[1](Arg1: u64)
	1: MoveLoc[2](Arg2: u64)
	2: PackVariant(EnumDefinitionIndex(0), 1)
	3: MoveLoc[0](Arg0: &mut EnumWithTwoVariants)
	4: WriteRef
	5: Ret

}
public is_variant_two(Arg0: &EnumWithTwoVariants): bool {
L0:	loc1: &u64
B0:
	0: CopyLoc[0](Arg0: &EnumWithTwoVariants)
	1: VariantSwitch(VariantJumpTableIndex(0))
B1:
	2: LdFalse
	3: Ret
B2:
	4: LdTrue
	5: Ret
Jump tables:
[0]:	variant_switch EnumWithTwoVariants {
		Variant0 => jump 2
		Variant1 => jump 4
	}
}
}
