processed 6 tasks

task 2 'run'. lines 37-37:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x2a::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'run'. lines 39-39:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(1),
    location: 0x2a::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(1), 1)],
}

task 4 'run'. lines 41-41:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(2),
    location: 0x2a::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(4), 1)],
}

task 5 'run'. lines 43-43:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(2),
    location: 0x2a::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(5), 1)],
}
