processed 3 tasks

task 1, lines 3-6:
//# publish-and-call --call 0x42::n::make
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x42::n,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2, line 8:
//# run 0x42::n::make
Error: Function execution failed with VMError: {
    major_status: LINKER_ERROR,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}
