processed 5 tasks

task 1 'run-graphql'. lines 6-28:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "CxPW4F6QmtoZtsRyoRHGrQjp5zGmo46LCsKrR3uwwPbT",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "CxPW4F6QmtoZtsRyoRHGrQjp5zGmo46LCsKrR3uwwPbT",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "CxPW4F6QmtoZtsRyoRHGrQjp5zGmo46LCsKrR3uwwPbT",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "CxPW4F6QmtoZtsRyoRHGrQjp5zGmo46LCsKrR3uwwPbT",
      "sequenceNumber": 0
    }
  }
}

task 2 'create-checkpoint'. lines 30-30:
Checkpoint created: 1

task 3 'create-checkpoint'. lines 33-33:
Checkpoint created: 2

task 4 'run-graphql'. lines 36-58:
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "CxPW4F6QmtoZtsRyoRHGrQjp5zGmo46LCsKrR3uwwPbT",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "7yCEVprArX5v8zgncdQ9v2NnhS8HkiibzKTP2oRyP3Sd",
        "sequenceNumber": 2
      }
    },
    "first": {
      "digest": "CxPW4F6QmtoZtsRyoRHGrQjp5zGmo46LCsKrR3uwwPbT",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "7yCEVprArX5v8zgncdQ9v2NnhS8HkiibzKTP2oRyP3Sd",
      "sequenceNumber": 2
    }
  }
}
