processed 8 tasks

init:
C: object(0,0), O: object(0,1), P: object(0,2), Q: object(0,3), R: object(0,4), S: object(0,5)

task 1 'programmable'. lines 6-8:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5928000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 10-15:
mutated: object(0,0), object(1,0), object(1,1), object(1,2), object(1,3), object(1,4)
gas summary: computation_cost: 1000000, storage_cost: 5928000,  storage_rebate: 5868720, non_refundable_storage_fee: 59280

task 3 'create-checkpoint'. lines 17-17:
Checkpoint created: 1

task 4 'advance-epoch'. lines 19-19:
Epoch advanced: 0

task 5 'run-graphql'. lines 21-45:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": [
          {
            "effects": {
              "balanceChanges": {
                "pageInfo": {
                  "hasPreviousPage": false,
                  "hasNextPage": false,
                  "startCursor": "MA",
                  "endCursor": "NQ"
                },
                "edges": [
                  {
                    "node": {
                      "amount": "2000"
                    },
                    "cursor": "MA"
                  },
                  {
                    "node": {
                      "amount": "1000"
                    },
                    "cursor": "MQ"
                  },
                  {
                    "node": {
                      "amount": "3000"
                    },
                    "cursor": "Mg"
                  },
                  {
                    "node": {
                      "amount": "4000"
                    },
                    "cursor": "Mw"
                  },
                  {
                    "node": {
                      "amount": "5000"
                    },
                    "cursor": "NA"
                  },
                  {
                    "node": {
                      "amount": "-1074280"
                    },
                    "cursor": "NQ"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 6 'run-graphql'. lines 47-71:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": [
          {
            "effects": {
              "balanceChanges": {
                "pageInfo": {
                  "hasPreviousPage": true,
                  "hasNextPage": true,
                  "startCursor": "Mw",
                  "endCursor": "NA"
                },
                "edges": [
                  {
                    "node": {
                      "amount": "4000"
                    },
                    "cursor": "Mw"
                  },
                  {
                    "node": {
                      "amount": "5000"
                    },
                    "cursor": "NA"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'run-graphql'. lines 73-97:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": [
          {
            "effects": {
              "balanceChanges": {
                "pageInfo": {
                  "hasPreviousPage": false,
                  "hasNextPage": true,
                  "startCursor": "MA",
                  "endCursor": "Mg"
                },
                "edges": [
                  {
                    "node": {
                      "amount": "2000"
                    },
                    "cursor": "MA"
                  },
                  {
                    "node": {
                      "amount": "1000"
                    },
                    "cursor": "MQ"
                  },
                  {
                    "node": {
                      "amount": "3000"
                    },
                    "cursor": "Mg"
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}
