processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-33:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6194000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 35-35:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 37-37:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 39-39:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 41-41:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 43-43:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'programmable'. lines 45-49:
created: object(7,0)
mutated: object(0,0), object(2,0), object(3,0), object(4,0), object(5,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 8876800,  storage_rebate: 6508260, non_refundable_storage_fee: 65740

task 8 'run'. lines 51-51:
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 9 'create-checkpoint'. lines 53-53:
Checkpoint created: 1

task 10 'run-graphql'. lines 56-93:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "6c1VrCKixZoK9Pmhna8fGzeSnmuYFcd3DR3n7mk44iKm",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": false,
                "hasNextPage": false,
                "startCursor": "eyJpIjowLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "digest": "TCVU1ZmKsviJsuhqvpS76f6X8qKoN2eH7VfrhQ2c4Gf",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "create"
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "3S1Bm2ipnoGVsCTMfGrRMzgEFShwfS7huM3KWJ8MMf1P",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {},
                          {
                            "module": "package",
                            "functionName": "make_immutable"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 95-132:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "6c1VrCKixZoK9Pmhna8fGzeSnmuYFcd3DR3n7mk44iKm",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": true,
                "hasNextPage": false,
                "startCursor": "eyJpIjoxLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "3S1Bm2ipnoGVsCTMfGrRMzgEFShwfS7huM3KWJ8MMf1P",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {},
                          {
                            "module": "package",
                            "functionName": "make_immutable"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
