processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-36:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6194000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 38-38:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 40-40:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 42-42:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 44-44:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 46-46:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'programmable'. lines 48-52:
created: object(7,0)
mutated: object(0,0), object(2,0), object(3,0), object(4,0), object(5,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 8876800,  storage_rebate: 6508260, non_refundable_storage_fee: 65740

task 8 'run'. lines 54-54:
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 9 'create-checkpoint'. lines 56-56:
Checkpoint created: 1

task 10 'run-graphql'. lines 59-96:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9EEJmHdyzP4mtZRzzmF1HYVYNXhke7pVFZi5zWjxkbUW",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": false,
                "hasNextPage": false,
                "startCursor": "eyJpIjowLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "digest": "4rQNs2g2o3rkZnTj8nrW29B1ny3xnuWgcJRCqDcRgzfj",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "sum"
                          },
                          {
                            "module": "M1",
                            "functionName": "create"
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "5PGio3yi8X6XdeoGD6vsGFawH8RYNCZ5adFg7zj6RBx3",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {},
                          {
                            "module": "package",
                            "functionName": "make_immutable"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 98-135:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9EEJmHdyzP4mtZRzzmF1HYVYNXhke7pVFZi5zWjxkbUW",
          "effects": {
            "dependencies": {
              "pageInfo": {
                "hasPreviousPage": true,
                "hasNextPage": false,
                "startCursor": "eyJpIjoxLCJjIjoxfQ",
                "endCursor": "eyJpIjoxLCJjIjoxfQ"
              },
              "edges": [
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "digest": "5PGio3yi8X6XdeoGD6vsGFawH8RYNCZ5adFg7zj6RBx3",
                    "kind": {
                      "__typename": "ProgrammableTransactionBlock",
                      "transactions": {
                        "nodes": [
                          {},
                          {
                            "module": "package",
                            "functionName": "make_immutable"
                          }
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
