processed 10 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-28:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5251600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 30-30:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 32-32:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [10, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [11, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 34-34:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [100, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [101, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [102, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'create-checkpoint'. lines 36-36:
Checkpoint created: 1

task 6 'run-graphql'. lines 38-57:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "events": {
              "edges": [
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "1"
                    },
                    "bcs": "AQAAAAAAAAA="
                  }
                }
              ]
            }
          }
        },
        {
          "effects": {
            "events": {
              "edges": [
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "10"
                    },
                    "bcs": "CgAAAAAAAAA="
                  }
                },
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "11"
                    },
                    "bcs": "CwAAAAAAAAA="
                  }
                }
              ]
            }
          }
        },
        {
          "effects": {
            "events": {
              "edges": [
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "100"
                    },
                    "bcs": "ZAAAAAAAAAA="
                  }
                },
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "101"
                    },
                    "bcs": "ZQAAAAAAAAA="
                  }
                },
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "102"
                    },
                    "bcs": "ZgAAAAAAAAA="
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 7 'run-graphql'. lines 59-70:
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M1"
          },
          "json": {
            "new_value": "1"
          },
          "bcs": "AQAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "json": {
            "new_value": "10"
          },
          "bcs": "CgAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "json": {
            "new_value": "11"
          },
          "bcs": "CwAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "json": {
            "new_value": "100"
          },
          "bcs": "ZAAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "json": {
            "new_value": "101"
          },
          "bcs": "ZQAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "json": {
            "new_value": "102"
          },
          "bcs": "ZgAAAAAAAAA="
        }
      ]
    }
  }
}

task 8 'run-graphql'. lines 72-91:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "events": {
              "edges": [
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "1"
                    },
                    "bcs": "AQAAAAAAAAA="
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 9 'run-graphql'. lines 93-112:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "events": {
              "edges": [
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "101"
                    },
                    "bcs": "ZQAAAAAAAAA="
                  }
                },
                {
                  "node": {
                    "sendingModule": {
                      "name": "M1"
                    },
                    "json": {
                      "new_value": "102"
                    },
                    "bcs": "ZgAAAAAAAAA="
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
