processed 6 tasks

init:
validator_0: object(0,0)

task 1 'publish'. lines 6-28:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 30-30:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 32-32:
Checkpoint created: 1

task 4 'run-graphql'. lines 34-53:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "pageInfo": {
                "hasPreviousPage": false,
                "hasNextPage": true,
                "startCursor": "MA",
                "endCursor": "MTk"
              },
              "edges": [
                {
                  "cursor": "MA"
                },
                {
                  "cursor": "MQ"
                },
                {
                  "cursor": "Mg"
                },
                {
                  "cursor": "Mw"
                },
                {
                  "cursor": "NA"
                },
                {
                  "cursor": "NQ"
                },
                {
                  "cursor": "Ng"
                },
                {
                  "cursor": "Nw"
                },
                {
                  "cursor": "OA"
                },
                {
                  "cursor": "OQ"
                },
                {
                  "cursor": "MTA"
                },
                {
                  "cursor": "MTE"
                },
                {
                  "cursor": "MTI"
                },
                {
                  "cursor": "MTM"
                },
                {
                  "cursor": "MTQ"
                },
                {
                  "cursor": "MTU"
                },
                {
                  "cursor": "MTY"
                },
                {
                  "cursor": "MTc"
                },
                {
                  "cursor": "MTg"
                },
                {
                  "cursor": "MTk"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 5 'run-graphql'. lines 55-74:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "pageInfo": {
                "hasPreviousPage": true,
                "hasNextPage": true,
                "startCursor": "MTE",
                "endCursor": "MTU"
              },
              "edges": [
                {
                  "cursor": "MTE"
                },
                {
                  "cursor": "MTI"
                },
                {
                  "cursor": "MTM"
                },
                {
                  "cursor": "MTQ"
                },
                {
                  "cursor": "MTU"
                }
              ]
            }
          }
        }
      ]
    }
  }
}
