warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_2024/folding/equal_operand_after_optimizations.move:13:5
   │
 9 │         x = 1;
   │             - This expression
   ·
12 │     let y = if (true) 1 else 1;
   │                       - Evaluates to the same value as this expression
13 │     x == y
   │     ^^^^^^ Equal operands detected in binary operation, which always evaluates to 'true'
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_2024/folding/equal_operand_after_optimizations.move:23:9
   │
21 │         y = 0;
   │             - This expression
22 │         x == x;
23 │         y == 0;
   │         ^^^^^^
   │         │    │
   │         │    Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

