warning[W08002]: redundant equal operands for binary operatiop
  ┌─ tests/move_2024/folding/equal_operand.move:6:5
  │
6 │     1 == 1;
  │     ^^^^^^
  │     │    │
  │     │    Evaluates to the same value as this expression
  │     Equal operands detected in binary operation, which always evaluates to 'true'
  │     This expression
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
  ┌─ tests/move_2024/folding/equal_operand.move:7:5
  │
7 │     {1} == 1;
  │     ^^^^^^^^
  │     ││     │
  │     ││     Evaluates to the same value as this expression
  │     │This expression
  │     Equal operands detected in binary operation, which always evaluates to 'true'
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
  ┌─ tests/move_2024/folding/equal_operand.move:8:5
  │
8 │     1 == {1};
  │     ^^^^^^^^
  │     │     │
  │     │     Evaluates to the same value as this expression
  │     Equal operands detected in binary operation, which always evaluates to 'true'
  │     This expression
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
  ┌─ tests/move_2024/folding/equal_operand.move:9:5
  │
9 │     {1} == {1};
  │     ^^^^^^^^^^
  │     ││      │
  │     ││      Evaluates to the same value as this expression
  │     │This expression
  │     Equal operands detected in binary operation, which always evaluates to 'true'
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:10:5
   │
10 │     {{{1}}} == {{{{1}}}};
   │     ^^^^^^^^^^^^^^^^^^^^
   │     │  │           │
   │     │  │           Evaluates to the same value as this expression
   │     │  This expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:14:5
   │
14 │     false == false;
   │     ^^^^^^^^^^^^^^
   │     │        │
   │     │        Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:15:5
   │
15 │     0u8 == 0u8;
   │     ^^^^^^^^^^
   │     │      │
   │     │      Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:16:5
   │
16 │     1u16 == 1u16;
   │     ^^^^^^^^^^^^
   │     │       │
   │     │       Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:17:5
   │
17 │     2u32 == 2u32;
   │     ^^^^^^^^^^^^
   │     │       │
   │     │       Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:18:5
   │
18 │     3u64 == 3u64;
   │     ^^^^^^^^^^^^
   │     │       │
   │     │       Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:19:5
   │
19 │     4u128 == 4u128;
   │     ^^^^^^^^^^^^^^
   │     │        │
   │     │        Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:20:5
   │
20 │     5u256 == 5u256;
   │     ^^^^^^^^^^^^^^
   │     │        │
   │     │        Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:21:5
   │
21 │     @a == @a;
   │     ^^^^^^^^
   │     │     │
   │     │     Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:22:5
   │
22 │     vector<vector<u8>>[] == vector[];
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │     │                       │
   │     │                       Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operatiop
   ┌─ tests/move_2024/folding/equal_operand.move:23:5
   │
23 │     vector[1] == vector[1];
   │     ^^^^^^^^^^^^^^^^^^^^^^
   │     │            │
   │     │            Evaluates to the same value as this expression
   │     Equal operands detected in binary operation, which always evaluates to 'true'
   │     This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

