processed 11 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-37:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 18392000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 38-40:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2437776, non_refundable_storage_fee: 24624

task 3 'run'. lines 41-43:
events: Event { package_id: sui, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: sui, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 99, 99, 98, 54, 101, 48, 54, 98, 100, 51, 53, 102, 54, 52, 99, 102, 101, 57, 54, 54, 52, 51, 51, 53, 51, 57, 57, 99, 98, 51, 48, 101, 98, 52, 55, 54, 49, 49, 101, 49, 99, 56, 97, 50, 56, 56, 102, 56, 48, 56, 52, 52, 57, 52, 56, 51, 98, 98, 51, 102, 50, 102, 51, 101, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 111, 92, 117, 216, 246, 218, 26, 172, 163, 34, 123, 188, 238, 245, 77, 153, 179, 41, 124, 6, 21, 158, 75, 211, 154, 61, 181, 219, 3, 222, 9, 251] }
created: object(3,0), object(3,1), object(3,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 12190400,  storage_rebate: 2746260, non_refundable_storage_fee: 27740

task 4 'run'. lines 44-44:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2437776, non_refundable_storage_fee: 24624

task 5 'advance-epoch'. lines 46-48:
Epoch advanced: 1

task 6 'run'. lines 49-51:
Error: Transaction Effects Status: Address B is denied for coin test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: AddressDeniedForCoin { address: B, coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 7 'run'. lines 52-54:
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 6794172, non_refundable_storage_fee: 68628

task 8 'run'. lines 55-55:
Error: Transaction Effects Status: Address B is denied for coin test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: AddressDeniedForCoin { address: B, coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 9 'advance-epoch'. lines 57-59:
Epoch advanced: 2

task 10 'run'. lines 60-60:
created: object(10,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2437776, non_refundable_storage_fee: 24624
