processed 22 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-72:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 21964000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 73-75:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 3936800,  storage_rebate: 2437776, non_refundable_storage_fee: 24624

task 3 'run'. lines 76-78:
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2437776, non_refundable_storage_fee: 24624

task 4 'run'. lines 79-81:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2437776, non_refundable_storage_fee: 24624

task 5 'run'. lines 82-84:
events: Event { package_id: sui, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: sui, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 54, 101, 99, 53, 53, 52, 55, 102, 50, 98, 99, 101, 48, 55, 97, 49, 48, 97, 102, 50, 57, 49, 57, 101, 97, 48, 101, 97, 57, 54, 97, 97, 102, 97, 56, 57, 54, 57, 56, 55, 56, 55, 50, 49, 50, 56, 55, 101, 98, 102, 54, 54, 102, 52, 48, 51, 100, 50, 100, 54, 99, 53, 57, 50, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 254, 127, 25, 0, 75, 139, 142, 51, 141, 181, 23, 12, 237, 165, 178, 199, 150, 191, 43, 48, 121, 145, 70, 28, 15, 98, 69, 101, 83, 67, 172, 114] }
created: object(5,0), object(5,1), object(5,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 11985200,  storage_rebate: 2746260, non_refundable_storage_fee: 27740

task 6 'run'. lines 85-87:
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'run'. lines 88-90:
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 8 'transfer-object'. lines 91-93:
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 9 'run'. lines 94-97:
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 10 'run'. lines 98-98:
mutated: object(0,0)
unwrapped: object(10,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2462400,  storage_rebate: 2618352, non_refundable_storage_fee: 26448

task 11 'advance-epoch'. lines 100-103:
Epoch advanced: 1

task 12 'run'. lines 104-106:
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 13 'run'. lines 107-109:
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 14 'run'. lines 110-112:
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 15 'run'. lines 113-115:
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(5,1)
gas summary: computation_cost: 1000000, storage_cost: 6657600,  storage_rebate: 6591024, non_refundable_storage_fee: 66576

task 16 'run'. lines 116-118:
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 17 'run'. lines 119-121:
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 18 'run'. lines 122-125:
created: object(18,0)
mutated: object(0,0)
wrapped: object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 2644800,  storage_rebate: 2437776, non_refundable_storage_fee: 24624

task 19 'run'. lines 126-126:
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 20 'advance-epoch'. lines 128-130:
Epoch advanced: 2

task 21 'run'. lines 131-131:
mutated: object(0,0)
unwrapped: object(1,1)
deleted: object(18,0)
gas summary: computation_cost: 1000000, storage_cost: 2462400,  storage_rebate: 2618352, non_refundable_storage_fee: 26448
