processed 6 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 6-26:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6209200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 28-30:
Owner: Shared
Version: 1
Contents: sui::random::Random {id: sui::object::UID {id: sui::object::ID {bytes: 0x0000000000000000000000000000000000000000000000000000000000000008}}, inner: sui::versioned::Versioned {id: sui::object::UID {id: sui::object::ID {bytes: _}}, version: 1u64}}

task 3 'programmable'. lines 31-35:
Error: Error checking transaction input objects: PostRandomCommandLimits

task 4 'programmable'. lines 36-40:
Error: Error checking transaction input objects: PostRandomCommandLimits

task 5 'programmable'. lines 41-72:
Error: Error checking transaction input objects: PostRandomCommandLimits
