warning[W04041]: use of deprecated function
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:16:9
   │
16 │         internal();
   │         ^^^^^^^^ This function is deprecated: This is a deprecated function within a deprecated module.

warning[W04038]: use of deprecated module
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:31:12
   │
31 │         f: X,
   │            ^ This module member is deprecated since the whole module is marked deprecated: Use the k module instead.

warning[W04038]: use of deprecated module
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:35:14
   │
35 │         Some(X),
   │              ^ This module member is deprecated since the whole module is marked deprecated: Use the k module instead.
36 │         Other { y: X },
   │                    - Deprecated module member used again here

warning[W04039]: use of deprecated struct
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:42:13
   │
42 │         Bad(A),
   │             ^ This struct is deprecated: Use the B struct instead.

warning[W04041]: use of deprecated function
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:67:9
   │
67 │         foo();
   │         ^^^ This function is deprecated

warning[W04041]: use of deprecated function
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:68:9
   │
68 │         bar_dep();
   │         ^^^^^^^ This function is deprecated: Use the baz function instead.

warning[W04039]: use of deprecated struct
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:71:23
   │
71 │     public fun qux(_: A) { }
   │                       ^ This struct is deprecated: Use the B struct instead.

warning[W04038]: use of deprecated module
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:75:24
   │
75 │     public fun quux(x: 0x7::l::X) {
   │                        ^^^^^^^^^ This module member is deprecated since the whole module is marked deprecated: Use the k module instead.
76 │         0x7::l::foo();
   │                 --- Deprecated module member used again here
77 │         x.bar();
   │           --- Deprecated module member used again here

warning[W04038]: use of deprecated module
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:83:12
   │
83 │         l::foo(); 
   │            ^^^ This module member is deprecated since the whole module is marked deprecated: Use the k module instead.

warning[W04037]: use of deprecated constant
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:87:9
   │
87 │         H
   │         ^ This constant is deprecated: Use the L constant instead.

warning[W04038]: use of deprecated module
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:93:11
   │
93 │         x.bar();
   │           ^^^ This module member is deprecated since the whole module is marked deprecated: Use the k module instead.

warning[W04041]: use of deprecated function
   ┌─ tests/move_2024/typing/all_deprecation_attributes.move:98:11
   │
98 │         x.lol();
   │           ^^^ This function is deprecated: Use the other function instead.

warning[W04037]: use of deprecated constant
    ┌─ tests/move_2024/typing/all_deprecation_attributes.move:105:15
    │
105 │         abort OldError
    │               ^^^^^^^^ This constant is deprecated: Use `NewError` instead.

warning[W04039]: use of deprecated struct
    ┌─ tests/move_2024/typing/all_deprecation_attributes.move:109:18
    │
109 │         let y = (A(): A);
    │                  ^    - Deprecated struct used again here
    │                  │     
    │                  This struct is deprecated: Use the B struct instead.
110 │         match (y) {
111 │             A() => (),
    │             - Deprecated struct used again here
112 │         };
113 │         A() = A();
    │         ---   - Deprecated struct used again here
    │         │      
    │         Deprecated struct used again here
114 │         let A() = A();
    │             ---   - Deprecated struct used again here
    │             │      
    │             Deprecated struct used again here

warning[W04038]: use of deprecated module
    ┌─ tests/move_2024/typing/all_deprecation_attributes.move:118:33
    │
118 │         let _ = T::Some(0x7::l::make_x());
    │                                 ^^^^^^ This module member is deprecated since the whole module is marked deprecated: Use the k module instead.
119 │         let _ = T::Other { y: 0x7::l::make_x()};
    │                                       ------ Deprecated module member used again here

warning[W04039]: use of deprecated struct
    ┌─ tests/move_2024/typing/all_deprecation_attributes.move:121:24
    │
121 │         let _ = R::Bad(A());
    │                        ^ This struct is deprecated: Use the B struct instead.

