warning[W04037]: deprecated usage
  ┌─ tests/move_2024/typing/deprecated_ty_params.move:9:19
  │
9 │         let _ = Y<X>();
  │                   ^ The struct '0x42::m::X' is deprecated

warning[W04037]: deprecated usage
   ┌─ tests/move_2024/typing/deprecated_ty_params.move:10:15
   │
10 │         let Y<X>() = Y<X>();
   │               ^ The struct '0x42::m::X' is deprecated

warning[W04037]: deprecated usage
   ┌─ tests/move_2024/typing/deprecated_ty_params.move:10:24
   │
10 │         let Y<X>() = Y<X>();
   │                        ^ The struct '0x42::m::X' is deprecated

warning[W04037]: deprecated usage
   ┌─ tests/move_2024/typing/deprecated_ty_params.move:16:11
   │
16 │         g<X>();
   │           ^ The struct '0x42::m::X' is deprecated

warning[W04037]: deprecated usage
   ┌─ tests/move_2024/typing/deprecated_ty_params.move:17:13
   │
17 │         g<Y<X>>();
   │             ^ The struct '0x42::m::X' is deprecated

warning[W04037]: deprecated usage
   ┌─ tests/move_2024/typing/deprecated_ty_params.move:18:19
   │
18 │         g<Y<Y<Y<Y<X>>>>>();
   │                   ^ The struct '0x42::m::X' is deprecated

