processed 3 tasks

task 1 'publish'. lines 8-12:
created: object(103)
written: object(102)

task 2 'publish'. lines 14-19:
Error: Transaction Effects Status: Sui Move Bytecode Verification Error. Please run the Sui Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some("Expected exactly one parameter for _::n::init  of type &mut sui::tx_context::TxContext") } }
