warning[W01004]: invalid documentation comment
  ┌─ tests/move_check/parser/doc_comments_placement.move:6:5
  │
6 │     /** There can be no doc comment on uses. */
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Documentation comment cannot be matched to a language item
  │
  = This warning can be suppressed with with '#[allow(invalid_doc_comment)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W01004]: invalid documentation comment
   ┌─ tests/move_check/parser/doc_comments_placement.move:16:9
   │
16 │         /// There can be no doc comment after last field.
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Documentation comment cannot be matched to a language item
   │
   = This warning can be suppressed with with '#[allow(invalid_doc_comment)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W01004]: invalid documentation comment
   ┌─ tests/move_check/parser/doc_comments_placement.move:23:9
   │
23 │         /// There can be no doc comment after last block member.
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Documentation comment cannot be matched to a language item
   │
   = This warning can be suppressed with with '#[allow(invalid_doc_comment)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W01004]: invalid documentation comment
   ┌─ tests/move_check/parser/doc_comments_placement.move:26:5
   │
26 │     /// There can be no doc comment after last module item.
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Documentation comment cannot be matched to a language item
   │
   = This warning can be suppressed with with '#[allow(invalid_doc_comment)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W01004]: invalid documentation comment
   ┌─ tests/move_check/parser/doc_comments_placement.move:29:1
   │
29 │ /// There can be no doc comment at end of file.
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Documentation comment cannot be matched to a language item
   │
   = This warning can be suppressed with with '#[allow(invalid_doc_comment)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

