processed 16 tasks

init:
A: object(0,0), B: object(0,1), C: object(0,2), D: object(0,3), E: object(0,4)

task 1 'publish'. lines 6-19:
created: object(1,0)
mutated: object(0,5)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run'. lines 23-23:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 25-25:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5 'run'. lines 27-27:
created: object(5,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 6 'run'. lines 29-29:
created: object(6,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7 'run'. lines 31-31:
created: object(7,0)
mutated: object(0,4)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 8 'create-checkpoint'. lines 33-33:
Checkpoint created: 2

task 9 'run-graphql'. lines 35-53:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjoyLCJ0Ijo2fQ",
        "startCursor": "eyJjIjoyLCJ0IjoyfQ"
      },
      "nodes": [
        {
          "digest": "78YAzuJPHbHXsqqj2GjiBibpAiWim7sha6MseSCN2Y6g",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "9zVSnZuHjSQZKcbrwmpkUfsRTA4J9VKqSiqzNCmycPex",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "BmipCooPMB1CHeRuFHS15q4VQ14pSLoYvuuNEfNsvZBc",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "W3YEPxp4z4LzuwoGq4kmCBiy12xv4cNuEvwusrsxDem",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        },
        {
          "digest": "HCNwnSLqsQYEju3KoQbxpa3SD5mVG6FLcggkd2ZYxHvB",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        }
      ]
    }
  }
}

task 10 'run-graphql'. lines 55-73:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjoyLCJ0IjoyfQ",
        "startCursor": "eyJjIjoyLCJ0IjoyfQ"
      },
      "nodes": [
        {
          "digest": "78YAzuJPHbHXsqqj2GjiBibpAiWim7sha6MseSCN2Y6g",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 75-93:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjoyLCJ0IjozfQ",
        "startCursor": "eyJjIjoyLCJ0IjozfQ"
      },
      "nodes": [
        {
          "digest": "9zVSnZuHjSQZKcbrwmpkUfsRTA4J9VKqSiqzNCmycPex",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        }
      ]
    }
  }
}

task 12 'run-graphql'. lines 95-113:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjoyLCJ0Ijo0fQ",
        "startCursor": "eyJjIjoyLCJ0Ijo0fQ"
      },
      "nodes": [
        {
          "digest": "BmipCooPMB1CHeRuFHS15q4VQ14pSLoYvuuNEfNsvZBc",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        }
      ]
    }
  }
}

task 13 'run-graphql'. lines 115-133:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjoyLCJ0Ijo1fQ",
        "startCursor": "eyJjIjoyLCJ0Ijo1fQ"
      },
      "nodes": [
        {
          "digest": "W3YEPxp4z4LzuwoGq4kmCBiy12xv4cNuEvwusrsxDem",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 135-153:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": "eyJjIjoyLCJ0Ijo2fQ",
        "startCursor": "eyJjIjoyLCJ0Ijo2fQ"
      },
      "nodes": [
        {
          "digest": "HCNwnSLqsQYEju3KoQbxpa3SD5mVG6FLcggkd2ZYxHvB",
          "effects": {
            "checkpoint": {
              "sequenceNumber": 2
            }
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 155-173:
Response: {
  "data": {
    "transactionBlocks": {
      "pageInfo": {
        "hasNextPage": false,
        "hasPreviousPage": false,
        "endCursor": null,
        "startCursor": null
      },
      "nodes": []
    }
  }
}
