processed 7 tasks

task 1 'create-checkpoint'. lines 6-6:
Checkpoint created: 1

task 2 'advance-epoch'. lines 8-8:
Epoch advanced: 0

task 3 'run-graphql'. lines 10-46:
Response: {
  "data": {
    "epoch": {
      "protocolConfigs": {
        "protocolVersion": 34,
        "randomBeacon": {
          "value": true
        }
      }
    },
    "object": {
      "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
      "version": 2,
      "asMoveObject": {
        "contents": {
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
          },
          "json": {
            "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
            "inner": {
              "id": "0x598f291ccc58fcd31753bcc12496c10a3ad4505a080fcb346bb4964fc5a77ea9",
              "version": "1"
            }
          }
        }
      }
    },
    "transactionBlockConnection": {
      "nodes": [
        {
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "MA",
                  "node": {
                    "__typename": "RandomnessStateCreateTransaction"
                  }
                },
                {
                  "cursor": "MQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction"
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 4 'set-random-state'. lines 49-50:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::random::update_randomness_state (function index 3) at offset 54, Abort Code: 2
Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("random") }, function: 3, instruction: 54, function_name: Some("update_randomness_state") }, 2) at command Some(0)

task 5 'create-checkpoint'. lines 52-52:
Checkpoint created: 3

task 6 'run-graphql'. lines 54-69:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "kind": {
            "__typename": "RandomnessStateUpdateTransaction",
            "epoch": {
              "epochId": 0
            },
            "randomnessRound": 1,
            "randomBytes": "SGVsbG8gU3Vp",
            "randomnessObjInitialSharedVersion": 2
          }
        }
      ]
    }
  }
}
