processed 8 tasks

task 1 'run-graphql'. lines 8-102:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "B8h8ao93BGn3TzqDae2BvMDQxQAeo5FmutfXH4yK9s5q",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZXZlbnQiLCJjIjowfQ",
                            "node": {
                              "name": "event"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZ3JvdGgxNiIsImMiOjB9",
                            "node": {
                              "name": "groth16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZ3JvdXBfb3BzIiwiYyI6MH0",
                            "node": {
                              "name": "group_ops"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2Vfc3Vic2lkeSIsImMiOjB9",
                            "node": {
                              "name": "stake_subsidy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "sui_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "sui_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x1bc6a898922bdd062d09ff2eccdd2fdc6fed3bafe88e40c8d6d62b04318e2a59",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x2491b6ded86769e0030ffb7286f464f2d46c673101928e5e9bd266547ce6fac4",
                            "size": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiY2xvYiIsImMiOjB9",
                            "node": {
                              "name": "clob"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvYl92MiIsImMiOjB9",
                            "node": {
                              "name": "clob_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3JpdGJpdCIsImMiOjB9",
                            "node": {
                              "name": "critbit"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuIiwiYyI6MH0",
                            "node": {
                              "name": "custodian"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VzdG9kaWFuX3YyIiwiYyI6MH0",
                            "node": {
                              "name": "custodian_v2"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWF0aCIsImMiOjB9",
                            "node": {
                              "name": "math"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3JkZXJfcXVlcnkiLCJjIjowfQ",
                            "node": {
                              "name": "order_query"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x0028475d1eb349945e7e155475dc17114f9fa64395f1a7207e638d62f94fcab9",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000002::object::ID,address>"
                        },
                        "json": {
                          "id": "0x0028475d1eb349945e7e155475dc17114f9fa64395f1a7207e638d62f94fcab9",
                          "name": "0x22a43eb154259bb7e181125ff8d3f8241055562bf5a9c9a2ecf910d5e9d9f20e",
                          "value": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x2f2d3fef3e40a443f0a7a616d40c2cf55d7c9eeab8fc9915df3106d9eb6ae62e",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x2f2d3fef3e40a443f0a7a616d40c2cf55d7c9eeab8fc9915df3106d9eb6ae62e",
                          "balance": {
                            "value": "30000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::sui_system_state_inner::SuiSystemStateInner>"
                        },
                        "json": {
                          "id": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                          "name": "1",
                          "value": {
                            "epoch": "0",
                            "protocol_version": "38",
                            "system_state_version": "1",
                            "validators": {
                              "total_stake": "20000000000000000",
                              "active_validators": [
                                {
                                  "metadata": {
                                    "sui_address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                                    "protocol_pubkey_bytes": [
                                      168,
                                      10,
                                      113,
                                      148,
                                      146,
                                      18,
                                      4,
                                      206,
                                      160,
                                      17,
                                      65,
                                      3,
                                      192,
                                      72,
                                      69,
                                      3,
                                      34,
                                      62,
                                      177,
                                      119,
                                      149,
                                      119,
                                      28,
                                      226,
                                      120,
                                      84,
                                      208,
                                      34,
                                      33,
                                      221,
                                      215,
                                      26,
                                      19,
                                      43,
                                      135,
                                      198,
                                      111,
                                      189,
                                      25,
                                      213,
                                      111,
                                      170,
                                      66,
                                      24,
                                      110,
                                      12,
                                      78,
                                      20,
                                      10,
                                      27,
                                      128,
                                      57,
                                      246,
                                      144,
                                      114,
                                      82,
                                      79,
                                      96,
                                      215,
                                      59,
                                      240,
                                      247,
                                      211,
                                      18,
                                      143,
                                      1,
                                      109,
                                      137,
                                      179,
                                      82,
                                      215,
                                      118,
                                      63,
                                      135,
                                      18,
                                      31,
                                      123,
                                      40,
                                      235,
                                      25,
                                      153,
                                      189,
                                      81,
                                      129,
                                      128,
                                      219,
                                      99,
                                      215,
                                      146,
                                      145,
                                      113,
                                      132,
                                      99,
                                      76,
                                      126,
                                      246
                                    ],
                                    "network_pubkey_bytes": [
                                      222,
                                      193,
                                      56,
                                      253,
                                      223,
                                      140,
                                      108,
                                      228,
                                      161,
                                      246,
                                      151,
                                      172,
                                      42,
                                      190,
                                      219,
                                      243,
                                      212,
                                      210,
                                      59,
                                      152,
                                      5,
                                      6,
                                      236,
                                      134,
                                      82,
                                      53,
                                      90,
                                      224,
                                      105,
                                      93,
                                      152,
                                      85
                                    ],
                                    "worker_pubkey_bytes": [
                                      172,
                                      116,
                                      152,
                                      220,
                                      228,
                                      127,
                                      173,
                                      148,
                                      84,
                                      44,
                                      112,
                                      162,
                                      74,
                                      125,
                                      50,
                                      95,
                                      124,
                                      147,
                                      55,
                                      36,
                                      241,
                                      143,
                                      223,
                                      60,
                                      129,
                                      224,
                                      221,
                                      102,
                                      15,
                                      35,
                                      217,
                                      101
                                    ],
                                    "proof_of_possession": [
                                      128,
                                      156,
                                      67,
                                      33,
                                      58,
                                      1,
                                      39,
                                      117,
                                      201,
                                      238,
                                      255,
                                      186,
                                      75,
                                      160,
                                      126,
                                      112,
                                      202,
                                      232,
                                      153,
                                      37,
                                      253,
                                      202,
                                      71,
                                      140,
                                      94,
                                      117,
                                      125,
                                      17,
                                      181,
                                      101,
                                      235,
                                      149,
                                      12,
                                      103,
                                      135,
                                      36,
                                      124,
                                      64,
                                      40,
                                      191,
                                      203,
                                      204,
                                      20,
                                      212,
                                      46,
                                      230,
                                      32,
                                      74
                                    ],
                                    "name": "validator-0",
                                    "description": "",
                                    "image_url": {
                                      "url": ""
                                    },
                                    "project_url": {
                                      "url": ""
                                    },
                                    "net_address": "/ip4/127.0.0.1/tcp/8000/http",
                                    "p2p_address": "/ip4/127.0.0.1/udp/8001/http",
                                    "primary_address": "/ip4/127.0.0.1/udp/8004/http",
                                    "worker_address": "/ip4/127.0.0.1/udp/8005/http",
                                    "next_epoch_protocol_pubkey_bytes": null,
                                    "next_epoch_proof_of_possession": null,
                                    "next_epoch_network_pubkey_bytes": null,
                                    "next_epoch_worker_pubkey_bytes": null,
                                    "next_epoch_net_address": null,
                                    "next_epoch_p2p_address": null,
                                    "next_epoch_primary_address": null,
                                    "next_epoch_worker_address": null,
                                    "extra_fields": {
                                      "id": "0x0e87e20caefb18e2ee817e5790b6fef9cc0d34524f8710907c0d6db94653ea84",
                                      "size": "0"
                                    }
                                  },
                                  "voting_power": "10000",
                                  "operation_cap_id": "0x902b13eec179ad10980ca88e02ad48460fc2256f947e5e6fc11f70b4eafbf17d",
                                  "gas_price": "1000",
                                  "staking_pool": {
                                    "id": "0x22a43eb154259bb7e181125ff8d3f8241055562bf5a9c9a2ecf910d5e9d9f20e",
                                    "activation_epoch": "0",
                                    "deactivation_epoch": null,
                                    "sui_balance": "20000000000000000",
                                    "rewards_pool": {
                                      "value": "0"
                                    },
                                    "pool_token_balance": "20000000000000000",
                                    "exchange_rates": {
                                      "id": "0x201a911f7e41e780023865423c3a871012f39a7e96738b71bdaf12e401edf55e",
                                      "size": "1"
                                    },
                                    "pending_stake": "0",
                                    "pending_total_sui_withdraw": "0",
                                    "pending_pool_token_withdraw": "0",
                                    "extra_fields": {
                                      "id": "0x0a30e200083c6a853800cacb6cffddca369fe8f61492443fb704381888b1e169",
                                      "size": "0"
                                    }
                                  },
                                  "commission_rate": "200",
                                  "next_epoch_stake": "20000000000000000",
                                  "next_epoch_gas_price": "1000",
                                  "next_epoch_commission_rate": "200",
                                  "extra_fields": {
                                    "id": "0xc34a474ce1d3d1bf0e2f16b9d7cefff204b6a50609e1df5ce126effd1d5c589b",
                                    "size": "0"
                                  }
                                }
                              ],
                              "pending_active_validators": {
                                "contents": {
                                  "id": "0xc37135ce51c7170214956e8235226c115ef3d400aca22c90466bfbe72dc8692d",
                                  "size": "0"
                                }
                              },
                              "pending_removals": [],
                              "staking_pool_mappings": {
                                "id": "0x529691ca068c9e33dc68f80c7ed98c453a9e280e6b77c00327c354087bf1c84c",
                                "size": "1"
                              },
                              "inactive_validators": {
                                "id": "0xe4f6a3964cd6cd5388824eeb2a6bcf7583524fd2160fd388552369a2b36f10fb",
                                "size": "0"
                              },
                              "validator_candidates": {
                                "id": "0x8ad67f5c486b4495a456ae75de20d2a00e337a069bbd949e56f948216a08e70f",
                                "size": "0"
                              },
                              "at_risk_validators": {
                                "contents": []
                              },
                              "extra_fields": {
                                "id": "0x5fcce571d17ad43525769dc3d9b013e09e436714f31cdde885594121fde97915",
                                "size": "0"
                              }
                            },
                            "storage_fund": {
                              "total_object_storage_rebates": {
                                "value": "0"
                              },
                              "non_refundable_balance": {
                                "value": "0"
                              }
                            },
                            "parameters": {
                              "epoch_duration_ms": "86400000",
                              "stake_subsidy_start_epoch": "0",
                              "max_validator_count": "150",
                              "min_validator_joining_stake": "30000000000000000",
                              "validator_low_stake_threshold": "20000000000000000",
                              "validator_very_low_stake_threshold": "15000000000000000",
                              "validator_low_stake_grace_period": "7",
                              "extra_fields": {
                                "id": "0x0f9261a6d8b9d7ac7e245efcd979699dd3c53cbd9ebdacf685057886a0e892c7",
                                "size": "0"
                              }
                            },
                            "reference_gas_price": "1000",
                            "validator_report_records": {
                              "contents": []
                            },
                            "stake_subsidy": {
                              "balance": {
                                "value": "9949700000000000000"
                              },
                              "distribution_counter": "0",
                              "current_distribution_amount": "1000000000000000",
                              "stake_subsidy_period_length": "10",
                              "stake_subsidy_decrease_rate": 1000,
                              "extra_fields": {
                                "id": "0xf8b6dddaab575813ceb114081bd52691abd8545de6d1d77c8082cc2e3dce54b0",
                                "size": "0"
                              }
                            },
                            "safe_mode": false,
                            "safe_mode_storage_rewards": {
                              "value": "0"
                            },
                            "safe_mode_computation_rewards": {
                              "value": "0"
                            },
                            "safe_mode_storage_rebates": "0",
                            "safe_mode_non_refundable_storage_fee": "0",
                            "epoch_start_timestamp_ms": "0",
                            "extra_fields": {
                              "id": "0xee35685b237690eb5bf0b1542828b6ff1fb57b320ae1c102c8233b2188e6013a",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x6ee5941cdbb5b8ddf6c1706175c832c6c7ae26849058c9050642ae4fc3ec0a1c",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x6ee5941cdbb5b8ddf6c1706175c832c6c7ae26849058c9050642ae4fc3ec0a1c",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x76658f5a8794fdd5ca04c6088a4608839a921054160ee50845a0c7180f1471ba",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::PoolTokenExchangeRate>"
                        },
                        "json": {
                          "id": "0x76658f5a8794fdd5ca04c6088a4608839a921054160ee50845a0c7180f1471ba",
                          "name": "0",
                          "value": {
                            "sui_amount": "0",
                            "pool_token_amount": "0"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x902b13eec179ad10980ca88e02ad48460fc2256f947e5e6fc11f70b4eafbf17d",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::validator_cap::UnverifiedValidatorOperationCap"
                        },
                        "json": {
                          "id": "0x902b13eec179ad10980ca88e02ad48460fc2256f947e5e6fc11f70b4eafbf17d",
                          "authorizer_validator_address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0x984bf655be18c421272d3984a11c255d9fc75d1b4fb05143073dbd03698d8b77",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x984bf655be18c421272d3984a11c255d9fc75d1b4fb05143073dbd03698d8b77",
                          "decimals": 9,
                          "name": "Sui",
                          "symbol": "SUI",
                          "description": "",
                          "icon_url": null
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0xa1a25ce6cef3c8b0bdfc979cb10609eb7b2c0dedb8e467d0855785d375c735b9",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::PerTypeList>"
                        },
                        "json": {
                          "id": "0xa1a25ce6cef3c8b0bdfc979cb10609eb7b2c0dedb8e467d0855785d375c735b9",
                          "name": "0",
                          "value": {
                            "id": "0x35c1af0717032e1e2cf11b28f0e63b314dec3bd9022862a3e7ed96c5b8c3be05",
                            "denied_count": {
                              "id": "0x7b7f22e0d4d2d9db5c2879b91b12260451422b93f40bbfc83aada17ae5bba22c",
                              "size": "0"
                            },
                            "denied_addresses": {
                              "id": "0x168dbe67f7d045c607bbb9620ce1e5c2bf3a6d7e3e90e87a83b3cc2e19a4effc",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorStateInner>"
                        },
                        "json": {
                          "id": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "active_jwks": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0xd3048a7af6ebe5715cb5a68ed23e4c402959243324a48b8b00b1538b29b526b5",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x0000000000000000000000000000000000000000000000000000000000000002::random::RandomInner>"
                        },
                        "json": {
                          "id": "0xd3048a7af6ebe5715cb5a68ed23e4c402959243324a48b8b00b1538b29b526b5",
                          "name": "1",
                          "value": {
                            "version": "1",
                            "epoch": "0",
                            "randomness_round": "0",
                            "random_bytes": []
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOSwiYyI6MH0",
                  "node": {
                    "address": "0xd6004763d5482bb63888936b742375d96d6b7b895f2a65f6b6c4545714d9ec48",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                        },
                        "json": {
                          "id": "0xd6004763d5482bb63888936b742375d96d6b7b895f2a65f6b6c4545714d9ec48",
                          "pool_id": "0x22a43eb154259bb7e181125ff8d3f8241055562bf5a9c9a2ecf910d5e9d9f20e",
                          "stake_activation_epoch": "0",
                          "principal": {
                            "value": "20000000000000000"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                  },
                  "amount": "30000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                },
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "8CRSSoemgecpp3k9k3ozuUDv8boeJ27Vfrm6m1zKmku5"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "ESgY196dRbaE1RPBzN2WDJc5GDDfqnBGKwxKVXJzVcrw"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "4Ee9CRAY1viqBmutpgpG7ryn2G5cMR6vW1iMLWUTBQXG"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "8LCTchM1fv6cxWD4H7ZySvCswTRQJmCfyUv7xzPSq85j"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "9yYHs4fZnAgetuW5gBzQEs8QVAs5zzkSmAMEtyB1i4Qh"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "digest": "BJc88gLeG9JP6Yzk8z7EMm4J3YHeiYvke8nXV361HGw2"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "GxmMANQGLvHwZRPBtdDqDL3T4VWwFzUyd88YFkoEu5AY"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "DnUaRQtfRbfQbFut5WxivhmbK1UGF1MsTxueCyNMW6V6"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000dee9",
                    "digest": "3RcYeUi8Lfj33F1ejav5ch69F8x62EdpCUbvdzSpvbWr"
                  }
                },
                {
                  "address": "0x0028475d1eb349945e7e155475dc17114f9fa64395f1a7207e638d62f94fcab9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0028475d1eb349945e7e155475dc17114f9fa64395f1a7207e638d62f94fcab9",
                    "digest": "83su5LMPLU8R3HpawvyTBTx6esxgcLagPPVnhWmcSsx7"
                  }
                },
                {
                  "address": "0x2f2d3fef3e40a443f0a7a616d40c2cf55d7c9eeab8fc9915df3106d9eb6ae62e",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x2f2d3fef3e40a443f0a7a616d40c2cf55d7c9eeab8fc9915df3106d9eb6ae62e",
                    "digest": "B3QrWS6pBP969EFkEiX1i9kEJoi7ThuDrPNKvmbKd1US"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                    "digest": "DKnfA8rUynGXss2Sohtc8KTvSoGAetJJD2MhnLuDFVLH"
                  }
                },
                {
                  "address": "0x6ee5941cdbb5b8ddf6c1706175c832c6c7ae26849058c9050642ae4fc3ec0a1c",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6ee5941cdbb5b8ddf6c1706175c832c6c7ae26849058c9050642ae4fc3ec0a1c",
                    "digest": "B4ndAJ3LQASXbAJ34G4sAE6wBArQveaeWBuHYeB7XDiC"
                  }
                },
                {
                  "address": "0x76658f5a8794fdd5ca04c6088a4608839a921054160ee50845a0c7180f1471ba",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x76658f5a8794fdd5ca04c6088a4608839a921054160ee50845a0c7180f1471ba",
                    "digest": "Ha5NgDkQtwZZymRAvLPiFuomykCixRauHMspzPzLh9jD"
                  }
                },
                {
                  "address": "0x902b13eec179ad10980ca88e02ad48460fc2256f947e5e6fc11f70b4eafbf17d",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x902b13eec179ad10980ca88e02ad48460fc2256f947e5e6fc11f70b4eafbf17d",
                    "digest": "ozJXW4FTjywMqyVEhNjbTGAMbLsAnP39tEASdN9kAgL"
                  }
                },
                {
                  "address": "0x984bf655be18c421272d3984a11c255d9fc75d1b4fb05143073dbd03698d8b77",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x984bf655be18c421272d3984a11c255d9fc75d1b4fb05143073dbd03698d8b77",
                    "digest": "2rF5knbNcgUYchEdv659bzQHYr4Hn9M2G9cg9owHjizD"
                  }
                },
                {
                  "address": "0xa1a25ce6cef3c8b0bdfc979cb10609eb7b2c0dedb8e467d0855785d375c735b9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xa1a25ce6cef3c8b0bdfc979cb10609eb7b2c0dedb8e467d0855785d375c735b9",
                    "digest": "CypAsRyALTKJXCtsMrrB1CMzirY34iBty5Tgip1nSBqi"
                  }
                },
                {
                  "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xcfecb053c69314e75f36561910f3535dd466b6e2e3593708f370e80424617ae7",
                    "digest": "Hp7uCyJnGNPDw7RndqG5WrEsJYWrurGuixC17jyxFuN8"
                  }
                },
                {
                  "address": "0xd3048a7af6ebe5715cb5a68ed23e4c402959243324a48b8b00b1538b29b526b5",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd3048a7af6ebe5715cb5a68ed23e4c402959243324a48b8b00b1538b29b526b5",
                    "digest": "CadrGMTxiQ7LJwiNvutHtvnqFBzAMiT2GmGLKDYBw5j4"
                  }
                },
                {
                  "address": "0xd6004763d5482bb63888936b742375d96d6b7b895f2a65f6b6c4545714d9ec48",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd6004763d5482bb63888936b742375d96d6b7b895f2a65f6b6c4545714d9ec48",
                    "digest": "FNp4qET9pQSZRyyGA35YxVKyaQn4agMj4Dxzwtx4xvKm"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "B8h8ao93BGn3TzqDae2BvMDQxQAeo5FmutfXH4yK9s5q"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3 'create-checkpoint'. lines 106-106:
Checkpoint created: 1

task 4 'run-graphql'. lines 108-183:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "B8h8ao93BGn3TzqDae2BvMDQxQAeo5FmutfXH4yK9s5q"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "28w3Mp2x4vt94bq4TejrbLcfMsMaevDyPz6h98sgcnw4"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "CHyKA8xirNCGtcDMLJcxBZsxGyAA7DNrzDEVodxZzNn"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6 'advance-epoch'. lines 187-187:
Epoch advanced: 0

task 7 'run-graphql'. lines 189-276:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "9RJkHDq2KNvb6utbcqaY7BMJQ6Fw8HBnshi8z53dVman",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 38,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "B8h8ao93BGn3TzqDae2BvMDQxQAeo5FmutfXH4yK9s5q"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "9Ke6cgqonjWKvYhH7ap2Wy6QoeAvXztswWrNyJnd9pLG"
                  }
                },
                {
                  "address": "0x1b0921e7106d60b88b529b2288feab92e84231ede465477654b57863c11c026b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1b0921e7106d60b88b529b2288feab92e84231ede465477654b57863c11c026b",
                    "digest": "6o7wqLg6A6beKMwvCecLKpbxMopKWPkLhCZPFjqs6oCd"
                  }
                },
                {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                    "digest": "2SbyAkWjWoTBXVTwVQ1XVHgUbvCPxCktzy8Qz7No2wpC"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": true,
                  "outputState": null
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "9RJkHDq2KNvb6utbcqaY7BMJQ6Fw8HBnshi8z53dVman"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
