current frame stack:
  function: test (m.move:27)
    scope 0 :
  function: foo (m.move:0)
    scope 0 :
  function: __inlined__ (m.move:11)
    scope 0 :
current frame stack:
  function: test (m.move:27)
    scope 0 :
  function: foo (m.move:0)
    scope 0 :
  function: __inlined__ (m.move:11)
    scope 0 :
  function: __inlined__ (m_dep.move:4)
    scope 0 :
current frame stack:
  function: test (m.move:27)
    scope 0 :
  function: foo (m.move:22)
    scope 0 :
      v : 12
      type: u64

current frame stack:
  function: test (m.move:27)
    scope 0 :
  function: foo (m.move:22)
    scope 0 :
      v : 12
      type: u64

  function: __inlined__ (m_dep.move:4)
    scope 0 :
line breakpoints
  m_dep.move
    4
