processed 7 tasks

task 0 'publish'. lines 1-17:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: FIELD_EXISTS_MUTABLE_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 5)],
}

task 1 'publish'. lines 19-36:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: FIELD_EXISTS_MUTABLE_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 2 'publish'. lines 38-54:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: FIELD_EXISTS_MUTABLE_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 3 'publish'. lines 56-74:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: FIELD_EXISTS_MUTABLE_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 5)],
}

task 5 'publish'. lines 96-118:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::invalid'. Got VMError: {
    major_status: WRITEREF_EXISTS_BORROW_ERROR,
    sub_status: None,
    location: 0x1::invalid,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 21)],
}

task 6 'publish'. lines 120-142:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::invalid'. Got VMError: {
    major_status: READREF_EXISTS_MUTABLE_BORROW_ERROR,
    sub_status: None,
    location: 0x1::invalid,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 17)],
}
