processed 5 tasks

task 0 'publish'. lines 1-37:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: WRITEREF_EXISTS_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 30)],
}

task 1 'publish'. lines 39-76:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: WRITEREF_EXISTS_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 32)],
}

task 2 'publish'. lines 78-114:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: WRITEREF_EXISTS_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 32)],
}

task 3 'publish'. lines 116-155:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: WRITEREF_EXISTS_BORROW_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 54)],
}

task 4 'publish'. lines 157-197:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::o'. Got VMError: {
    major_status: COPYLOC_UNAVAILABLE_ERROR,
    sub_status: None,
    location: 0x1::o,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 13)],
}
