processed 2 tasks

task 0 'run'. lines 1-16:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: VEC_UPDATE_EXISTS_MUTABLE_BORROW_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 10)],
}

task 1 'run'. lines 17-32:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: VEC_UPDATE_EXISTS_MUTABLE_BORROW_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 10)],
}
