// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY, Generated by ./scripts/execution-layer

use std::sync::Arc;

use sui_protocol_config::ProtocolConfig;
use sui_types::error::SuiResult;

pub use executor::Executor;
pub mod executor;

mod latest;
mod v0;
mod v1;
mod v2;

#[cfg(test)]
mod tests;

pub fn executor(
    protocol_config: &ProtocolConfig,
    silent: bool,
) -> SuiResult<Arc<dyn Executor + Send + Sync>> {
    let version = protocol_config.execution_version_as_option().unwrap_or(0);
    Ok(match version {
        0 => Arc::new(v0::Executor::new(protocol_config, silent)?),

        1 => Arc::new(v1::Executor::new(protocol_config, silent)?),

        2 => Arc::new(v2::Executor::new(protocol_config, silent)?),

        3 => Arc::new(latest::Executor::new(protocol_config, silent)?),

        v => panic!("Unsupported execution version {v}"),
    })
}
