processed 2 tasks

task 0 'publish'. lines 4-14:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Access to Move global storage is not allowed. Found in function no: [Exists(StructDefinitionIndex(0))]\"), command: None } }" }

task 1 'publish'. lines 16-25:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Access to Move global storage is not allowed. Found in function no: [ExistsGeneric(StructDefInstantiationIndex(0))]\"), command: None } }" }
