processed 2 tasks

task 0 'publish'. lines 4-14:
Error: Failed to verify the Move module, reason: "Access to Move global storage is not allowed. Found in function no: [Exists(StructDefinitionIndex(0))]".

task 1 'publish'. lines 16-25:
Error: Failed to verify the Move module, reason: "Access to Move global storage is not allowed. Found in function no: [ExistsGeneric(StructDefInstantiationIndex(0))]".
