processed 2 tasks

task 0 'publish'. lines 4-20:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Access to Move global storage is not allowed. Found in function no: [MoveFrom(StructDefinitionIndex(0))]\"), command: None } }" }

task 1 'publish'. lines 22-38:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Access to Move global storage is not allowed. Found in function no: [MoveFromGeneric(StructDefInstantiationIndex(0))]\"), command: None } }" }
