bug[ICE12003]: INTERNAL COMPILER ERROR
   ┌─ tests/move_2024/matching/guard_backtrack_5.move:16:20
   │
16 │         let o: P<P<u64>> = P::Both(P::Both(0, 1), P::Both(2, 3));
   │                    ^^^ ICE base type constraint failed: &(u64: copy+drop+store)

   │
   = The Move compiler has encountered an internal compiler error.
      Please report this this issue to the Mysten Labs Move language team,
      including this error and any relevant code, to the Mysten Labs issue tracker
      at : https://github.com/MystenLabs/sui/issues

bug[ICE12003]: INTERNAL COMPILER ERROR
   ┌─ tests/move_2024/matching/guard_backtrack_5.move:19:21
   │
19 │             P::Both(P::Both(m, n), P::Both(q, r)) if (&(*q + *r) == &5) => m + n + q + r,
   │                     ^^^^^^^^^^^^^ ICE base type constraint failed: &(0x42::m::Pair<(u64: copy+drop+store)>: drop)

   │
   = The Move compiler has encountered an internal compiler error.
      Please report this this issue to the Mysten Labs Move language team,
      including this error and any relevant code, to the Mysten Labs issue tracker
      at : https://github.com/MystenLabs/sui/issues

