processed 34 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 19-46:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 48:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 50-52:
//# programmable --sender A --inputs object(1,5) 100 object(1,1)
//> 0: sui::coin::mint<P0::fake::FAKE>(Input(0), Input(1));
//> MergeCoins(Input(2), [Result(0)]);
mutated: object(0,0), object(1,1), object(1,5)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 3972672, non_refundable_storage_fee: 40128

task 4, line 54:
//# create-checkpoint
Checkpoint created: 2

task 5, line 56:
//# transfer-object 1,2 --sender A --recipient B
mutated: object(0,0), object(1,2)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 6, line 58:
//# create-checkpoint
Checkpoint created: 3

task 7, line 60:
//# transfer-object 1,3 --sender A --recipient B
mutated: object(0,0), object(1,3)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 9, line 64:
//# create-checkpoint
Checkpoint created: 4

task 11, line 68:
//# create-checkpoint
Checkpoint created: 5

task 13, line 72:
//# create-checkpoint
Checkpoint created: 6

task 15, line 76:
//# create-checkpoint
Checkpoint created: 7

task 16, lines 78-99:
//# run-graphql --cursors {"c":2,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "700"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999982296272"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 3,
                  "totalBalance": "700"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 17, lines 101-122:
//# run-graphql --cursors {"c":3,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "500"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981273168"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "500"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 18, lines 124-145:
//# run-graphql --cursors {"c":4,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "400"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980250064"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "400"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 19, line 147:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 3
Objects snapshot updated to [0 to 3)

task 20, line 149:
//# create-checkpoint
Checkpoint created: 8

task 21, lines 151-172:
//# run-graphql --cursors {"c":2,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "700"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999982296272"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 3,
                  "totalBalance": "700"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 22, lines 174-195:
//# run-graphql --cursors {"c":3,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "500"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981273168"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "500"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 23, lines 197-218:
//# run-graphql --cursors {"c":4,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "400"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980250064"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "400"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 24, line 220:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 4
Objects snapshot updated to [0 to 4)

task 25, line 222:
//# create-checkpoint
Checkpoint created: 9

task 26, lines 224-245:
//# run-graphql --cursors {"c":2,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 27, lines 247-268:
//# run-graphql --cursors {"c":3,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "500"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999981273168"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 2,
                  "totalBalance": "500"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 28, lines 270-291:
//# run-graphql --cursors {"c":4,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": {
            "fakeCoinBalance": {
              "totalBalance": "400"
            },
            "allBalances": {
              "nodes": [
                {
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "299999980250064"
                },
                {
                  "coinType": {
                    "repr": "0x4cb538cc5d434cbcb404ea346e0fcd175e5db3edccbada62a489de17da4e81f1::fake::FAKE"
                  },
                  "coinObjectCount": 1,
                  "totalBalance": "400"
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 29, line 294:
//# force-object-snapshot-catchup --start-cp 0 --end-cp 6
Objects snapshot updated to [0 to 6)

task 30, line 296:
//# create-checkpoint
Checkpoint created: 10

task 31, lines 298-319:
//# run-graphql --cursors {"c":2,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 32, lines 321-342:
//# run-graphql --cursors {"c":3,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 33, lines 344-365:
//# run-graphql --cursors {"c":4,"t":1,"tc":1}
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "sender": null
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 9,
          "column": 9
        }
      ],
      "path": [
        "transactionBlocks",
        "nodes",
        0,
        "sender",
        "allBalances"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
