processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-39:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 41-41:
Checkpoint created: 1

task 3 'programmable'. lines 43-45:
mutated: object(0,0), object(1,1), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 3972672, non_refundable_storage_fee: 40128

task 4 'create-checkpoint'. lines 47-47:
Checkpoint created: 2

task 5 'run-graphql'. lines 49-90:
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6 'run-graphql'. lines 92-133:
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'transfer-object'. lines 135-135:
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 8 'transfer-object'. lines 137-137:
mutated: object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 9 'create-checkpoint'. lines 139-139:
Checkpoint created: 3

task 10 'run-graphql'. lines 141-194:
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        },
        {
          "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          },
          {
            "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'create-checkpoint'. lines 198-198:
Checkpoint created: 4

task 14 'create-checkpoint'. lines 202-202:
Checkpoint created: 5

task 16 'create-checkpoint'. lines 206-206:
Checkpoint created: 6

task 17 'run-graphql'. lines 208-249:
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IO0LbBHA6s+0nIIwkOrvpbjy1P6Na/9gk4utGx/H7Y9aAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xed0b6c11c0eacfb49c823090eaefa5b8f2d4fe8d6bff60938bad1b1fc7ed8f5a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IDoasqQrBZEgmkswaO11oVhWiiJPSykBQSZN2uIlXB3TAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x3a1ab2a42b0591209a4b3068ed75a158568a224f4b290141264ddae2255c1dd3",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IMBU6ZryfexuK3xJIffTvXQjLrWVUvl40LnqQFvQhrSyAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xc054e99af27dec6e2b7c4921f7d3bd74232eb59552f978d0b9ea405bd086b4b2",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18 'force-object-snapshot-catchup'. lines 251-251:
Objects snapshot updated to [0 to 4)

task 19 'create-checkpoint'. lines 253-253:
Checkpoint created: 7

task 20 'run-graphql'. lines 255-284:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
