processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-41:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 3 'programmable'. lines 45-47:
mutated: object(0,0), object(1,1), object(1,5)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 3972672, non_refundable_storage_fee: 40128

task 4 'create-checkpoint'. lines 49-49:
Checkpoint created: 2

task 5 'run-graphql'. lines 51-92:
Response: {
  "data": {
    "queryCoinsAtLatest": {
      "edges": [
        {
          "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAgAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAgAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoins": {
      "coins": {
        "edges": [
          {
            "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAgAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 6 'run-graphql'. lines 94-135:
Response: {
  "data": {
    "queryCoinsAtChkpt1": {
      "edges": [
        {
          "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1": {
      "coins": {
        "edges": [
          {
            "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'transfer-object'. lines 137-137:
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 8 'transfer-object'. lines 139-139:
mutated: object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 2310400,  storage_rebate: 2287296, non_refundable_storage_fee: 23104

task 9 'create-checkpoint'. lines 141-141:
Checkpoint created: 3

task 10 'run-graphql'. lines 143-196:
Response: {
  "data": {
    "queryCoins": {
      "edges": [
        {
          "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100100"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                "balance": {
                  "value": "100100"
                }
              }
            }
          }
        },
        {
          "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        },
        {
          "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAwAAAAAAAAA=",
          "node": {
            "owner": {
              "owner": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAwAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                "balance": {
                  "value": "300"
                }
              }
            }
          }
        }
      ]
    },
    "addressCoinsA": {
      "coins": {
        "edges": [
          {
            "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                  "balance": {
                    "value": "100100"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "addressCoinsB": {
      "coins": {
        "edges": [
          {
            "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAwAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                  "balance": {
                    "value": "300"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'create-checkpoint'. lines 200-200:
Checkpoint created: 4

task 14 'create-checkpoint'. lines 204-204:
Checkpoint created: 5

task 16 'create-checkpoint'. lines 208-208:
Checkpoint created: 6

task 17 'run-graphql'. lines 210-251:
Response: {
  "data": {
    "queryCoinsAtChkpt1BeforeSnapshotCatchup": {
      "edges": [
        {
          "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                "balance": {
                  "value": "100"
                }
              }
            }
          }
        },
        {
          "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
          "node": {
            "consistentStateForEachCoin": {
              "owner": {
                "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e",
                "coins": {
                  "edges": [
                    {
                      "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                            "balance": {
                              "value": "100"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                            "balance": {
                              "value": "200"
                            }
                          }
                        }
                      }
                    },
                    {
                      "cursor": "IKT6/naSEp68xu/0xB1Giwa10O5PX2EfSab0i57acN4BAQAAAAAAAAA=",
                      "node": {
                        "contents": {
                          "json": {
                            "id": "0xa4fafe7692129ebcc6eff4c41d468b06b5d0ee4f5f611f49a6f48b9eda70de01",
                            "balance": {
                              "value": "300"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            },
            "contents": {
              "json": {
                "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                "balance": {
                  "value": "200"
                }
              }
            }
          }
        }
      ]
    },
    "queryAddressCoinsAtChkpt1BeforeSnapshotCatchup": {
      "coins": {
        "edges": [
          {
            "cursor": "IJm+ZV0jAjpw/L9olTOc8LoBTR8/cEetUqMkLTT0DjtXAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0x99be655d23023a70fcbf6895339cf0ba014d1f3f7047ad52a3242d34f40e3b57",
                  "balance": {
                    "value": "100"
                  }
                }
              }
            }
          },
          {
            "cursor": "IKFAoAbXRYFfAT4SNTnWyXgH7rvhFmQadZziF4ABubdqAQAAAAAAAAA=",
            "node": {
              "contents": {
                "json": {
                  "id": "0xa140a006d745815f013e123539d6c97807eebbe116641a759ce2178001b9b76a",
                  "balance": {
                    "value": "200"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 18 'force-object-snapshot-catchup'. lines 253-253:
Objects snapshot updated to [0 to 4)

task 19 'create-checkpoint'. lines 255-255:
Checkpoint created: 7

task 20 'run-graphql'. lines 257-286:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "queryCoinsAtChkpt1AfterSnapshotCatchup"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
