processed 34 tasks

init:
A: object(0,0)

task 1 'publish'. lines 12-85:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 11012400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 87-89:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3549200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 91-91:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 4 'view-object'. lines 93-93:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 5 'programmable'. lines 95-97:
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6004000,  storage_rebate: 3513708, non_refundable_storage_fee: 35492

task 6 'view-object'. lines 99-99:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 7 'view-object'. lines 101-101:
Owner: Object ID: ( fake(5,0) )
Version: 3
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 1u64}

task 8 'create-checkpoint'. lines 103-103:
Checkpoint created: 1

task 9 'run-graphql'. lines 105-191:
Response: {
  "data": {
    "parent_version_2_no_dof": {
      "address": "0x25418846f7ffe5ee3bb2de5a600ee742d016159f0ecc9c24c88a4a17ad448dc3",
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_3_has_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      },
      "child_dof_state_consistent": {
        "value": {
          "address": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
          "owner": {
            "parent": {
              "dynamicFields": {
                "edges": []
              }
            }
          }
        }
      }
    },
    "child_version_2_no_parent": {
      "address": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
      "owner": {}
    },
    "child_version_3_has_parent": {
      "owner": {
        "parent": {
          "address": "0x474cb5cb10c38c5bd72f7e87a0dc4b4dd109440a17ec5ada98081c9a6a392383"
        }
      }
    }
  }
}

task 10 'programmable'. lines 193-195:
created: object(10,0), object(10,1), object(10,2)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 9910400,  storage_rebate: 3513708, non_refundable_storage_fee: 35492

task 11 'view-object'. lines 197-197:
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 12 'view-object'. lines 199-199:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 2u64}

task 13 'create-checkpoint'. lines 201-201:
Checkpoint created: 2

task 14 'run-graphql'. lines 203-263:
Response: {
  "data": {
    "parent_version_4_show_dof_and_dfs": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEQIaFkdx7vqo7e+tEQHg2K3Nos2jyEMWQz39kFyRIdQAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IF2pqGcLv056m9dwzboKmSsrIw4m56KqTv0XefkEBuDgAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IKfuuYBZoFmZiJgOfJccjObQ0g/NGr3ChZwNFH48cqW1AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          }
        ]
      }
    },
    "parent_version_3_only_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_3_cursor_at_parent_version_3": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_version_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 15 'run-graphql'. lines 265-302:
Response: {
  "data": {
    "parent_version_3": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
              "count": "2"
            }
          }
        }
      },
      "dfNotAvailableYet": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_4": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
              "count": "2"
            }
          }
        }
      },
      "dfAddedHere": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    }
  }
}

task 16 'programmable'. lines 305-306:
created: object(16,0), object(16,1), object(16,2)
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 8603200,  storage_rebate: 2219580, non_refundable_storage_fee: 22420

task 17 'view-object'. lines 308-308:
Owner: Account Address ( A )
Version: 5
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 18 'view-object'. lines 310-310:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 2u64}

task 19 'create-checkpoint'. lines 312-312:
Checkpoint created: 3

task 20 'run-graphql'. lines 314-364:
Response: {
  "data": {
    "parent_version_4_has_4_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEQIaFkdx7vqo7e+tEQHg2K3Nos2jyEMWQz39kFyRIdQAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IF2pqGcLv056m9dwzboKmSsrIw4m56KqTv0XefkEBuDgAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IKfuuYBZoFmZiJgOfJccjObQ0g/NGr3ChZwNFH48cqW1AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_5_has_7_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ID6P1eZZLHfFNjRyoLXEZ9B+t9XRi1Rd3Kmw1k4xndi8AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IEQIaFkdx7vqo7e+tEQHg2K3Nos2jyEMWQz39kFyRIdQAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IErIWASFvZ2bKCntxuOmGUX7pkmR8Ee9E3CBzHBrfLSWAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IF2pqGcLv056m9dwzboKmSsrIw4m56KqTv0XefkEBuDgAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IJGnxMEs3n6Z9TGcRWP31gf/psqDyX7Ol9VYDGaRCr99AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IKfuuYBZoFmZiJgOfJccjObQ0g/NGr3ChZwNFH48cqW1AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          }
        ]
      }
    },
    "parent_version_5_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 21 'programmable'. lines 366-367:
mutated: object(0,0), object(2,1)
deleted: object(10,0), object(10,1), object(10,2)
gas summary: computation_cost: 1000000, storage_cost: 2242000,  storage_rebate: 8517168, non_refundable_storage_fee: 86032

task 22 'view-object'. lines 369-369:
Owner: Account Address ( A )
Version: 6
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 23 'view-object'. lines 371-371:
Owner: Object ID: ( fake(5,0) )
Version: 4
Contents: Test::M1::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 2u64}

task 24 'create-checkpoint'. lines 373-373:
Checkpoint created: 4

task 25 'run-graphql'. lines 375-425:
Response: {
  "data": {
    "parent_version_4_has_df1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEQIaFkdx7vqo7e+tEQHg2K3Nos2jyEMWQz39kFyRIdQAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IF2pqGcLv056m9dwzboKmSsrIw4m56KqTv0XefkEBuDgAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IKfuuYBZoFmZiJgOfJccjObQ0g/NGr3ChZwNFH48cqW1AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ID6P1eZZLHfFNjRyoLXEZ9B+t9XRi1Rd3Kmw1k4xndi8AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IEQIaFkdx7vqo7e+tEQHg2K3Nos2jyEMWQz39kFyRIdQAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IErIWASFvZ2bKCntxuOmGUX7pkmR8Ee9E3CBzHBrfLSWAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IF2pqGcLv056m9dwzboKmSsrIw4m56KqTv0XefkEBuDgAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IJGnxMEs3n6Z9TGcRWP31gf/psqDyX7Ol9VYDGaRCr99AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IKfuuYBZoFmZiJgOfJccjObQ0g/NGr3ChZwNFH48cqW1AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 26 'run-graphql'. lines 427-458:
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4": null
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}

task 28 'create-checkpoint'. lines 462-462:
Checkpoint created: 5

task 30 'create-checkpoint'. lines 466-466:
Checkpoint created: 6

task 31 'force-object-snapshot-catchup'. lines 468-468:
Objects snapshot updated to [0 to 5)

task 32 'run-graphql'. lines 470-520:
Response: {
  "data": {
    "parent_version_4_outside_consistent_range": null,
    "parent_version_4_paginated_outside_consistent_range": null,
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "ID6P1eZZLHfFNjRyoLXEZ9B+t9XRi1Rd3Kmw1k4xndi8AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IEdMtcsQw4xb1y9+h6DcS03RCUQKF+xa2pgIHJpqOSODAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0x5fab7f2559f39354da23e6e963cf4e65f3720e1bd6d38730fc1d5f49a554a198",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IErIWASFvZ2bKCntxuOmGUX7pkmR8Ee9E3CBzHBrfLSWAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IJGnxMEs3n6Z9TGcRWP31gf/psqDyX7Ol9VYDGaRCr99AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 33 'run-graphql'. lines 522-553:
Response: {
  "data": {
    "parent_version_4": null,
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}
