processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 15-32:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 34-34:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 36-36:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 5 'run-graphql'. lines 40-68:
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "if_the_other_does_not": {
      "nodes": []
    }
  }
}

task 6 'run'. lines 70-70:
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'run'. lines 72-72:
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 74-74:
Checkpoint created: 2

task 9 'run-graphql'. lines 76-104:
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": []
    }
  }
}

task 10 'run-graphql'. lines 106-121:
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                "value": "0"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                "value": "1"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xaaa2997ee28f7af80fe9f0d02e6987cb25f6828bbecb0d5213643419ffb040d7",
                "value": "2"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                "value": "3"
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 123-148:
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                "value": "0"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                "value": "1"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xaaa2997ee28f7af80fe9f0d02e6987cb25f6828bbecb0d5213643419ffb040d7",
                "value": "2"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                "value": "3"
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'programmable'. lines 150-151:
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 5206608, non_refundable_storage_fee: 52592

task 13 'create-checkpoint'. lines 153-153:
Checkpoint created: 3

task 14 'run-graphql'. lines 155-217:
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                "value": "3"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x761e0b830ff149fb1b2a9c7addd9ea2f9ea65301cf6a38d872f595e4d83bd6ae",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0xaaa2997ee28f7af80fe9f0d02e6987cb25f6828bbecb0d5213643419ffb040d7",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                          "value": "3"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                "value": "0"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x761e0b830ff149fb1b2a9c7addd9ea2f9ea65301cf6a38d872f595e4d83bd6ae",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0xaaa2997ee28f7af80fe9f0d02e6987cb25f6828bbecb0d5213643419ffb040d7",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                          "value": "3"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 4,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                "value": "1"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x761e0b830ff149fb1b2a9c7addd9ea2f9ea65301cf6a38d872f595e4d83bd6ae",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0xaaa2997ee28f7af80fe9f0d02e6987cb25f6828bbecb0d5213643419ffb040d7",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
                        },
                        "json": {
                          "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                          "value": "3"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16 'create-checkpoint'. lines 221-221:
Checkpoint created: 4

task 18 'create-checkpoint'. lines 225-225:
Checkpoint created: 5

task 19 'force-object-snapshot-catchup'. lines 227-227:
Objects snapshot updated to [0 to 4)

task 20 'create-checkpoint'. lines 229-229:
Checkpoint created: 6

task 21 'run-graphql'. lines 231-246:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22 'run-graphql'. lines 248-264:
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                "value": "1"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xaaa2997ee28f7af80fe9f0d02e6987cb25f6828bbecb0d5213643419ffb040d7",
                "value": "2"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                "value": "3"
              }
            }
          }
        ]
      }
    }
  }
}

task 23 'run-graphql'. lines 266-292:
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x3c0efd0485b663cb783edf2178b5b0d40c6a97a019e70020151f9de3c83eea4d",
                "value": "0"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0x744b9c6137d3eea10382767871cf297ad69076728c439f5c85b6c795f7e000cd",
                "value": "1"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xaaa2997ee28f7af80fe9f0d02e6987cb25f6828bbecb0d5213643419ffb040d7",
                "value": "2"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x49173d3d77e4ce24d5ed0b74b1daa0618ca3af505c437f87c367f42cf05c703a::M1::Object"
              },
              "json": {
                "id": "0xe1f10834ecc45ce1cafecdad83dec99e96a49b66ed50be6cc2522181d83286b6",
                "value": "3"
              }
            }
          }
        ]
      }
    }
  }
}
