processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-27:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5456800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 29-29:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 31-31:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 33-33:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 5 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 6 'run-graphql'. lines 37-65:
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 7 'run'. lines 67-67:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 8 'create-checkpoint'. lines 69-69:
Checkpoint created: 2

task 9 'run-graphql'. lines 71-100:
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 102-177:
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                "value": "200"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0xb6ef2b910085dfd78006853560a0d8bd68db5389ac1e67b230f3857ea6f4c0f3",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
                        },
                        "json": {
                          "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
                        },
                        "json": {
                          "id": "0xb6ef2b910085dfd78006853560a0d8bd68db5389ac1e67b230f3857ea6f4c0f3",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run'. lines 179-179:
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 12 'create-checkpoint'. lines 181-181:
Checkpoint created: 3

task 13 'run-graphql'. lines 183-246:
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
                        },
                        "json": {
                          "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
                        },
                        "json": {
                          "id": "0xb6ef2b910085dfd78006853560a0d8bd68db5389ac1e67b230f3857ea6f4c0f3",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 14 'run-graphql'. lines 248-323:
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                "value": "200"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0xb6ef2b910085dfd78006853560a0d8bd68db5389ac1e67b230f3857ea6f4c0f3",
                "value": "300"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
              },
              "json": {
                "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
                        },
                        "json": {
                          "id": "0x4e3c4a16e66a99de490f12b2cca08fefc26338efbf47806dfe9a1268a8c39ac6",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x4274f15e37ba1881bdbba556dcd314c781123888c4cec9d4c1ced488eef14203::M1::Object"
                        },
                        "json": {
                          "id": "0xb6ef2b910085dfd78006853560a0d8bd68db5389ac1e67b230f3857ea6f4c0f3",
                          "value": "300"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}
