processed 24 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 15-32:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 34-34:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 36-36:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 5 'run-graphql'. lines 40-68:
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "if_the_other_does_not": {
      "nodes": []
    }
  }
}

task 6 'run'. lines 70-70:
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'run'. lines 72-72:
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 74-74:
Checkpoint created: 2

task 9 'run-graphql'. lines 76-104:
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": []
    }
  }
}

task 10 'run-graphql'. lines 106-121:
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x28d96e12e5ce0749c478e1941140a7b35ffb91b7f818e201f2b27f4489690de8",
                "value": "2"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x77e7d5374155e3b4f06e5805cc7d072c47b4ce6a23c1a4d818600c1f533cac94",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x9224310e32b75887d353f27d643fc05d01d4e0178e1827a3f0de46e5fea420da",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 123-148:
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x28d96e12e5ce0749c478e1941140a7b35ffb91b7f818e201f2b27f4489690de8",
                "value": "2"
              }
            }
          },
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x77e7d5374155e3b4f06e5805cc7d072c47b4ce6a23c1a4d818600c1f533cac94",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x9224310e32b75887d353f27d643fc05d01d4e0178e1827a3f0de46e5fea420da",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 12 'programmable'. lines 150-151:
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 5206608, non_refundable_storage_fee: 52592

task 13 'create-checkpoint'. lines 153-153:
Checkpoint created: 3

task 14 'run-graphql'. lines 155-217:
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x77e7d5374155e3b4f06e5805cc7d072c47b4ce6a23c1a4d818600c1f533cac94",
                "value": "0"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x28d96e12e5ce0749c478e1941140a7b35ffb91b7f818e201f2b27f4489690de8",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x3732dff5c4a9b80a9fe19790c6d99ca69f0a91bccd9ae437beb4cf9af01e707b",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x77e7d5374155e3b4f06e5805cc7d072c47b4ce6a23c1a4d818600c1f533cac94",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x9224310e32b75887d353f27d643fc05d01d4e0178e1827a3f0de46e5fea420da",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x9224310e32b75887d353f27d643fc05d01d4e0178e1827a3f0de46e5fea420da",
                "value": "3"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x28d96e12e5ce0749c478e1941140a7b35ffb91b7f818e201f2b27f4489690de8",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x3732dff5c4a9b80a9fe19790c6d99ca69f0a91bccd9ae437beb4cf9af01e707b",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x77e7d5374155e3b4f06e5805cc7d072c47b4ce6a23c1a4d818600c1f533cac94",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x9224310e32b75887d353f27d643fc05d01d4e0178e1827a3f0de46e5fea420da",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                "value": "1"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x28d96e12e5ce0749c478e1941140a7b35ffb91b7f818e201f2b27f4489690de8",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0x3732dff5c4a9b80a9fe19790c6d99ca69f0a91bccd9ae437beb4cf9af01e707b",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x77e7d5374155e3b4f06e5805cc7d072c47b4ce6a23c1a4d818600c1f533cac94",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0x9224310e32b75887d353f27d643fc05d01d4e0178e1827a3f0de46e5fea420da",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
                        },
                        "json": {
                          "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": []
    }
  }
}

task 16 'create-checkpoint'. lines 221-221:
Checkpoint created: 4

task 18 'create-checkpoint'. lines 225-225:
Checkpoint created: 5

task 19 'force-object-snapshot-catchup'. lines 227-227:
Objects snapshot updated to [0 to 4)

task 20 'create-checkpoint'. lines 229-229:
Checkpoint created: 6

task 21 'run-graphql'. lines 231-246:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 22 'run-graphql'. lines 248-264:
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x28d96e12e5ce0749c478e1941140a7b35ffb91b7f818e201f2b27f4489690de8",
                "value": "2"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x77e7d5374155e3b4f06e5805cc7d072c47b4ce6a23c1a4d818600c1f533cac94",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0x9224310e32b75887d353f27d643fc05d01d4e0178e1827a3f0de46e5fea420da",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0x97b8c04faae741d71e98e24d9faea7161dbf91ca79fb554d3fb245b1643a2b18::M1::Object"
              },
              "json": {
                "id": "0xd7e8ba092d7883256ada55ba886e3db4f7210edd8c0030c36c9c3b3c123ae79d",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 23 'run-graphql'. lines 266-292:
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": []
      }
    }
  }
}
