processed 20 tasks

init:
A: object(0,0)

task 1 'publish'. lines 19-56:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7014800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 58-58:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 60-60:
Checkpoint created: 1

task 4 'run-graphql'. lines 62-75:
Response: {
  "data": {
    "object": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "0"
          }
        }
      }
    }
  }
}

task 5 'run'. lines 77-77:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 6 'create-checkpoint'. lines 79-79:
Checkpoint created: 2

task 7 'run-graphql'. lines 81-107:
Response: {
  "data": {
    "latest_version": {
      "status": "INDEXED",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "1"
          }
        }
      }
    },
    "previous_version": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "0"
          }
        }
      }
    }
  }
}

task 8 'run'. lines 109-109:
created: object(8,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 9 'create-checkpoint'. lines 111-111:
Checkpoint created: 3

task 10 'run-graphql'. lines 113-139:
Response: {
  "data": {
    "latest_wrapped": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "previous_version": {
      "status": "INDEXED",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "1"
          }
        }
      }
    }
  }
}

task 11 'run'. lines 141-141:
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(8,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 12 'create-checkpoint'. lines 143-143:
Checkpoint created: 4

task 13 'run-graphql'. lines 145-183:
Response: {
  "data": {
    "latest_unwrapped": {
      "status": "INDEXED",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "1"
          }
        }
      }
    },
    "previous_version": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "first_version": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "0"
          }
        }
      }
    }
  }
}

task 14 'run'. lines 185-185:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 15 'create-checkpoint'. lines 187-187:
Checkpoint created: 5

task 16 'run-graphql'. lines 189-215:
Response: {
  "data": {
    "latest_deleted": {
      "status": "WRAPPED_OR_DELETED",
      "version": 7,
      "asMoveObject": null
    },
    "version_specified": {
      "status": "WRAPPED_OR_DELETED",
      "version": 7,
      "asMoveObject": null
    }
  }
}

task 17 'force-object-snapshot-catchup'. lines 217-217:
Objects snapshot updated to [0 to 5)

task 18 'create-checkpoint'. lines 219-219:
Checkpoint created: 6

task 19 'run-graphql'. lines 221-260:
Response: {
  "data": {
    "object_within_available_range": {
      "status": "INDEXED",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "1"
          }
        }
      }
    },
    "object_outside_available_range": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "object_not_in_snapshot": {
      "status": "INDEXED",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x3a52109e235a2b2b1e09b617e300547148e6a60068ac23248b2c96f43a690336",
            "value": "0"
          }
        }
      }
    }
  }
}
