processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-27:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5456800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 29-29:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 31-31:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 33-33:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 5 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 6 'run-graphql'. lines 37-65:
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 7 'run'. lines 67-67:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 8 'create-checkpoint'. lines 69-69:
Checkpoint created: 2

task 9 'run-graphql'. lines 71-100:
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 10 'run-graphql'. lines 102-177:
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xb0ee31984e13962c43e49c8a458a872746a1bad4182c0a53e2a63540c5ae00fc",
                "value": "1"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
                        },
                        "json": {
                          "id": "0xb0ee31984e13962c43e49c8a458a872746a1bad4182c0a53e2a63540c5ae00fc",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
                        },
                        "json": {
                          "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}

task 11 'run'. lines 179-179:
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 12 'create-checkpoint'. lines 181-181:
Checkpoint created: 3

task 13 'run-graphql'. lines 183-246:
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
                        },
                        "json": {
                          "id": "0xb0ee31984e13962c43e49c8a458a872746a1bad4182c0a53e2a63540c5ae00fc",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
                        },
                        "json": {
                          "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 14 'run-graphql'. lines 248-323:
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xb0ee31984e13962c43e49c8a458a872746a1bad4182c0a53e2a63540c5ae00fc",
                "value": "300"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
              },
              "json": {
                "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
                        },
                        "json": {
                          "id": "0xb0ee31984e13962c43e49c8a458a872746a1bad4182c0a53e2a63540c5ae00fc",
                          "value": "300"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xc50c3d1b815e6b11a499175ba7e732eb6fbcee23bd2ad106dfb4a2474a2a186b::M1::Object"
                        },
                        "json": {
                          "id": "0xc4bddcbccc6243088c23181ede4367a8299f494f97b49e91cb19c45dcd8cf3ef",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}
