processed 15 tasks

init:
C: object(0,0)

task 1 'run-graphql'. lines 6-18:
Response: {
  "data": {
    "address": {
      "stakedSuis": {
        "edges": []
      }
    }
  }
}

task 2 'programmable'. lines 20-22:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 24-24:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [47, 110, 138, 153, 188, 27, 152, 129, 24, 104, 150, 221, 204, 249, 164, 26, 86, 20, 242, 110, 225, 63, 55, 123, 107, 51, 205, 228, 29, 90, 126, 74, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0), object(3,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 4 'create-checkpoint'. lines 26-26:
Checkpoint created: 1

task 5 'advance-epoch'. lines 28-28:
Epoch advanced: 0

task 6 'programmable'. lines 30-32:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'run'. lines 34-34:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [47, 110, 138, 153, 188, 27, 152, 129, 24, 104, 150, 221, 204, 249, 164, 26, 86, 20, 242, 110, 225, 63, 55, 123, 107, 51, 205, 228, 29, 90, 126, 74, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(7,0)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0), object(3,0)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 14626656, non_refundable_storage_fee: 147744

task 8 'create-checkpoint'. lines 36-36:
Checkpoint created: 3

task 9 'advance-epoch'. lines 38-38:
Epoch advanced: 1

task 10 'view-object'. lines 40-40:
Owner: Account Address ( C )
Version: 3
Contents: sui_system::staking_pool::StakedSui {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,1),
        },
    },
    pool_id: sui::object::ID {
        bytes: _,
    },
    stake_activation_epoch: 1u64,
    principal: sui::balance::Balance<sui::sui::SUI> {
        value: 10000000000u64,
    },
}

task 11 'view-object'. lines 42-42:
Owner: Account Address ( C )
Version: 5
Contents: sui_system::staking_pool::StakedSui {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(7,0),
        },
    },
    pool_id: sui::object::ID {
        bytes: _,
    },
    stake_activation_epoch: 2u64,
    principal: sui::balance::Balance<sui::sui::SUI> {
        value: 10000000000u64,
    },
}

task 12 'run-graphql'. lines 44-56:
Response: {
  "data": {
    "address": {
      "stakedSuis": {
        "edges": [
          {
            "cursor": "IMCqYYUFtQgPF2vk6KmFReZSmEBb7bMyp4Gc9VWZO437BAAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          },
          {
            "cursor": "IPI9o24alDXGVaatOzS0UpLQ7Gn3kXdzMSuZUmqi97TRBAAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}

task 13 'run-graphql'. lines 58-102:
Response: {
  "data": {
    "no_coins_after_obj_3_1_chkpt_1": {
      "stakedSuis": {
        "edges": []
      }
    },
    "no_coins_before_obj_3_1_chkpt_1": {
      "stakedSuis": {
        "edges": []
      }
    },
    "no_coins_after_obj_7_0_chkpt_1": {
      "stakedSuis": {
        "edges": []
      }
    },
    "no_coins_before_obj_7_0_chkpt_1": {
      "stakedSuis": {
        "edges": []
      }
    }
  }
}

task 14 'run-graphql'. lines 104-147:
Response: {
  "data": {
    "coins_after_obj_3_1_chkpt_3": {
      "stakedSuis": {
        "edges": [
          {
            "cursor": "IPI9o24alDXGVaatOzS0UpLQ7Gn3kXdzMSuZUmqi97TRAwAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    },
    "coins_before_obj_3_1_chkpt_3": {
      "stakedSuis": {
        "edges": []
      }
    },
    "coins_after_obj_7_0_chkpt_3": {
      "stakedSuis": {
        "edges": []
      }
    },
    "coins_before_obj_7_0_chkpt_3": {
      "stakedSuis": {
        "edges": [
          {
            "cursor": "IMCqYYUFtQgPF2vk6KmFReZSmEBb7bMyp4Gc9VWZO437AwAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}
