processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 17-34:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 36-37:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 39-39:
Checkpoint created: 1

task 4 'programmable'. lines 41-44:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 46-46:
Checkpoint created: 2

task 6 'programmable'. lines 48-52:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 54-54:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 58-58:
Checkpoint created: 4

task 10 'run-graphql'. lines 60-134:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                "value": "2"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                "value": "4"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                "value": "5"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                "value": "200"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                "value": "3"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                "value": "6"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xb066651cfb87297e55e186d803455fbf4c2f9f080960a07d6c69af13b609279e",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 136-180:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xb066651cfb87297e55e186d803455fbf4c2f9f080960a07d6c69af13b609279e",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xb066651cfb87297e55e186d803455fbf4c2f9f080960a07d6c69af13b609279e",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xb066651cfb87297e55e186d803455fbf4c2f9f080960a07d6c69af13b609279e",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 182-182:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 184-184:
Checkpoint created: 5

task 14 'run-graphql'. lines 186-260:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                "value": "2"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                "value": "4"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                "value": "5"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                "value": "200"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                "value": "3"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                "value": "6"
              },
              "type": {
                "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xb066651cfb87297e55e186d803455fbf4c2f9f080960a07d6c69af13b609279e",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 262-262:
Checkpoint created: 6

task 16 'run-graphql'. lines 264-299:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x0ef29279f01f04116ca11adb000c8a18ace25489adbb7a3bd47b4d35fbfb65be",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x4a4bf1f88e418a0448d53286cddc81c31588c1ddbcb571ba6ff22cdeacb18d7e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xbeae5780de18772b8c30f20aec91d4cfff9d77137fd5b08368625dd48b5b7328",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc0f2ea1c6ea56775d522ace891d078396e4eee69d804acd8657906c79d2bdd2f",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb4f980dd89ad20f2766711a1ae3c2a733ee936f3a89f7a2b234fbf096440936",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xd4b7c50330664acb4998240f827b7491193ec569c942055197f543a05c76e571",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x5b90f0ead546fc71a4fa213bf632ae8f4de59f7e59a87ef8b84f205f2819d1b1::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
