processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 17-38:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 40-41:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 4 'programmable'. lines 45-48:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 50-50:
Checkpoint created: 2

task 6 'programmable'. lines 52-56:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 58-58:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 62-62:
Checkpoint created: 4

task 10 'run-graphql'. lines 64-138:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                "value": "200"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                "value": "2"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                "value": "3"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                "value": "6"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                "value": "4"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                "value": "5"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x0aa65a0907be36302a533f932b4aa1532a8f33a93416774eb432a77bf0058bd5",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 140-184:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                        "value": "0"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x0aa65a0907be36302a533f932b4aa1532a8f33a93416774eb432a77bf0058bd5",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x0aa65a0907be36302a533f932b4aa1532a8f33a93416774eb432a77bf0058bd5",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x0aa65a0907be36302a533f932b4aa1532a8f33a93416774eb432a77bf0058bd5",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 186-186:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 188-188:
Checkpoint created: 5

task 14 'run-graphql'. lines 190-264:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                "value": "200"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                "value": "2"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                "value": "3"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                "value": "6"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                "value": "4"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                "value": "5"
              },
              "type": {
                "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0x0aa65a0907be36302a533f932b4aa1532a8f33a93416774eb432a77bf0058bd5",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 266-266:
Checkpoint created: 6

task 16 'run-graphql'. lines 268-303:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": null
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x3d6f6b2b5b7c8a50136ca25568745bc61e847bfb1879b79f984abc0641b80b5b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x9fabaef1170ad95586792223172da9c5384135d8b5d01b3f8258bea35ea36eb5",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc168ad3794bba8ede7a5c907060b91a5ce0813db422598a8b0db96dc0a96212c",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xcb1ac06b2b05111d3d8621d48eb2b1244969c1cbfed33616730371e4ae049a9e",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf750b95e5615356dbfcba9d06dbc4789c18e5edfdfcf34aa3412e88f0664790d",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf952a53c5005ea6ff59beb04b166b61863b80a8f62136146ee84aae3e3a54190",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xfad7a164cd5d867bc62dd3492976c96256e499df222184a219ee018079f8e056::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 21,
          "column": 11
        }
      ],
      "path": [
        "all_transactions",
        "nodes",
        0,
        "gasInput",
        "gasSponsor",
        "objects"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
