processed 4 tasks

task 1 'run'. lines 75-83:
Error: Script execution failed with VMError: {
    major_status: VM_MAX_VALUE_DEPTH_REACHED,
    sub_status: None,
    location: 0x42::M,
    indices: [],
    offsets: [(FunctionDefinitionIndex(6), 2)],
}

task 2 'run'. lines 85-92:
Error: Script execution failed with VMError: {
    major_status: VM_MAX_VALUE_DEPTH_REACHED,
    sub_status: None,
    location: 0x42::M,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'run'. lines 95-103:
Error: Script execution failed with VMError: {
    major_status: VM_MAX_VALUE_DEPTH_REACHED,
    sub_status: None,
    location: 0x42::M,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}
