Command `migrate`:
Package toml does not specify an edition. As of 2024, Move requires all packages to define a language edition.

Please select one of the following editions:

1) 2024
2) legacy

Selection (default=1): 

Would you like the Move compiler to migrate your code to Move 2024? (Y/n) 
Generated changes . . .
INCLUDING DEPENDENCY MoveStdlib
BUILDING A

The following changes will be made.
============================================================

--- ./sources/mut_name.move
+++ ./sources/mut_name.move
@@ -3 +3 @@
-    fun dumpster_fire(mut x: u64, mut: u64): u64 {
+    fun dumpster_fire(mut x: u64, `mut`: u64): u64 {
@@ -5,2 +5,2 @@
-        let mut: u64 = mut + 2;
-        mut + y + x
+        let `mut`: u64 = `mut` + 2;
+        `mut` + y + x


============================================================
Apply changes? (Y/n) 
Updating "./sources/mut_name.move" . . .

Changes complete
Wrote patchfile out to: ./migration.patch

Recorded edition in 'Move.toml'
External Command `diff -r -s sources migration_sources`:
Files sources/mut_name.move and migration_sources/mut_name.move are identical
External Command `diff -s Move.toml Move.toml.expected`:
Files Move.toml and Move.toml.expected are identical
