warning[Lint W03001]: sub-optimal 'sui::coin::Coin' field type
   ┌─ tests/linter/coin_field.move:10:12
   │
10 │     struct S2 has key, store {
   │            ^^ The field 'c' of 'S2' has type 'sui::coin::Coin'
11 │         id: UID,
12 │         c: Coin<S1>,
   │         - Storing 'sui::balance::Balance' in this field will typically be more space-efficient
   │
   = This warning can be suppressed with '#[lint_allow(coin_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09009]: unused struct field
   ┌─ tests/linter/coin_field.move:11:9
   │
11 │         id: UID,
   │         ^^ The 'id' field of the 'S2' type is unused
   │
   = This warning can be suppressed with '#[allow(unused_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09009]: unused struct field
   ┌─ tests/linter/coin_field.move:12:9
   │
12 │         c: Coin<S1>,
   │         ^ The 'c' field of the 'S2' type is unused
   │
   = This warning can be suppressed with '#[allow(unused_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W03001]: sub-optimal 'sui::coin::Coin' field type
   ┌─ tests/linter/coin_field.move:23:12
   │
23 │     struct S2 has key, store {
   │            ^^ The field 'c' of 'S2' has type 'sui::coin::Coin'
24 │         id: UID,
25 │         c: Balance<S1>,
   │         - Storing 'sui::balance::Balance' in this field will typically be more space-efficient
   │
   = This warning can be suppressed with '#[lint_allow(coin_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09009]: unused struct field
   ┌─ tests/linter/coin_field.move:24:9
   │
24 │         id: UID,
   │         ^^ The 'id' field of the 'S2' type is unused
   │
   = This warning can be suppressed with '#[allow(unused_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09009]: unused struct field
   ┌─ tests/linter/coin_field.move:25:9
   │
25 │         c: Balance<S1>,
   │         ^ The 'c' field of the 'S2' type is unused
   │
   = This warning can be suppressed with '#[allow(unused_field)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

