warning[Lint W04001]: attempting to freeze wrapped objects
   ┌─ tests/linter/freeze_wrapped.move:28:40
   │
12 │     struct Wrapper has key, store {
   │            ------- The field inner of Wrapper contains  wrapped objects
   ·
28 │         transfer::public_freeze_object(w);
   │                                        ^ Freezing an object containing other wrapped objects will disallow unwrapping these objects in the future.
   │
   = This warning can be suppressed with '#[lint_allow(freeze_wrapped)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W04001]: attempting to freeze wrapped objects
   ┌─ tests/linter/freeze_wrapped.move:32:40
   │
 8 │     struct Inner has key, store {
   │            ----- Indirectly wrapped object is of this type
   ·
21 │     struct IndirectWrapper has key, store {
   │            --------------- The field s of IndirectWrapper contains indirectly wrapped objects
   ·
32 │         transfer::public_freeze_object(w);
   │                                        ^ Freezing an object containing other wrapped objects will disallow unwrapping these objects in the future.
   │
   = This warning can be suppressed with '#[lint_allow(freeze_wrapped)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

