warning[Lint W02001]: non-composable transfer to sender
   ┌─ tests/linter/self_transfer.move:23:9
   │
22 │     public fun public_transfer_bad(ctx: &mut TxContext) {
   │                ------------------- Returning an object from a function, allows a caller to use the object and enables composability via programmable transactions.
23 │         transfer::public_transfer(S1 { id: object::new(ctx), }, tx_context::sender(ctx))
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                                                       │
   │         │                                                       Transaction sender address coming from here
   │         Transfer of an object to transaction sender address in function public_transfer_bad
   │
   = This warning can be suppressed with '#[lint_allow(self_transfer)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W02001]: non-composable transfer to sender
   ┌─ tests/linter/self_transfer.move:27:9
   │
26 │     public fun private_transfer_bad(ctx: &mut TxContext) {
   │                -------------------- Returning an object from a function, allows a caller to use the object and enables composability via programmable transactions.
27 │         transfer::transfer(S1 { id: object::new(ctx), }, tx_context::sender(ctx))
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                                                │
   │         │                                                Transaction sender address coming from here
   │         Transfer of an object to transaction sender address in function private_transfer_bad
   │
   = This warning can be suppressed with '#[lint_allow(self_transfer)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W02001]: non-composable transfer to sender
   ┌─ tests/linter/self_transfer.move:31:9
   │
30 │     public fun private_transfer_no_store_bad(ctx: &mut TxContext) {
   │                ----------------------------- Returning an object from a function, allows a caller to use the object and enables composability via programmable transactions.
31 │         transfer::transfer(S2 { id: object::new(ctx), }, tx_context::sender(ctx))
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                                                │
   │         │                                                Transaction sender address coming from here
   │         Transfer of an object to transaction sender address in function private_transfer_no_store_bad
   │
   = This warning can be suppressed with '#[lint_allow(self_transfer)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W02001]: non-composable transfer to sender
   ┌─ tests/linter/self_transfer.move:39:9
   │
36 │     public fun transfer_through_assigns_bad(ctx: &mut TxContext) {
   │                ---------------------------- Returning an object from a function, allows a caller to use the object and enables composability via programmable transactions.
37 │         let sender = tx_context::sender(ctx);
   │                      ----------------------- Transaction sender address coming from here
38 │         let another_sender = sender;
39 │         transfer::public_transfer(S1 { id: object::new(ctx), }, another_sender)
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Transfer of an object to transaction sender address in function transfer_through_assigns_bad
   │
   = This warning can be suppressed with '#[lint_allow(self_transfer)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

