warning[Lint W01001]: possible owned object share
   ┌─ tests/linter/share_owned.move:14:9
   │
12 │     public entry fun arg_object(o: Obj) {
   │                                 - A potentially owned object coming from here
13 │         let arg = o;
14 │         transfer::public_share_object(arg);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                             │
   │         │                             Creating a fresh object and sharing it within the same function will ensure this does not abort.
   │         Potential abort from a (potentially) owned object created by a different transaction.

warning[Lint W01001]: possible owned object share
   ┌─ tests/linter/share_owned.move:35:9
   │
34 │         let Wrapper { id, i: _, o } = w;
   │                                 - A potentially owned object coming from here
35 │         transfer::public_share_object(o);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                             │
   │         │                             Creating a fresh object and sharing it within the same function will ensure this does not abort.
   │         Potential abort from a (potentially) owned object created by a different transaction.

