processed 3 tasks

task 1 'run'. lines 19-32:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::m'. Got VMError: {
    major_status: STLOC_UNSAFE_TO_DESTROY_ERROR,
    sub_status: None,
    location: 0x2::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 2 'run'. lines 34-46:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000003::m'. Got VMError: {
    major_status: STLOC_UNSAFE_TO_DESTROY_ERROR,
    sub_status: None,
    location: 0x3::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}
