processed 2 tasks

task 0 'publish'. lines 1-22:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::Enums'. Got VMError: {
    major_status: WRITEREF_WITHOUT_DROP_ABILITY,
    sub_status: None,
    location: 0x1::Enums,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 10)],
}

task 1 'publish'. lines 24-47:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::Enums'. Got VMError: {
    major_status: WRITEREF_WITHOUT_DROP_ABILITY,
    sub_status: None,
    location: 0x1::Enums,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 10)],
}
