error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:8:76
   │
 8 │     public fun no<T>(s: &signer, addr: address, r: R, g: G<T>) acquires R, G {
   │                                                                            ^ Invalid usage of global storage acquires
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:9:13
   │
 9 │         _ = exists<R>(addr);
   │             ^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'exists'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:10:13
   │
10 │         _ = exists<G<T>>(addr);
   │             ^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'exists'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:11:13
   │
11 │         _ = borrow_global<R>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'borrow_global'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:12:13
   │
12 │         _ = borrow_global<G<T>>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'borrow_global'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:13:13
   │
13 │         _ = borrow_global_mut<R>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'borrow_global_mut'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:14:13
   │
14 │         _ = borrow_global_mut<G<T>>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'borrow_global_mut'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:15:20
   │
15 │         consume<R>(move_from<R>(addr));
   │                    ^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'move_from'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:16:23
   │
16 │         consume<G<T>>(move_from<G<T>>(addr));
   │                       ^^^^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'move_from'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:17:9
   │
17 │         move_to<R>(s, r);
   │         ^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'move_to'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: invalid global storage usage
   ┌─ tests/sui_mode/global_storage_access/all.move:18:9
   │
18 │         move_to<G<T>>(s, g);
   │         ^^^^^^^^^^^^^^^^^^^ Invalid usage of global storage primitive 'move_to'
   ·
33 │ module sui::transfer {
   │             -------- Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

