error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:11:76
   │
11 │     public fun no<T>(s: &signer, addr: address, r: R, g: G<T>) acquires R, G {
   │                                                                            ^ Global storage acquires are not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:12:13
   │
12 │         _ = exists<R>(addr);
   │             ^^^^^^^^^^^^^^^ Global storage primitive 'exists' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:13:13
   │
13 │         _ = exists<G<T>>(addr);
   │             ^^^^^^^^^^^^^^^^^^ Global storage primitive 'exists' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:14:13
   │
14 │         _ = borrow_global<R>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^ Global storage primitive 'borrow_global' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:15:13
   │
15 │         _ = borrow_global<G<T>>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^ Global storage primitive 'borrow_global' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:16:13
   │
16 │         _ = borrow_global_mut<R>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^ Global storage primitive 'borrow_global_mut' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:17:13
   │
17 │         _ = borrow_global_mut<G<T>>(addr);
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Global storage primitive 'borrow_global_mut' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:18:20
   │
18 │         consume<R>(move_from<R>(addr));
   │                    ^^^^^^^^^^^^^^^^^^ Global storage primitive 'move_from' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:19:23
   │
19 │         consume<G<T>>(move_from<G<T>>(addr));
   │                       ^^^^^^^^^^^^^^^^^^^^^ Global storage primitive 'move_from' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:20:9
   │
20 │         move_to<R>(s, r);
   │         ^^^^^^^^^^^^^^^^ Global storage primitive 'move_to' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

error[Sui E02009]: global storage is not supported in Sui
   ┌─ tests/sui_mode/global_storage_access/all_without_sui_transfer.move:21:9
   │
21 │         move_to<G<T>>(s, g);
   │         ^^^^^^^^^^^^^^^^^^^ Global storage primitive 'move_to' is not supported in Sui
   │
   = Global storage is not used in Sui. Instead objects (structs with the 'key' ability) are used with programmable transaction blocks and the 'sui::transfer' functions.

