processed 4 tasks

init:
A: object(100)

task 1 'publish'. lines 9-30:
created: object(105)
written: object(104)

task 2 'run'. lines 32-32:
created: object(107), object(108)
written: object(106)

task 3 'run'. lines 34-34:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::dynamic_field::add (function index 0) at offset 15, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 0, instruction: 15, function_name: Some("add") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: Some("sui::dynamic_field::add at offset 15"), exec_state: Some(ExecutionState { stack_trace: [(Some(ModuleId { address: a, name: Identifier("m") }), FunctionDefinitionIndex(1), 4)] }), location: Module(ModuleId { address: sui, name: Identifier("dynamic_field") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 15)] }), command: Some(0) } }
