processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-60:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8603200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 62-62:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2211600,  storage_rebate: 0, non_refundable_storage_fee: 0
