processed 8 tasks

init:
A: object(103)

task 1 'publish'. lines 6-62:
created: object(105)
mutated: object(104)

task 2 'run'. lines 64-64:
created: object(107)
mutated: object(106)

task 3 'run'. lines 66-66:
created: object(109)
mutated: object(108)

task 4 'run'. lines 68-68:
created: object(111)
mutated: object(107), object(109), object(110)

task 5 'view-object'. lines 70-70:
Owner: Object ID: ( fake(111) )
Version: 3
Contents: test::m::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(109)}}, value: 0u64}

task 6 'run'. lines 72-72:
created: object(113)
mutated: object(107), object(109), object(112)
deleted: object(111)

task 7 'view-object'. lines 74-74:
Owner: Account Address ( A )
Version: 4
Contents: test::m::Child {id: sui::object::UID {id: sui::object::ID {bytes: fake(109)}}, value: 0u64}
