processed 11 tasks

init:
A: object(103)

task 1 'publish'. lines 9-79:
created: object(105)
mutated: object(104)

task 2 'run'. lines 81-81:
created: object(107)
mutated: object(106)

task 3 'run'. lines 83-83:
created: object(109), object(110), object(111)
mutated: object(107), object(108)

task 4 'run'. lines 85-85:
mutated: object(107), object(112)

task 5 'run'. lines 87-87:
mutated: object(107), object(113)

task 6 'run'. lines 89-89:
mutated: object(107), object(109), object(110), object(111), object(114)

task 7 'run'. lines 91-91:
mutated: object(107), object(115)

task 8 'run'. lines 93-93:
mutated: object(107), object(116)
deleted: object(110), object(111)

task 9 'run'. lines 95-95:
mutated: object(107), object(117)

task 10 'run'. lines 97-97:
mutated: object(118)
deleted: object(107)
