processed 11 tasks

init:
A: object(103)

task 1 'publish'. lines 10-104:
created: object(105)
mutated: object(104)

task 2 'run'. lines 106-106:
created: object(107)
mutated: object(106)

task 3 'run'. lines 108-108:
created: object(109), object(110), object(111), object(112), object(113), object(114)
mutated: object(107), object(108)

task 4 'run'. lines 110-110:
mutated: object(107), object(115)

task 5 'run'. lines 112-112:
mutated: object(107), object(116)

task 6 'run'. lines 114-114:
mutated: object(107), object(109), object(110), object(111), object(117)

task 7 'run'. lines 116-116:
mutated: object(107), object(118)

task 8 'run'. lines 118-118:
mutated: object(107), object(119)
deleted: object(109), object(111), object(113), object(114)

task 9 'run'. lines 120-120:
mutated: object(107), object(120)

task 10 'run'. lines 122-122:
mutated: object(121)
deleted: object(107)
