processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 11-57:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9614000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 59-61:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2249600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 62-62:
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5950800,  storage_rebate: 2227104, non_refundable_storage_fee: 22496

task 4 'run'. lines 64-66:
mutated: object(0,0), object(2,0), object(3,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3496000,  storage_rebate: 5891292, non_refundable_storage_fee: 59508

task 5 'run'. lines 67-67:
created: object(3,0), object(5,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5950800,  storage_rebate: 2227104, non_refundable_storage_fee: 22496

task 6 'run'. lines 69-71:
mutated: object(0,0), object(2,0)
deleted: object(3,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2249600,  storage_rebate: 5891292, non_refundable_storage_fee: 59508

task 7 'run'. lines 72-72:
created: object(3,0), object(7,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5950800,  storage_rebate: 2227104, non_refundable_storage_fee: 22496

task 8 'run'. lines 74-74:
mutated: object(0,0), object(2,0)
deleted: object(3,0)
wrapped: object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2492800,  storage_rebate: 5891292, non_refundable_storage_fee: 59508
