processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 11-52:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8762800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 54-54:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2242000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 56-56:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2242000,  storage_rebate: 2219580, non_refundable_storage_fee: 22420

task 4 'run'. lines 58-58:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2242000,  storage_rebate: 2219580, non_refundable_storage_fee: 22420
