processed 11 tasks

init:
A: object(100)

task 1 'publish'. lines 10-67:
created: object(105)
written: object(104)

task 2 'run'. lines 69-69:
created: object(107)
written: object(106)

task 3 'run'. lines 71-71:
created: object(109)
written: object(108)

task 4 'run'. lines 73-73:
created: object(111), object(112)
written: object(107), object(110)

task 5 'run'. lines 75-75:
written: object(107), object(111), object(113)

task 6 'run'. lines 77-77:
written: object(107), object(114)

task 7 'run'. lines 79-79:
created: object(116)
written: object(107), object(109), object(111), object(115)
deleted: object(112)

task 8 'run'. lines 81-81:
written: object(109), object(111), object(117)

task 9 'run'. lines 83-83:
written: object(109), object(118)

task 10 'run'. lines 85-85:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::dynamic_field::borrow_child_object_mut (function index 12) at offset 0, Abort Code: 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 12, instruction: 0, function_name: Some("borrow_child_object_mut") }, 1), source: Some(VMError { major_status: ABORTED, sub_status: Some(1), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("dynamic_field") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(0) } }
