processed 12 tasks

init:
A: object(103)

task 1 'publish'. lines 8-41:
created: object(105)
mutated: object(104)

task 2 'run'. lines 43-43:
created: object(107), object(108), object(109)
mutated: object(106)

task 3 'view-object'. lines 45-45:
Owner: Account Address ( A )
Version: 2
Contents: a::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}

task 4 'run'. lines 47-47:
Error: Object 0xa3520bbf03b9236b44e2b6a098cba4be28ffa57169ce6da445dd879ce497858e is owned by object 0x4eeb215c80c209f03da8950d2505b4254774d1dedd8888f73462ef17de06de8d. Objects owned by other objects cannot be used as input arguments.

task 5 'run'. lines 50-50:
created: object(112), object(113), object(114)
mutated: object(111)

task 6 'view-object'. lines 52-52:
Owner: Object ID: ( fake(113) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(114)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(112)}}

task 7 'run'. lines 54-54:
mutated: object(113), object(115)
deleted: object(112), object(114)

task 8 'run'. lines 57-57:
created: object(117), object(118), object(119)
mutated: object(116)

task 9 'view-object'. lines 59-59:
Owner: Object ID: ( fake(117) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(119)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(118)}}

task 10 'run'. lines 61-61:
mutated: object(117), object(118), object(120)
deleted: object(119)

task 11 'view-object'. lines 63-63:
No object at id 119
