processed 3 tasks

task 1 'publish'. lines 8-13:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"0000000000000000000000000000000000000000000000000000000000000000::m. 'init' cannot be 'entry'\"), command: None } }" }

task 2 'run'. lines 15-15:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }
