processed 7 tasks

init:
A: object(100)

task 1 'publish'. lines 6-53:
created: object(105)
written: object(104)

task 2 'programmable'. lines 55-61:
written: object(106)

task 3 'programmable'. lines 63-69:
written: object(107)

task 4 'programmable'. lines 71-74:
written: object(108)

task 5 'programmable'. lines 76-79:
Error: Transaction Effects Status: Invalid command argument at 0. The argument cannot be deserialized into a value of the specified type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidBCSBytes }, source: Some("Function expects std::string::String but provided argument's value does not match"), command: Some(0) } }

task 6 'programmable'. lines 81-85:
written: object(110)
