processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-30:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5198400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 32-32:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2287600,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'view-object'. lines 34-34:
Owner: Shared
Version: 3
Contents: test::m1::Coin {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 1000000u64}

task 4 'programmable'. lines 36-37:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Debug of error: CommandArgumentError { arg_idx: 1, kind: TypeMismatch } at command Some(0)
