processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-21:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4993200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 23-25:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'programmable'. lines 27-29:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 31-31:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'view-object'. lines 33-35:
Owner: Shared
Version: 3
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(4,0)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 0u64}}

task 6 'programmable'. lines 36-40:
created: object(6,0)
mutated: object(0,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 7 'programmable'. lines 41-44:
Error: Transaction Effects Status: The shared object operation is not allowed.
Debug of error: SharedObjectOperationNotAllowed at command None
