:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]
:xref-Upgrades-deployUUPSProxy-string-bytes-struct-Options-: xref:#Upgrades-deployUUPSProxy-string-bytes-struct-Options-
:xref-Upgrades-deployUUPSProxy-string-bytes-: xref:#Upgrades-deployUUPSProxy-string-bytes-
:xref-Upgrades-deployTransparentProxy-string-address-bytes-struct-Options-: xref:#Upgrades-deployTransparentProxy-string-address-bytes-struct-Options-
:xref-Upgrades-deployTransparentProxy-string-address-bytes-: xref:#Upgrades-deployTransparentProxy-string-address-bytes-
:xref-Upgrades-upgradeProxy-address-string-bytes-struct-Options-: xref:#Upgrades-upgradeProxy-address-string-bytes-struct-Options-
:xref-Upgrades-upgradeProxy-address-string-bytes-: xref:#Upgrades-upgradeProxy-address-string-bytes-
:xref-Upgrades-upgradeProxy-address-string-bytes-struct-Options-address-: xref:#Upgrades-upgradeProxy-address-string-bytes-struct-Options-address-
:xref-Upgrades-upgradeProxy-address-string-bytes-address-: xref:#Upgrades-upgradeProxy-address-string-bytes-address-
:xref-Upgrades-deployBeacon-string-address-struct-Options-: xref:#Upgrades-deployBeacon-string-address-struct-Options-
:xref-Upgrades-deployBeacon-string-address-: xref:#Upgrades-deployBeacon-string-address-
:xref-Upgrades-upgradeBeacon-address-string-struct-Options-: xref:#Upgrades-upgradeBeacon-address-string-struct-Options-
:xref-Upgrades-upgradeBeacon-address-string-: xref:#Upgrades-upgradeBeacon-address-string-
:xref-Upgrades-upgradeBeacon-address-string-struct-Options-address-: xref:#Upgrades-upgradeBeacon-address-string-struct-Options-address-
:xref-Upgrades-upgradeBeacon-address-string-address-: xref:#Upgrades-upgradeBeacon-address-string-address-
:xref-Upgrades-deployBeaconProxy-address-bytes-: xref:#Upgrades-deployBeaconProxy-address-bytes-
:xref-Upgrades-deployBeaconProxy-address-bytes-struct-Options-: xref:#Upgrades-deployBeaconProxy-address-bytes-struct-Options-
:xref-Upgrades-validateImplementation-string-struct-Options-: xref:#Upgrades-validateImplementation-string-struct-Options-
:xref-Upgrades-deployImplementation-string-struct-Options-: xref:#Upgrades-deployImplementation-string-struct-Options-
:xref-Upgrades-validateUpgrade-string-struct-Options-: xref:#Upgrades-validateUpgrade-string-struct-Options-
:xref-Upgrades-prepareUpgrade-string-struct-Options-: xref:#Upgrades-prepareUpgrade-string-struct-Options-
:xref-Upgrades-getAdminAddress-address-: xref:#Upgrades-getAdminAddress-address-
:xref-Upgrades-getImplementationAddress-address-: xref:#Upgrades-getImplementationAddress-address-
:xref-Upgrades-getBeaconAddress-address-: xref:#Upgrades-getBeaconAddress-address-
:xref-Upgrades-tryPrank-address-: xref:#Upgrades-tryPrank-address-
:xref-Upgrades-CHEATCODE_ADDRESS-address: xref:#Upgrades-CHEATCODE_ADDRESS-address
:xref-Defender-deployContract-string-: xref:#Defender-deployContract-string-
:xref-Defender-deployContract-string-struct-DefenderOptions-: xref:#Defender-deployContract-string-struct-DefenderOptions-
:xref-Defender-deployContract-string-bytes-: xref:#Defender-deployContract-string-bytes-
:xref-Defender-deployContract-string-bytes-struct-DefenderOptions-: xref:#Defender-deployContract-string-bytes-struct-DefenderOptions-
:xref-Defender-proposeUpgrade-address-string-struct-Options-: xref:#Defender-proposeUpgrade-address-string-struct-Options-
:xref-Defender-getDeployApprovalProcess--: xref:#Defender-getDeployApprovalProcess--
:xref-Defender-getUpgradeApprovalProcess--: xref:#Defender-getUpgradeApprovalProcess--
= OpenZeppelin Foundry Upgrades API

== Common Options

The following options can be used with some of the below functions. See https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Options.sol[Options.sol] for detailed descriptions of each option.

[[Options]]
=== `++Options++` link:https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Options.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import { Options } from "openzeppelin-foundry-upgrades/Options.sol";
```

```solidity
struct Options {
  string referenceContract;
  bytes constructorData;
  string unsafeAllow;
  bool unsafeAllowRenames;
  bool unsafeSkipStorageCheck;
  bool unsafeSkipAllChecks;
  struct DefenderOptions defender;
}
```

[[DefenderOptions]]
=== `++DefenderOptions++` link:https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Options.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import { DefenderOptions } from "openzeppelin-foundry-upgrades/Options.sol";
```

```solidity
struct DefenderOptions {
  bool useDefenderDeploy;
  bool skipVerifySourceCode;
  string relayerId;
  bytes32 salt;
  string upgradeApprovalProcessId;
  string licenseType;
  bool skipLicenseType;
  struct TxOverrides txOverrides;
}
```

[[TxOverrides]]
=== `++TxOverrides++` link:https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Options.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import { TxOverrides } from "openzeppelin-foundry-upgrades/Options.sol";
```

```solidity
struct TxOverrides {
  uint256 gasLimit;
  uint256 gasPrice;
  uint256 maxFeePerGas;
  uint256 maxPriorityFeePerGas;
}
```

== Foundry Upgrades

:deployUUPSProxy: pass:normal[xref:#Upgrades-deployUUPSProxy-string-bytes-struct-Options-[`++deployUUPSProxy++`]]
:deployUUPSProxy: pass:normal[xref:#Upgrades-deployUUPSProxy-string-bytes-[`++deployUUPSProxy++`]]
:deployTransparentProxy: pass:normal[xref:#Upgrades-deployTransparentProxy-string-address-bytes-struct-Options-[`++deployTransparentProxy++`]]
:deployTransparentProxy: pass:normal[xref:#Upgrades-deployTransparentProxy-string-address-bytes-[`++deployTransparentProxy++`]]
:upgradeProxy: pass:normal[xref:#Upgrades-upgradeProxy-address-string-bytes-struct-Options-[`++upgradeProxy++`]]
:upgradeProxy: pass:normal[xref:#Upgrades-upgradeProxy-address-string-bytes-[`++upgradeProxy++`]]
:upgradeProxy: pass:normal[xref:#Upgrades-upgradeProxy-address-string-bytes-struct-Options-address-[`++upgradeProxy++`]]
:upgradeProxy: pass:normal[xref:#Upgrades-upgradeProxy-address-string-bytes-address-[`++upgradeProxy++`]]
:deployBeacon: pass:normal[xref:#Upgrades-deployBeacon-string-address-struct-Options-[`++deployBeacon++`]]
:deployBeacon: pass:normal[xref:#Upgrades-deployBeacon-string-address-[`++deployBeacon++`]]
:upgradeBeacon: pass:normal[xref:#Upgrades-upgradeBeacon-address-string-struct-Options-[`++upgradeBeacon++`]]
:upgradeBeacon: pass:normal[xref:#Upgrades-upgradeBeacon-address-string-[`++upgradeBeacon++`]]
:upgradeBeacon: pass:normal[xref:#Upgrades-upgradeBeacon-address-string-struct-Options-address-[`++upgradeBeacon++`]]
:upgradeBeacon: pass:normal[xref:#Upgrades-upgradeBeacon-address-string-address-[`++upgradeBeacon++`]]
:deployBeaconProxy: pass:normal[xref:#Upgrades-deployBeaconProxy-address-bytes-[`++deployBeaconProxy++`]]
:deployBeaconProxy: pass:normal[xref:#Upgrades-deployBeaconProxy-address-bytes-struct-Options-[`++deployBeaconProxy++`]]
:validateImplementation: pass:normal[xref:#Upgrades-validateImplementation-string-struct-Options-[`++validateImplementation++`]]
:deployImplementation: pass:normal[xref:#Upgrades-deployImplementation-string-struct-Options-[`++deployImplementation++`]]
:validateUpgrade: pass:normal[xref:#Upgrades-validateUpgrade-string-struct-Options-[`++validateUpgrade++`]]
:prepareUpgrade: pass:normal[xref:#Upgrades-prepareUpgrade-string-struct-Options-[`++prepareUpgrade++`]]
:getAdminAddress: pass:normal[xref:#Upgrades-getAdminAddress-address-[`++getAdminAddress++`]]
:getImplementationAddress: pass:normal[xref:#Upgrades-getImplementationAddress-address-[`++getImplementationAddress++`]]
:getBeaconAddress: pass:normal[xref:#Upgrades-getBeaconAddress-address-[`++getBeaconAddress++`]]
:tryPrank: pass:normal[xref:#Upgrades-tryPrank-address-[`++tryPrank++`]]
:CHEATCODE_ADDRESS: pass:normal[xref:#Upgrades-CHEATCODE_ADDRESS-address[`++CHEATCODE_ADDRESS++`]]

[.contract]
[[Upgrades]]
=== `++Upgrades++` link:https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Upgrades.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import { Upgrades } from "openzeppelin-foundry-upgrades/Upgrades.sol";
```

Library for deploying and managing upgradeable contracts from Forge scripts or tests.

[.contract-index]
.Functions
--
* {xref-Upgrades-deployUUPSProxy-string-bytes-struct-Options-}[`++deployUUPSProxy(contractName, initializerData, opts)++`]
* {xref-Upgrades-deployUUPSProxy-string-bytes-}[`++deployUUPSProxy(contractName, initializerData)++`]
* {xref-Upgrades-deployTransparentProxy-string-address-bytes-struct-Options-}[`++deployTransparentProxy(contractName, initialOwner, initializerData, opts)++`]
* {xref-Upgrades-deployTransparentProxy-string-address-bytes-}[`++deployTransparentProxy(contractName, initialOwner, initializerData)++`]
* {xref-Upgrades-upgradeProxy-address-string-bytes-struct-Options-}[`++upgradeProxy(proxy, contractName, data, opts)++`]
* {xref-Upgrades-upgradeProxy-address-string-bytes-}[`++upgradeProxy(proxy, contractName, data)++`]
* {xref-Upgrades-upgradeProxy-address-string-bytes-struct-Options-address-}[`++upgradeProxy(proxy, contractName, data, opts, tryCaller)++`]
* {xref-Upgrades-upgradeProxy-address-string-bytes-address-}[`++upgradeProxy(proxy, contractName, data, tryCaller)++`]
* {xref-Upgrades-deployBeacon-string-address-struct-Options-}[`++deployBeacon(contractName, initialOwner, opts)++`]
* {xref-Upgrades-deployBeacon-string-address-}[`++deployBeacon(contractName, initialOwner)++`]
* {xref-Upgrades-upgradeBeacon-address-string-struct-Options-}[`++upgradeBeacon(beacon, contractName, opts)++`]
* {xref-Upgrades-upgradeBeacon-address-string-}[`++upgradeBeacon(beacon, contractName)++`]
* {xref-Upgrades-upgradeBeacon-address-string-struct-Options-address-}[`++upgradeBeacon(beacon, contractName, opts, tryCaller)++`]
* {xref-Upgrades-upgradeBeacon-address-string-address-}[`++upgradeBeacon(beacon, contractName, tryCaller)++`]
* {xref-Upgrades-deployBeaconProxy-address-bytes-}[`++deployBeaconProxy(beacon, data)++`]
* {xref-Upgrades-deployBeaconProxy-address-bytes-struct-Options-}[`++deployBeaconProxy(beacon, data, opts)++`]
* {xref-Upgrades-validateImplementation-string-struct-Options-}[`++validateImplementation(contractName, opts)++`]
* {xref-Upgrades-deployImplementation-string-struct-Options-}[`++deployImplementation(contractName, opts)++`]
* {xref-Upgrades-validateUpgrade-string-struct-Options-}[`++validateUpgrade(contractName, opts)++`]
* {xref-Upgrades-prepareUpgrade-string-struct-Options-}[`++prepareUpgrade(contractName, opts)++`]
* {xref-Upgrades-getAdminAddress-address-}[`++getAdminAddress(proxy)++`]
* {xref-Upgrades-getImplementationAddress-address-}[`++getImplementationAddress(proxy)++`]
* {xref-Upgrades-getBeaconAddress-address-}[`++getBeaconAddress(proxy)++`]

--

[.contract-index]
.Modifiers
--
* {xref-Upgrades-tryPrank-address-}[`++tryPrank(deployer)++`]
--

[.contract-index]
.Internal Variables
--
* {xref-Upgrades-CHEATCODE_ADDRESS-address}[`++address constant CHEATCODE_ADDRESS++`]

--

[.contract-item]
[[Upgrades-deployUUPSProxy-string-bytes-struct-Options-]]
==== `[.contract-item-name]#++deployUUPSProxy++#++(string contractName, bytes initializerData, struct Options opts) → address++` [.item-kind]#internal#

Deploys a UUPS proxy using the given contract as the implementation.

*Parameters:*

* `contractName` (`string`) - Name of the contract to use as the implementation, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `initializerData` (`bytes`) - Encoded call data of the initializer function to call during creation of the proxy, or empty if no initialization is required
* `opts` (`struct Options`) - Common options

*Returns*

* (`address`) - Proxy address

[.contract-item]
[[Upgrades-deployUUPSProxy-string-bytes-]]
==== `[.contract-item-name]#++deployUUPSProxy++#++(string contractName, bytes initializerData) → address++` [.item-kind]#internal#

Deploys a UUPS proxy using the given contract as the implementation.

*Parameters:*

* `contractName` (`string`) - Name of the contract to use as the implementation, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `initializerData` (`bytes`) - Encoded call data of the initializer function to call during creation of the proxy, or empty if no initialization is required

*Returns*

* (`address`) - Proxy address

[.contract-item]
[[Upgrades-deployTransparentProxy-string-address-bytes-struct-Options-]]
==== `[.contract-item-name]#++deployTransparentProxy++#++(string contractName, address initialOwner, bytes initializerData, struct Options opts) → address++` [.item-kind]#internal#

Deploys a transparent proxy using the given contract as the implementation.

*Parameters:*

* `contractName` (`string`) - Name of the contract to use as the implementation, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `initialOwner` (`address`) - Address to set as the owner of the ProxyAdmin contract which gets deployed by the proxy
* `initializerData` (`bytes`) - Encoded call data of the initializer function to call during creation of the proxy, or empty if no initialization is required
* `opts` (`struct Options`) - Common options

*Returns*

* (`address`) - Proxy address

[.contract-item]
[[Upgrades-deployTransparentProxy-string-address-bytes-]]
==== `[.contract-item-name]#++deployTransparentProxy++#++(string contractName, address initialOwner, bytes initializerData) → address++` [.item-kind]#internal#

Deploys a transparent proxy using the given contract as the implementation.

*Parameters:*

* `contractName` (`string`) - Name of the contract to use as the implementation, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `initialOwner` (`address`) - Address to set as the owner of the ProxyAdmin contract which gets deployed by the proxy
* `initializerData` (`bytes`) - Encoded call data of the initializer function to call during creation of the proxy, or empty if no initialization is required

*Returns*

* (`address`) - Proxy address

[.contract-item]
[[Upgrades-upgradeProxy-address-string-bytes-struct-Options-]]
==== `[.contract-item-name]#++upgradeProxy++#++(address proxy, string contractName, bytes data, struct Options opts)++` [.item-kind]#internal#

Upgrades a proxy to a new implementation contract. Only supported for UUPS or transparent proxies.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

*Parameters:*

* `proxy` (`address`) - Address of the proxy to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `data` (`bytes`) - Encoded call data of an arbitrary function to call during the upgrade process, or empty if no function needs to be called during the upgrade
* `opts` (`struct Options`) - Common options

[.contract-item]
[[Upgrades-upgradeProxy-address-string-bytes-]]
==== `[.contract-item-name]#++upgradeProxy++#++(address proxy, string contractName, bytes data)++` [.item-kind]#internal#

Upgrades a proxy to a new implementation contract. Only supported for UUPS or transparent proxies.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

*Parameters:*

* `proxy` (`address`) - Address of the proxy to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `data` (`bytes`) - Encoded call data of an arbitrary function to call during the upgrade process, or empty if no function needs to be called during the upgrade

[.contract-item]
[[Upgrades-upgradeProxy-address-string-bytes-struct-Options-address-]]
==== `[.contract-item-name]#++upgradeProxy++#++(address proxy, string contractName, bytes data, struct Options opts, address tryCaller)++` [.item-kind]#internal#

NOTE: For tests only. If broadcasting in scripts, use the `--sender <ADDRESS>` option with `forge script` instead.

Upgrades a proxy to a new implementation contract. Only supported for UUPS or transparent proxies.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

This function provides an additional `tryCaller` parameter to test an upgrade using a specific caller address.
Use this if you encounter `OwnableUnauthorizedAccount` errors in your tests.

*Parameters:*

* `proxy` (`address`) - Address of the proxy to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `data` (`bytes`) - Encoded call data of an arbitrary function to call during the upgrade process, or empty if no function needs to be called during the upgrade
* `opts` (`struct Options`) - Common options
* `tryCaller` (`address`) - Address to use as the caller of the upgrade function. This should be the address that owns the proxy or its ProxyAdmin.

[.contract-item]
[[Upgrades-upgradeProxy-address-string-bytes-address-]]
==== `[.contract-item-name]#++upgradeProxy++#++(address proxy, string contractName, bytes data, address tryCaller)++` [.item-kind]#internal#

NOTE: For tests only. If broadcasting in scripts, use the `--sender <ADDRESS>` option with `forge script` instead.

Upgrades a proxy to a new implementation contract. Only supported for UUPS or transparent proxies.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

This function provides an additional `tryCaller` parameter to test an upgrade using a specific caller address.
Use this if you encounter `OwnableUnauthorizedAccount` errors in your tests.

*Parameters:*

* `proxy` (`address`) - Address of the proxy to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `data` (`bytes`) - Encoded call data of an arbitrary function to call during the upgrade process, or empty if no function needs to be called during the upgrade
* `tryCaller` (`address`) - Address to use as the caller of the upgrade function. This should be the address that owns the proxy or its ProxyAdmin.

[.contract-item]
[[Upgrades-deployBeacon-string-address-struct-Options-]]
==== `[.contract-item-name]#++deployBeacon++#++(string contractName, address initialOwner, struct Options opts) → address++` [.item-kind]#internal#

Deploys an upgradeable beacon using the given contract as the implementation.

*Parameters:*

* `contractName` (`string`) - Name of the contract to use as the implementation, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `initialOwner` (`address`) - Address to set as the owner of the UpgradeableBeacon contract which gets deployed
* `opts` (`struct Options`) - Common options

*Returns*

* (`address`) - Beacon address

[.contract-item]
[[Upgrades-deployBeacon-string-address-]]
==== `[.contract-item-name]#++deployBeacon++#++(string contractName, address initialOwner) → address++` [.item-kind]#internal#

Deploys an upgradeable beacon using the given contract as the implementation.

*Parameters:*

* `contractName` (`string`) - Name of the contract to use as the implementation, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `initialOwner` (`address`) - Address to set as the owner of the UpgradeableBeacon contract which gets deployed

*Returns*

* (`address`) - Beacon address

[.contract-item]
[[Upgrades-upgradeBeacon-address-string-struct-Options-]]
==== `[.contract-item-name]#++upgradeBeacon++#++(address beacon, string contractName, struct Options opts)++` [.item-kind]#internal#

Upgrades a beacon to a new implementation contract.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

*Parameters:*

* `beacon` (`address`) - Address of the beacon to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `opts` (`struct Options`) - Common options

[.contract-item]
[[Upgrades-upgradeBeacon-address-string-]]
==== `[.contract-item-name]#++upgradeBeacon++#++(address beacon, string contractName)++` [.item-kind]#internal#

Upgrades a beacon to a new implementation contract.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

*Parameters:*

* `beacon` (`address`) - Address of the beacon to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory

[.contract-item]
[[Upgrades-upgradeBeacon-address-string-struct-Options-address-]]
==== `[.contract-item-name]#++upgradeBeacon++#++(address beacon, string contractName, struct Options opts, address tryCaller)++` [.item-kind]#internal#

NOTE: For tests only. If broadcasting in scripts, use the `--sender <ADDRESS>` option with `forge script` instead.

Upgrades a beacon to a new implementation contract.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

This function provides an additional `tryCaller` parameter to test an upgrade using a specific caller address.
Use this if you encounter `OwnableUnauthorizedAccount` errors in your tests.

*Parameters:*

* `beacon` (`address`) - Address of the beacon to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `opts` (`struct Options`) - Common options
* `tryCaller` (`address`) - Address to use as the caller of the upgrade function. This should be the address that owns the beacon.

[.contract-item]
[[Upgrades-upgradeBeacon-address-string-address-]]
==== `[.contract-item-name]#++upgradeBeacon++#++(address beacon, string contractName, address tryCaller)++` [.item-kind]#internal#

NOTE: For tests only. If broadcasting in scripts, use the `--sender <ADDRESS>` option with `forge script` instead.

Upgrades a beacon to a new implementation contract.

Requires that either the `referenceContract` option is set, or the new implementation contract has a `@custom:oz-upgrades-from <reference>` annotation.

This function provides an additional `tryCaller` parameter to test an upgrade using a specific caller address.
Use this if you encounter `OwnableUnauthorizedAccount` errors in your tests.

*Parameters:*

* `beacon` (`address`) - Address of the beacon to upgrade
* `contractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `tryCaller` (`address`) - Address to use as the caller of the upgrade function. This should be the address that owns the beacon.

[.contract-item]
[[Upgrades-deployBeaconProxy-address-bytes-]]
==== `[.contract-item-name]#++deployBeaconProxy++#++(address beacon, bytes data) → address++` [.item-kind]#internal#

Deploys a beacon proxy using the given beacon and call data.

*Parameters:*

* `beacon` (`address`) - Address of the beacon to use
* `data` (`bytes`) - Encoded call data of the initializer function to call during creation of the proxy, or empty if no initialization is required

*Returns*

* (`address`) - Proxy address

[.contract-item]
[[Upgrades-deployBeaconProxy-address-bytes-struct-Options-]]
==== `[.contract-item-name]#++deployBeaconProxy++#++(address beacon, bytes data, struct Options opts) → address++` [.item-kind]#internal#

Deploys a beacon proxy using the given beacon and call data.

*Parameters:*

* `beacon` (`address`) - Address of the beacon to use
* `data` (`bytes`) - Encoded call data of the initializer function to call during creation of the proxy, or empty if no initialization is required
* `opts` (`struct Options`) - Common options

*Returns*

* (`address`) - Proxy address

[.contract-item]
[[Upgrades-validateImplementation-string-struct-Options-]]
==== `[.contract-item-name]#++validateImplementation++#++(string contractName, struct Options opts)++` [.item-kind]#internal#

Validates an implementation contract, but does not deploy it.

*Parameters:*

* `contractName` (`string`) - Name of the contract to validate, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `opts` (`struct Options`) - Common options

[.contract-item]
[[Upgrades-deployImplementation-string-struct-Options-]]
==== `[.contract-item-name]#++deployImplementation++#++(string contractName, struct Options opts) → address++` [.item-kind]#internal#

Validates and deploys an implementation contract, and returns its address.

*Parameters:*

* `contractName` (`string`) - Name of the contract to deploy, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `opts` (`struct Options`) - Common options

*Returns*

* (`address`) - Address of the implementation contract

[.contract-item]
[[Upgrades-validateUpgrade-string-struct-Options-]]
==== `[.contract-item-name]#++validateUpgrade++#++(string contractName, struct Options opts)++` [.item-kind]#internal#

Validates a new implementation contract in comparison with a reference contract, but does not deploy it.

Requires that either the `referenceContract` option is set, or the contract has a `@custom:oz-upgrades-from <reference>` annotation.

*Parameters:*

* `contractName` (`string`) - Name of the contract to validate, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `opts` (`struct Options`) - Common options

[.contract-item]
[[Upgrades-prepareUpgrade-string-struct-Options-]]
==== `[.contract-item-name]#++prepareUpgrade++#++(string contractName, struct Options opts) → address++` [.item-kind]#internal#

Validates a new implementation contract in comparison with a reference contract, deploys the new implementation contract,
and returns its address.

Requires that either the `referenceContract` option is set, or the contract has a `@custom:oz-upgrades-from <reference>` annotation.

Use this method to prepare an upgrade to be run from an admin address you do not control directly or cannot use from your deployment environment.

*Parameters:*

* `contractName` (`string`) - Name of the contract to deploy, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `opts` (`struct Options`) - Common options

*Returns*

* (`address`) - Address of the new implementation contract

[.contract-item]
[[Upgrades-getAdminAddress-address-]]
==== `[.contract-item-name]#++getAdminAddress++#++(address proxy) → address++` [.item-kind]#internal#

Gets the admin address of a transparent proxy from its ERC1967 admin storage slot.

*Parameters:*

* `proxy` (`address`) - Address of a transparent proxy

*Returns*

* (`address`) - Admin address

[.contract-item]
[[Upgrades-getImplementationAddress-address-]]
==== `[.contract-item-name]#++getImplementationAddress++#++(address proxy) → address++` [.item-kind]#internal#

Gets the implementation address of a transparent or UUPS proxy from its ERC1967 implementation storage slot.

*Parameters:*

* `proxy` (`address`) - Address of a transparent or UUPS proxy

*Returns*

* (`address`) - Implementation address

[.contract-item]
[[Upgrades-getBeaconAddress-address-]]
==== `[.contract-item-name]#++getBeaconAddress++#++(address proxy) → address++` [.item-kind]#internal#

Gets the beacon address of a beacon proxy from its ERC1967 beacon storage slot.

*Parameters:*

* `proxy` (`address`) - Address of a beacon proxy

*Returns*

* (`address`) - Beacon address

[.contract-item]
[[Upgrades-tryPrank-address-]]
==== `[.contract-item-name]#++tryPrank++#++(address deployer)++` [.item-kind]#modifier#

Runs a function as a prank, or just runs the function normally if the prank could not be started.

[.contract-item]
[[Upgrades-CHEATCODE_ADDRESS-address]]
==== `address [.contract-item-name]#++CHEATCODE_ADDRESS++#` [.item-kind]#internal constant#

== Foundry Defender

:deployContract: pass:normal[xref:#Defender-deployContract-string-[`++deployContract++`]]
:deployContract: pass:normal[xref:#Defender-deployContract-string-struct-DefenderOptions-[`++deployContract++`]]
:deployContract: pass:normal[xref:#Defender-deployContract-string-bytes-[`++deployContract++`]]
:deployContract: pass:normal[xref:#Defender-deployContract-string-bytes-struct-DefenderOptions-[`++deployContract++`]]
:proposeUpgrade: pass:normal[xref:#Defender-proposeUpgrade-address-string-struct-Options-[`++proposeUpgrade++`]]
:getDeployApprovalProcess: pass:normal[xref:#Defender-getDeployApprovalProcess--[`++getDeployApprovalProcess++`]]
:getUpgradeApprovalProcess: pass:normal[xref:#Defender-getUpgradeApprovalProcess--[`++getUpgradeApprovalProcess++`]]

[.contract]
[[Defender]]
=== `++Defender++` link:https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Defender.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import { Defender } from "openzeppelin-foundry-upgrades/Defender.sol";
```

Library for interacting with OpenZeppelin Defender from Forge scripts or tests.

[.contract-index]
.Functions
--
* {xref-Defender-deployContract-string-}[`++deployContract(contractName)++`]
* {xref-Defender-deployContract-string-struct-DefenderOptions-}[`++deployContract(contractName, defenderOpts)++`]
* {xref-Defender-deployContract-string-bytes-}[`++deployContract(contractName, constructorData)++`]
* {xref-Defender-deployContract-string-bytes-struct-DefenderOptions-}[`++deployContract(contractName, constructorData, defenderOpts)++`]
* {xref-Defender-proposeUpgrade-address-string-struct-Options-}[`++proposeUpgrade(proxyAddress, newImplementationContractName, opts)++`]
* {xref-Defender-getDeployApprovalProcess--}[`++getDeployApprovalProcess()++`]
* {xref-Defender-getUpgradeApprovalProcess--}[`++getUpgradeApprovalProcess()++`]

--

[.contract-item]
[[Defender-deployContract-string-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName) → address++` [.item-kind]#internal#

Deploys a contract to the current network using OpenZeppelin Defender.

WARNING: Do not use this function directly if you are deploying an upgradeable contract. This function does not validate whether the contract is upgrade safe.

NOTE: If using an EOA or Safe to deploy, go to https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] to submit the pending deployment while the script is running.
The script waits for the deployment to complete before it continues.

*Parameters:*

* `contractName` (`string`) - Name of the contract to deploy, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory

*Returns*

* (`address`) - Address of the deployed contract

[.contract-item]
[[Defender-deployContract-string-struct-DefenderOptions-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName, struct DefenderOptions defenderOpts) → address++` [.item-kind]#internal#

Deploys a contract to the current network using OpenZeppelin Defender.

WARNING: Do not use this function directly if you are deploying an upgradeable contract. This function does not validate whether the contract is upgrade safe.

NOTE: If using an EOA or Safe to deploy, go to https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] to submit the pending deployment while the script is running.
The script waits for the deployment to complete before it continues.

*Parameters:*

* `contractName` (`string`) - Name of the contract to deploy, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `defenderOpts` (`struct DefenderOptions`) - Defender deployment options. Note that the `useDefenderDeploy` option is always treated as `true` when called from this function.

*Returns*

* (`address`) - Address of the deployed contract

[.contract-item]
[[Defender-deployContract-string-bytes-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName, bytes constructorData) → address++` [.item-kind]#internal#

Deploys a contract with constructor arguments to the current network using OpenZeppelin Defender.

WARNING: Do not use this function directly if you are deploying an upgradeable contract. This function does not validate whether the contract is upgrade safe.

NOTE: If using an EOA or Safe to deploy, go to https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] to submit the pending deployment while the script is running.
The script waits for the deployment to complete before it continues.

*Parameters:*

* `contractName` (`string`) - Name of the contract to deploy, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `constructorData` (`bytes`) - Encoded constructor arguments

*Returns*

* (`address`) - Address of the deployed contract

[.contract-item]
[[Defender-deployContract-string-bytes-struct-DefenderOptions-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName, bytes constructorData, struct DefenderOptions defenderOpts) → address++` [.item-kind]#internal#

Deploys a contract with constructor arguments to the current network using OpenZeppelin Defender.

WARNING: Do not use this function directly if you are deploying an upgradeable contract. This function does not validate whether the contract is upgrade safe.

NOTE: If using an EOA or Safe to deploy, go to https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] to submit the pending deployment while the script is running.
The script waits for the deployment to complete before it continues.

*Parameters:*

* `contractName` (`string`) - Name of the contract to deploy, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `constructorData` (`bytes`) - Encoded constructor arguments
* `defenderOpts` (`struct DefenderOptions`) - Defender deployment options. Note that the `useDefenderDeploy` option is always treated as `true` when called from this function.

*Returns*

* (`address`) - Address of the deployed contract

[.contract-item]
[[Defender-proposeUpgrade-address-string-struct-Options-]]
==== `[.contract-item-name]#++proposeUpgrade++#++(address proxyAddress, string newImplementationContractName, struct Options opts) → struct ProposeUpgradeResponse++` [.item-kind]#internal#

Proposes an upgrade to an upgradeable proxy using OpenZeppelin Defender.

This function validates a new implementation contract in comparison with a reference contract, deploys the new implementation contract using Defender,
and proposes an upgrade to the new implementation contract using an upgrade approval process on Defender.

Supported for UUPS or Transparent proxies. Not currently supported for beacon proxies or beacons.
For beacons, use `Upgrades.prepareUpgrade` along with a transaction proposal on Defender to upgrade the beacon to the deployed implementation.

Requires that either the `referenceContract` option is set, or the contract has a `@custom:oz-upgrades-from <reference>` annotation.

WARNING: Ensure that the reference contract is the same as the current implementation contract that the proxy is pointing to.
This function does not validate that the reference contract is the current implementation.

NOTE: If using an EOA or Safe to deploy, go to https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] to submit the pending deployment of the new implementation contract while the script is running.
The script waits for the deployment to complete before it continues.

*Parameters:*

* `proxyAddress` (`address`) - The proxy address
* `newImplementationContractName` (`string`) - Name of the new implementation contract to upgrade to, e.g. "MyContract.sol" or "MyContract.sol:MyContract" or artifact path relative to the project root directory
* `opts` (`struct Options`) - Common options. Note that the `defender.useDefenderDeploy` option is always treated as `true` when called from this function.

*Returns*

* (`struct ProposeUpgradeResponse`) - Struct containing the proposal ID and URL for the upgrade proposal

[.contract-item]
[[Defender-getDeployApprovalProcess--]]
==== `[.contract-item-name]#++getDeployApprovalProcess++#++() → struct ApprovalProcessResponse++` [.item-kind]#internal#

Gets the default deploy approval process configured for your deployment environment on OpenZeppelin Defender.

*Returns*

* (`struct ApprovalProcessResponse`) - Struct with the default deploy approval process ID and the associated address, such as a Relayer, EOA, or multisig wallet address.

[.contract-item]
[[Defender-getUpgradeApprovalProcess--]]
==== `[.contract-item-name]#++getUpgradeApprovalProcess++#++() → struct ApprovalProcessResponse++` [.item-kind]#internal#

Gets the default upgrade approval process configured for your deployment environment on OpenZeppelin Defender.
For example, this is useful for determining the default multisig wallet that you can use in your scripts to assign as the owner of your proxy.

*Returns*

* (`struct ApprovalProcessResponse`) - Struct with the default upgrade approval process ID and the associated address, such as a multisig or governor contract address.

