error[Sui E02002]: invalid 'entry' function signature
  ┌─ tests/sui_mode/entry_points/generic_obj_ref_vector.move:4:32
  │
4 │     public entry fun no<T:key>(_: &vector<T>) {
  │            -----               ^  ---------- 'entry' parameters must be primitives (by-value), vectors of primitives, objects (by-reference or by-value), or vectors of objects
  │            │                   │   
  │            │                   Invalid 'entry' parameter type for parameter '_'
  │            'no' was declared 'entry' here

