error[Sui E02002]: invalid 'entry' function signature
  ┌─ tests/sui_mode/entry_points/nested_key_generic_vector_param.move:3:34
  │
3 │     public entry fun foo<T: key>(_: vector<vector<T>>) {
  │            -----                 ^  ----------------- 'entry' parameters must be primitives (by-value), vectors of primitives, objects (by-reference or by-value), or vectors of objects
  │            │                     │   
  │            │                     Invalid 'entry' parameter type for parameter '_'
  │            'foo' was declared 'entry' here

