error[Sui E02002]: invalid 'entry' function signature
  ┌─ tests/sui_mode/entry_points/non_key_struct.move:6:25
  │
6 │     public entry fun no(_: S) {
  │            -----        ^  - 'entry' parameters must be primitives (by-value), vectors of primitives, objects (by-reference or by-value), or vectors of objects
  │            │            │   
  │            │            Invalid 'entry' parameter type for parameter '_'
  │            'no' was declared 'entry' here

