processed 2 tasks

task 0 'publish'. lines 6-16:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: 0x1::option::Option<T0>\"), command: None } }" }

task 1 'publish'. lines 18-28:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: vector<0x1::option::Option<T0>>\"), command: None } }" }
