processed 2 tasks

task 0 'publish'. lines 6-21:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: 0x0::m::Obj<0x0::m::NoStore>\"), command: None } }" }

task 1 'publish'. lines 23-35:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: 0x0::m::Obj<T0>\"), command: None } }" }
