processed 6 tasks

task 0 'publish'. lines 6-13:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point return type. Expected a non reference type.\"), command: None } }" }

task 1 'publish'. lines 15-22:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point return type. Expected a non reference type.\"), command: None } }" }

task 2 'publish'. lines 24-31:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point return type. Expected a non reference type.\"), command: None } }" }

task 3 'publish'. lines 33-41:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point return type. The specified return type does not have the 'drop' ability: 0x0::m::Copyable\"), command: None } }" }

task 4 'publish'. lines 43-52:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point return type. The specified return type does not have the 'drop' ability: 0x0::m::Obj\"), command: None } }" }

task 5 'publish'. lines 54-63:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point return type. The specified return type does not have the 'drop' ability: vector<0x0::m::Obj>\"), command: None } }" }
