processed 6 tasks

task 0, lines 1-10:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 1, lines 11-20:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 2, lines 21-30:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 3, lines 31-40:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 4, lines 41-50:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 5, lines 51-60:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}
