processed 4 tasks

task 0, lines 1-23:
//# publish
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::Test'. Got VMError: {
    major_status: NEGATIVE_STACK_SIZE_WITHIN_BLOCK,
    sub_status: None,
    location: 0x1::Test,
    indices: [(FunctionDefinition, 1)],
    offsets: [(FunctionDefinitionIndex(1), 0)],
}

task 1, lines 25-46:
//# publish
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::Test'. Got VMError: {
    major_status: GENERIC_MEMBER_OPCODE_MISMATCH,
    sub_status: None,
    location: 0x1::Test,
    indices: [],
    offsets: [(FunctionDefinitionIndex(1), 1)],
}

task 2, lines 48-69:
//# publish
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::Test'. Got VMError: {
    major_status: NEGATIVE_STACK_SIZE_WITHIN_BLOCK,
    sub_status: None,
    location: 0x1::Test,
    indices: [(FunctionDefinition, 1)],
    offsets: [(FunctionDefinitionIndex(1), 0)],
}

task 3, lines 71-92:
//# publish
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::Test'. Got VMError: {
    major_status: NEGATIVE_STACK_SIZE_WITHIN_BLOCK,
    sub_status: None,
    location: 0x1::Test,
    indices: [(FunctionDefinition, 1)],
    offsets: [(FunctionDefinitionIndex(1), 0)],
}
