processed 4 tasks

task 0 'run'. lines 1-11:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 1 'run'. lines 12-22:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: NEGATIVE_STACK_SIZE_WITHIN_BLOCK,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 2 'run'. lines 23-35:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: POSITIVE_STACK_SIZE_AT_BLOCK_END,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 3 'run'. lines 36-48:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: NEGATIVE_STACK_SIZE_WITHIN_BLOCK,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}
