processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-167:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 18164000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 169-171:
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4), object(2,5), object(2,6), object(2,7), object(2,8), object(2,9), object(2,10), object(2,11), object(2,12), object(2,13), object(2,14), object(2,15), object(2,16)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 34002400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 173-173:
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,8),
        },
    },
    other: test::m::EnumWrapper::A{
        pos0: test::m::Inner::A{
            pos0: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
        },
    },
    wrapped: test::m::Wrapped {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        other: test::m::EnumWrapper::A{
            pos0: test::m::Inner::A{
                pos0: sui::object::UID {
                    id: sui::object::ID {
                        bytes: _,
                    },
                },
            },
        },
    },
    many: vector[
        test::m::Wrapped {
            id: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
            other: test::m::EnumWrapper::A{
                pos0: test::m::Inner::A{
                    pos0: sui::object::UID {
                        id: sui::object::ID {
                            bytes: _,
                        },
                    },
                },
            },
        },
        test::m::Wrapped {
            id: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
            other: test::m::EnumWrapper::B{
                pos0: test::m::Inner::B{
                    pos0: sui::object::UID {
                        id: sui::object::ID {
                            bytes: _,
                        },
                    },
                },
            },
        },
    ],
}

task 4 'programmable'. lines 175-176:
mutated: object(0,0), object(2,8), object(2,9), object(2,10), object(2,11), object(2,12), object(2,13), object(2,14), object(2,15), object(2,16)
gas summary: computation_cost: 1000000, storage_cost: 14364000,  storage_rebate: 14220360, non_refundable_storage_fee: 143640

task 5 'view-object'. lines 178-178:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,8),
        },
    },
    other: test::m::EnumWrapper::A{
        pos0: test::m::Inner::A{
            pos0: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
        },
    },
    wrapped: test::m::Wrapped {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        other: test::m::EnumWrapper::A{
            pos0: test::m::Inner::A{
                pos0: sui::object::UID {
                    id: sui::object::ID {
                        bytes: _,
                    },
                },
            },
        },
    },
    many: vector[
        test::m::Wrapped {
            id: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
            other: test::m::EnumWrapper::A{
                pos0: test::m::Inner::A{
                    pos0: sui::object::UID {
                        id: sui::object::ID {
                            bytes: _,
                        },
                    },
                },
            },
        },
        test::m::Wrapped {
            id: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
            other: test::m::EnumWrapper::B{
                pos0: test::m::Inner::B{
                    pos0: sui::object::UID {
                        id: sui::object::ID {
                            bytes: _,
                        },
                    },
                },
            },
        },
    ],
}

task 6 'programmable'. lines 180-181:
mutated: object(0,0), object(2,8)
deleted: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4), object(2,5), object(2,6), object(2,7), object(2,9), object(2,10), object(2,11), object(2,12), object(2,13), object(2,14), object(2,15), object(2,16)
gas summary: computation_cost: 1000000, storage_cost: 3967200,  storage_rebate: 33662376, non_refundable_storage_fee: 340024

task 7 'view-object'. lines 183-185:
Owner: Account Address ( A )
Version: 4
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,8),
        },
    },
    other: test::m::EnumWrapper::A{
        pos0: test::m::Inner::A{
            pos0: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
        },
    },
    wrapped: test::m::Wrapped {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        other: test::m::EnumWrapper::A{
            pos0: test::m::Inner::A{
                pos0: sui::object::UID {
                    id: sui::object::ID {
                        bytes: _,
                    },
                },
            },
        },
    },
    many: vector[
        test::m::Wrapped {
            id: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
            other: test::m::EnumWrapper::A{
                pos0: test::m::Inner::A{
                    pos0: sui::object::UID {
                        id: sui::object::ID {
                            bytes: _,
                        },
                    },
                },
            },
        },
        test::m::Wrapped {
            id: sui::object::UID {
                id: sui::object::ID {
                    bytes: _,
                },
            },
            other: test::m::EnumWrapper::B{
                pos0: test::m::Inner::B{
                    pos0: sui::object::UID {
                        id: sui::object::ID {
                            bytes: _,
                        },
                    },
                },
            },
        },
    ],
}

task 8 'programmable'. lines 187-188:
mutated: object(_), object(2,8)
gas summary: computation_cost: 500000, storage_cost: 3967200,  storage_rebate: 2949408, non_refundable_storage_fee: 29792

task 9 'programmable'. lines 190-191:
mutated: object(_), object(2,8)
gas summary: computation_cost: 500000, storage_cost: 3967200,  storage_rebate: 2949408, non_refundable_storage_fee: 29792

task 10 'programmable'. lines 193-198:
mutated: object(_), object(2,8)
gas summary: computation_cost: 500000, storage_cost: 3967200,  storage_rebate: 2949408, non_refundable_storage_fee: 29792

task 11 'programmable'. lines 199-202:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 14, instruction: 18, function_name: Some("check_") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 14, instruction: 18, function_name: Some("check_") }, 0) in command 0

task 12 'programmable'. lines 203-206:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0

task 13 'programmable'. lines 207-208:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 14, instruction: 26, function_name: Some("check_") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 14, instruction: 26, function_name: Some("check_") }, 0) in command 0
