processed 17 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-54:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9606400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 56-56:
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4), object(2,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 11004800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 58-58:
Owner: Object ID: ( fake(2,5) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(2,2)}}

task 4 'view-object'. lines 60-60:
Owner: Object ID: ( fake(2,3) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(2,4)}}

task 5 'view-object'. lines 62-62:
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 6 'view-object'. lines 64-64:
Owner: Account Address ( A )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,3)}}, value: 0u64}

task 7 'view-object'. lines 66-66:
Owner: Object ID: ( fake(2,1) )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,4)}}, value: 0u64}

task 8 'view-object'. lines 68-68:
Owner: Account Address ( A )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,5)}}, value: 0u64}

task 9 'run'. lines 70-70:
mutated: object(0,0), object(2,3), object(2,4), object(2,5)
gas summary: computation_cost: 1000000, storage_cost: 4818400,  storage_rebate: 4770216, non_refundable_storage_fee: 48184

task 10 'view-object'. lines 72-72:
Owner: Object ID: ( fake(2,5) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(2,2)}}

task 11 'view-object'. lines 74-74:
Owner: Object ID: ( fake(2,3) )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(2,4)}}

task 12 'view-object'. lines 76-76:
Owner: Object ID: ( fake(2,0) )
Version: 2
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 13 'view-object'. lines 78-78:
Owner: Account Address ( fake(2,5) )
Version: 3
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,3)}}, value: 40u64}

task 14 'view-object'. lines 80-80:
Owner: Object ID: ( fake(2,1) )
Version: 3
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,4)}}, value: 40u64}

task 15 'view-object'. lines 82-82:
Owner: Account Address ( A )
Version: 3
Contents: tto::M1::A {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,5)}}, value: 0u64}

task 16 'run'. lines 84-84:
created: object(16,0)
mutated: object(0,0), object(2,3), object(2,5)
gas summary: computation_cost: 1000000, storage_cost: 5996400,  storage_rebate: 3506184, non_refundable_storage_fee: 35416
