warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/parser/control_exp_as_term.move:7:13
  │
7 │         1 + loop {} + 2;
  │             ^^^^^^^ Expected a value. Any code surrounding or after this expression will not be reached
  │
  = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/parser/control_exp_as_term.move:8:9
  │
8 │         1 + return + 0;
  │         ^^^^^^^^^^^^^^ Unreachable code. This statement (and any following statements) will not be executed.
  │
  = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

