processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7691200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 44-44:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 46-46:
Owner: Shared
Version: 2
Contents: a::m::Inner {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 4 'run'. lines 48-48:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::dynamic_field::add_child_object (function index 10) at offset 0, Abort Code: 1
Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 10, instruction: 0, function_name: Some("add_child_object") }, 1) at command Some(0)

task 5 'run'. lines 50-50:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'view-object'. lines 52-52:
Owner: Shared
Version: 4
Contents: a::m::Inner {id: sui::object::UID {id: sui::object::ID {bytes: fake(5,0)}}}

task 7 'run'. lines 54-54:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::dynamic_field::add_child_object (function index 10) at offset 0, Abort Code: 1
Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 10, instruction: 0, function_name: Some("add_child_object") }, 1) at command Some(0)
