processed 9 tasks

task 1 'publish'. lines 9-30:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5342800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 32-40:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4453600,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 42-42:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 44-46:
Owner: Shared
Version: 4
Contents: t2::o2::Obj2 {id: sui::object::UID {id: sui::object::ID {bytes: fake(3,0)}}}

task 5 'run'. lines 47-47:
mutated: object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 6 'run'. lines 49-49:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'view-object'. lines 51-53:
Owner: Shared
Version: 6
Contents: t2::o2::Obj2 {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}

task 8 'run'. lines 54-54:
mutated: object(0,0)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2204532, non_refundable_storage_fee: 22268
