processed 7 tasks

task 1 'publish'. lines 8-28:
created: object(104)
written: object(103)

task 2 'publish'. lines 30-38:
created: object(106)
written: object(105)

task 3 'run'. lines 41-41:
created: object(108)
written: object(107)

task 4 'view-object'. lines 43-43:
Owner: Shared
Version: 2
Contents: t2::o2::Obj2 {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}

task 5 'run'. lines 45-45:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue }, source: None, command: Some(0) } }

task 6 'run'. lines 47-47:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue }, source: None, command: Some(0) } }
