processed 11 tasks

task 1 'publish'. lines 6-35:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6384000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 37-37:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 39-39:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 41-41:
Owner: Shared
Version: 3
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 5 'view-object'. lines 43-45:
Owner: Shared
Version: 4
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
}

task 6 'programmable'. lines 46-48:
mutated: object(0,0), object(2,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 3430944, non_refundable_storage_fee: 34656

task 7 'run'. lines 50-50:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'view-object'. lines 52-54:
Owner: Shared
Version: 6
Contents: sui::coin::Coin<sui::sui::SUI> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(7,0),
        },
    },
    balance: sui::balance::Balance<sui::sui::SUI> {
        value: 0u64,
    },
}

task 9 'programmable'. lines 55-61:
created: object(9,0)
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 10 'programmable'. lines 62-66:
created: object(10,0)
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 1956240, non_refundable_storage_fee: 19760
