processed 12 tasks

task 1 'publish'. lines 8-29:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5882400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 31-31:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'view-object'. lines 33-33:
Owner: Shared( 3 )
Version: 3
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'run'. lines 35-35:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 5 'view-object'. lines 37-37:
Owner: Shared( 3 )
Version: 4
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 6 'run'. lines 39-39:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 7 'view-object'. lines 41-41:
Owner: Shared( 0 )
Version: 5
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 8 'run'. lines 43-43:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 9 'view-object'. lines 45-45:
Owner: Shared( 0 )
Version: 6
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 10 'run'. lines 47-47:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2226800,  storage_rebate: 2204532, non_refundable_storage_fee: 22268

task 11 'view-object'. lines 49-49:
Owner: Shared( 0 )
Version: 7
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}
