processed 7 tasks

init:
A: object(100)

task 1 'publish'. lines 8-40:
created: object(105)
written: object(104)

task 2 'run'. lines 42-42:
created: object(107), object(108), object(109), object(110)
written: object(106)

task 3 'view-object'. lines 44-44:
Owner: Object ID: ( fake(107) )
Version: 2
Contents: t::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}}

task 4 'run'. lines 46-46:
Error: Object 0xe6ff026a903dda0711f951bab1d01161791f0f6fe94badadcb0424cf05bd591d is owned by object 0xf2c06d97f4ad9da4a8a6cfb80dd73173302be0c6c245c62279a4bc86a366f33c. Objects owned by other objects cannot be used as input arguments.

task 5 'run'. lines 48-48:
Error: Object 0xe6ff026a903dda0711f951bab1d01161791f0f6fe94badadcb0424cf05bd591d is owned by object 0xf2c06d97f4ad9da4a8a6cfb80dd73173302be0c6c245c62279a4bc86a366f33c. Objects owned by other objects cannot be used as input arguments.

task 6 'run'. lines 50-50:
Error: Object 0xe6ff026a903dda0711f951bab1d01161791f0f6fe94badadcb0424cf05bd591d is owned by object 0xf2c06d97f4ad9da4a8a6cfb80dd73173302be0c6c245c62279a4bc86a366f33c. Objects owned by other objects cannot be used as input arguments.
