processed 7 tasks

init:
A: object(100)

task 1 'publish'. lines 8-40:
created: object(105)
written: object(104)

task 2 'run'. lines 42-42:
created: object(107), object(108), object(109), object(110)
written: object(106)

task 3 'view-object'. lines 44-44:
Owner: Account Address ( A )
Version: 2
Contents: t::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}}

task 4 'run'. lines 46-46:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::share_object (function index 2) at offset 0, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 2, instruction: 0, function_name: Some("share_object") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(2), 0)] }), command: Some(0) } }

task 5 'run'. lines 48-48:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::share_object (function index 2) at offset 0, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 2, instruction: 0, function_name: Some("share_object") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(2), 0)] }), command: Some(0) } }

task 6 'run'. lines 50-50:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::share_object (function index 2) at offset 0, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 2, instruction: 0, function_name: Some("share_object") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(2), 0)] }), command: Some(0) } }
