erlang_application(
    name = "common",
    srcs = glob([
        "src/*.erl",
        "src/*.hrl",
    ]),
    applications = [
        "kernel",
        "stdlib",
    ],
    erl_opts = [
        "+debug_info",
        "+warnings_as_errors",
    ],
    includes = glob(["include/*.hrl"]),
    shell_libs = [],
    use_global_parse_transforms = False,
    visibility = ["PUBLIC"],
)
