{
 "title": "Cluster Running Status",
 "time": { "from": "2024-02-27T20:55:44.150Z", "to": "2024-02-28T14:08:15.494Z" },
 "templating": {
  "list": [
   { "name": "validator", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{host=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} 50%ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{host=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} 95%ile"
    }
   ]
  },
  {
   "title": "Handle Cert 50%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "validator_service_handle_certificate_consensus_latency{host=~\"$validator\", pct=\"50\"} / 1000",
     "legendFormat": "{{host}} shared obj txn"
    },
    {
     "expr": "validator_service_handle_certificate_non_consensus_latency{host=~\"$validator\", pct=\"50\"} / 1000",
     "legendFormat": "{{host}} single write txn"
    }
   ]
  },
  {
   "title": "Handle Cert 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "validator_service_handle_certificate_consensus_latency{host=~\"$validator\", pct=\"95\"} / 1000",
     "legendFormat": "{{host}} shared obj txn"
    },
    {
     "expr": "validator_service_handle_certificate_non_consensus_latency{host=~\"$validator\", pct=\"95\"} / 1000",
     "legendFormat": "{{host}} single write txn"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_tx_errors[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Txn Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Txn Rate (1m interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "quantile(0.67, sum by (host) (rate(total_transaction_certificates{host=~\"$validator\"}[1m])) - sum by (host) (rate(num_shared_obj_tx{host=~\"$validator\"}[1m])))",
     "legendFormat": "Owned"
    },
    {
     "expr": "quantile(0.67, rate(num_shared_obj_tx{host=~\"$validator\"}[1m]))",
     "legendFormat": "Shared"
    }
   ]
  },
  {
   "title": "Txn Manager Executing Cert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(transaction_manager_num_executing_certificates{host=~\"$validator\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "transaction_manager_num_executing_certificates{host=~\"$validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txn Manager Pending Cert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(transaction_manager_num_pending_certificates{host=~\"$validator\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "transaction_manager_num_pending_certificates{host=~\"$validator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txn Rate (5min interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "quantile(0.67, sum by (host) (rate(total_transaction_certificates{host=~\"$validator\"}[5m])) - sum by (host) (rate(num_shared_obj_tx{host=~\"$validator\"}[5m])))",
     "legendFormat": "Owned"
    },
    {
     "expr": "quantile(0.67, rate(num_shared_obj_tx{host=~\"$validator\"}[5m]))",
     "legendFormat": "Shared"
    }
   ]
  },
  {
   "title": "Execution Driver Dispatch Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "execution_driver_dispatch_queue{host=~\"$validator\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Txn Manager Ready Cert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(transaction_manager_num_ready{host=~\"$validator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(transaction_manager_num_ready{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Try Execute Immediately and Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(authority_state_internal_execution_latency_bucket{host=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(authority_state_commit_certificate_latency_bucket{host=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Manager Tx Enqueue Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "rate(transaction_manager_num_enqueued_certificates{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}} {{result}}"
    }
   ]
  },
  { "title": "Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Overload Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "authority_overload_status{host=~\"$validator\"}",
     "legendFormat": "{{host}} overload status"
    }
   ]
  },
  {
   "title": "Load shedding percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "authority_load_shedding_percentage{host=~\"$validator\"}",
     "legendFormat": "{{host}} load shedding percentage"
    }
   ]
  },
  {
   "title": "Queueing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le, host) (rate(execution_queueing_delay_s_bucket{host=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Last Constructed Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(last_constructed_checkpoint{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Checkpoint Age (50%ile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "last_created_checkpoint_age_ms{host=~\"$validator\", pct=\"50\"}",
     "legendFormat": "Created {{host}}"
    },
    {
     "expr": "last_executed_checkpoint_age_ms{host=~\"$validator\", pct=\"50\"}",
     "legendFormat": "Executed {{host}}"
    },
    {
     "expr": "last_certified_checkpoint_age_ms{host=~\"$validator\", pct=\"50\"}",
     "legendFormat": "Certified {{host}}"
    }
   ]
  },
  {
   "title": "Checkpoint Execution In flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "checkpoint_exec_inflight{host=~\"$validator\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Last Executed Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(last_executed_checkpoint{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Checkpoint Age (95%ile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "last_created_checkpoint_age_ms{pct=\"95\", host=~\"$validator\"}",
     "legendFormat": "{{host}} last created"
    },
    {
     "expr": "last_executed_checkpoint_age_ms{host=~\"$validator\", pct=\"95\"}",
     "legendFormat": "{{host}} last executed"
    },
    {
     "expr": "last_certified_checkpoint_age_ms{host=~\"$validator\", pct=\"95\"}",
     "legendFormat": "{{host}} last certified"
    }
   ]
  },
  {
   "title": "Checkpoint Seq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "last_constructed_checkpoint{host=~\"$validator\"}",
     "legendFormat": "Created {{host}}"
    },
    {
     "expr": "last_executed_checkpoint{host=~\"$validator\"}",
     "legendFormat": "Executed {{host}}"
    },
    {
     "expr": "last_certified_checkpoint{host=~\"$validator\"}",
     "legendFormat": "Certified {{host}}"
    },
    {
     "expr": "highest_verified_checkpoint{host=~\"$validator\"}",
     "legendFormat": "Verified {{host}}"
    }
   ]
  },
  {
   "title": "Checkpoint Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "rate(last_constructed_checkpoint{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Created {{host}}"
    },
    {
     "expr": "rate(last_executed_checkpoint{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Executed {{host}}"
    },
    {
     "expr": "rate(last_certified_checkpoint{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Certified {{host}}"
    },
    {
     "expr": "rate(highest_verified_checkpoint{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Verified {{host}}"
    }
   ]
  },
  {
   "title": "RocksDb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "RocksDb Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, db_name) (rate(rocksdb_write_batch_commit_latency_seconds_bucket{host=~\"$validator\"}[$__rate_interval])))",
       "legendFormat": "{{db_name}} batch commit"
      }
     ]
    },
    {
     "title": "Get Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_get_latency_seconds_bucket{host=~\"$validator\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Batch Size (KB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, db_name) (rate(rocksdb_batch_commit_bytes_bucket{host=~\"$validator\", db_name!=\"checkpoint\"}[$__rate_interval]))) / 1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RocksDb Put Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_put_latency_seconds_bucket{host=~\"$validator\"}[$__rate_interval])))",
       "legendFormat": "{{cf_name}} delete"
      }
     ]
    },
    {
     "title": "Iter Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "clamp_max(histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_iter_latency_seconds_bucket{host=~\"$validator\"}[$__rate_interval]))), 0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RocksDb Delete Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate( rocksdb_delete_latency_seconds_bucket {host=~\"$validator\"}[$__rate_interval])))",
       "legendFormat": "{{cf_name}} delete"
      }
     ]
    },
    {
     "title": "Multi Get Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_multiget_latency_seconds_bucket{host=~\"$validator\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}