warning[Lint W01008]: Detected a meaningless math operation that has no effect.
   ┌─ tests/linter/false_negative_meaningless_math_operation.move:16:11
   │
16 │         x / 0 // This is undefined behavior, should be caught by a different linter
   │           ^ Detected a meaningless math operation that has no effect.
   │
   = This warning can be suppressed with '#[allow(lint(meaningless_math_operation))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

