warning[Lint W00001]: constant should follow naming convention
  ┌─ tests/linter/incorrect_constant_naming.move:3:5
  │
3 │     const Another_BadName: u64 = 42; // Should trigger a warning
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'Another_BadName' should be ALL_CAPS. Or for error constants, use PascalCase
  │
  = This warning can be suppressed with '#[allow(lint(constant_naming))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W00001]: constant should follow naming convention
  ┌─ tests/linter/incorrect_constant_naming.move:6:5
  │
6 │     const minimumValue: u64 = 10; 
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'minimumValue' should be ALL_CAPS. Or for error constants, use PascalCase
  │
  = This warning can be suppressed with '#[allow(lint(constant_naming))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

error[E02010]: invalid name
  ┌─ tests/linter/incorrect_constant_naming.move:6:11
  │
6 │     const minimumValue: u64 = 10; 
  │           ^^^^^^^^^^^^ Invalid constant name 'minimumValue'. Constant names must start with 'A'..'Z'

warning[Lint W00001]: constant should follow naming convention
  ┌─ tests/linter/incorrect_constant_naming.move:7:5
  │
7 │     const some_important_number: u64 = 55;
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'some_important_number' should be ALL_CAPS. Or for error constants, use PascalCase
  │
  = This warning can be suppressed with '#[allow(lint(constant_naming))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

error[E02010]: invalid name
  ┌─ tests/linter/incorrect_constant_naming.move:7:11
  │
7 │     const some_important_number: u64 = 55;
  │           ^^^^^^^^^^^^^^^^^^^^^ Invalid constant name 'some_important_number'. Constant names must start with 'A'..'Z'

warning[Lint W00001]: constant should follow naming convention
   ┌─ tests/linter/incorrect_constant_naming.move:10:5
   │
10 │     const JSON_Max_Size: u64 = 1048576;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 'JSON_Max_Size' should be ALL_CAPS. Or for error constants, use PascalCase
   │
   = This warning can be suppressed with '#[allow(lint(constant_naming))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

error[E02010]: invalid name
   ┌─ tests/linter/incorrect_constant_naming.move:15:11
   │
15 │     const numItems: u64 = 30;   
   │           ^^^^^^^^ Invalid constant name 'numItems'. Constant names must start with 'A'..'Z'

