warning[Lint W02019]: Freezing a capability-like type can lead to design issues.
   ┌─ tests/linter/incorrect_freezing_capability.move:10:9
   │
10 │         transfer::public_freeze_object(w);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Freezing a capability-like type can lead to design issues.
   │
   = This warning can be suppressed with '#[allow(lint(freezing_capability))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

