warning[Lint W01010]: 
   ┌─ tests/linter/incorrect_collapsible_else_if.move:6:16
   │  
 6 │           } else {
   │ ╭────────────────^
 7 │ │             if (x < 0) {
 8 │ │                 
 9 │ │             }
10 │ │         }
   │ ╰─────────^ Detected a collapsible `else { if ... }` expression. Consider refactoring to `else if ...`.
   │  
   = This warning can be suppressed with '#[allow(lint(collapsible_else_if))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

