warning[Lint W01015]: Function has too many parameters, which may hinder readability and maintainability.
  ┌─ tests/linter/incorrect_too_many_arguments.move:4:82
  │  
4 │       public fun badFunction(_a: u64, _b: u64, _c: u64, _d: u64, _e: u64, _f: u64) {
  │ ╭──────────────────────────────────────────────────────────────────────────────────^
5 │ │         // Function body
6 │ │     }
  │ ╰─────^ Function 'badFunction' has too many parameters (6). Consider refactoring to improve readability.
  │  
  = This warning can be suppressed with '#[allow(lint(excessive_params))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

