warning[Lint W02002]: Potential overflow detected. The number of bits being shifted exceeds the bit width of the variable being shifted.
  ┌─ tests/linter/incorrect_shift_overflow.move:3:18
  │
3 │         let _b = x << 64; // Should raise an issue
  │                  ^^^^^^^ The 64 of bits being shifted exceeds the 64 bit width of the variable being shifted.
  │
  = This warning can be suppressed with '#[allow(lint(shift_overflow))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W02002]: Potential overflow detected. The number of bits being shifted exceeds the bit width of the variable being shifted.
  ┌─ tests/linter/incorrect_shift_overflow.move:4:18
  │
4 │         let _b = x << 65; // Should raise an issue
  │                  ^^^^^^^ The 65 of bits being shifted exceeds the 64 bit width of the variable being shifted.
  │
  = This warning can be suppressed with '#[allow(lint(shift_overflow))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W02002]: Potential overflow detected. The number of bits being shifted exceeds the bit width of the variable being shifted.
  ┌─ tests/linter/incorrect_shift_overflow.move:5:18
  │
5 │         let _b = x >> 66; // Should raise an issue
  │                  ^^^^^^^ The 66 of bits being shifted exceeds the 64 bit width of the variable being shifted.
  │
  = This warning can be suppressed with '#[allow(lint(shift_overflow))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

