warning[Lint W01016]: Double comparison detected that could be simplified to a single range check.
  ┌─ tests/linter/incorrect_double_comparisons.move:8:13
  │
8 │         if (x == 10 || x > 10) {
  │             ^^^^^^^^^^^^^^^^^ Consider simplifying this comparison to `>=` for better clarity.
  │
  = This warning can be suppressed with '#[allow(lint(double_comparison))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W01016]: Double comparison detected that could be simplified to a single range check.
   ┌─ tests/linter/incorrect_double_comparisons.move:12:13
   │
12 │         if (x == 10 || 10 > x) {};
   │             ^^^^^^^^^^^^^^^^^ Consider simplifying this comparison to `>=` for better clarity.
   │
   = This warning can be suppressed with '#[allow(lint(double_comparison))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

