warning[Lint W01007]: 
   ┌─ tests/linter/incorrect_excessive_nesting.move:10:36
   │  
10 │                       if (x - y < 0) {
   │ ╭────────────────────────────────────^
11 │ │                         // Further nesting beyond recommended levels
12 │ │                         if (y % 2 == 0) {
13 │ │                             abort 1
   · │
16 │ │                         }
17 │ │                     };
   │ ╰─────────────────────^ Detected excessive block nesting. Consider refactoring to simplify the code.
   │  
   = This warning can be suppressed with '#[allow(lint(excessive_nesting))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

