warning[Lint W04010]: unit `()` expression can be removed or simplified
  ┌─ tests/linter/suppress_combinable_bool_conditions.move:8:30
  │
8 │         if (x == y || x < y) {};
  │             ---------------  ^^ Unnecessary unit '()'
  │             │                 
  │             Consider negating the 'if' condition and simplifying
  │
  = For example 'if (cond) () else e' can be simplified to 'if (!cond) e'
  = This warning can be suppressed with '#[allow(lint(unnecessary_unit))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W04010]: unit `()` expression can be removed or simplified
   ┌─ tests/linter/suppress_combinable_bool_conditions.move:11:50
   │
11 │         if (get_value() == y || get_value() < y) {};
   │             -----------------------------------  ^^ Unnecessary unit '()'
   │             │                                     
   │             Consider negating the 'if' condition and simplifying
   │
   = For example 'if (cond) () else e' can be simplified to 'if (!cond) e'
   = This warning can be suppressed with '#[allow(lint(unnecessary_unit))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

