error[E02010]: invalid name
  ┌─ tests/linter/suppressed_incorrect_constant_naming.move:7:11
  │
7 │     const minimumValue: u64 = 10; 
  │           ^^^^^^^^^^^^ Invalid constant name 'minimumValue'. Constant names must start with 'A'..'Z'

error[E02010]: invalid name
  ┌─ tests/linter/suppressed_incorrect_constant_naming.move:8:11
  │
8 │     const some_important_number: u64 = 55;
  │           ^^^^^^^^^^^^^^^^^^^^^ Invalid constant name 'some_important_number'. Constant names must start with 'A'..'Z'

error[E02010]: invalid name
   ┌─ tests/linter/suppressed_incorrect_constant_naming.move:14:11
   │
14 │     const numItems: u64 = 30;   
   │           ^^^^^^^^ Invalid constant name 'numItems'. Constant names must start with 'A'..'Z'

