warning[Lint W02006]: 
  ┌─ tests/linter/true_positive_public_mut_tx_context.move:4:38
  │
4 │     public fun incorrect_mint(_ctx: &TxContext) {
  │                                      ^^^^^^^^^ Public functions should take `&mut TxContext` instead of `&TxContext` for better upgradability.
  │
  = This warning can be suppressed with '#[allow(lint(require_mutable_tx_context))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W02006]: 
  ┌─ tests/linter/true_positive_public_mut_tx_context.move:8:48
  │
8 │     public fun another_incorrect(_a: u64, _b: &TxContext, _c: u64) {
  │                                                ^^^^^^^^^ Public functions should take `&mut TxContext` instead of `&TxContext` for better upgradability.
  │
  = This warning can be suppressed with '#[allow(lint(require_mutable_tx_context))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

