warning[Lint W02011]: Equal operands detected in binary operation, which might indicate a logical error or redundancy.
  ┌─ tests/linter/true_negative_unnecessary_while_loop.move:8:16
  │
8 │         while (false || false) {};
  │                ^^^^^^^^^^^^^^ Equal operands detected in binary operation, which might indicate a logical error or redundancy.
  │
  = This warning can be suppressed with '#[allow(lint(equal_operands))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

