warning[Lint W01002]: unnecessary 'while (true)', replace with 'loop'
  ┌─ tests/linter/true_positive_empty_loop.move:4:9
  │
4 │         while (true) {}
  │         ^^^^^^^^^^^^^^^ 'while (true)' can be always replaced with 'loop'
  │
  = A 'loop' is more useful in these cases. Unlike 'while', 'loop' can have a 'break' with a value, e.g. 'let x = loop { break 42 };'
  = This warning can be suppressed with '#[allow(lint(while_true))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W01006]: empty loop
  ┌─ tests/linter/true_positive_empty_loop.move:8:9
  │
8 │         loop {}
  │         ^^^^^^^ Detected an empty loop expression potentially leading to an infinite loop.
  │
  = This warning can be suppressed with '#[allow(lint(empty_loop))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[Lint W01006]: empty loop
   ┌─ tests/linter/true_positive_empty_loop.move:12:9
   │  
12 │ ╭         loop {
13 │ │             // Empty block
14 │ │         }
   │ ╰─────────^ Detected an empty loop expression potentially leading to an infinite loop.
   │  
   = This warning can be suppressed with '#[allow(lint(empty_loop))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

