warning[Lint W01008]: excessive nesting
  ┌─ tests/linter/true_negative_unnecessary_while_loop.move:8:32
  │
8 │         while (false || false) {};
  │                                ^^ Detected excessive block nesting. Consider refactoring to simplify the code.
  │
  = This warning can be suppressed with '#[allow(lint(excessive_nesting))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

