warning[Lint W01008]: excessive nesting
   ┌─ tests/linter/true_negative_excessive_nesting.move:23:20
   │  
23 │           if (x > 5) {
   │ ╭────────────────────^
24 │ │             {
25 │ │                 // Still only 2nd level
26 │ │             }
27 │ │         };
   │ ╰─────────^ Detected excessive block nesting. Consider refactoring to simplify the code.
   │  
   = This warning can be suppressed with '#[allow(lint(excessive_nesting))]' applied to the 'module' or module member ('const', 'fun', or 'struct')

