warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_2024/parsing/clever_errors_raw_abort.move:30:10
   │
30 │     abort;
   │     -----^
   │     │    │
   │     │    Invalid trailing ';'
   │     │    A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │     Any code after this expression will not be reached
   │
   = This warning can be suppressed with '#[allow(unused_trailing_semi)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

