current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 10)
    scope 0 :
      val2 : 7
      type: u64

      shadowed_var : 7
      type: u64

      res : 0
      type: u64

    scope 1 :
      shadowed_var : 14
      type: u64

current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 12)
    scope 0 :
      shadowed_var : 7
      type: u64

      res : 0
      type: u64

    scope 1 :
      shadowed_var : 14
      type: u64

    scope 2 :
      shadowed_var : 21
      type: u64

current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 17)
    scope 0 :
      shadowed_var : 7
      type: u64

      res : 84
      type: u64

    scope 1 :
      shadowed_var : 14
      type: u64

current frame stack:
  function: test (line 25)
    scope 0 :
  function: foo (line 20)
    scope 0 :
      shadowed_var : 7
      type: u64

      res : 98
      type: u64

