note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:16:15
   │
16 │         let A(.., _q) = a;
   │               ^^ Ellipsis expansion: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:17:19
   │
17 │         let A(_q, ..) = a;
   │                   ^^ Ellipsis expansion: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:18:15
   │
18 │         let A(..) = a;
   │               ^^ Ellipsis expansion: _, _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:20:24
   │
20 │         let B { q: _q, .. } = b;
   │                        ^^ Ellipsis expansion: a: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:21:24
   │
21 │         let B { a: _a, .. } = b;
   │                        ^^ Ellipsis expansion: q: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:22:17
   │
22 │         let B { .. } = b;
   │                 ^^ Ellipsis expansion: a: _, q: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:25:22
   │
25 │             C::X(_q, ..) => (),
   │                      ^^ Ellipsis expansion: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:26:18
   │
26 │             C::X(.., _z) => (),
   │                  ^^ Ellipsis expansion: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:27:18
   │
27 │             C::X(..) => (),
   │                  ^^ Ellipsis expansion: _, _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:29:27
   │
29 │             C::Y { y: _y, .. } => (),
   │                           ^^ Ellipsis expansion: z: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:30:20
   │
30 │             C::Y { .., y: _y } => (),
   │                    ^^ Ellipsis expansion: z: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:31:20
   │
31 │             C::Y { .., z: _z } => (),
   │                    ^^ Ellipsis expansion: y: _

note[I15005]: IDE ellipsis expansion
   ┌─ tests/move_2024/ide_mode/ellipsis_expansion.move:32:20
   │
32 │             C::Y { .. } => ()
   │                    ^^ Ellipsis expansion: y: _, z: _

