warning[W09005]: dead or unreachable code
   ┌─ tests/move_check/control_flow/infinite_loop_with_dead_exits.move:13:17
   │
13 │             if (return) break;
   │                 ^^^^^^ Invalid use of a divergent expression. The code following the evaluation of this expression will be dead and should be removed.
   │
   = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09004]: unnecessary trailing semicolon
   ┌─ tests/move_check/control_flow/infinite_loop_with_dead_exits.move:13:30
   │
13 │             if (return) break;
   │             -----------------^
   │             │                │
   │             │                Invalid trailing ';'
   │             │                A trailing ';' in an expression block implicitly adds a '()' value after the semicolon. That '()' value will not be reachable
   │             Any code after this expression will not be reached
   │
   = This warning can be suppressed with '#[allow(unused_trailing_semi)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

