processed 9 tasks

task 0 'print-bytecode'. lines 1-13:
// Move bytecode v7
module 1.m {




entry foo() {
L0:	loc0: u64
L1:	loc1: &u64
B0:
	0: LdU64(3)
	1: StLoc[0](loc0: u64)
	2: ImmBorrowLoc[0](loc0: u64)
	3: StLoc[1](loc1: &u64)
	4: MoveLoc[1](loc1: &u64)
	5: Pop
	6: Ret

}
}

task 1 'print-bytecode'. lines 15-28:
// Move bytecode v7
module 2.m {




entry foo() {
L0:	loc0: u64
L1:	loc1: &u64
L2:	loc2: &u64
B0:
	0: LdU64(3)
	1: StLoc[0](loc0: u64)
	2: ImmBorrowLoc[0](loc0: u64)
	3: StLoc[1](loc1: &u64)
	4: ImmBorrowLoc[1](loc1: &u64)
	5: StLoc[2](loc2: &u64)
	6: Ret

}
}

task 2 'print-bytecode'. lines 30-63:
// Move bytecode v7
module 1d4.M {
struct T {
	u: u64
}



f(Arg0: &T) {
B0:
	0: MoveLoc[0](Arg0: &T)
	1: ImmBorrowField[0](T.u: u64)
	2: StLoc[1](loc0: &u64)
	3: MoveLoc[1](loc0: &u64)
	4: Pop
	5: Ret

}
g(Arg0: &mut T) {
B0:
	0: MoveLoc[0](Arg0: &mut T)
	1: ImmBorrowField[0](T.u: u64)
	2: StLoc[1](loc0: &u64)
	3: MoveLoc[1](loc0: &u64)
	4: Pop
	5: Ret

}
public h(Arg0: &mut T) {
B0:
	0: MoveLoc[0](Arg0: &mut T)
	1: MutBorrowField[0](T.u: u64)
	2: StLoc[1](loc0: &mut u64)
	3: MoveLoc[1](loc0: &mut u64)
	4: Pop
	5: Ret

}
}

task 3 'print-bytecode'. lines 65-84:
// Move bytecode v7
module 2d4.M {
struct T<Ty0> {
	u: Ty0
}



f(Arg0: &T<u64>) {
B0:
	0: MoveLoc[0](Arg0: &T<u64>)
	1: ImmBorrowFieldGeneric[0](T.u: Ty0)
	2: StLoc[1](loc0: &u64)
	3: MoveLoc[1](loc0: &u64)
	4: Pop
	5: Ret

}
g(Arg0: &mut T<u128>) {
B0:
	0: MoveLoc[0](Arg0: &mut T<u128>)
	1: ImmBorrowFieldGeneric[1](T.u: Ty0)
	2: StLoc[1](loc0: &u128)
	3: MoveLoc[1](loc0: &u128)
	4: Pop
	5: Ret

}
}

task 5 'print-bytecode'. lines 97-112:
Error: Unbound struct Self.T

task 6 'print-bytecode'. lines 114-125:
Error: Unbound struct Self.T

task 7 'print-bytecode'. lines 127-142:
Error: Unbound struct Self.T

task 8 'print-bytecode'. lines 144-154:
Error: Unbound module alias M
