current frame stack:
  function: test (m.move:33)
    scope 0 :
      some_struct : (0x0::m::SomeStruct) {
        struct_field : (0x0::m::VecStruct) {
          vec_field : [
            0 : 0
            1 : 7
          ]
        }
      }
      type: 0x0::m::SomeStruct

  function: foo (m.move:19)
    scope 0 :
      some_struct_ref : (0x0::m::SomeStruct) {
        struct_field : (0x0::m::VecStruct) {
          vec_field : [
            0 : 0
            1 : 7
          ]
        }
      }
      type: &mut 0x0::m::SomeStruct

  function: bar (m.move:13)
    scope 0 :
      vec_ref : [
        0 : 0
        1 : 7
      ]
      type: &mut vector<u64>

current frame stack:
  function: test (m.move:33)
    scope 0 :
      some_struct : (0x0::m::SomeStruct) {
        struct_field : (0x0::m::VecStruct) {
          vec_field : [
            0 : 42
            1 : 7
          ]
        }
      }
      type: 0x0::m::SomeStruct

  function: foo (m.move:19)
    scope 0 :
      some_struct_ref : (0x0::m::SomeStruct) {
        struct_field : (0x0::m::VecStruct) {
          vec_field : [
            0 : 42
            1 : 7
          ]
        }
      }
      type: &mut 0x0::m::SomeStruct

  function: bar (m.move:15)
    scope 0 :
      vec_ref : [
        0 : 42
        1 : 7
      ]
      type: &mut vector<u64>

