#!/bin/bash

if [ "$1" != "simtest" ]; then
  echo "expected to be invoked via \`cargo simtest\`"
  exit 1
fi

# consume simtest arg
shift

# cargo does not export $CARGO_MANIFEST_DIR to subcommands so we have to find it
# ourselves.
STARTING_DIR=$(pwd)
MANIFEST_DIR="$STARTING_DIR"
while true; do
  if grep -q '^\[workspace\]$' Cargo.toml 2> /dev/null; then
    break
  fi
  cd ..
  MANIFEST_DIR=$(pwd)
done

cd "$MANIFEST_DIR"
if ! git diff --quiet Cargo.lock; then
  echo "Please commit or revert your changes to Cargo.lock before running cargo simtest"
  exit 1
fi
cd "$STARTING_DIR"

cleanup () {
  cd "$MANIFEST_DIR"
  git checkout Cargo.lock > /dev/null
  cd "$STARTING_DIR"
}

trap cleanup SIGINT

if [ -z "$MADSIM_TEST_SEED" ]; then
  export MADSIM_TEST_SEED=1
else
  echo "Using MADSIM_TEST_SEED=$MADSIM_TEST_SEED from the environment"
fi

cargo nextest run \
  --cargo-profile simulator \
  --config 'build.rustflags = ["--cfg", "madsim"]' \
  --config 'patch.crates-io.tokio.path = "/Users/mlogan/dev/madsim-fork/madsim-tokio"' \
  --config 'patch.crates-io.hyper.path = "/Users/mlogan/dev/madsim-fork/hyper-madsim-fork"' \
  "$@"


STATUS=$?

cleanup

exit $STATUS
