processed 2 tasks

task 0 'publish'. lines 1-12:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::A'. Got VMError: {
    major_status: WRITEREF_WITHOUT_DROP_ABILITY,
    sub_status: None,
    location: 0x42::A,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 1 'publish'. lines 14-25:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000043::A'. Got VMError: {
    major_status: WRITEREF_WITHOUT_DROP_ABILITY,
    sub_status: None,
    location: 0x43::A,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
