processed 18 tasks

task 0 'run'. lines 1-9:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 1 'run'. lines 11-20:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'run'. lines 21-30:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'run'. lines 31-40:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 4 'run'. lines 41-50:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 5 'run'. lines 51-60:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 6 'run'. lines 62-71:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 7 'run'. lines 72-81:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 8 'run'. lines 82-91:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 9 'run'. lines 92-101:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 10 'run'. lines 102-111:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 11 'run'. lines 112-121:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 12 'publish'. lines 123-131:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 13 'publish'. lines 133-141:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 14 'publish'. lines 143-151:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 15 'publish'. lines 153-161:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 16 'publish'. lines 163-171:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 17 'publish'. lines 173-181:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M'. Got VMError: {
    major_status: INTEGER_OP_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
