processed 3 tasks

task 1 'run'. lines 21-30:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x1::M,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'run'. lines 32-41:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x1::M,
    indices: [],
    offsets: [(FunctionDefinitionIndex(1), 1)],
}
