processed 2 tasks

task 0 'publish'. lines 1-12:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::M'. Got VMError: {
    major_status: COPYLOC_WITHOUT_COPY_ABILITY,
    sub_status: None,
    location: 0x1::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}

task 1 'publish'. lines 14-25:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::M'. Got VMError: {
    major_status: COPYLOC_WITHOUT_COPY_ABILITY,
    sub_status: None,
    location: 0x2::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 0)],
}
