processed 8 tasks

task 0 'publish'. lines 1-11:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::M'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x1::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 1 'publish'. lines 13-24:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::N'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x1::N,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2 'publish'. lines 26-37:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::O'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x1::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 3 'publish'. lines 39-50:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::P'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x1::P,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 4 'publish'. lines 53-63:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::M'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x2::M,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 5 'publish'. lines 65-76:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::N'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x2::N,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 6 'publish'. lines 78-89:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7 'publish'. lines 91-102:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::P'. Got VMError: {
    major_status: PACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x2::P,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}
