processed 2 tasks

task 0 'publish'. lines 1-25:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::Token'. Got VMError: {
    major_status: UNPACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::Token,
    indices: [(FunctionDefinition, 2)],
    offsets: [(FunctionDefinitionIndex(2), 1)],
}

task 1 'publish'. lines 27-38:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::Token'. Got VMError: {
    major_status: UNPACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x42::Token,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}
