processed 8 tasks

task 0 'publish'. lines 1-10:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M1'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x42::M1,
    indices: [(Signature, 0), (FunctionHandle, 0)],
    offsets: [],
}

task 1 'publish'. lines 12-21:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M2'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x42::M2,
    indices: [(Signature, 0), (FunctionHandle, 0)],
    offsets: [],
}

task 2 'publish'. lines 23-32:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M3'. Got VMError: {
    major_status: NUMBER_OF_TYPE_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 3 'publish'. lines 34-44:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::M4'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x42::M4,
    indices: [(Signature, 0), (FunctionHandle, 0)],
    offsets: [],
}

task 4 'publish'. lines 46-55:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000043::M1'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x43::M1,
    indices: [(Signature, 0), (FunctionHandle, 0)],
    offsets: [],
}

task 5 'publish'. lines 57-66:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000043::M2'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x43::M2,
    indices: [(Signature, 0), (FunctionHandle, 0)],
    offsets: [],
}

task 6 'publish'. lines 68-77:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000043::M3'. Got VMError: {
    major_status: NUMBER_OF_TYPE_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 7 'publish'. lines 79-89:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000043::M4'. Got VMError: {
    major_status: CONSTRAINT_NOT_SATISFIED,
    sub_status: None,
    location: 0x43::M4,
    indices: [(Signature, 0), (FunctionHandle, 0)],
    offsets: [],
}
