processed 2 tasks

task 0 'publish'. lines 1-19:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::Test'. Got VMError: {
    major_status: UNPACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x1::Test,
    indices: [(FunctionDefinition, 1)],
    offsets: [(FunctionDefinitionIndex(1), 1)],
}

task 1 'publish'. lines 21-38:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::Test'. Got VMError: {
    major_status: UNPACK_TYPE_MISMATCH_ERROR,
    sub_status: None,
    location: 0x2::Test,
    indices: [(FunctionDefinition, 1)],
    offsets: [(FunctionDefinitionIndex(1), 1)],
}
