processed 3 tasks

task 1 'publish'. lines 16-28:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: PARTIAL_ENUM_SWITCH,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'publish'. lines 30-43:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: PARTIAL_ENUM_SWITCH,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}
