processed 11 tasks

task 0 'publish'. lines 1-14:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: ENUM_SWITCH_BAD_OPERAND,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 1 'publish'. lines 16-29:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: ENUM_SWITCH_BAD_OPERAND,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'publish'. lines 31-44:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: ENUM_SWITCH_BAD_OPERAND,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'publish'. lines 46-59:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: ENUM_TYPE_MISMATCH,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 4 'publish'. lines 61-74:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: ENUM_SWITCH_BAD_OPERAND,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 5 'publish'. lines 77-92:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: ENUM_TYPE_MISMATCH,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 6 'publish'. lines 94-109:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: ENUM_SWITCH_BAD_OPERAND,
    sub_status: None,
    location: 0x2::O,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 8 'publish'. lines 127-141:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::P'. Got VMError: {
    major_status: ENUM_TYPE_MISMATCH,
    sub_status: None,
    location: 0x2::P,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 9 'publish'. lines 143-157:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::P'. Got VMError: {
    major_status: ENUM_TYPE_MISMATCH,
    sub_status: None,
    location: 0x2::P,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 10 'publish'. lines 159-173:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::P'. Got VMError: {
    major_status: ENUM_TYPE_MISMATCH,
    sub_status: None,
    location: 0x2::P,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}
