processed 3 tasks

task 1 'publish'. lines 16-28:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: INVALID_ENUM_SWITCH,
    sub_status: None,
    location: undefined,
    indices: [(VariantTag, 0)],
    offsets: [],
}

task 2 'publish'. lines 30-43:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000002::O'. Got VMError: {
    major_status: INVALID_ENUM_SWITCH,
    sub_status: None,
    location: undefined,
    indices: [(VariantTag, 1)],
    offsets: [],
}
