processed 4 tasks

task 0, lines 1-13:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 1, lines 15-29:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2, lines 31-42:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 3, lines 44-56:
//# run
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000042::m'. Got VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: 0x42::m,
    indices: [(FunctionDefinition, 0)],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}
