error[Sui E02009]: invalid private transfer call
  ┌─ tests/sui_mode/private_generics/no_public_transfer_generic.move:9:9
  │
8 │     public fun t1<T: key>(s: T) {
  │                              - The type 'T' is not declared in the current module
9 │         transfer::transfer(s, @0x100);
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::transfer' is restricted to being called in the object's module

error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_generic.move:13:9
   │
12 │     public fun t2<T: key>(s: T) {
   │                              - The type 'T' is not declared in the current module
13 │         transfer::freeze_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::freeze_object' is restricted to being called in the object's module

error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_generic.move:17:9
   │
16 │     public fun t3<T: key>(s: T) {
   │                              - The type 'T' is not declared in the current module
17 │         transfer::share_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::share_object' is restricted to being called in the object's module

