Command `migrate`:
Package toml does not specify an edition. As of 2024, Move requires all packages to define a language edition.

Please select one of the following editions:

1) 2024
2) legacy

Selection (default=1): 

Would you like the Move compiler to migrate your code to Move 2024? (Y/n) 
Generated changes . . .
INCLUDING DEPENDENCY MoveStdlib
BUILDING A

The following changes will be made.
============================================================

--- ./sources/address_migration.move
+++ ./sources/address_migration.move
@@ -1,2 +1,2 @@
-address 0x2 {
-module m {
+/* address 0x2 { */
+module 0x2::m {
@@ -4 +4 @@
-module n {
+module 0x2::n {
@@ -6 +6 @@
-}
+/* } */
--- ./sources/address_migration1.move
+++ ./sources/address_migration1.move
@@ -1 +1 @@
-address /* some inline comment */ 0x2 
+/* address /* some inline comment */ 0x2 
@@ -3,2 +3,2 @@
-{
-module m {
+{ */
+module 0x2::m {
@@ -6 +6 @@
-module n {
+module 0x2::n {
@@ -8 +8 @@
-/* an inline comment*/}
+/* an inline comment*//* } */
--- ./sources/address_migration2.move
+++ ./sources/address_migration2.move
@@ -1 +1 @@
-address 0x2{ module m {} module n {}}
+/* address 0x2{ */ module 0x2::m {} module 0x2::n {}/* } */
--- ./sources/address_migration3.move
+++ ./sources/address_migration3.move
@@ -1,2 +1,2 @@
-address A {
-module m {
+/* address A { */
+module A::m {
@@ -4 +4 @@
-module n {
+module A::n {
@@ -6 +6 @@
-}
+/* } */


============================================================
Apply changes? (Y/n) 
Updating "./sources/address_migration.move" . . .
Updating "./sources/address_migration1.move" . . .
Updating "./sources/address_migration2.move" . . .
Updating "./sources/address_migration3.move" . . .

Changes complete
Wrote patchfile out to: ./migration.patch

Recorded edition in 'Move.toml'
External Command `diff -r -s sources migration_sources`:
Files sources/address_migration.move and migration_sources/address_migration.move are identical
Files sources/address_migration1.move and migration_sources/address_migration1.move are identical
Files sources/address_migration2.move and migration_sources/address_migration2.move are identical
Files sources/address_migration3.move and migration_sources/address_migration3.move are identical
External Command `diff -s Move.toml Move.toml.expected`:
Files Move.toml and Move.toml.expected are identical
