processed 4 tasks

task 1 'publish'. lines 8-18:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: IDENTIFIER_TOO_LONG, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: _, name: Identifier("M1_1234567891234567890123456789012345678912345678901234567890123456789123456789012345678908901234567891234567890123456789078912345678901234567890") }), indices: [(Identifier, 0)], offsets: [] }), command: Some(0) } }

task 2 'publish'. lines 20-30:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: IDENTIFIER_TOO_LONG, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: _, name: Identifier("M1_12345678912345678901234567890") }), indices: [(Identifier, 1)], offsets: [] }), command: Some(0) } }

task 3 'publish'. lines 33-57:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6095200,  storage_rebate: 978120, non_refundable_storage_fee: 9880
