processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-82:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9963600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 83-85:
Error: Transaction Effects Status: Move object with size 256001 is larger than the maximum object size 256000
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveObjectTooBig { object_size: 256001, max_object_size: 256000 }, source: None, command: None } }

task 3 'run'. lines 86-88:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1888000000, storage_cost: 1947553200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 89-89:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1888000000, storage_cost: 1947560800,  storage_rebate: 978120, non_refundable_storage_fee: 9880
