processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-32:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7926800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 34-36:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 38-38:
mutated: object(0,0), object(1,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2629600,  storage_rebate: 3280464, non_refundable_storage_fee: 33136

task 4 'run'. lines 40-40:
mutated: object(0,0), object(1,0)
unwrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 3313600,  storage_rebate: 2603304, non_refundable_storage_fee: 26296
