processed 7 tasks

init:
A: object(100), B: object(101), C: object(102)

task 1 'view-object'. lines 8-8:
Owner: Account Address ( A )
Version: 0
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(100)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 1000000u64}}

task 2 'run'. lines 10-10:
created: object(106)
written: object(100), object(105)

task 3 'view-object'. lines 12-12:
Owner: Account Address ( A )
Version: 1
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(100)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 999990u64}}

task 4 'view-object'. lines 14-14:
Owner: Account Address ( B )
Version: 1
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(106)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 10u64}}

task 5 'run'. lines 16-16:
created: object(108)
written: object(100), object(107)

task 6 'view-object'. lines 18-18:
Owner: Account Address ( A )
Version: 2
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(100)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 999990u64}}
