processed 9 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-70:
created: object(106)
written: object(105)

task 2 'run'. lines 72-72:
created: object(108)
written: object(107)

task 3 'view-object'. lines 74-74:
Owner: Account Address ( A )
Version: 2
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}, value: 10u64}

task 4 'run'. lines 76-76:
written: object(108), object(109)

task 5 'view-object'. lines 78-78:
Owner: Account Address ( B )
Version: 3
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}, value: 10u64}

task 6 'run'. lines 80-80:
created: object(111)
written: object(110)

task 7 'run'. lines 82-82:
events: CoinBalanceChange { package_id: sui, transaction_module: Identifier("gas"), sender: B, change_type: Gas, owner: AddressOwner(B), coin_type: "sui::sui::SUI", coin_object_id: fake(112), version: SequenceNumber(1), amount: -390 }, MutateObject { package_id: sui, transaction_module: Identifier("unused_input_object"), sender: B, object_type: "test::object_basics::Object", object_id: fake(108), version: SequenceNumber(4) }, MutateObject { package_id: sui, transaction_module: Identifier("unused_input_object"), sender: B, object_type: "test::object_basics::Object", object_id: fake(111), version: SequenceNumber(4) }, MoveEvent { package_id: test, transaction_module: Identifier("object_basics"), sender: B, type_: StructTag { address: test, module: Identifier("object_basics"), name: Identifier("NewValueEvent"), type_params: [] }, contents: [20, 0, 0, 0, 0, 0, 0, 0] }
written: object(108), object(111), object(112)

task 8 'run'. lines 84-84:
written: object(113)
deleted: object(108)
