processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-65:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7516400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 67-67:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2386400,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 69-69:
created: object(3,0)
mutated: object(0,1)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2637200,  storage_rebate: 2362536, non_refundable_storage_fee: 23864

task 4 'run'. lines 71-71:
mutated: object(0,1)
deleted: object(3,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2610828, non_refundable_storage_fee: 26372

task 5 'run'. lines 73-73:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2637200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 75-75:
mutated: object(0,1)
deleted: object(5,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2610828, non_refundable_storage_fee: 26372
