processed 7 tasks

init:
A: object(100)

task 1 'publish'. lines 9-42:
created: object(105)
written: object(104)

task 2 'run'. lines 44-44:
created: object(107)
written: object(106)

task 3 'view-object'. lines 46-46:
Owner: Account Address ( A )
Version: 2
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}, value: 10u64}

task 4 'run'. lines 48-48:
created: object(109)
written: object(108)
deleted: object(107)

task 5 'run'. lines 50-50:
written: object(107), object(110)
deleted: object(109)

task 6 'view-object'. lines 52-52:
Owner: Immutable
Version: 4
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}, value: 10u64}
