processed 7 tasks

init:
A: object(100)

task 1 'publish'. lines 9-71:
created: object(105)
written: object(104)

task 2 'run'. lines 73-73:
created: object(107)
written: object(106)

task 3 'view-object'. lines 75-75:
Owner: Account Address ( A )
Version: 2
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}, value: 10u64}

task 4 'run'. lines 77-77:
created: object(109)
written: object(108)
deleted: object(107)

task 5 'run'. lines 79-79:
written: object(107), object(110)
deleted: object(109)

task 6 'view-object'. lines 81-81:
Owner: Account Address ( A )
Version: 4
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}, value: 10u64}
