processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-71:
created: object(1,0)
mutated: object(0,1)

task 2 'run'. lines 73-73:
created: object(2,0)
mutated: object(0,1)

task 3 'view-object'. lines 75-75:
Owner: Account Address ( A )
Version: 3
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}

task 4 'run'. lines 77-77:
created: object(4,0)
mutated: object(0,0)
wrapped: object(2,0)

task 5 'run'. lines 79-79:
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(4,0)

task 6 'view-object'. lines 81-81:
Owner: Account Address ( A )
Version: 5
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}
