// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use prometheus::{
    Gauge, GaugeVec, Histogram, HistogramVec, IntCounter, IntCounterVec, IntGauge, IntGaugeVec,
    Registry, exponential_buckets, register_gauge_vec_with_registry, register_gauge_with_registry,
    register_histogram_vec_with_registry, register_histogram_with_registry,
    register_int_counter_vec_with_registry, register_int_counter_with_registry,
    register_int_gauge_vec_with_registry, register_int_gauge_with_registry,
};

use crate::network::metrics::NetworkMetrics;

// starts from 1μs, 50μs, 100μs...
const FINE_GRAINED_LATENCY_SEC_BUCKETS: &[f64] = &[
    0.000_001, 0.000_050, 0.000_100, 0.000_500, 0.001, 0.005, 0.01, 0.05, 0.1, 0.15, 0.2, 0.25,
    0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.5, 3.0, 3.5,
    4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10., 20., 30., 60., 120.,
];

const NUM_BUCKETS: &[f64] = &[
    1.0,
    2.0,
    4.0,
    8.0,
    10.0,
    20.0,
    40.0,
    80.0,
    100.0,
    150.0,
    200.0,
    250.0,
    300.0,
    400.0,
    500.0,
    600.0,
    700.0,
    800.0,
    900.0,
    1000.0,
    1500.0,
    2000.0,
    2500.0,
    3000.0,
    4000.0,
    5000.0,
    6000.0,
    7000.0,
    8000.0,
    9000.0,
    10000.0,
    15000.0,
    20000.0,
    25000.0,
    30000.0,
    40000.0,
    50000.0,
    100_000.0,
    200_000.0,
    300_000.0,
    500_000.0,
    1_000_000.0,
];

const LATENCY_SEC_BUCKETS: &[f64] = &[
    0.001, 0.005, 0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 0.9,
    1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5,
    9.0, 9.5, 10., 12.5, 15., 17.5, 20., 25., 30., 60., 90., 120., 180., 300.,
];

const SIZE_BUCKETS: &[f64] = &[
    100.,
    400.,
    800.,
    1_000.,
    2_000.,
    5_000.,
    10_000.,
    20_000.,
    50_000.,
    100_000.,
    150_000.,
    200_000.0,
    250_000.0,
    300_000.0,
    350_000.0,
    400_000.0,
    450_000.0,
    500_000.0,
    600_000.0,
    700_000.0,
    800_000.0,
    900_000.0,
    1_000_000.0,
    2_000_000.0,
    3_000_000.0,
    5_000_000.0,
    10_000_000.0,
]; // size in bytes

// Because of indirect finalization, the round delay should be at most 3 rounds.
const ROUND_DELAY_BUCKETS: &[f64] = &[0.0, 0.5, 1.0, 2.0, 3.0, 4.0];

pub struct Metrics {
    pub(crate) node_metrics: NodeMetrics,
    pub(crate) network_metrics: NetworkMetrics,
}

pub(crate) fn initialise_metrics(registry: Registry) -> Arc<Metrics> {
    let node_metrics = NodeMetrics::new(&registry);
    let network_metrics = NetworkMetrics::new(&registry);

    Arc::new(Metrics {
        node_metrics,
        network_metrics,
    })
}

pub(crate) fn test_metrics() -> Arc<Metrics> {
    initialise_metrics(Registry::new())
}

pub(crate) struct NodeMetrics {
    pub(crate) authority_index: IntGaugeVec,
    pub(crate) protocol_version: IntGauge,
    pub(crate) block_commit_latency: Histogram,
    pub(crate) handle_send_block_deserialize_latency: Histogram,
    pub(crate) handle_send_block_permit_wait_latency: Histogram,
    pub(crate) verify_block_latency: Histogram,
    pub(crate) verify_vote_batch_latency: Histogram,
    pub(crate) handle_send_block_verify_latency: Histogram,
    pub(crate) handle_send_block_add_blocks_latency: Histogram,
    pub(crate) handle_send_block_block_age: Histogram,
    pub(crate) threshold_clock_round_duration: Histogram,
    pub(crate) subscription_dispatch_age: Histogram,
    pub(crate) subscription_throttle_delay: Histogram,
    pub(crate) proposed_blocks: IntCounterVec,
    pub(crate) proposed_block_commit_latency: Histogram,
    pub(crate) proposed_block_finalization_latency: Histogram,
    pub(crate) proposed_block_size: Histogram,
    pub(crate) proposed_block_transactions: Histogram,
    pub(crate) proposed_block_transaction_bytes: Histogram,
    pub(crate) proposed_block_transaction_vote_blocks: Histogram,
    pub(crate) proposed_block_transaction_vote_entries: Histogram,
    pub(crate) proposed_block_ancestors: Histogram,
    pub(crate) proposed_block_ancestors_depth: HistogramVec,
    pub(crate) proposed_block_ancestors_timestamp_drift_ms: IntCounterVec,
    pub(crate) highest_verified_authority_round: IntGaugeVec,
    pub(crate) lowest_verified_authority_round: IntGaugeVec,
    pub(crate) block_proposal_interval: Histogram,
    pub(crate) block_proposal_leader_wait_ms: IntCounterVec,
    pub(crate) block_proposal_leader_wait_count: IntCounterVec,
    pub(crate) block_timestamp_drift_ms: IntCounterVec,
    pub(crate) blocks_per_commit_count: Histogram,
    pub(crate) blocks_pruned_on_commit: IntCounterVec,
    pub(crate) commit_observer_last_recovered_commit_index: IntGauge,
    pub(crate) core_add_blocks_batch_size: Histogram,
    pub(crate) core_check_block_refs_batch_size: Histogram,
    pub(crate) core_lock_dequeued: IntCounter,
    pub(crate) core_lock_enqueued: IntCounter,
    pub(crate) priority_submission_backpressure: IntCounter,
    pub(crate) core_skipped_proposals: IntCounterVec,
    pub(crate) handler_received_block_missing_ancestors: IntCounterVec,
    pub(crate) highest_accepted_authority_round: IntGaugeVec,
    pub(crate) highest_accepted_round: IntGauge,
    pub(crate) accepted_block_time_drift_ms: IntCounterVec,
    pub(crate) accepted_blocks: IntCounterVec,
    pub(crate) dag_state_recent_blocks: IntGauge,
    pub(crate) dag_state_recent_refs: IntGauge,
    pub(crate) dag_state_store_read_count: IntCounterVec,
    pub(crate) dag_state_store_write_count: IntCounter,
    pub(crate) fetch_blocks_scheduler_inflight: IntGauge,
    pub(crate) synchronizer_fetched_blocks_by_peer: IntCounterVec,
    pub(crate) synchronizer_missing_blocks_by_authority: IntCounterVec,
    pub(crate) synchronizer_current_missing_blocks_by_authority: IntGaugeVec,
    pub(crate) synchronizer_fetched_blocks_by_authority: IntCounterVec,
    pub(crate) synchronizer_fetch_failures: IntCounterVec,
    pub(crate) synchronizer_skipped_fetch_requests: IntCounterVec,
    pub(crate) synchronizer_process_fetched_failures: IntCounterVec,
    pub(crate) synchronizer_periodic_sync_decision: IntCounterVec,
    pub(crate) network_received_excluded_ancestors_from_authority: IntCounterVec,
    pub(crate) network_excluded_ancestors_sent_to_fetch: IntCounterVec,
    pub(crate) network_excluded_ancestors_count_by_authority: IntCounterVec,
    pub(crate) invalid_blocks: IntCounterVec,
    pub(crate) rejected_blocks: IntCounterVec,
    pub(crate) subscribed_blocks: IntCounterVec,
    pub(crate) observer_subscribed_blocks_batch_size: Histogram,
    pub(crate) verified_blocks: IntCounterVec,
    pub(crate) committed_leaders_total: IntCounterVec,
    pub(crate) last_committed_authority_round: IntGaugeVec,
    pub(crate) last_committed_leader_round: IntGauge,
    pub(crate) last_commit_index: IntGauge,
    pub(crate) last_commit_time_diff: Histogram,
    pub(crate) last_known_own_block_round: IntGauge,
    pub(crate) sync_last_known_own_block_retries: IntCounter,
    pub(crate) commit_round_advancement_interval: Histogram,
    pub(crate) last_decided_leader_round: IntGauge,
    pub(crate) leader_timeout_total: IntCounterVec,
    pub(crate) smart_selection_wait: IntCounter,
    pub(crate) ancestor_state_change_by_authority: IntCounterVec,
    pub(crate) excluded_proposal_ancestors_count_by_authority: IntCounterVec,
    pub(crate) included_excluded_proposal_ancestors_count_by_authority: IntCounterVec,
    pub(crate) missing_blocks_total: IntCounter,
    pub(crate) missing_blocks_after_fetch_total: IntCounter,
    pub(crate) num_of_bad_nodes: IntGauge,
    pub(crate) quorum_receive_latency: Histogram,
    pub(crate) block_receive_delay: IntCounterVec,
    pub(crate) reputation_scores: IntGaugeVec,
    pub(crate) leader_schedule_total_scores: IntGaugeVec,
    pub(crate) leader_schedule_normalized_scores: GaugeVec,
    pub(crate) leader_schedule_last_num_leaders: IntGauge,
    pub(crate) leader_schedule_average_num_leaders: Gauge,
    pub(crate) scope_processing_time: HistogramVec,
    pub(crate) sub_dags_per_commit_count: Histogram,
    pub(crate) block_suspensions: IntCounterVec,
    pub(crate) block_unsuspensions: IntCounterVec,
    pub(crate) suspended_block_time: HistogramVec,
    pub(crate) block_manager_suspended_blocks: IntGauge,
    pub(crate) block_manager_missing_ancestors: IntGauge,
    pub(crate) block_manager_missing_blocks: IntGauge,
    pub(crate) block_manager_missing_blocks_by_authority: IntCounterVec,
    pub(crate) block_manager_missing_ancestors_by_authority: IntCounterVec,
    pub(crate) block_manager_gced_blocks: IntCounterVec,
    pub(crate) block_manager_gc_unsuspended_blocks: IntCounterVec,
    pub(crate) block_manager_skipped_blocks: IntCounterVec,
    pub(crate) threshold_clock_round: IntGauge,
    pub(crate) subscriber_connection_attempts: IntCounterVec,
    pub(crate) subscribed_to: IntGaugeVec,
    pub(crate) subscribed_by: IntGaugeVec,
    pub(crate) commit_sync_inflight_fetches: IntGauge,
    pub(crate) commit_sync_pending_fetches: IntGauge,
    pub(crate) commit_sync_fetch_commits_handler_uncertified_skipped: IntCounter,
    pub(crate) commit_sync_fetched_commits: IntCounter,
    pub(crate) commit_sync_fetched_blocks: IntCounter,
    pub(crate) commit_sync_total_fetched_blocks_size: IntCounter,
    pub(crate) commit_sync_quorum_index: IntGauge,
    pub(crate) commit_sync_highest_synced_index: IntGauge,
    pub(crate) commit_sync_highest_fetched_index: IntGauge,
    pub(crate) commit_sync_local_index: IntGauge,
    pub(crate) commit_sync_gap_on_processing: IntCounter,
    pub(crate) commit_sync_fetch_loop_latency: Histogram,
    pub(crate) commit_sync_fetch_once_latency: Histogram,
    pub(crate) commit_sync_fetch_once_errors: IntCounterVec,
    pub(crate) commit_sync_fetch_missing_blocks: IntCounterVec,
    pub(crate) round_tracker_received_quorum_round_gaps: IntGaugeVec,
    pub(crate) round_tracker_accepted_quorum_round_gaps: IntGaugeVec,
    pub(crate) round_tracker_low_received_quorum_round: IntGaugeVec,
    pub(crate) round_tracker_low_accepted_quorum_round: IntGaugeVec,
    pub(crate) round_tracker_current_received_round_gaps: IntGaugeVec,
    pub(crate) round_tracker_current_accepted_round_gaps: IntGaugeVec,
    pub(crate) round_tracker_propagation_delays: Histogram,
    pub(crate) round_tracker_last_propagation_delay: IntGauge,
    pub(crate) round_prober_request_errors: IntCounterVec,
    pub(crate) certifier_gc_round: IntGauge,
    pub(crate) certifier_own_reject_votes: IntCounterVec,
    pub(crate) finalizer_buffered_commits: IntGauge,
    pub(crate) finalizer_blocks_entries: IntGauge,
    pub(crate) finalizer_blocks_bytes: IntGauge,
    pub(crate) certifier_votes_entries: IntGauge,
    pub(crate) certifier_votes_bytes: IntGauge,
    pub(crate) adaptive_block_cap_bytes: IntGauge,
    pub(crate) handle_send_block_pre_receive_age: Histogram,
    pub(crate) handle_send_block_verify_queue_wait: Histogram,
    pub(crate) handle_send_block_verify_exec: Histogram,
    pub(crate) handle_send_block_vote_record_latency: Histogram,
    pub(crate) handle_send_block_core_dispatch_latency: Histogram,
    pub(crate) handle_send_block_age_accepted: Histogram,
    pub(crate) signed_block_census: IntGauge,
    pub(crate) commit_sync_fetched_ranges_bytes: IntGauge,
    pub(crate) finalizer_round_delay: Histogram,
    pub(crate) finalizer_transaction_status: IntCounterVec,
    pub(crate) finalizer_reject_votes: IntCounterVec,
    pub(crate) finalizer_output_commits: IntCounterVec,
    pub(crate) finalizer_skipped_voting_blocks: IntCounterVec,
    pub(crate) uptime: Histogram,
}

impl NodeMetrics {
    pub(crate) fn new(registry: &Registry) -> Self {
        Self {
            authority_index: register_int_gauge_vec_with_registry!(
                "authority_index",
                "The index of the authority",
                &["name"],
                registry,
            ).unwrap(),
            protocol_version: register_int_gauge_with_registry!(
                "protocol_version",
                "The protocol version used in this epoch",
                registry,
            ).unwrap(),
            block_commit_latency: register_histogram_with_registry!(
                "block_commit_latency",
                "The time taken between block creation and block commit.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_deserialize_latency: register_histogram_with_registry!(
                "handle_send_block_deserialize_latency",
                "The time handle_send_block spends bcs-deserializing the received block.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            verify_block_latency: register_histogram_with_registry!(
                "verify_block_latency",
                "The time spent on block-level verification (signature, structure, digest) inside verify_and_vote.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            verify_vote_batch_latency: register_histogram_with_registry!(
                "verify_vote_batch_latency",
                "The time spent voting on all transactions of a block inside verify_and_vote.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_permit_wait_latency: register_histogram_with_registry!(
                "handle_send_block_permit_wait_latency",
                "The time handle_send_block waits to acquire a verification permit.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_verify_latency: register_histogram_with_registry!(
                "handle_send_block_verify_latency",
                "The time handle_send_block spends in verify_and_vote, including the blocking task round trip.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_add_blocks_latency: register_histogram_with_registry!(
                "handle_send_block_add_blocks_latency",
                "The time handle_send_block spends enqueuing a verified block to the Core thread.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            subscription_dispatch_age: register_histogram_with_registry!(
                "subscription_dispatch_age",
                "Block age when the author's per-peer subscription stream task yields it toward the network stack (fan-out dispatch latency).",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            subscription_throttle_delay: register_histogram_with_registry!(
                "subscription_throttle_delay",
                "Delay a received subscription-stream block spends in the min_round_delay/2 rate limiter before the subscriber sees it.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_block_age: register_histogram_with_registry!(
                "handle_send_block_block_age",
                "Age of a received block at handler entry: local receive time minus the author's block timestamp (includes author send queue, wire, h2 and decompression).",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            threshold_clock_round_duration: register_histogram_with_registry!(
                "threshold_clock_round_duration",
                "Wall time from round start (previous quorum) to quorum formation advancing the threshold clock.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            proposed_blocks: register_int_counter_vec_with_registry!(
                "proposed_blocks",
                "Total number of proposed blocks. If force is true then this block has been created forcefully via a leader timeout event.",
                &["force"],
                registry,
            ).unwrap(),
            proposed_block_commit_latency: register_histogram_with_registry!(
                "proposed_block_commit_latency",
                "The time taken between block proposal and commit.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            proposed_block_finalization_latency: register_histogram_with_registry!(
                "proposed_block_finalization_latency",
                "The time taken between block proposal and finalization.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            proposed_block_size: register_histogram_with_registry!(
                "proposed_block_size",
                "The size (in bytes) of proposed blocks",
                SIZE_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_transactions: register_histogram_with_registry!(
                "proposed_block_transactions",
                "# of transactions contained in proposed blocks",
                NUM_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_transaction_bytes: register_histogram_with_registry!(
                "proposed_block_transaction_bytes",
                "Total size (in bytes) of transactions contained in proposed blocks",
                SIZE_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_transaction_vote_blocks: register_histogram_with_registry!(
                "proposed_block_transaction_vote_blocks",
                "Number of blocks with reject votes contained in proposed blocks",
                NUM_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_transaction_vote_entries: register_histogram_with_registry!(
                "proposed_block_transaction_vote_entries",
                "Number of reject vote entries contained in proposed blocks",
                NUM_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_ancestors: register_histogram_with_registry!(
                "proposed_block_ancestors",
                "Number of ancestors in proposed blocks",
                exponential_buckets(1.0, 1.4, 20).unwrap(),
                registry,
            ).unwrap(),
            proposed_block_ancestors_timestamp_drift_ms: register_int_counter_vec_with_registry!(
                "proposed_block_ancestors_timestamp_drift_ms",
                "The drift in ms of ancestors' timestamps included in newly proposed blocks",
                &["authority"],
                registry,
            ).unwrap(),
            proposed_block_ancestors_depth: register_histogram_vec_with_registry!(
                "proposed_block_ancestors_depth",
                "The depth in rounds of ancestors included in newly proposed blocks",
                &["authority"],
                exponential_buckets(1.0, 2.0, 14).unwrap(),
                registry,
            ).unwrap(),
            highest_verified_authority_round: register_int_gauge_vec_with_registry!(
                "highest_verified_authority_round",
                "The highest round of verified block for the corresponding authority",
                &["authority"],
                registry,
            ).unwrap(),
            lowest_verified_authority_round: register_int_gauge_vec_with_registry!(
                "lowest_verified_authority_round",
                "The lowest round of verified block for the corresponding authority",
                &["authority"],
                registry,
            ).unwrap(),
            block_proposal_interval: register_histogram_with_registry!(
                "block_proposal_interval",
                "Intervals (in secs) between block proposals.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            block_proposal_leader_wait_ms: register_int_counter_vec_with_registry!(
                "block_proposal_leader_wait_ms",
                "Total time in ms spent waiting for a leader when proposing blocks.",
                &["authority"],
                registry,
            ).unwrap(),
            block_proposal_leader_wait_count: register_int_counter_vec_with_registry!(
                "block_proposal_leader_wait_count",
                "Total times waiting for a leader when proposing blocks.",
                &["authority"],
                registry,
            ).unwrap(),
            block_timestamp_drift_ms: register_int_counter_vec_with_registry!(
                "block_timestamp_drift_ms",
                "The clock drift time between a received block and the current node's time.",
                &["authority", "source"],
                registry,
            ).unwrap(),
            blocks_per_commit_count: register_histogram_with_registry!(
                "blocks_per_commit_count",
                "The number of blocks per commit.",
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            blocks_pruned_on_commit: register_int_counter_vec_with_registry!(
                "blocks_pruned_on_commit",
                "Number of blocks that got pruned due to garbage collection during a commit. This is not an accurate metric and measures the pruned blocks on the edge of the commit.",
                &["authority", "commit_status"],
                registry,
            ).unwrap(),
            commit_observer_last_recovered_commit_index: register_int_gauge_with_registry!(
                "commit_observer_last_recovered_commit_index",
                "The last commit index recovered by the commit observer",
                registry,
            ).unwrap(),
            core_add_blocks_batch_size: register_histogram_with_registry!(
                "core_add_blocks_batch_size",
                "The number of blocks received from Core for processing on a single batch",
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            core_check_block_refs_batch_size: register_histogram_with_registry!(
                "core_check_block_refs_batch_size",
                "The number of excluded blocks received from Core for search on a single batch",
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            core_lock_dequeued: register_int_counter_with_registry!(
                "core_lock_dequeued",
                "Number of dequeued core requests",
                registry,
            ).unwrap(),
            core_lock_enqueued: register_int_counter_with_registry!(
                "core_lock_enqueued",
                "Number of enqueued core requests",
                registry,
            ).unwrap(),
            priority_submission_backpressure: register_int_counter_with_registry!(
                "priority_submission_backpressure",
                "Number of high-priority submissions that found the reserved priority input channel full and had to wait for capacity",
                registry,
            ).unwrap(),
            core_skipped_proposals: register_int_counter_vec_with_registry!(
                "core_skipped_proposals",
                "Number of proposals skipped in the Core, per reason",
                &["reason"],
                registry,
            ).unwrap(),
            handler_received_block_missing_ancestors: register_int_counter_vec_with_registry!(
                "handler_received_block_missing_ancestors",
                "Number of missing ancestors in blocks received in the handler, separated by peer",
                &["authority"],
                registry,
            ).unwrap(),
            highest_accepted_authority_round: register_int_gauge_vec_with_registry!(
                "highest_accepted_authority_round",
                "The highest round where a block has been accepted per authority. Resets on restart.",
                &["authority"],
                registry,
            ).unwrap(),
            highest_accepted_round: register_int_gauge_with_registry!(
                "highest_accepted_round",
                "The highest round where a block has been accepted. Resets on restart.",
                registry,
            ).unwrap(),
            accepted_block_time_drift_ms: register_int_counter_vec_with_registry!(
                "accepted_block_time_drift_ms",
                "The time drift in ms of an accepted block compared to local time",
                &["authority"],
                registry,
            ).unwrap(),
            accepted_blocks: register_int_counter_vec_with_registry!(
                "accepted_blocks",
                "Number of accepted blocks by source (own, others)",
                &["source"],
                registry,
            ).unwrap(),
            dag_state_recent_blocks: register_int_gauge_with_registry!(
                "dag_state_recent_blocks",
                "Number of recent blocks cached in the DagState",
                registry,
            ).unwrap(),
            dag_state_recent_refs: register_int_gauge_with_registry!(
                "dag_state_recent_refs",
                "Number of recent refs cached in the DagState",
                registry,
            ).unwrap(),
            dag_state_store_read_count: register_int_counter_vec_with_registry!(
                "dag_state_store_read_count",
                "Number of times DagState needs to read from store per operation type",
                &["type"],
                registry,
            ).unwrap(),
            dag_state_store_write_count: register_int_counter_with_registry!(
                "dag_state_store_write_count",
                "Number of times DagState needs to write to store",
                registry,
            ).unwrap(),
            fetch_blocks_scheduler_inflight: register_int_gauge_with_registry!(
                "fetch_blocks_scheduler_inflight",
                "Designates whether the synchronizer scheduler task to fetch blocks is currently running",
                registry,
            ).unwrap(),
            synchronizer_fetched_blocks_by_peer: register_int_counter_vec_with_registry!(
                "synchronizer_fetched_blocks_by_peer",
                "Number of fetched blocks per peer authority via the synchronizer and also by block authority",
                &["peer", "type"],
                registry,
            ).unwrap(),
            synchronizer_missing_blocks_by_authority: register_int_counter_vec_with_registry!(
                "synchronizer_missing_blocks_by_authority",
                "Number of missing blocks per block author, as observed by the synchronizer during periodic sync.",
                &["authority"],
                registry,
            ).unwrap(),
            synchronizer_current_missing_blocks_by_authority: register_int_gauge_vec_with_registry!(
                "synchronizer_current_missing_blocks_by_authority",
                "Current number of missing blocks per block author, as observed by the synchronizer during periodic sync.",
                &["authority"],
                registry,
            ).unwrap(),
            synchronizer_fetched_blocks_by_authority: register_int_counter_vec_with_registry!(
                "synchronizer_fetched_blocks_by_authority",
                "Number of fetched blocks per block author via the synchronizer",
                &["authority", "type"],
                registry,
            ).unwrap(),
            synchronizer_fetch_failures: register_int_counter_vec_with_registry!(
                "synchronizer_fetch_failures",
                "Number of fetch failures against each peer",
                &["peer", "type"],
                registry,
            ).unwrap(),
            synchronizer_skipped_fetch_requests: register_int_counter_vec_with_registry!(
                "synchronizer_skipped_fetch_requests",
                "Number of fetch requests skipped against each peer, because the peer is saturated",
                &["peer"],
                registry,
            ).unwrap(),
            synchronizer_process_fetched_failures: register_int_counter_vec_with_registry!(
                "synchronizer_process_fetched_failures",
                "Number of failures for processing fetched blocks against each peer",
                &["peer", "type"],
                registry,
            ).unwrap(),
            synchronizer_periodic_sync_decision: register_int_counter_vec_with_registry!(
                "synchronizer_periodic_sync_decision",
                "Decision to run periodic sync",
                &["decision", "reason"],
                registry,
            ).unwrap(),
            network_received_excluded_ancestors_from_authority: register_int_counter_vec_with_registry!(
                "network_received_excluded_ancestors_from_authority",
                "Number of excluded ancestors received from each authority.",
                &["authority"],
                registry,
            ).unwrap(),
            network_excluded_ancestors_count_by_authority: register_int_counter_vec_with_registry!(
                "network_excluded_ancestors_count_by_authority",
                "Total number of excluded ancestors per authority.",
                &["authority"],
                registry,
            ).unwrap(),
            network_excluded_ancestors_sent_to_fetch: register_int_counter_vec_with_registry!(
                "network_excluded_ancestors_sent_to_fetch",
                "Number of excluded ancestors sent to fetch.",
                &["authority"],
                registry,
            ).unwrap(),
            last_known_own_block_round: register_int_gauge_with_registry!(
                "last_known_own_block_round",
                "The highest round of our own block as this has been synced from peers during an amnesia recovery",
                registry,
            ).unwrap(),
            sync_last_known_own_block_retries: register_int_counter_with_registry!(
                "sync_last_known_own_block_retries",
                "Number of times this node tried to fetch the last own block from peers",
                registry,
            ).unwrap(),
            invalid_blocks: register_int_counter_vec_with_registry!(
                "invalid_blocks",
                "Number of invalid blocks per peer authority",
                &["authority", "source", "error"],
                registry,
            ).unwrap(),
            rejected_blocks: register_int_counter_vec_with_registry!(
                "rejected_blocks",
                "Number of blocks rejected before verifications",
                &["reason"],
                registry,
            ).unwrap(),
            subscribed_blocks: register_int_counter_vec_with_registry!(
                "subscribed_blocks",
                "Number of blocks received from each peer before verification",
                &["authority"],
                registry,
            ).unwrap(),
            observer_subscribed_blocks_batch_size: register_histogram_with_registry!(
                "observer_subscribed_blocks_batch_size",
                "The number of blocks received from a peer before verification in a single batch",
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            verified_blocks: register_int_counter_vec_with_registry!(
                "verified_blocks",
                "Number of blocks received from each peer that are verified",
                &["authority"],
                registry,
            ).unwrap(),
            committed_leaders_total: register_int_counter_vec_with_registry!(
                "committed_leaders_total",
                "Total number of (direct or indirect) committed leaders per authority",
                &["authority", "commit_type"],
                registry,
            ).unwrap(),
            last_committed_authority_round: register_int_gauge_vec_with_registry!(
                "last_committed_authority_round",
                "The last round committed by authority.",
                &["authority"],
                registry,
            ).unwrap(),
            last_committed_leader_round: register_int_gauge_with_registry!(
                "last_committed_leader_round",
                "The last round where a leader was committed to store and sent to commit consumer.",
                registry,
            ).unwrap(),
            last_commit_index: register_int_gauge_with_registry!(
                "last_commit_index",
                "Index of the last commit.",
                registry,
            ).unwrap(),
            last_commit_time_diff: register_histogram_with_registry!(
                "last_commit_time_diff",
                "The time diff between the last commit and previous one.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            commit_round_advancement_interval: register_histogram_with_registry!(
                "commit_round_advancement_interval",
                "Intervals (in secs) between commit round advancements.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            last_decided_leader_round: register_int_gauge_with_registry!(
                "last_decided_leader_round",
                "The last round where a commit decision was made.",
                registry,
            ).unwrap(),
            leader_timeout_total: register_int_counter_vec_with_registry!(
                "leader_timeout_total",
                "Total number of leader timeouts, either when the min round time has passed, or max leader timeout",
                &["timeout_type"],
                registry,
            ).unwrap(),
            smart_selection_wait: register_int_counter_with_registry!(
                "smart_selection_wait",
                "Number of times we waited for smart ancestor selection.",
                registry,
            ).unwrap(),
            ancestor_state_change_by_authority: register_int_counter_vec_with_registry!(
                "ancestor_state_change_by_authority",
                "The total number of times an ancestor state changed to EXCLUDE or INCLUDE.",
                &["authority", "state"],
                registry,
            ).unwrap(),
            excluded_proposal_ancestors_count_by_authority: register_int_counter_vec_with_registry!(
                "excluded_proposal_ancestors_count_by_authority",
                "Total number of excluded ancestors per authority during proposal.",
                &["authority"],
                registry,
            ).unwrap(),
            included_excluded_proposal_ancestors_count_by_authority: register_int_counter_vec_with_registry!(
                "included_excluded_proposal_ancestors_count_by_authority",
                "Total number of ancestors per authority with 'excluded' status that got included in proposal. Either weak or strong type.",
                &["authority", "type"],
                registry,
            ).unwrap(),
            missing_blocks_total: register_int_counter_with_registry!(
                "missing_blocks_total",
                "Total cumulative number of missing blocks",
                registry,
            ).unwrap(),
            missing_blocks_after_fetch_total: register_int_counter_with_registry!(
                "missing_blocks_after_fetch_total",
                "Total number of missing blocks after fetching blocks from peer",
                registry,
            ).unwrap(),
            num_of_bad_nodes: register_int_gauge_with_registry!(
                "num_of_bad_nodes",
                "The number of bad nodes in the new leader schedule",
                registry
            ).unwrap(),
            quorum_receive_latency: register_histogram_with_registry!(
                "quorum_receive_latency",
                "The time it took to receive a new round quorum of blocks",
                registry
            ).unwrap(),
            block_receive_delay: register_int_counter_vec_with_registry!(
                "block_receive_delay",
                "Total delay from the start of the round to receiving the block, in milliseconds per authority",
                &["authority"],
                registry,
            ).unwrap(),
            reputation_scores: register_int_gauge_vec_with_registry!(
                "reputation_scores",
                "Reputation scores for each authority",
                &["authority"],
                registry,
            ).unwrap(),
            leader_schedule_total_scores: register_int_gauge_vec_with_registry!(
                "leader_schedule_total_scores",
                "LeaderScheduleV3 running per-authority score over the scoring window. Each commit contributes voted_for_stake * certified_by_stake (stake^2 units)",
                &["authority"],
                registry,
            ).unwrap(),
            leader_schedule_normalized_scores: register_gauge_vec_with_registry!(
                "leader_schedule_normalized_scores",
                "LeaderScheduleV3 per-authority total score divided by (running sum of per-commit leader stake) * committee total stake. Stake^2 over stake^2; a fraction with no stake dimension",
                &["authority"],
                registry,
            ).unwrap(),
            leader_schedule_last_num_leaders: register_int_gauge_with_registry!(
                "leader_schedule_last_num_leaders",
                "LeaderScheduleV3 number of leader-round blocks in the most recently scored commit",
                registry,
            ).unwrap(),
            leader_schedule_average_num_leaders: register_gauge_with_registry!(
                "leader_schedule_average_num_leaders",
                "LeaderScheduleV3 moving average of the number of leaders per commit across the scoring window",
                registry,
            ).unwrap(),
            scope_processing_time: register_histogram_vec_with_registry!(
                "scope_processing_time",
                "The processing time of a specific code scope",
                &["scope"],
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            sub_dags_per_commit_count: register_histogram_with_registry!(
                "sub_dags_per_commit_count",
                "The number of subdags per commit.",
                registry,
            ).unwrap(),
            block_suspensions: register_int_counter_vec_with_registry!(
                "block_suspensions",
                "The number block suspensions. The counter is reported uniquely, so if a block is sent for reprocessing while already suspended then is not double counted",
                &["authority"],
                registry,
            ).unwrap(),
            block_unsuspensions: register_int_counter_vec_with_registry!(
                "block_unsuspensions",
                "The number of block unsuspensions.",
                &["authority"],
                registry,
            ).unwrap(),
            suspended_block_time: register_histogram_vec_with_registry!(
                "suspended_block_time",
                "The time for which a block remains suspended",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_suspended_blocks: register_int_gauge_with_registry!(
                "block_manager_suspended_blocks",
                "The number of blocks currently suspended in the block manager",
                registry,
            ).unwrap(),
            block_manager_missing_ancestors: register_int_gauge_with_registry!(
                "block_manager_missing_ancestors",
                "The number of missing ancestors tracked in the block manager",
                registry,
            ).unwrap(),
            block_manager_missing_blocks: register_int_gauge_with_registry!(
                "block_manager_missing_blocks",
                "The number of blocks missing content tracked in the block manager",
                registry,
            ).unwrap(),
            block_manager_missing_blocks_by_authority: register_int_counter_vec_with_registry!(
                "block_manager_missing_blocks_by_authority",
                "The number of new missing blocks by block authority",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_missing_ancestors_by_authority: register_int_counter_vec_with_registry!(
                "block_manager_missing_ancestors_by_authority",
                "The number of missing ancestors by ancestor authority across received blocks",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_gced_blocks: register_int_counter_vec_with_registry!(
                "block_manager_gced_blocks",
                "The number of blocks that garbage collected and did not get accepted, counted by block's source authority",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_gc_unsuspended_blocks: register_int_counter_vec_with_registry!(
                "block_manager_gc_unsuspended_blocks",
                "The number of blocks unsuspended because their missing ancestors are garbage collected by the block manager, counted by block's source authority",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_skipped_blocks: register_int_counter_vec_with_registry!(
                "block_manager_skipped_blocks",
                "The number of blocks skipped by the block manager due to block round being <= gc_round",
                &["authority"],
                registry,
            ).unwrap(),
            threshold_clock_round: register_int_gauge_with_registry!(
                "threshold_clock_round",
                "The current threshold clock round. We only advance to a new round when a quorum of parents have been synced.",
                registry,
            ).unwrap(),
            subscriber_connection_attempts: register_int_counter_vec_with_registry!(
                "subscriber_connection_attempts",
                "The number of connection attempts per peer",
                &["authority", "status"],
                registry,
            ).unwrap(),
            subscribed_to: register_int_gauge_vec_with_registry!(
                "subscribed_to",
                "Peers that this authority subscribed to for block streams.",
                &["authority"],
                registry,
            ).unwrap(),
            subscribed_by: register_int_gauge_vec_with_registry!(
                "subscribed_by",
                "Peers subscribing for block streams from this authority.",
                &["authority"],
                registry,
            ).unwrap(),
            commit_sync_inflight_fetches: register_int_gauge_with_registry!(
                "commit_sync_inflight_fetches",
                "The number of inflight fetches in commit syncer",
                registry,
            ).unwrap(),
            commit_sync_pending_fetches: register_int_gauge_with_registry!(
                "commit_sync_pending_fetches",
                "The number of pending fetches in commit syncer",
                registry,
            ).unwrap(),
            commit_sync_fetched_commits: register_int_counter_with_registry!(
                "commit_sync_fetched_commits",
                "The number of commits fetched via commit syncer",
                registry,
            ).unwrap(),
            commit_sync_fetched_blocks: register_int_counter_with_registry!(
                "commit_sync_fetched_blocks",
                "The number of blocks fetched via commit syncer",
                registry,
            ).unwrap(),
            commit_sync_total_fetched_blocks_size: register_int_counter_with_registry!(
                "commit_sync_total_fetched_blocks_size",
                "The total size in bytes of blocks fetched via commit syncer",
                registry,
            ).unwrap(),
            commit_sync_quorum_index: register_int_gauge_with_registry!(
                "commit_sync_quorum_index",
                "The maximum commit index voted by a quorum of authorities",
                registry,
            ).unwrap(),
            commit_sync_highest_synced_index: register_int_gauge_with_registry!(
                "commit_sync_fetched_index",
                "The max commit index among local and fetched commits",
                registry,
            ).unwrap(),
            commit_sync_highest_fetched_index: register_int_gauge_with_registry!(
                "commit_sync_highest_fetched_index",
                "The max commit index that has been fetched via network",
                registry,
            ).unwrap(),
            commit_sync_local_index: register_int_gauge_with_registry!(
                "commit_sync_local_index",
                "The local commit index",
                registry,
            ).unwrap(),
            commit_sync_gap_on_processing: register_int_counter_with_registry!(
                "commit_sync_gap_on_processing",
                "Number of instances where a gap was found in fetched commit processing",
                registry,
            ).unwrap(),
            commit_sync_fetch_loop_latency: register_histogram_with_registry!(
                "commit_sync_fetch_loop_latency",
                "The time taken to finish fetching commits and blocks from a given range",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            commit_sync_fetch_once_latency: register_histogram_with_registry!(
                "commit_sync_fetch_once_latency",
                "The time taken to fetch commits and blocks once",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            commit_sync_fetch_once_errors: register_int_counter_vec_with_registry!(
                "commit_sync_fetch_once_errors",
                "Number of errors when attempting to fetch commits and blocks from single authority during commit sync.",
                &["authority", "error"],
                registry
            ).unwrap(),
            commit_sync_fetch_missing_blocks: register_int_counter_vec_with_registry!(
                "commit_sync_fetch_missing_blocks",
                "Number of ancestor blocks that are missing when processing blocks via commit sync.",
                &["authority"],
                registry,
            ).unwrap(),
            commit_sync_fetch_commits_handler_uncertified_skipped: register_int_counter_with_registry!(
                "commit_sync_fetch_commits_handler_uncertified_skipped",
                "Number of uncertified commits that got skipped when fetching commits due to lack of votes",
                registry,
            ).unwrap(),
            round_tracker_received_quorum_round_gaps: register_int_gauge_vec_with_registry!(
                "round_tracker_received_quorum_round_gaps",
                "Received round gaps among peers for blocks proposed from each authority",
                &["authority"],
                registry
            ).unwrap(),
            round_tracker_accepted_quorum_round_gaps: register_int_gauge_vec_with_registry!(
                "round_tracker_accepted_quorum_round_gaps",
                "Accepted round gaps among peers for blocks proposed & accepted from each authority",
                &["authority"],
                registry
            ).unwrap(),
            round_tracker_low_received_quorum_round: register_int_gauge_vec_with_registry!(
                "round_tracker_low_received_quorum_round",
                "Low quorum round among peers for blocks proposed from each authority",
                &["authority"],
                registry
            ).unwrap(),
            round_tracker_low_accepted_quorum_round: register_int_gauge_vec_with_registry!(
                "round_tracker_low_accepted_quorum_round",
                "Low quorum round among peers for blocks proposed & accepted from each authority",
                &["authority"],
                registry
            ).unwrap(),
            round_tracker_current_received_round_gaps: register_int_gauge_vec_with_registry!(
                "round_tracker_current_received_round_gaps",
                "Received round gaps from local last proposed round to the low received quorum round of each peer. Can be negative.",
                &["authority"],
                registry
            ).unwrap(),
            round_tracker_current_accepted_round_gaps: register_int_gauge_vec_with_registry!(
                "round_tracker_current_accepted_round_gaps",
                "Accepted round gaps from local last proposed & accepted round to the low accepted quorum round of each peer. Can be negative.",
                &["authority"],
                registry
            ).unwrap(),
            round_tracker_propagation_delays: register_histogram_with_registry!(
                "round_tracker_propagation_delays",
                "Round gaps between the last proposed block round and the lower bound of own quorum round",
                NUM_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            round_tracker_last_propagation_delay: register_int_gauge_with_registry!(
                "round_tracker_last_propagation_delay",
                "Most recent propagation delay observed by RoundTracker",
                registry
            ).unwrap(),
            round_prober_request_errors: register_int_counter_vec_with_registry!(
                "round_prober_request_errors",
                "Number of errors when probing against peers per error type",
                &["error_type"],
                registry
            ).unwrap(),
            certifier_gc_round: register_int_gauge_with_registry!(
                "certifier_gc_round",
                "The current GC round of the certifier",
                registry
            ).unwrap(),
            certifier_own_reject_votes: register_int_counter_vec_with_registry!(
                "certifier_own_reject_votes",
                "Number of own reject votes against each peer authority",
                &["authority"],
                registry
            ).unwrap(),
            finalizer_buffered_commits: register_int_gauge_with_registry!(
                "finalizer_buffered_commits",
                "The number of commits buffered in the finalizer",
                registry,
            ).unwrap(),
            finalizer_blocks_entries: register_int_gauge_with_registry!(
                "finalizer_blocks_entries",
                "The number of blocks retained in the finalizer blocks map",
                registry,
            ).unwrap(),
            finalizer_blocks_bytes: register_int_gauge_with_registry!(
                "finalizer_blocks_bytes",
                "Total serialized bytes of blocks retained in the finalizer blocks map",
                registry,
            ).unwrap(),
            certifier_votes_entries: register_int_gauge_with_registry!(
                "certifier_votes_entries",
                "The number of entries in the transaction vote tracker",
                registry,
            ).unwrap(),
            certifier_votes_bytes: register_int_gauge_with_registry!(
                "certifier_votes_bytes",
                "Total serialized bytes of blocks retained in the transaction vote tracker",
                registry,
            ).unwrap(),
            adaptive_block_cap_bytes: register_int_gauge_with_registry!(
                "adaptive_block_cap_bytes",
                "Current adaptive block byte cap applied to own proposals",
                registry,
            ).unwrap(),
            handle_send_block_pre_receive_age: register_histogram_with_registry!(
                "handle_send_block_pre_receive_age",
                "Block age at receiver pickup (creation to parse): sender queue + wire + skew",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_verify_queue_wait: register_histogram_with_registry!(
                "handle_send_block_verify_queue_wait",
                "Wait between verify spawn and verify start on the blocking pool",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_verify_exec: register_histogram_with_registry!(
                "handle_send_block_verify_exec",
                "verify_and_vote execution time excluding pool queue wait",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_vote_record_latency: register_histogram_with_registry!(
                "handle_send_block_vote_record_latency",
                "Time recording own votes into the shared vote tracker (lock path)",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_core_dispatch_latency: register_histogram_with_registry!(
                "handle_send_block_core_dispatch_latency",
                "add_blocks dispatch to Core: queue wait + DAG insert + persistence",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            handle_send_block_age_accepted: register_histogram_with_registry!(
                "handle_send_block_age_accepted",
                "Block age at Core acceptance (creation to accepted): full pipeline",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            signed_block_census: register_int_gauge_with_registry!(
                "signed_block_census",
                "Number of SignedBlock instances currently live in memory",
                registry,
            ).unwrap(),
            commit_sync_fetched_ranges_bytes: register_int_gauge_with_registry!(
                "commit_sync_fetched_ranges_bytes",
                "Total serialized block bytes buffered in commit syncer fetched ranges",
                registry,
            ).unwrap(),
            finalizer_round_delay: register_histogram_with_registry!(
                "finalizer_round_delay",
                "The delay between the round of the last committed block and the round of the finalized commit.",
                ROUND_DELAY_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            finalizer_transaction_status: register_int_counter_vec_with_registry!(
                "finalizer_transaction_status",
                "Number of transactions finalized by the finalizer, grouped by status.",
                &["status"],
                registry
            ).unwrap(),
            finalizer_reject_votes: register_int_counter_vec_with_registry!(
                "finalizer_reject_votes",
                "Number of reject votes casted by each authority observed by the finalizer.",
                &["authority"],
                registry
            ).unwrap(),
            finalizer_output_commits: register_int_counter_vec_with_registry!(
                "finalizer_output_commits",
                "Number of output commits finalized by the finalizer, grouped by type.",
                &["type"],
                registry
            ).unwrap(),
            finalizer_skipped_voting_blocks: register_int_counter_vec_with_registry!(
                "finalizer_skipped_voting_blocks",
                "Number of times where another block skipped voting due to potentially out of GC bound. Authority is from the voted block.",
                &["authority", "type"],
                registry
            ).unwrap(),
            uptime: register_histogram_with_registry!(
                "uptime",
                "Total node uptime",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
        }
    }
}
