processed 4 tasks

task 1 'publish'. lines 7-21:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5236400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 23-42:
warning: You may be trying to share an owned object. A typical pattern is to create an object and share it within the same function.
  ┌─ <unknown>:1:1
  │
1 │ <unknown>
  │ ^

created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5342800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'publish'. lines 44-71:
warning: You may be trying to share an owned object. A typical pattern is to create an object and share it within the same function.
  ┌─ <unknown>:1:1
  │
1 │ <unknown>
  │ ^

created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6292800,  storage_rebate: 978120, non_refundable_storage_fee: 9880
