Command `migrate`:
Package toml does not specify an edition. As of 2024, Move requires all packages to define a language edition.

Please select one of the following editions:

1) 2024
2) legacy

Selection (default=1): 

Would you like the Move compiler to migrate your code to Move 2024? (Y/n) 
Generated changes . . .
INCLUDING DEPENDENCY MoveStdlib
BUILDING migration

The following changes will be made.
============================================================

--- ./sources/other.move
+++ ./sources/other.move
@@ -4 +4 @@
-    public fun t() { migration::migration::t() }
+    public fun t() { ::migration::migration::t() }
--- ./tests/test0.move
+++ ./tests/test0.move
@@ -6 +6 @@
-    #[expected_failure(abort_code = migration::validate::ErrorCode)]
+    #[expected_failure(abort_code = ::migration::validate::ErrorCode)]


============================================================
Apply changes? (Y/n) 
Updating "./sources/other.move" . . .
Updating "./tests/test0.move" . . .

Changes complete
Wrote patchfile out to: ./migration.patch

Recorded edition in 'Move.toml'
External Command `diff -r -s sources migration_sources`:
Files sources/migration.move and migration_sources/migration.move are identical
Files sources/other.move and migration_sources/other.move are identical
Files sources/validate.move and migration_sources/validate.move are identical
External Command `diff -r -s tests migration_tests`:
Files tests/test0.move and migration_tests/test0.move are identical
External Command `diff -s Move.toml Move.toml.expected`:
Files Move.toml and Move.toml.expected are identical
