// Auto-generated by Move decompiler

module 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard;

// -- uses -- 

use 0x1::option;
use 0x1::vector;
use 0x2::object;
use 0x2::transfer;
use 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector;
use 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::chakra_nft;
use 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard;
use 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::utils;

// -- structs -- 

public struct Leaderboard
has key, store {
    id: 0x2::object::UID,
    data: 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::BigVector<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraItem>,
    config: 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Config,
    is_initialized: bool,
    is_frozen: bool,
}

public struct OrderPage
has copy, drop, store {
    orders: vector<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraItemReadOnly>,
    has_next_page: bool,
    next_ref: 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef,
    offset: u64,
}

public struct Config
has store {
    total_users: u64,
    level_7: u8,
    level_6: u8,
    level_5: u8,
    level_4: u8,
    level_3: u8,
    level_2: u8,
    level_1: u8,
}

public struct ChakraItem has copy, drop, store { chakra_number: u64, points: u64, nft_id: 0x2::object::ID }

public struct ChakraItemReadOnly has copy, drop, store { chakra_number: u64, points: u64, nft_id: 0x2::object::ID, user: address }

public struct ChakraTierRange has drop, store { lower_bound: u64, upper_bound: u64, chakra_tier: u8, search_rank: u64 }

// -- constants -- 

const C0: u64 = 1u64;

const C1: u64 = 2u64;

const C2: u64 = 3u64;

const C3: vector<u8> = vector[1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8];

const C4: address = @0000000000000000000000000000000000000000000000000000000000000000;

// -- functions -- 

public(friend) fun add(l0: &mut 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::chakra_nft::ChakraNFT) {
    assert!(*(&l0.is_frozen) == false, C2);
    let l5 = chakra_nft::maya_burnt(l1);
    let l4 = chakra_nft::number(l1);
    let l2 = utils::encode_chakra_id(l5, l4);
    let l3 = ChakraItem { chakra_number: l4, points: l5, nft_id: chakra_nft::id(l1) };
    big_vector::insert(&mut l0.data, l2, l3)
}

public fun admin_freeze_leaderboard(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::admin::AdminCap, l1: &mut 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l2: &0x2::tx_context::TxContext) {
    assert!(*(&l1.is_frozen) == false, C1);
    assert!(*(&l1.is_initialized) == true, C0);
    *(&mut l1.is_frozen) = true
}

public fun borrow_internal_slice(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef): &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::Slice<u64> {
    return big_vector::borrow_slice_internal(&l0.data, l1)
}

public fun borrow_slice(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef): &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::Slice<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraItem> {
    return big_vector::borrow_slice(&l0.data, l1)
}

public fun count(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard): u64 {
    return big_vector::length(&l0.data)
}

public(friend) fun exists(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::chakra_nft::ChakraNFT): bool {
    let l7 = chakra_nft::maya_burnt(l1);
    let l5 = chakra_nft::number(l1);
    let l4 = utils::encode_chakra_id(l7, l5);
    let (reg_10, reg_11) = big_vector::slice_around(&l0.data, l4);
    let l6 = reg_11;
    let l9 = reg_10;
    let l3 = if (big_vector::slice_is_null(&l9)) {
        false
    } else {
        let l8 = big_vector::borrow_slice(&l0.data, l9);
        let l2 = if (l6 < big_vector::slice_length(l8)) {
            big_vector::slice_key(l8, l6) == l4
        } else {
            false
        };
        l2
    };
    return l3
}

public fun find_points_at_rank(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: u64): ( u64, u64) {
    let l2 = if (leaderboard::count(l0) >= l1) {
        leaderboard::count(l0) - l1
    } else {
        1u64
    };
    let l3 = l2;
    let (reg_14, reg_15) = utils::decode_chakra_id(big_vector::find_key_at_rank(&l0.data, l3));
    return (reg_14, reg_15)
}

public fun find_points_at_rank_brute(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: u64): ( u64, u64) {
    let l8 = leaderboard::count(l0);
    assert!(!(l1 > l8), 0u64);
    let l2 = 0u64;
    let reg_10;
    (reg_10, reg_11) = big_vector::min_slice(&l0.data);
    let l3 = reg_10;
    loop {
        assert!(!(big_vector::slice_is_null(&l3)), 0u64);
        let l6 = big_vector::borrow_slice(&l0.data, l3);
        let l7 = big_vector::slice_length(l6);
        if (l2 + l7 < l1) {
            l2 = l2 + l7;
            l3 = big_vector::slice_next(l6);
            continue
        };
        if (l2 + l7 == l1) {
            let l4 = big_vector::slice_length(l6) - 1u64;
            return (*(&(big_vector::slice_borrow(l6, l4)).points), l1)
        } else {
            let l5 = l1 - l2;
            return (*(&(big_vector::slice_borrow(l6, l5)).points), l1)
        }
    }
}

public fun find_rank(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: u64, l2: u64): u64 {
    let l3 = utils::encode_chakra_id(l1, l2);
    let l4 = big_vector::find_rank(&l0.data, l3);
    return leaderboard::count(l0) - l4
}

public fun find_rank_brute(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: u64, l2: u64): u64 {
    let l4 = utils::encode_chakra_id(l1, l2);
    let l7 = 0u64;
    let reg_6;
    (reg_6, reg_7) = big_vector::min_slice(&l0.data);
    let l5 = reg_6;
    loop {
        if (!(big_vector::slice_is_null(&l5))) {
            let l8 = big_vector::borrow_slice(&l0.data, l5);
            let l6 = big_vector::slice_bisect_right(l8, l4);
            l7 = l7 + l6;
            let l3 = if (l6 < big_vector::slice_length(l8)) {
                big_vector::slice_key(l8, l6) == l4
            } else {
                false
            };
            if (l3) {
                
            } else {
                if (l6 == big_vector::slice_length(l8)) {
                    l5 = big_vector::slice_next(l8);
                    continue
                } else {
                    
                }
            }
        } else {
            break
        };
        return leaderboard::count(l0) - l7
    }
}

public fun get_tierwise_distribution(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard): vector<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraTierRange> {
    let l13 = big_vector::length(&l0.data);
    let l8 = vector[];
    let l7 = &l0.config;
    if (l13 == 0u64) {
        return l8
    } else {
        let l4 = vector[*(&l7.level_1), *(&l7.level_2), *(&l7.level_3), *(&l7.level_4), *(&l7.level_5), *(&l7.level_6), *(&l7.level_7)];
        let l6 = C3;
        let l11 = 0u64;
        loop {
            let l1 = if (!(vector::is_empty(&l4))) {
                !(vector::is_empty(&l6))
            } else {
                false
            };
            if (l1) {
                let l9 = (&mut l4).pop_back();
                let l5 = (&mut l6).pop_back();
                let l12 = l13 * l9as u64 / 100u64;
                let reg_56;
                (reg_56, reg_57) = leaderboard::find_points_at_rank(l0, l12);
                let l10 = reg_56;
                let l3 = &mut l8;
                let l2 = if (l11 > 1u64) {
                    l11 - 1u64
                } else {
                    0u64
                };
                l3.push_back(ChakraTierRange { lower_bound: l2, upper_bound: l10, chakra_tier: l5, search_rank: l12 });
                l11 = l10;
                continue
            };
            return l8
        }
    }
}

fun init(l0: &mut 0x2::tx_context::TxContext) {
    let l1 = big_vector::empty(16u64, 16u64, l0);
    transfer::public_share_object(Leaderboard { id: object::new(l0), data: l1, config: Config { total_users: 0u64, level_7: 1u8, level_6: 3u8, level_5: 5u8, level_4: 10u8, level_3: 20u8, level_2: 50u8, level_1: 100u8 }, is_initialized: true, is_frozen: false })
}

fun initial_slice(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::BigVector<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraItem>, l1: bool, l2: 0x1::option::Option<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef>, l3: 0x1::option::Option<u64>): ( 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef, u64) {
    let (l6, l7);
    l6 = if (option::is_some(&l2)) {
        l7 = *(option::borrow(&l3));
        *(option::borrow(&l2))
    } else {
        let (l4, l5);
        l4 = if (l1) {
            let (reg_11, reg_12) = leaderboard::max_slice(l0);
            l5 = reg_12;
            reg_11
        } else {
            let (reg_14, reg_15) = leaderboard::min_slice(l0);
            l5 = reg_15;
            reg_14
        };
        l7 = l5;
        l4
    };
    return (l6, l7)
}

public fun inorder_values(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard): vector<vector<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraItem>> {
    return big_vector::inorder_values(&l0.data)
}

public fun is_frozen(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard): bool {
    return *(&l0.is_frozen)
}

public fun is_initialized(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard): bool {
    return *(&l0.is_initialized)
}

fun max_slice(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::BigVector<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraItem>): ( 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef, u64) {
    let (reg_1, reg_2) = big_vector::max_slice(l0);
    return (reg_1, reg_2)
}

fun min_slice(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::BigVector<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::ChakraItem>): ( 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef, u64) {
    let (reg_1, reg_2) = big_vector::min_slice(l0);
    return (reg_1, reg_2)
}

public fun page_offset(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::OrderPage): u64 {
    return *(&l0.offset)
}

public fun page_slice_ref(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::OrderPage): 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef {
    return *(&l0.next_ref)
}

public fun query(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::chakra_nft::GlobalConfig, l2: 0x1::option::Option<0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::big_vector::SliceRef>, l3: 0x1::option::Option<u64>, l4: bool, l5: u64): 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::OrderPage {
    let l11 = vector[];
    let (reg_6, reg_7) = leaderboard::initial_slice(&l0.data, l4, l2, l3);
    let l9 = reg_7;
    let l12 = reg_6;
    loop {
        let l6 = if (!(big_vector::slice_is_null(&l12))) {
            &l11.len() < l5
        } else {
            false
        };
        if (l6) {
            let (l7, l8);
            let l10 = big_vector::slice_borrow(big_vector::borrow_slice(&l0.data, l12), l9);
            (&mut l11).push_back(ChakraItemReadOnly { chakra_number: *(&l10.chakra_number), points: *(&l10.points), nft_id: *(&l10.nft_id), user: C4 });
            l7 = if (l4) {
                let (reg_40, reg_41) = big_vector::prev_slice(&l0.data, l12, l9);
                l8 = reg_41;
                reg_40
            } else {
                let (reg_46, reg_47) = big_vector::next_slice(&l0.data, l12, l9);
                l8 = reg_47;
                reg_46
            };
            l9 = l8;
            l12 = l7;
            continue
        };
        return OrderPage { orders: l11, has_next_page: !(big_vector::slice_is_null(&l12)), next_ref: l12, offset: l9 }
    }
}

public(friend) fun remove(l0: &mut 0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard, l1: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::chakra_nft::ChakraNFT) {
    assert!(*(&l0.is_frozen) == false, C2);
    let l4 = chakra_nft::maya_burnt(l1);
    let l3 = chakra_nft::number(l1);
    let l2 = utils::encode_chakra_id(l4, l3);
}

public fun root_id(l0: &0xa58752107caae3e4b65a704ec5e17de40dc9a46e5a4de1e92905a353830cc3cc::leaderboard::Leaderboard): u64 {
    return big_vector::root_id(&l0.data)
}

