warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/translated_ir_tests/move/commands/dead_return_local.move:4:5
  │
4 │     assert!(false, 42);
  │     ^^^^^^^^^^^^^^^^^^ Unreachable code. This statement (and any following statements) will not be executed.
  │
  = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/translated_ir_tests/move/commands/dead_return_local.move:5:5
  │
5 │     return ()
  │     ^^^^^^^^^ Unreachable code. This statement (and any following statements) will not be executed.
  │
  = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

