# Copyright (c) Mysten Labs, Inc.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "authenticated_event"
edition = "2024.beta"

[dependencies]
Sui = { local = "../../../../sui-framework/packages/sui-framework" }

[addresses]
authenticated_event = "0x0"
