processed 17 tasks

task 1 'create-checkpoint'. lines 31-31:
Checkpoint created: 12

task 2 'run-graphql'. lines 33-45:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        }
      ]
    }
  }
}

task 3 'run-graphql'. lines 47-59:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6N30",
          "node": {
            "sequenceNumber": 7
          }
        }
      ]
    }
  }
}

task 4 'run-graphql'. lines 61-73:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 5 'run-graphql'. lines 75-87:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 6 'run-graphql'. lines 89-101:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        }
      ]
    }
  }
}

task 7 'run-graphql'. lines 103-115:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 8 'run-graphql'. lines 117-129:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 9 'run-graphql'. lines 131-143:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Nn0",
          "node": {
            "sequenceNumber": 6
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 10 'run-graphql'. lines 145-157:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6M30",
          "node": {
            "sequenceNumber": 3
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 159-171:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        }
      ]
    }
  }
}

task 12 'run-graphql'. lines 173-185:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 13 'run-graphql'. lines 187-199:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6M30",
          "node": {
            "sequenceNumber": 3
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NH0",
          "node": {
            "sequenceNumber": 4
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6NX0",
          "node": {
            "sequenceNumber": 5
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Nn0",
          "node": {
            "sequenceNumber": 6
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6N30",
          "node": {
            "sequenceNumber": 7
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OH0",
          "node": {
            "sequenceNumber": 8
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 201-213:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MH0",
          "node": {
            "sequenceNumber": 0
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MX0",
          "node": {
            "sequenceNumber": 1
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6Mn0",
          "node": {
            "sequenceNumber": 2
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6M30",
          "node": {
            "sequenceNumber": 3
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 215-227:
Response: {
  "data": {
    "checkpoints": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6OX0",
          "node": {
            "sequenceNumber": 9
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTB9",
          "node": {
            "sequenceNumber": 10
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTF9",
          "node": {
            "sequenceNumber": 11
          }
        },
        {
          "cursor": "eyJjaGVja3BvaW50X3ZpZXdlZF9hdCI6MTIsInNlcXVlbmNlX251bWJlciI6MTJ9",
          "node": {
            "sequenceNumber": 12
          }
        }
      ]
    }
  }
}

task 16 'run-graphql'. lines 229-241:
Response: {
  "data": null,
  "errors": [
    {
      "message": "'first' and 'last' must not be used together",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "checkpoints"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
