processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-20:
created: object(1,0), object(1,1), object(1,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10617200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 22-22:
Checkpoint created: 1

task 3 'run-graphql'. lines 24-35:
Response: {
  "data": {
    "coinMetadata": {
      "decimals": 2,
      "name": "",
      "symbol": "FAKE",
      "description": "",
      "iconUrl": null,
      "supply": "0",
      "hasPublicTransfer": true
    }
  }
}

task 4 'programmable'. lines 38-40:
created: object(4,0)
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 4012800,  storage_rebate: 2663496, non_refundable_storage_fee: 26904

task 5 'create-checkpoint'. lines 42-42:
Checkpoint created: 2

task 6 'run-graphql'. lines 44-55:
Response: {
  "data": {
    "coinMetadata": {
      "decimals": 2,
      "name": "",
      "symbol": "FAKE",
      "description": "",
      "iconUrl": null,
      "supply": "100",
      "hasPublicTransfer": true
    }
  }
}
