processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-55:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8329600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 57-57:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2234400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 59-59:
created: object(3,0), object(3,1), object(3,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6536000,  storage_rebate: 2212056, non_refundable_storage_fee: 22344

task 4 'run'. lines 61-61:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5928000,  storage_rebate: 2212056, non_refundable_storage_fee: 22344

task 5 'create-checkpoint'. lines 63-63:
Checkpoint created: 1

task 6 'run-graphql'. lines 65-88:
Response: {
  "data": {
    "object": {
      "dynamicFieldConnection": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject"
            }
          }
        ]
      }
    }
  }
}

task 7 'run'. lines 90-90:
created: object(7,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2485200,  storage_rebate: 2212056, non_refundable_storage_fee: 22344

task 8 'create-checkpoint'. lines 92-92:
Checkpoint created: 2

task 9 'run-graphql'. lines 94-117:
Response: {
  "data": {
    "object": null
  }
}

task 10 'run-graphql'. lines 119-144:
Response: {
  "data": {
    "owner": {
      "dynamicFieldConnection": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject"
            }
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 146-171:
Response: {
  "data": {
    "owner": {
      "dynamicFieldConnection": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject"
            }
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 173-193:
Response: {
  "data": {
    "owner": {
      "dynamicField": {
        "name": {
          "type": {
            "repr": "u64"
          },
          "data": {
            "Number": "0"
          },
          "bcs": "AAAAAAAAAAA="
        },
        "value": {
          "__typename": "MoveValue",
          "bcs": "AAAAAAAAAAA=",
          "data": {
            "Number": "0"
          }
        }
      }
    }
  }
}

task 13 'run-graphql'. lines 195-206:
Response: {
  "data": {
    "owner": {
      "dynamicObjectField": {
        "value": {
          "__typename": "MoveObject"
        }
      }
    }
  }
}
