processed 13 tasks

init:
A: object(0,0)

task 1, lines 13-52:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8329600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 54:
//# run Test::m::create_obj --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2234400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 56:
//# run Test::m::add_df --sender A --args object(2,0)
created: object(3,0), object(3,1), object(3,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6536000,  storage_rebate: 2212056, non_refundable_storage_fee: 22344

task 4, line 58:
//# run Test::m::add_dof --sender A --args object(2,0)
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5928000,  storage_rebate: 2212056, non_refundable_storage_fee: 22344

task 5, line 60:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 62-85:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject"
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue"
            }
          }
        ]
      }
    }
  }
}

task 7, line 87:
//# run Test::m::wrap --sender A --args object(2,0)
created: object(7,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2485200,  storage_rebate: 2212056, non_refundable_storage_fee: 22344

task 8, line 89:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 91-114:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject"
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue"
            }
          }
        ]
      }
    }
  }
}

task 10, lines 116-141:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject"
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              },
              "__typename": "MoveValue"
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              },
              "__typename": "MoveValue"
            }
          }
        ]
      }
    }
  }
}

task 11, lines 143-163:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "dynamicField": {
        "name": {
          "type": {
            "repr": "u64"
          },
          "data": {
            "Number": "0"
          },
          "bcs": "AAAAAAAAAAA="
        },
        "value": {
          "__typename": "MoveValue",
          "bcs": "AAAAAAAAAAA=",
          "data": {
            "Number": "0"
          }
        }
      }
    }
  }
}

task 12, lines 165-176:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "dynamicObjectField": {
        "value": {
          "__typename": "MoveObject"
        }
      }
    }
  }
}
