processed 21 tasks

init:
validator_0: object(0,0)

task 1 'publish'. lines 6-28:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 30-30:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 32-32:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 34-34:
Owner: Account Address ( validator_0 )
Version: 1
Contents: sui_system::staking_pool::StakedSui {id: sui::object::UID {id: sui::object::ID {bytes: fake(0,0)}}, pool_id: sui::object::ID {bytes: _}, stake_activation_epoch: 0u64, principal: sui::balance::Balance<sui::sui::SUI> {value: 20000000000000000u64}}

task 5 'view-object'. lines 36-36:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 6 'view-object'. lines 38-38:
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(3,0)}}, value: 0u64}

task 7 'create-checkpoint'. lines 40-40:
Checkpoint created: 4

task 8 'view-checkpoint'. lines 42-42:
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, storage_cost: 10176400, storage_rebate: 1956240, non_refundable_storage_fee: 19760 }}

task 9 'advance-epoch'. lines 45-45:
Epoch advanced: 5

task 10 'view-checkpoint'. lines 47-47:
CheckpointSummary { epoch: 5, seq: 10, content_digest: 4PCTh3N2KWm6w6yuWa7WJdrxcP1mnzsQbJhw5Evzsezp,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11 'run-graphql'. lines 49-55:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12 'create-checkpoint'. lines 56-56:
Checkpoint created: 11

task 13 'view-checkpoint'. lines 58-58:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14 'run-graphql'. lines 60-66:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15 'run-graphql'. lines 68-74:
Headers: {
    "content-type": "application/json",
    "content-length": "137",
    "x-sui-rpc-version": "0.1.0",
}
Service version: 0.1.0
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "nodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "query_payload": 41
    }
  }
}

task 16 'view-checkpoint'. lines 76-76:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17 'advance-epoch'. lines 78-81:
Epoch advanced: 6

task 18 'run-graphql'. lines 83-96:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "node": {
              "address": "0x5c488f887622f4aebab0588e2c9e14f3b87a81ef9beb6ad886913d07d0fe24e2",
              "digest": "KvFgrZRKuWj94sHbuDKUG9pYuzvWLqCuDaF7XSRqzJN",
              "kind": "OWNED"
            }
          }
        ]
      }
    }
  }
}

task 19 'run-graphql'. lines 98-145:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": []
      }
    },
    "second": {
      "objectConnection": {
        "edges": [
          {
            "node": {
              "address": "0x5c488f887622f4aebab0588e2c9e14f3b87a81ef9beb6ad886913d07d0fe24e2",
              "digest": "KvFgrZRKuWj94sHbuDKUG9pYuzvWLqCuDaF7XSRqzJN",
              "kind": "OWNED"
            }
          }
        ]
      }
    },
    "val_objs": {
      "objectConnection": {
        "edges": [
          {
            "node": {
              "address": "0x450473248410d217532c6504bf6d196c1b6c3b5dc9f7f4f7a4bded426415cc6b",
              "digest": "8fBZrFLZecK1XqqSnMSQzUmNWXNNU9GLkDJD8Z1r4Q7g",
              "kind": "OWNED",
              "owner": {
                "address": "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"
              }
            }
          },
          {
            "node": {
              "address": "0x4cbaa9966e842947194b553ef836c7c3e07ecd40c83bdc858253a851fc4785bb",
              "digest": "39rNZNGWpBEruitrjTaoBjFP9JTnaVPEAwX6GQPh18sE",
              "kind": "OWNED",
              "owner": {
                "address": "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"
              }
            }
          },
          {
            "node": {
              "address": "0x84c25f619fe55becb8c360f338b69e2730a194a5f21c19cb458620c58a6bf774",
              "digest": "88CFVc1HqH4UCqxHZ8zy1iH9i8M93mPgBri1qEMYA3Hg",
              "kind": "OWNED",
              "owner": {
                "address": "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"
              }
            }
          },
          {
            "node": {
              "address": "0xc9e16274a2b3a7ed0fe03a5d61bee1e9abce94295c8c9f573c1f3498aa0884ee",
              "digest": "5TV7t83siTj56jB9NB37ZxuGe62mMbMxhYPqvjwo4JoV",
              "kind": "OWNED",
              "owner": {
                "address": "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"
              }
            }
          },
          {
            "node": {
              "address": "0xd0f352d0ac08c0f9b32a575bce8838057322c591c6f92eeb66b7c4170a48db52",
              "digest": "AxY5U32U1P8AHmMvtR8URJU8fQsbCVhTAKpsp2XfeDsY",
              "kind": "OWNED",
              "owner": {
                "address": "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"
              }
            }
          },
          {
            "node": {
              "address": "0xf53c86cbac6e258ea90a1a28e28a517d18cbbbda1cfe2fe5fd46310ce3d821d4",
              "digest": "ADv7kfMZsB4W1yhy73kNe3CJRtQiFXxim5XRQDxyMUuV",
              "kind": "OWNED",
              "owner": {
                "address": "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
      }
    }
  }
}

task 20 'view-graphql-variables'. lines 148-149:
Name: A
Type: SuiAddress!
Value: "0x42"

Name: A_opt
Type: SuiAddress
Value: "0x42"

Name: Test
Type: SuiAddress!
Value: "0x1b0d6059365674220463383118e5071b68a9a60d75b6daa0eaebc6d5e1e8baff"

Name: Test_opt
Type: SuiAddress
Value: "0x1b0d6059365674220463383118e5071b68a9a60d75b6daa0eaebc6d5e1e8baff"

Name: deepbook
Type: SuiAddress!
Value: "0xdee9"

Name: deepbook_opt
Type: SuiAddress
Value: "0xdee9"

Name: obj_0_0
Type: SuiAddress!
Value: "0x4cbaa9966e842947194b553ef836c7c3e07ecd40c83bdc858253a851fc4785bb"

Name: obj_0_0_opt
Type: SuiAddress
Value: "0x4cbaa9966e842947194b553ef836c7c3e07ecd40c83bdc858253a851fc4785bb"

Name: obj_0_1
Type: SuiAddress!
Value: "0x41fecca58b50f58462de38ffb1e51db734242696ec338a366f3502c7d02b79cd"

Name: obj_0_1_opt
Type: SuiAddress
Value: "0x41fecca58b50f58462de38ffb1e51db734242696ec338a366f3502c7d02b79cd"

Name: obj_1_0
Type: SuiAddress!
Value: "0x1b0d6059365674220463383118e5071b68a9a60d75b6daa0eaebc6d5e1e8baff"

Name: obj_1_0_opt
Type: SuiAddress
Value: "0x1b0d6059365674220463383118e5071b68a9a60d75b6daa0eaebc6d5e1e8baff"

Name: obj_2_0
Type: SuiAddress!
Value: "0x5c488f887622f4aebab0588e2c9e14f3b87a81ef9beb6ad886913d07d0fe24e2"

Name: obj_2_0_opt
Type: SuiAddress
Value: "0x5c488f887622f4aebab0588e2c9e14f3b87a81ef9beb6ad886913d07d0fe24e2"

Name: obj_3_0
Type: SuiAddress!
Value: "0x450473248410d217532c6504bf6d196c1b6c3b5dc9f7f4f7a4bded426415cc6b"

Name: obj_3_0_opt
Type: SuiAddress
Value: "0x450473248410d217532c6504bf6d196c1b6c3b5dc9f7f4f7a4bded426415cc6b"

Name: std
Type: SuiAddress!
Value: "0x1"

Name: std_opt
Type: SuiAddress
Value: "0x1"

Name: sui
Type: SuiAddress!
Value: "0x2"

Name: sui_opt
Type: SuiAddress
Value: "0x2"

Name: sui_system
Type: SuiAddress!
Value: "0x3"

Name: sui_system_opt
Type: SuiAddress
Value: "0x3"

Name: validator_0
Type: SuiAddress!
Value: "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"

Name: validator_0_opt
Type: SuiAddress
Value: "0xcff74df5324d2c0ec2a5f21d85206d5b007d5f548978cad7a9e9ca33015780fc"
