processed 25 tasks

init:
validator_0: object(0,0)

task 1 'publish'. lines 6-28:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5570800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 30-30:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 32-32:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 34-34:
Owner: Account Address ( validator_0 )
Version: 1
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(0,0)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 30000000000000000u64}}

task 5 'view-object'. lines 36-36:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 0u64}

task 6 'view-object'. lines 38-38:
Owner: Account Address ( validator_0 )
Version: 4
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(3,0)}}, value: 0u64}

task 7 'create-checkpoint'. lines 40-40:
Checkpoint created: 4

task 8 'view-checkpoint'. lines 42-42:
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 3000000, storage_cost: 10176400, storage_rebate: 1956240, non_refundable_storage_fee: 19760 }}

task 9 'advance-epoch'. lines 44-44:
Epoch advanced: 5

task 10 'view-checkpoint'. lines 46-46:
CheckpointSummary { epoch: 5, seq: 10, content_digest: 95jet51pYzX7nsd1bb5QUfUVhXcBFb6Fq2wTW2StTKHo,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11 'run-graphql'. lines 48-53:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12 'create-checkpoint'. lines 55-55:
Checkpoint created: 11

task 13 'view-checkpoint'. lines 57-57:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14 'run-graphql'. lines 59-64:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15 'run-graphql'. lines 66-71:
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-sui-rpc-version": "2024.2.0",
    "access-control-allow-origin": "*",
    "vary": "origin",
    "vary": "access-control-request-method",
    "vary": "access-control-request-headers",
}
Service version: 2024.2.0
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16 'view-checkpoint'. lines 73-73:
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17 'advance-epoch'. lines 75-78:
Epoch advanced: 6

task 18 'run-graphql'. lines 80-95:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x5bf9d767a9494f51dcc9933b5c61f26a25f7b193940633797297c2ee3fb6c2c1",
              "digest": "6cpS1eAoVQFWmrM6nUiSP1tmUN4tdeKnyJW8q2xSi958",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19 'run-graphql'. lines 97-152:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x5bf9d767a9494f51dcc9933b5c61f26a25f7b193940633797297c2ee3fb6c2c1",
              "digest": "6cpS1eAoVQFWmrM6nUiSP1tmUN4tdeKnyJW8q2xSi958",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x3b476ceccf27b6f59e428e383d6d83dd7a4f8cdf6d6b983662ccfb8e8a3bd83c",
              "digest": "6eLg22RPZADgStWXvhfM9Za2Pct4jG4UBjvwKTt9MTxi",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x45b74ecfaf3c3939def51444348deef625842d9d264b89ef910718301bee24ad",
              "digest": "6dt8b2dKGeDFxjMYJWi746sDYu6MzPRy5QRzWm15oxNZ",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x4636e0c518891e50177c081cef767c80ec26df11e325cd82272efbe85653be25",
              "digest": "CRncSadf4RkZR6eU4gK3GK15Gx5zsGE8RQQ6y2hnPrGp",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x89ef2b8756e64df9175b26645f26be580efda56e54c9ab351befedff12ad3f69",
              "digest": "9sQhqE6oCsdDiR1v5iH2rq5qBzkASracUaisMVVvxQk2",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xbb3e5961f19cab9e1e5a7eefd63d0b59688ee754f8a45a156feafd85d70999a1",
              "digest": "EjaW8GqmV7Hf5NTFCNJZgiPyK6DKzRLxVDb2TNJKinX3",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xe268b525b91a4819a26b1bf6e428174736419e2d999fe5a3fcbaf94e153a8e9d",
              "digest": "3pe6Gxc2EBNnXMJK1SGrySLunxU5kWUUVV4xaH8ubyQB",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20 'run-graphql'. lines 154-170:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
    }
  }
}

task 21 'run-graphql'. lines 172-178:
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22 'run'. lines 180-180:
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 23 'run'. lines 182-182:
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 24 'run'. lines 184-184:
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880
