warning[W08002]: redundant equal operands for binary operation
  ┌─ tests/move_check/folding/equal_operand.move:6:9
  │
6 │         1 == 1;
  │         ^^^^^^
  │         │    │
  │         │    Evaluates to the same value as this expression
  │         Equal operands detected in binary operation, which always evaluates to 'true'
  │         This expression
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
  ┌─ tests/move_check/folding/equal_operand.move:7:9
  │
7 │         {1} == 1;
  │         ^^^^^^^^
  │         ││     │
  │         ││     Evaluates to the same value as this expression
  │         │This expression
  │         Equal operands detected in binary operation, which always evaluates to 'true'
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
  ┌─ tests/move_check/folding/equal_operand.move:8:9
  │
8 │         1 == {1};
  │         ^^^^^^^^
  │         │     │
  │         │     Evaluates to the same value as this expression
  │         Equal operands detected in binary operation, which always evaluates to 'true'
  │         This expression
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
  ┌─ tests/move_check/folding/equal_operand.move:9:9
  │
9 │         {1} == {1};
  │         ^^^^^^^^^^
  │         ││      │
  │         ││      Evaluates to the same value as this expression
  │         │This expression
  │         Equal operands detected in binary operation, which always evaluates to 'true'
  │
  = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:10:9
   │
10 │         {{{1}}} == {{{{1}}}};
   │         ^^^^^^^^^^^^^^^^^^^^
   │         │  │           │
   │         │  │           Evaluates to the same value as this expression
   │         │  This expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:14:9
   │
14 │         false == false;
   │         ^^^^^^^^^^^^^^
   │         │        │
   │         │        Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:15:9
   │
15 │         0u8 == 0u8;
   │         ^^^^^^^^^^
   │         │      │
   │         │      Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:16:9
   │
16 │         1u16 == 1u16;
   │         ^^^^^^^^^^^^
   │         │       │
   │         │       Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:17:9
   │
17 │         2u32 == 2u32;
   │         ^^^^^^^^^^^^
   │         │       │
   │         │       Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:18:9
   │
18 │         3u64 == 3u64;
   │         ^^^^^^^^^^^^
   │         │       │
   │         │       Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:19:9
   │
19 │         4u128 == 4u128;
   │         ^^^^^^^^^^^^^^
   │         │        │
   │         │        Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:20:9
   │
20 │         5u256 == 5u256;
   │         ^^^^^^^^^^^^^^
   │         │        │
   │         │        Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:21:9
   │
21 │         @a == @a;
   │         ^^^^^^^^
   │         │     │
   │         │     Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:22:9
   │
22 │         vector<vector<u8>>[] == vector[];
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │         │                       │
   │         │                       Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W08002]: redundant equal operands for binary operation
   ┌─ tests/move_check/folding/equal_operand.move:23:9
   │
23 │         vector[1] == vector[1];
   │         ^^^^^^^^^^^^^^^^^^^^^^
   │         │            │
   │         │            Evaluates to the same value as this expression
   │         Equal operands detected in binary operation, which always evaluates to 'true'
   │         This expression
   │
   = This warning can be suppressed with '#[allow(equal_operands)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

