
# Generated on Mon, 29 Jul 2024 21:00:34 +0000
# !buckify
# code within the buckify block will be auto-replaced when buckify is run
deps = [
  "//buck/third-party:anyhow_1_0_81",
  "//buck/third-party:axum-extra_0_9_3",
  "//buck/third-party:axum-server_0_6_1",
  "//buck/third-party:axum_0_7_5",
  "//buck/third-party:bytes_1_5_0",
  "//buck/third-party:clap_4_5_4",
  "//buck/third-party:const-str_0_5_6",
  "//buck/third-party:fastcrypto_0_1_8",
  "//buck/third-party:hex_0_4_3",
  "//buck/third-party:hyper_1_4_1",
  "//buck/third-party:ipnetwork_0_20_0",
  "//buck/third-party:itertools_0_10_5",
  "//buck/third-party:multiaddr_0_17_0",
  "//buck/third-party:once_cell_1_19_0",
  "//buck/third-party:prometheus_0_13_3",
  "//buck/third-party:prost_0_13_1",
  "//buck/third-party:protobuf_2_28_0",
  "//buck/third-party:rand_0_8_5",
  "//buck/third-party:reqwest_0_12_5",
  "//buck/third-party:rustls-pemfile_2_1_2",
  "//buck/third-party:rustls_0_23_12",
  "//buck/third-party:serde_1_0_202",
  "//buck/third-party:serde_json_1_0_120",
  "//buck/third-party:serde_with_3_8_1",
  "//buck/third-party:serde_yaml_0_8_26",
  "//buck/third-party:snap_1_1_0",
  "//buck/third-party:tokio_1_36_0",
  "//buck/third-party:tower-http_0_5_2",
  "//buck/third-party:tower_0_4_13",
  "//buck/third-party:tracing_0_1_40",
  "//crates/bin-version:bin-version",
  "//crates/mysten-metrics:mysten-metrics",
  "//crates/sui-tls:sui-tls",
  "//crates/sui-types:sui-types",
  "//crates/telemetry-subscribers:telemetry-subscribers"
]
build_deps = [
  "//buck/third-party:prost-build_0_13_1"
]
# buckify!

rust_library(
    name = "sui-proxy",
    srcs = glob(["**/*"]),
    deps = deps,
    env = {
        "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
        "CARGO_PKG_NAME": "sui-proxy",
        "OUT_DIR": "$(location :sui-proxy-build-script-run[out_dir])",
        "CARGO_PKG_VERSION": "0.0.2",
        "CARGO_MANIFEST_DIR": ".",
        "CARGO_PKG_DESCRIPTION": "",
    },
    crate_root = "src/lib.rs",
    edition = "2021",
    visibility = ["PUBLIC"],
)


rust_binary(
    name = "sui-proxy-bin",
    srcs = glob(["**/*"]),
    deps = deps,
    named_deps = {
        "sui-proxy": ":sui-proxy",
    },
    env = {
        "CARGO_BIN_NAME": "sui-proxy",
        "OUT_DIR": "$(location :sui-proxy-build-script-run[out_dir])",
        "CARGO_PKG_VERSION": "0.0.2",
        "CARGO_PKG_DESCRIPTION": "",
        "CARGO_PKG_BIN": "sui-proxy",
        "CARGO_MANIFEST_DIR": "",
        "CARGO_PKG_AUTHORS": "[Mysten Labs <build@mystenlabs.com>]",
        "CARGO_PKG_NAME": "sui-proxy",
    },
    crate_root = "src/main.rs",
    edition = "2021",
    visibility = ["PUBLIC"],
)


load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")

rust_binary(
    name = "sui-proxy-build-script-build",
    srcs = glob(["**/*"]),
    deps = deps + build_deps,
    env = {
        "CARGO_MANIFEST_DIR": "",
        "OUT_DIR": "",
    },
    crate_root = "build.rs",
    crate = "build_script_build",
    edition = "2021",
)

buildscript_run(
    name = "sui-proxy-build-script-run",
    buildscript_rule = ":sui-proxy-build-script-build",
    package_name = "sui-proxy",
    version = "0.0.2",
)

