warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/typing/return_any_type.move:5:13
  │
5 │         0 + (return ());
  │             ^^^^^^^^^^^ Expected a value. Any code surrounding or after this expression will not be reached
  │
  = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/typing/return_any_type.move:9:13
  │
9 │         foo(return ());
  │             ^^^^^^^^^ Expected a value. Any code surrounding or after this expression will not be reached
  │
  = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

