// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// This file is generated by genversion.mjs. Do not edit it directly.

<<<<<<< HEAD
export const PACKAGE_VERSION = '1.16.2';
=======
export const PACKAGE_VERSION = '1.16.0';
>>>>>>> 8e91ea9f6d (rebase)
export const TARGETED_RPC_VERSION = '1.40.0';
