processed 4 tasks

task 1 'publish'. lines 8-18:
Error: Transaction Effects Status: Sui Move Bytecode Verification Error. Please run the Sui Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some("_::m::t. Invalid call to 'sui::transfer::transfer' on an object of type 'sui::locked_coin::LockedCoin<_::m::TestCoin>'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }

task 2 'publish'. lines 20-30:
Error: Transaction Effects Status: Sui Move Bytecode Verification Error. Please run the Sui Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some("_::m::t. Invalid call to 'sui::transfer::share_object' on an object of type 'sui::locked_coin::LockedCoin<_::m::TestCoin>'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }

task 3 'publish'. lines 32-42:
Error: Transaction Effects Status: Sui Move Bytecode Verification Error. Please run the Sui Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some("_::m::t. Invalid call to 'sui::transfer::freeze_object' on an object of type 'sui::locked_coin::LockedCoin<_::m::TestCoin>'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }
