current frame stack:
  function: test (m.move:17)
    scope 0 :
  function: foo (m.move:0)
    scope 0 :
  function: __inlined__ (m_dep.move:4)
    scope 0 :
current frame stack:
  function: test (m.move:17)
    scope 0 :
  function: foo (m.move:0)
    scope 0 :
  function: __inlined__ (m_dep.move:10)
    scope 0 :
current frame stack:
  function: test (m.move:17)
    scope 0 :
  function: foo (m.move:12)
    scope 0 :
      v : 6
      type: u64

  function: __inlined__ (m_dep.move:4)
    scope 0 :
line breakpoints
  m_dep.move
    4
