warning[W09005]: dead or unreachable code
  ┌─ tests/move_check/typing/borrow_divergent.move:4:13
  │
4 │            &break;
  │             ^^^^^ Expected a value. Any code surrounding or after this expression will not be reached
  │
  = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09005]: dead or unreachable code
   ┌─ tests/move_check/typing/borrow_divergent.move:11:12
   │
11 │         &{ return };
   │            ^^^^^^ Expected a value. Any code surrounding or after this expression will not be reached
   │
   = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09005]: dead or unreachable code
   ┌─ tests/move_check/typing/borrow_divergent.move:18:10
   │
18 │         &(if (cond) return else return);
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expected a value. Any code surrounding or after this expression will not be reached
   │
   = This warning can be suppressed with '#[allow(dead_code)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

