warning[W04028]: implicit copy of a constant
  ┌─ tests/move_check/typing/implicit_const_copy.move:7:9
  │
7 │         &C;
  │         ^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
  │
  = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W04028]: implicit copy of a constant
  ┌─ tests/move_check/typing/implicit_const_copy.move:8:9
  │
8 │         &BYTES;
  │         ^^^^^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
  │
  = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W04028]: implicit copy of a constant
  ┌─ tests/move_check/typing/implicit_const_copy.move:9:10
  │
9 │         *&C;
  │          ^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
  │
  = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W04028]: implicit copy of a constant
   ┌─ tests/move_check/typing/implicit_const_copy.move:10:10
   │
10 │         *&BYTES;
   │          ^^^^^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
   │
   = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W04028]: implicit copy of a constant
   ┌─ tests/move_check/typing/implicit_const_copy.move:11:9
   │
11 │         &mut C;
   │         ^^^^^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
   │
   = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W04028]: implicit copy of a constant
   ┌─ tests/move_check/typing/implicit_const_copy.move:12:9
   │
12 │         &mut BYTES;
   │         ^^^^^^^^^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
   │
   = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W04028]: implicit copy of a constant
   ┌─ tests/move_check/typing/implicit_const_copy.move:13:10
   │
13 │         *&mut C = 1;
   │          ^^^^^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
   │
   = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W04028]: implicit copy of a constant
   ┌─ tests/move_check/typing/implicit_const_copy.move:14:10
   │
14 │         *&mut BYTES = b"bye";
   │          ^^^^^^^^^^ Borrowing, or accessing the field of, a constant will first copy the entire constant. Consider first binding the value to a variable to make this copy explicit.
   │
   = This warning can be suppressed with '#[allow(implicit_const_copy)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

