processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-144:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 2 'programmable'. lines 146-148:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 3 'view-object'. lines 150-150:
Error: task 3, lines 150-150. Unbound fake id 2,9

task 4 'programmable'. lines 152-153:
Error: INVALID TEST. Unknown object, object(2,9)

task 5 'view-object'. lines 155-155:
Error: task 5, lines 155-155. Unbound fake id 2,9

task 6 'programmable'. lines 157-158:
Error: INVALID TEST. Unknown object, object(2,9)

task 7 'view-object'. lines 160-163:
Error: task 7, lines 160-160. Unbound fake id 2,9

task 8 'programmable'. lines 165-166:
Error: INVALID TEST. Unknown object, object(2,9)

task 9 'programmable'. lines 168-169:
Error: INVALID TEST. Unknown object, object(2,9)

task 10 'programmable'. lines 171-175:
Error: INVALID TEST. Unknown object, object(2,9)

task 11 'programmable'. lines 177-178:
Error: INVALID TEST. Unknown object, object(2,9)

task 12 'programmable'. lines 180-181:
Error: INVALID TEST. Unknown object, object(2,9)

task 13 'programmable'. lines 183-184:
Error: INVALID TEST. Unknown object, object(2,9)
