processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-121:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 2 'programmable'. lines 123-125:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 3 'view-object'. lines 127-127:
Error: task 3, lines 127-127. Unbound fake id 2,8

task 4 'programmable'. lines 129-130:
Error: INVALID TEST. Unknown object, object(2,8)

task 5 'view-object'. lines 132-132:
Error: task 5, lines 132-132. Unbound fake id 2,8

task 6 'programmable'. lines 134-135:
Error: INVALID TEST. Unknown object, object(2,8)

task 7 'view-object'. lines 137-140:
Error: task 7, lines 137-137. Unbound fake id 2,8

task 8 'programmable'. lines 142-143:
Error: INVALID TEST. Unknown object, object(2,8)

task 9 'programmable'. lines 145-146:
Error: INVALID TEST. Unknown object, object(2,8)

task 10 'programmable'. lines 148-152:
Error: INVALID TEST. Unknown object, object(2,8)

task 11 'programmable'. lines 154-155:
Error: INVALID TEST. Unknown object, object(2,8)

task 12 'programmable'. lines 157-158:
Error: INVALID TEST. Unknown object, object(2,8)

task 13 'programmable'. lines 160-161:
Error: INVALID TEST. Unknown object, object(2,8)
