processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-134:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 2 'programmable'. lines 136-138:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 3 'view-object'. lines 140-140:
Error: task 3, lines 140-140. Unbound fake id 2,8

task 4 'programmable'. lines 142-143:
Error: INVALID TEST. Unknown object, object(2,8)

task 5 'view-object'. lines 145-145:
Error: task 5, lines 145-145. Unbound fake id 2,8

task 6 'programmable'. lines 147-148:
Error: INVALID TEST. Unknown object, object(2,8)

task 7 'view-object'. lines 150-153:
Error: task 7, lines 150-150. Unbound fake id 2,8

task 8 'programmable'. lines 155-156:
Error: INVALID TEST. Unknown object, object(2,8)

task 9 'programmable'. lines 158-159:
Error: INVALID TEST. Unknown object, object(2,8)

task 10 'programmable'. lines 161-165:
Error: INVALID TEST. Unknown object, object(2,8)

task 11 'programmable'. lines 167-168:
Error: INVALID TEST. Unknown object, object(2,8)

task 12 'programmable'. lines 170-171:
Error: INVALID TEST. Unknown object, object(2,8)

task 13 'programmable'. lines 173-174:
Error: INVALID TEST. Unknown object, object(2,8)
