processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-53:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 2 'programmable'. lines 55-59:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 3 'view-object'. lines 61-61:
Error: task 3, lines 61-61. Unbound fake id 2,0

task 4 'view-object'. lines 63-63:
Error: task 4, lines 63-63. Unbound fake id 2,1

task 5 'view-object'. lines 65-65:
Error: task 5, lines 65-65. Unbound fake id 2,2

task 6 'programmable'. lines 67-70:
Error: INVALID TEST. Unknown object, object(2,2)

task 7 'view-object'. lines 72-72:
Error: task 7, lines 72-72. Unbound fake id 2,0

task 8 'view-object'. lines 74-74:
Error: task 8, lines 74-74. Unbound fake id 2,1

task 9 'view-object'. lines 76-79:
Error: task 9, lines 76-76. Unbound fake id 2,2

task 10 'programmable'. lines 81-82:
Error: INVALID TEST. Unknown object, object(2,2)
