processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-53:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7493600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 55-59:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6285200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 61-61:
Owner: Object ID: ( _ )
Version: 2
Contents: sui::dynamic_field::Field<u64, test::m::Obj> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, name: 0u64, value: test::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: _}}, value: 0u64}}

task 4 'view-object'. lines 63-63:
Owner: Object ID: ( fake(2,2) )
Version: 2
Contents: sui::dynamic_field::Field<u64, test::m::Obj> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, name: 0u64, value: test::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: _}}, value: 0u64}}

task 5 'view-object'. lines 65-65:
Owner: Account Address ( A )
Version: 2
Contents: test::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 6 'programmable'. lines 67-70:
mutated: object(0,0), object(2,0), object(2,2)
gas summary: computation_cost: 1000000, storage_cost: 4278800,  storage_rebate: 4236012, non_refundable_storage_fee: 42788

task 7 'view-object'. lines 72-72:
Owner: Object ID: ( _ )
Version: 3
Contents: sui::dynamic_field::Field<u64, test::m::Obj> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, name: 0u64, value: test::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: _}}, value: 112u64}}

task 8 'view-object'. lines 74-74:
Owner: Object ID: ( fake(2,2) )
Version: 2
Contents: sui::dynamic_field::Field<u64, test::m::Obj> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}, name: 0u64, value: test::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: _}}, value: 0u64}}

task 9 'view-object'. lines 76-79:
Owner: Account Address ( A )
Version: 3
Contents: test::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,2)}}, value: 0u64}

task 10 'programmable'. lines 81-82:
mutated: object(0,0), object(2,2)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724
