processed 14 tasks

init:
P1: object(0,0), P2: object(0,1)

task 1 'publish'. lines 8-55:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 2 'programmable'. lines 57-59:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 3 'programmable'. lines 61-62:
Error: INVALID TEST. Unknown object, object(2,0)

task 4 'programmable'. lines 64-65:
Error: INVALID TEST. Unknown object, object(2,0)

task 5 'view-object'. lines 67-70:
Error: task 5, lines 67-67. Unbound fake id 2,0

task 6 'programmable'. lines 72-74:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 7 'view-object'. lines 76-76:
Error: task 7, lines 76-76. Unbound fake id 6,0

task 8 'programmable'. lines 78-79:
Error: INVALID TEST. Unknown object, object(6,1)

task 9 'view-object'. lines 81-85:
Error: task 9, lines 81-81. Unbound fake id 6,0

task 10 'programmable'. lines 87-92:
Error: INVALID TEST. Unknown object, object(2,0)

task 11 'programmable'. lines 94-98:
Error: INVALID TEST. Unknown object, object(2,0)

task 12 'programmable'. lines 100-104:
Error: INVALID TEST. Unknown object, object(2,0)

task 13 'programmable'. lines 106-108:
Error: INVALID TEST. Unknown object, object(2,0)
