processed 12 tasks

init:
P1: object(0,0), P2: object(0,1)

task 1 'publish'. lines 8-55:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 2 'programmable'. lines 57-59:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 3 'view-object'. lines 62-65:
Error: task 3, lines 62-62. Unbound fake id 2,0

task 4 'programmable'. lines 67-69:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 5 'view-object'. lines 71-71:
Error: task 5, lines 71-71. Unbound fake id 4,0

task 6 'programmable'. lines 73-74:
Error: INVALID TEST. Unknown object, object(4,1)

task 7 'view-object'. lines 76-79:
Error: task 7, lines 76-76. Unbound fake id 4,0

task 8 'programmable'. lines 81-86:
Error: INVALID TEST. Unknown object, object(2,0)

task 9 'programmable'. lines 88-92:
Error: INVALID TEST. Unknown object, object(2,0)

task 10 'programmable'. lines 94-98:
Error: INVALID TEST. Unknown object, object(2,0)

task 11 'programmable'. lines 100-102:
Error: INVALID TEST. Unknown object, object(2,0)
