current event stack:
  summary frame (line 2): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  no active event frame
current event stack:
  summary frame (line 2): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  event frame: 
    Publish: ()
current event stack:
  summary frame (line 3): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  current frame stack:
    function: init (my_coin.mvb:19)
      scope 0 :
        Arg0 : (fba24b2c50708ad973f7d4b590d03a7a272ee80ee3ea7abf60c20f6cb417398a::my_coin::MY_COIN) {
          dummy_field : true
        }
        type: fba24b2c50708ad973f7d4b590d03a7a272ee80ee3ea7abf60c20f6cb417398a::my_coin::MY_COIN

        Arg1 : (0x2::tx_context::TxContext) {
          sender : 0000000000000000000000000000000000000000000000000000000000000000
          tx_hash : [
            0 : 193
            1 : 252
            2 : 55
            3 : 57
            4 : 223
            5 : 47
            6 : 123
            7 : 181
            8 : 7
            9 : 28
            10 : 202
            11 : 103
            12 : 182
            13 : 158
            14 : 182
            15 : 206
            16 : 18
            17 : 243
            18 : 247
            19 : 17
            20 : 106
            21 : 18
            22 : 252
            23 : 156
            24 : 39
            25 : 204
            26 : 101
            27 : 244
            28 : 47
            29 : 154
            30 : 113
            31 : 237
          ]
          epoch : 0
          epoch_timestamp_ms : 0
          ids_created : 0
        }
        type: &mut 0x2::tx_context::TxContext

current event stack:
  summary frame (line 4): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  event frame: 
    TransferObjects: obj0...objN => ()
      obj0 : (0x2::package::UpgradeCap) {
        id : (0x2::object::UID) {
          id : (0x2::object::ID) {
            bytes : 8f3e305a36ef5ed09791b1027646401410a1fd0b391a007c3910a9ecd26f3b4f
          }
        }
        package : (0x2::object::ID) {
          bytes : fba24b2c50708ad973f7d4b590d03a7a272ee80ee3ea7abf60c20f6cb417398a
        }
        version : 1
        policy : 0
      }
      type: 0x2::package::UpgradeCap

current event stack:
  summary frame (line 5): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  event frame: 
    MakeMoveVec: vector
      vector : [
        0 : 500
        1 : 500
      ]
      type: vector<vector<u64>>

current event stack:
  summary frame (line 6): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  current frame stack:
    function: mint (my_coin.mvb:43)
      scope 0 :
        Arg0 : (0x2::coin::TreasuryCap<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              bytes : 3a7a381b1633c1e41324c61d042448c81c1b74300c25e8ab4c254d4f2891b1d9
            }
          }
          total_supply : (0x2::balance::Supply<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 0
          }
        }
        type: &mut 0x2::coin::TreasuryCap<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>

        Arg1 : [
          0 : 500
          1 : 500
        ]
        type: vector<u64>

        Arg2 : (0x2::tx_context::TxContext) {
          sender : 0000000000000000000000000000000000000000000000000000000000000000
          tx_hash : [
            0 : 193
            1 : 252
            2 : 55
            3 : 57
            4 : 223
            5 : 47
            6 : 123
            7 : 181
            8 : 7
            9 : 28
            10 : 202
            11 : 103
            12 : 182
            13 : 158
            14 : 182
            15 : 206
            16 : 18
            17 : 243
            18 : 247
            19 : 17
            20 : 106
            21 : 18
            22 : 252
            23 : 156
            24 : 39
            25 : 204
            26 : 101
            27 : 244
            28 : 47
            29 : 154
            30 : 113
            31 : 237
          ]
          epoch : 0
          epoch_timestamp_ms : 0
          ids_created : 0
        }
        type: &mut 0x2::tx_context::TxContext

current event stack:
  summary frame (line 7): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  event frame: 
    SplitCoins: input => result
      input : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
        id : (0x2::object::UID) {
          id : (0x2::object::ID) {
            value : 35a1482c6fa8bac922ce77875f433ebd3d57276cfeb4a103a1351d363360064f
          }
        }
        balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          value : 500
        }
      }
      type: 0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>

      result : [
        0 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : 80b35f8d44ac23fbac76234d7f6a289bfe2bae353fc6074dda53e2b9b251e03e
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 100
          }
        }
        1 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : d723059d5150d00be29ee38257c868778d26325c5b6c14e0723b57c1645509b6
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 100
          }
        }
        2 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : f5ae46bcb338fda2ee05ce24943e546e1e283c4225644679343eccca21d982df
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 100
          }
        }
        3 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : b3fc7fe7d0fbed8dd033e235b93068ec1ec8450869754234b08aafa3e3bf2c43
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 100
          }
        }
        4 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : c1ddaec2fc60593e3e43708862dcb2acbdfcbfd12eb1271a5010325c9267d89e
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 100
          }
        }
      ]
      type: vector<0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>>

current event stack:
  summary frame (line 8): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  event frame: 
    MergeCoins: merge_target, coin0...coinN => mergeresult
      merge_target : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
        id : (0x2::object::UID) {
          id : (0x2::object::ID) {
            value : 80b35f8d44ac23fbac76234d7f6a289bfe2bae353fc6074dda53e2b9b251e03e
          }
        }
        balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          value : 100
        }
      }
      type: 0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>

      coin0 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
        id : (0x2::object::UID) {
          id : (0x2::object::ID) {
            value : d723059d5150d00be29ee38257c868778d26325c5b6c14e0723b57c1645509b6
          }
        }
        balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          value : 100
        }
      }
      type: 0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>

      coin1 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
        id : (0x2::object::UID) {
          id : (0x2::object::ID) {
            value : f5ae46bcb338fda2ee05ce24943e546e1e283c4225644679343eccca21d982df
          }
        }
        balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          value : 100
        }
      }
      type: 0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>

      merge_result : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
        id : (0x2::object::UID) {
          id : (0x2::object::ID) {
            value : 80b35f8d44ac23fbac76234d7f6a289bfe2bae353fc6074dda53e2b9b251e03e
          }
        }
        balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          value : 300
        }
      }
      type: 0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>

current event stack:
  summary frame (line 9): 
    MoveCall
    Publish
    MoveCall
    TransferObjects
    MakeMoveVec
    MoveCall
    SplitCoins
    MergeCoins
    MakeMoveVec
    MoveCall
  event frame: 
    MakeMoveVec: vector
      vector : [
        0 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : 35a1482c6fa8bac922ce77875f433ebd3d57276cfeb4a103a1351d363360064f
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 500
          }
        }
        1 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : 80b35f8d44ac23fbac76234d7f6a289bfe2bae353fc6074dda53e2b9b251e03e
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 300
          }
        }
        2 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : b3fc7fe7d0fbed8dd033e235b93068ec1ec8450869754234b08aafa3e3bf2c43
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 100
          }
        }
        3 : (0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
          id : (0x2::object::UID) {
            id : (0x2::object::ID) {
              value : c1ddaec2fc60593e3e43708862dcb2acbdfcbfd12eb1271a5010325c9267d89e
            }
          }
          balance : (0x2::balance::Balance<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>) {
            value : 100
          }
        }
      ]
      type: vector<vector<0x2::coin::Coin<e8b55d70a0d6ab60dd84676d987b1177a6e77f0ca40cdb5ff0e920907cdb76b1::my_coin::MY_COIN>>>

