processed 23 tasks

task 1 'create-checkpoint'. lines 6-8:
Checkpoint created: 1

task 3 'create-checkpoint'. lines 11-13:
Checkpoint created: 2

task 5 'create-checkpoint'. lines 16-18:
Checkpoint created: 3

task 7 'create-checkpoint'. lines 21-23:
Checkpoint created: 4

task 9 'create-checkpoint'. lines 26-28:
Checkpoint created: 5

task 11 'create-checkpoint'. lines 31-33:
Checkpoint created: 6

task 13 'create-checkpoint'. lines 36-38:
Checkpoint created: 7

task 15 'advance-epoch'. lines 41-41:
Epoch advanced: 0

task 16 'create-checkpoint'. lines 43-45:
Checkpoint created: 9

task 19 'create-checkpoint'. lines 51-51:
Checkpoint created: 10

task 20 'advance-epoch'. lines 53-53:
Epoch advanced: 1

task 21 'run-graphql'. lines 55-66:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 2,
          "timestamp": "1970-01-01T00:00:00.001Z",
          "epoch": {
            "epochId": 0
          }
        },
        {
          "sequenceNumber": 3,
          "timestamp": "1970-01-01T00:00:00.002Z",
          "epoch": {
            "epochId": 0
          }
        },
        {
          "sequenceNumber": 4,
          "timestamp": "1970-01-01T00:00:00.003Z",
          "epoch": {
            "epochId": 0
          }
        },
        {
          "sequenceNumber": 5,
          "timestamp": "1970-01-01T00:00:00.013Z",
          "epoch": {
            "epochId": 0
          }
        },
        {
          "sequenceNumber": 6,
          "timestamp": "1970-01-01T00:00:02.013Z",
          "epoch": {
            "epochId": 0
          }
        },
        {
          "sequenceNumber": 7,
          "timestamp": "1970-01-01T00:16:32.013Z",
          "epoch": {
            "epochId": 0
          }
        },
        {
          "sequenceNumber": 8,
          "timestamp": "1970-01-01T03:01:32.013Z",
          "epoch": {
            "epochId": 0
          }
        },
        {
          "sequenceNumber": 9,
          "timestamp": "1970-01-01T03:01:32.013Z",
          "epoch": {
            "epochId": 1
          }
        },
        {
          "sequenceNumber": 10,
          "timestamp": "1970-01-01T03:01:34Z",
          "epoch": {
            "epochId": 1
          }
        },
        {
          "sequenceNumber": 11,
          "timestamp": "1970-01-01T03:01:34Z",
          "epoch": {
            "epochId": 1
          }
        }
      ]
    }
  }
}

task 22 'run-graphql'. lines 68-86:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "commitTimestamp": "1970-01-01T00:00:00.002Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "commitTimestamp": "1970-01-01T00:00:00.003Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "commitTimestamp": "1970-01-01T00:00:00.013Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "commitTimestamp": "1970-01-01T00:00:02.013Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "commitTimestamp": "1970-01-01T00:16:32.013Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "commitTimestamp": "1970-01-01T03:01:32.013Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "EndOfEpochTransaction"
          }
        },
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 1
            },
            "commitTimestamp": "1970-01-01T03:01:33.901Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 1
            },
            "commitTimestamp": "1970-01-01T03:01:34Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          }
        },
        {
          "kind": {
            "__typename": "EndOfEpochTransaction"
          }
        }
      ]
    }
  }
}
