Command `migrate`:
Package toml does not specify an edition. As of 2024, Move requires all packages to define a language edition.

Please select one of the following editions:

1) 2024.beta
2) legacy

Selection (default=1): 

Would you like the Move compiler to migrate your code to Move 2024? (Y/n) 
Generated changes . . .
INCLUDING DEPENDENCY MoveStdlib
BUILDING A

The following changes will be made.
============================================================

--- sources/mod_friend.move
+++ sources/mod_friend.move
@@ -3,2 +3,2 @@
-    friend // why
-    A::n;
+    /* friend // why
+    A::n; */
--- sources/mod_pub_friend.move
+++ sources/mod_pub_friend.move
@@ -2,3 +2 @@
-    public( // why folks, why
-        friend
-    ) fun t() {}
+    public(package) fun t() {}


============================================================
Apply changes? (Y/n) 
Updating "sources/mod_friend.move" . . .
Updating "sources/mod_pub_friend.move" . . .

Changes complete
Wrote patchfile out to: ./migration.patch

Recorded edition in 'Move.toml'
External Command `diff -r -s sources migration_sources`:
Files sources/mod_friend.move and migration_sources/mod_friend.move are identical
Files sources/mod_pub_friend.move and migration_sources/mod_pub_friend.move are identical
External Command `diff -s Move.toml Move.toml.expected`:
Files Move.toml and Move.toml.expected are identical
