Command `migrate`:
Package toml does not specify an edition. As of 2024, Move requires all packages to define a language edition.

Please select one of the following editions:

1) 2024
2) legacy

Selection (default=1): 

Would you like the Move compiler to migrate your code to Move 2024? (Y/n) 
Generated changes . . .
INCLUDING DEPENDENCY MoveStdlib
BUILDING A

The following changes will be made.
============================================================

--- ./sources/mod_friend.move
+++ ./sources/mod_friend.move
@@ -2,2 +2,2 @@
-    #[test_only]
-    friend A::b;
+    /* #[test_only] */
+    /* friend A::b; */
@@ -5 +5 @@
-    friend A::c;
+    /* friend A::c; */
@@ -7 +7 @@
-    #[ext(
+    /* #[ext(
@@ -10,2 +10,2 @@
-    ]
-    friend A::d;
+    ] */
+    /* friend A::d; */
@@ -13 +13 @@
-    #[ext(
+    /* #[ext(
@@ -18,2 +18,2 @@
-    ]
-    friend A::e;
+    ] */
+    /* friend A::e; */
--- ./sources/mod_pub_friend.move
+++ ./sources/mod_pub_friend.move
@@ -2 +2 @@
-    public(friend) fun t1() {}
+    public(package) fun t1() {}
@@ -4,2 +4 @@
-    public(
-        friend) fun t2() {}
+    public(package) fun t2() {}
@@ -7,3 +6 @@
-    public(
-        friend
-        ) fun t3() {}
+    public(package) fun t3() {}
@@ -11,3 +8 @@
-    public(
-        friend /* deleted */
-    ) fun t4() {}
+    public(package) fun t4() {}
@@ -15,4 +10 @@
-    /* stays */ public(
-        /* deleted */
-        friend
-        /*deleted */) /* stays */ fun t5() {} // stays
+    /* stays */ public(package) /* stays */ fun t5() {} // stays


============================================================
Apply changes? (Y/n) 
Updating "./sources/mod_friend.move" . . .
Updating "./sources/mod_pub_friend.move" . . .

Changes complete
Wrote patchfile out to: ./migration.patch

Recorded edition in 'Move.toml'
External Command `diff -r -s sources migration_sources`:
Files sources/mod_friend.move and migration_sources/mod_friend.move are identical
Files sources/mod_pub_friend.move and migration_sources/mod_pub_friend.move are identical
External Command `diff -s Move.toml Move.toml.expected`:
Files Move.toml and Move.toml.expected are identical
