processed 26 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 22-35:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 37:
//# create-checkpoint
Checkpoint created: 1

task 3, line 39:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 41:
//# create-checkpoint
Checkpoint created: 2

task 5, line 43:
//# advance-epoch
Epoch advanced: 0

task 6, lines 45-61:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 3
    },
    "epoch": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": []
      }
    }
  }
}

task 7, line 63:
//# run Test::M1::create --args 0 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8, line 65:
//# create-checkpoint
Checkpoint created: 4

task 9, line 67:
//# run Test::M1::create --args 0 @A --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10, line 69:
//# create-checkpoint
Checkpoint created: 5

task 11, line 71:
//# run Test::M1::create --args 0 @A --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12, line 73:
//# create-checkpoint
Checkpoint created: 6

task 13, line 75:
//# advance-epoch
Epoch advanced: 1

task 14, line 77:
//# run Test::M1::create --args 0 @A --sender A
created: object(14,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 15, line 79:
//# create-checkpoint
Checkpoint created: 8

task 16, line 81:
//# run Test::M1::create --args 0 @A --sender A
created: object(16,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 17, line 83:
//# create-checkpoint
Checkpoint created: 9

task 18, line 85:
//# run Test::M1::create --args 0 @A --sender A
created: object(18,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 19, line 87:
//# create-checkpoint
Checkpoint created: 10

task 20, line 89:
//# advance-epoch
Epoch advanced: 2

task 21, line 91:
//# advance-epoch
Epoch advanced: 3

task 22, lines 93-157:
//# run-graphql --cursors {"t":3,"i":false,"c":4} {"t":7,"i":false,"c":8} {"t":11,"i":false,"c":12}
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 12
    },
    "epoch_0_txs": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": []
      }
    },
    "txs_epoch_0": {
      "edges": []
    },
    "epoch_1_txs": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": []
      }
    },
    "txs_epoch_1": {
      "edges": []
    },
    "epoch_2_txs": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": []
      }
    },
    "txs_epoch_2": {
      "edges": []
    }
  }
}

task 23, lines 159-199:
//# run-graphql --cursors {"t":0,"i":false,"c":7} {"t":4,"i":false,"c":11} {"t":8,"i":false,"c":12}
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 12
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": []
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": []
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": []
      }
    }
  }
}

task 24, lines 201-241:
//# run-graphql --cursors {"t":1,"i":false,"c":2} {"t":5,"i":false,"c":6} {"t":9,"i":false,"c":10}
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 12
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": []
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": []
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": []
      }
    }
  }
}

task 25, lines 243-282:
//# run-graphql --cursors {"t":5,"i":false,"c":6}
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 12
    },
    "with_cursor": {
      "edges": []
    },
    "without_cursor": {
      "edges": []
    }
  }
}
