processed 2 tasks

task 1 'lint'. lines 6-29:
error: Unused private or `friend` function unused_functions::unused_friend. This function should be called or deleted
   ┌─ temp_test_file:16:5
   │
16 │     public(friend) fun unused_friend() {}
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Unused private or `friend` function unused_functions::unused_private. This function should be called or deleted
   ┌─ temp_test_file:13:5
   │
13 │     fun unused_private() {}
   │     ^^^^^^^^^^^^^^^^^^^^^^^


