processed 6 tasks

task 1 'publish'. lines 6-24:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5639200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 26-26:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 28-28:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 2234628, non_refundable_storage_fee: 22572

task 4 'advance-epoch'. lines 30-30:
Epoch advanced: 1

task 5 'run'. lines 32-32:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 2234628, non_refundable_storage_fee: 22572
