processed 4 tasks

task 1 'publish'. lines 6-24:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5684800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 26-26:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 28-28:
Error: Transaction Effects Status: Move Runtime Abort. Location: test::m::check (function index 1) at offset 11, Abort Code: 0
Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 1, instruction: 11, function_name: Some("check") }, 0) at command Some(0)
