processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 13-26:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 28-28:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 30-30:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 32-32:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 34-34:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'create-checkpoint'. lines 36-36:
Checkpoint created: 1

task 7 'run'. lines 38-38:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'run'. lines 40-40:
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'run'. lines 42-42:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 44-44:
Checkpoint created: 2

task 11 'run'. lines 46-46:
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'run'. lines 48-48:
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13 'create-checkpoint'. lines 50-50:
Checkpoint created: 3

task 14 'run-graphql'. lines 52-76:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJ0YyI6MX0",
                "node": {
                  "digest": "5SebKFAfQHQkCYWCfCfCTULYJ49Wf95J8gDHehNMVUeb",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJ0YyI6MX0",
                "node": {
                  "digest": "DgAJBq6ghbTjY5HggmA1FuMbpupdFMdNcCwBqDJ9B4Yp",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJ0YyI6MX0",
                "node": {
                  "digest": "BrBZjSxjqrBByjxZK13dS42BFtB9irGcoASYuwU2BZwu",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJ0YyI6MX0",
                "node": {
                  "digest": "iDye1on25gLDRsM1CQfNwnaFe3CbtK1qW17VTwAGHZB",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJ0YyI6Mn0",
                "node": {
                  "digest": "94rNPhgUMVouyD43Nqi6E2sxEM8LfcMnThQGNtbffbM4",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJ0YyI6Mn0",
                "node": {
                  "digest": "4cLbEhmDBfq7aEPsN8xwYTXFuu7mcpcYz7ULEz7XK7Sb",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJ0YyI6Mn0",
                "node": {
                  "digest": "CEwiKr5coSxJBdUpC3LVf455v5yJZ6v2tC9ReN17guu7",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJ0YyI6M30",
                "node": {
                  "digest": "GZ7xE1EbxpSgvaDFss8vHZ9A1mtSQmRu6Lj5LHNsesz1",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwidGMiOjN9",
                "node": {
                  "digest": "BxiJeYhFk8c7Yz6LWD8v4TUtiws3iWNVC65v8XTQBEX6",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IOmxU/59aBjbT+9uB3UQXpwRBBdaHct+iVbKHwuWf7CvAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 78-95:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
