processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 13-30:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 32-32:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 34-34:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 36-36:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 38-38:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'create-checkpoint'. lines 40-40:
Checkpoint created: 1

task 7 'run'. lines 42-42:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'run'. lines 44-44:
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'run'. lines 46-46:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 48-48:
Checkpoint created: 2

task 11 'run'. lines 50-50:
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'run'. lines 52-52:
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13 'create-checkpoint'. lines 54-54:
Checkpoint created: 3

task 14 'run-graphql'. lines 56-80:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJ0YyI6MX0",
                "node": {
                  "digest": "9Pjiq3n3uTjortcgPKqa1zR1k1LaJK35cdtkhbKH7JG7",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJ0YyI6MX0",
                "node": {
                  "digest": "EndENXveYXQ8AE2JSCwSMCxLMnrt3z8su41XPaTEL2P6",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJ0YyI6MX0",
                "node": {
                  "digest": "HZRVFCp9DJ3ZGJDzYw7Frk5VdpBC1gubQkHkGLXWZVs4",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJ0YyI6MX0",
                "node": {
                  "digest": "9GRa9HgP1XaJhNXr2eTUAr9sS1oMHeFsTD6fs9qFrQG4",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJ0YyI6Mn0",
                "node": {
                  "digest": "J2YjfuPKERDHWN2L5QXQoFnstmNZ6FD4zGhHQGTer3DY",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJ0YyI6Mn0",
                "node": {
                  "digest": "B7W9zJDZuQrMtvNTPbMYmWxfN8qJ8i785VDPXvGcERqo",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJ0YyI6Mn0",
                "node": {
                  "digest": "CyAR7zM5cxGZxRnFtJBRRE2GYW2qTM5y56zpS1bZRqgk",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJ0YyI6M30",
                "node": {
                  "digest": "EhuSJdK2VCmiMw3CVFoY3XxTeYAmLjcz5jHkGCKPnVX3",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwidGMiOjN9",
                "node": {
                  "digest": "EdDqt5p5k9R1UmFy8k9edrDShjVxS8budxUL37DczAHn",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "IPOcUu+NzSfvr7QnGvuBtw862Oq4hnV5ZBkw745OaHWHAwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 82-99:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
