processed 17 tasks

init:
A: object(0,0), C: object(0,1)

task 1 'create-checkpoint'. lines 8-8:
Checkpoint created: 1

task 2 'advance-epoch'. lines 10-10:
Epoch advanced: 0

task 3 'programmable'. lines 12-14:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 16-16:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [19, 65, 154, 239, 210, 25, 176, 160, 98, 215, 120, 192, 99, 141, 197, 129, 80, 21, 151, 37, 33, 102, 3, 96, 225, 234, 253, 206, 37, 47, 16, 125, 204, 90, 199, 15, 26, 115, 207, 23, 155, 27, 157, 111, 100, 63, 135, 83, 239, 230, 55, 48, 108, 61, 171, 142, 187, 175, 171, 222, 111, 196, 243, 215, 167, 176, 50, 112, 56, 120, 170, 116, 195, 18, 105, 53, 120, 159, 209, 212, 215, 225, 17, 213, 145, 27, 9, 36, 125, 105, 99, 6, 28, 49, 43, 90, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 5 'programmable'. lines 19-21:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'programmable'. lines 23-25:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'programmable'. lines 27-29:
created: object(7,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'programmable'. lines 31-33:
created: object(8,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'programmable'. lines 35-37:
created: object(9,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'programmable'. lines 39-41:
created: object(10,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 11 'programmable'. lines 43-45:
created: object(11,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'programmable'. lines 47-49:
created: object(12,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13 'programmable'. lines 51-55:
created: object(13,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 14 'create-checkpoint'. lines 56-56:
Checkpoint created: 3

task 15 'advance-epoch'. lines 58-60:
Epoch advanced: 1

task 16 'run-graphql'. lines 62-72:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": [
          {
            "apy": 0,
            "name": "validator-0"
          }
        ]
      }
    }
  }
}
