processed 23 tasks

init:
A: object(0,0), C: object(0,1), validator_0: object(0,2)

task 1 'advance-epoch'. lines 6-6:
Epoch advanced: 0

task 2 'create-checkpoint'. lines 8-8:
Checkpoint created: 2

task 3 'programmable'. lines 10-12:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 14-14:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [130, 192, 56, 57, 58, 48, 161, 93, 190, 96, 82, 252, 141, 167, 246, 93, 36, 151, 74, 180, 177, 159, 47, 200, 26, 108, 136, 163, 225, 128, 185, 70, 251, 197, 26, 138, 207, 9, 111, 134, 25, 141, 95, 164, 112, 98, 14, 214, 162, 10, 188, 9, 185, 78, 168, 145, 239, 2, 154, 93, 227, 243, 151, 19, 167, 176, 50, 112, 56, 120, 170, 116, 195, 18, 105, 53, 120, 159, 209, 212, 215, 225, 17, 213, 145, 27, 9, 36, 125, 105, 99, 6, 28, 49, 43, 90, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 5 'run'. lines 16-16:
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 13786400,  storage_rebate: 12670416, non_refundable_storage_fee: 127984

task 6 'run'. lines 18-18:
created: object(6,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 15557200,  storage_rebate: 13648536, non_refundable_storage_fee: 137864

task 7 'run'. lines 20-20:
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,2), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 15557200,  storage_rebate: 15401628, non_refundable_storage_fee: 155572

task 8 'run-graphql'. lines 22-28:
Response: {
  "data": {
    "latestSuiSystemState": {
      "referenceGasPrice": "1000"
    }
  }
}

task 9 'create-checkpoint'. lines 30-30:
Checkpoint created: 3

task 10 'publish'. lines 32-60:
created: object(10,0), object(10,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 11 'publish'. lines 62-90:
created: object(11,0), object(11,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'publish'. lines 93-121:
created: object(12,0), object(12,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13 'publish'. lines 123-151:
created: object(13,0), object(13,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 14 'publish'. lines 153-181:
created: object(14,0), object(14,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 15 'publish'. lines 183-211:
created: object(15,0), object(15,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 16 'publish'. lines 213-241:
created: object(16,0), object(16,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 17 'publish'. lines 243-271:
created: object(17,0), object(17,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 18 'publish'. lines 273-301:
created: object(18,0), object(18,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 19 'publish'. lines 303-333:
created: object(19,0), object(19,1)
mutated: object(0,0)
gas summary: computation_cost: 1415000000, storage_cost: 1936936000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 20 'create-checkpoint'. lines 334-334:
Checkpoint created: 4

task 21 'advance-epoch'. lines 336-338:
Epoch advanced: 1

task 22 'run-graphql'. lines 340-350:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": [
          {
            "apy": 2,
            "name": "validator-0"
          }
        ]
      }
    }
  }
}
