processed 10 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-29:
created: object(105)
written: object(104)

task 2 'run'. lines 31-31:
created: object(107)
written: object(106)

task 3 'view-object'. lines 33-33:
Owner: Account Address ( A )
Version: 1
Child Count: None
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 4 'transfer-object'. lines 35-35:
Error: Transaction Effects Status: Invalid Transfer Object Transaction. Possibly not address-owned or possibly does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None } }

task 5 'view-object'. lines 37-40:
Owner: Account Address ( A )
Version: 2
Child Count: None
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 6 'run'. lines 42-42:
created: object(110)
written: object(109)

task 7 'view-object'. lines 44-44:
Owner: Account Address ( A )
Version: 1
Child Count: None
Contents: test::m::Cup<test::m::S> {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}}

task 8 'transfer-object'. lines 46-46:
Error: Transaction Effects Status: Invalid Transfer Object Transaction. Possibly not address-owned or possibly does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None } }

task 9 'view-object'. lines 48-48:
Owner: Account Address ( A )
Version: 2
Child Count: None
Contents: test::m::Cup<test::m::S> {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}}
