processed 18 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-79:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: UNKNOWN_VERSION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 2 'run'. lines 81-81:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 3 'view-object'. lines 83-83:
Error: task 3, lines 83-83. Unbound fake id 2,0

task 4 'view-object'. lines 85-85:
Error: task 4, lines 85-85. Unbound fake id 2,1

task 5 'programmable'. lines 87-89:
Error: INVALID TEST. Unknown object, object(2,0)

task 6 'run'. lines 91-91:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 7 'view-object'. lines 93-93:
Error: task 7, lines 93-93. Unbound fake id 6,0

task 8 'view-object'. lines 95-95:
Error: task 8, lines 95-95. Unbound fake id 6,1

task 9 'programmable'. lines 97-101:
Error: INVALID TEST. Unknown object, object(6,1)

task 10 'run'. lines 103-103:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 11 'view-object'. lines 105-105:
Error: task 11, lines 105-105. Unbound fake id 10,0

task 12 'view-object'. lines 107-107:
Error: task 12, lines 107-107. Unbound fake id 10,1

task 13 'programmable'. lines 109-115:
Error: INVALID TEST. Unknown object, object(10,0)

task 14 'run'. lines 117-117:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 15 'view-object'. lines 119-119:
Error: task 15, lines 119-119. Unbound fake id 14,0

task 16 'view-object'. lines 121-121:
Error: task 16, lines 121-121. Unbound fake id 14,1

task 17 'programmable'. lines 123-127:
Error: INVALID TEST. Unknown object, object(14,0)
