processed 18 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-79:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 9659600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 81-81:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3442800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 83-83:
Owner: Account Address ( A )
Version: 2
Contents: test::m::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 4 'view-object'. lines 85-85:
Owner: Account Address ( fake(2,0) )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 5 'programmable'. lines 87-89:
mutated: object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2234400,  storage_rebate: 3408372, non_refundable_storage_fee: 34428

task 6 'run'. lines 91-91:
created: object(6,0), object(6,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3465600,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'view-object'. lines 93-93:
Owner: Account Address ( fake(6,1) )
Version: 4
Contents: test::m::Cup<u64> {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}

task 8 'view-object'. lines 95-95:
Owner: Account Address ( A )
Version: 4
Contents: test::m::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,1)}}}

task 9 'programmable'. lines 97-101:
mutated: object(0,0), object(6,1)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2234400,  storage_rebate: 3430944, non_refundable_storage_fee: 34656

task 10 'run'. lines 103-103:
created: object(10,0), object(10,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3442800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 11 'view-object'. lines 105-105:
Owner: Account Address ( A )
Version: 6
Contents: test::m::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(10,0)}}}

task 12 'view-object'. lines 107-107:
Owner: Account Address ( fake(10,0) )
Version: 6
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(10,1)}}}

task 13 'programmable'. lines 109-115:
mutated: object(0,0)
deleted: object(10,0), object(10,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 3408372, non_refundable_storage_fee: 34428

task 14 'run'. lines 117-117:
created: object(14,0), object(14,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3473200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 15 'view-object'. lines 119-119:
Owner: Account Address ( A )
Version: 8
Contents: test::m::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(14,0)}}}

task 16 'view-object'. lines 121-121:
Owner: Account Address ( fake(14,0) )
Version: 8
Contents: test::m::Store {id: sui::object::UID {id: sui::object::ID {bytes: fake(14,1)}}}

task 17 'programmable'. lines 123-127:
mutated: object(0,0)
deleted: object(14,0), object(14,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 3438468, non_refundable_storage_fee: 34732
