processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 8-29:
created: object(1,0)
mutated: object(0,2)

task 2 'run'. lines 31-31:
created: object(2,0)
mutated: object(0,0)

task 3 'view-object'. lines 33-33:
Owner: Account Address ( A )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 4 'transfer-object'. lines 35-35:
mutated: object(0,0), object(2,0)

task 5 'view-object'. lines 37-40:
Owner: Account Address ( B )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 6 'run'. lines 42-42:
created: object(6,0)
mutated: object(0,0)

task 7 'view-object'. lines 44-44:
Owner: Account Address ( A )
Version: 4
Contents: test::m::Cup<test::m::S> {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}

task 8 'transfer-object'. lines 46-46:
mutated: object(0,0), object(6,0)

task 9 'view-object'. lines 48-48:
Owner: Account Address ( B )
Version: 5
Contents: test::m::Cup<test::m::S> {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}
