processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-22:
created: object(106)
written: object(105)

task 2 'run'. lines 24-24:
created: object(108)
written: object(107)

task 3 'view-object'. lines 26-26:
Owner: Immutable
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}

task 4 'transfer-object'. lines 28-28:
Error: Attempt to transfer object 0x082da293d12d8186c1f1ff6ceee9e1ab0ccc9a298d8fa6c3975312671c259cc9 that does not have public transfer. Object transfer must be done instead using a distinct Move function call.

task 5 'view-object'. lines 30-30:
Owner: Immutable
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}
