processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-22:
created: object(105)
written: object(104)

task 2 'run'. lines 24-24:
created: object(107)
written: object(106)

task 3 'view-object'. lines 26-26:
Owner: Immutable
Version: 1
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 4 'transfer-object'. lines 28-28:
Error: Transaction Effects Status: Invalid Transfer Object Transaction. Possibly not address-owned or possibly does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None } }

task 5 'view-object'. lines 30-30:
Owner: Immutable
Version: 1
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}
