processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-22:
created: object(106)
written: object(105)

task 2 'run'. lines 24-24:
created: object(108)
written: object(107)

task 3 'view-object'. lines 26-26:
Owner: Immutable
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}

task 4 'transfer-object'. lines 28-28:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue }, source: None, command: Some(0) } }

task 5 'view-object'. lines 30-30:
Owner: Immutable
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}
