processed 5 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 8-10:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3176800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 13-13:
1,0::m

task 3 'transfer-object'. lines 15-15:
Error: Error checking transaction input objects: MovePackageAsObject { object_id: 0xea71cafce0431a127076a7884cb66612bdc9bb2ff442c4d3afbbc73dbc18f660 }

task 4 'view-object'. lines 17-17:
1,0::m
