processed 5 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-10:
created: object(106)
written: object(105)

task 2 'view-object'. lines 13-13:
106::m

task 3 'transfer-object'. lines 15-15:
Error: Transaction Effects Status: Invalid Transfer Object Transaction. Possibly not address-owned or possibly does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None, command: None } }

task 4 'view-object'. lines 17-17:
106::m
