processed 7 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-27:
created: object(106)
written: object(105)

task 2 'run'. lines 29-29:
created: object(108)
written: object(107)

task 3 'run'. lines 31-31:
created: object(110), object(111)
written: object(108), object(109)

task 4 'view-object'. lines 33-33:
Owner: Object ID: ( fake(108) )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(111)}}

task 5 'transfer-object'. lines 35-35:
Error: Object 0xa674c5d5ea9b99cdfd28ba8fe8dcb35c70922afbc81d64a2b6b6afaee353578f is owned by object 0x1357b03c3a886f73d3868d2018c0ed739d8a55c8426e534d9c64fc9559ec0dc5. Objects owned by other objects cannot be used as input arguments.

task 6 'view-object'. lines 37-37:
Owner: Object ID: ( fake(108) )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(111)}}
