processed 7 tasks

init:
A: object(103), B: object(104)

task 1 'publish'. lines 8-27:
created: object(106)
mutated: object(105)

task 2 'run'. lines 29-29:
created: object(108)
mutated: object(107)

task 3 'run'. lines 31-31:
created: object(110), object(111)
mutated: object(108), object(109)

task 4 'view-object'. lines 33-33:
Owner: Object ID: ( fake(108) )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(111)}}

task 5 'transfer-object'. lines 35-35:
Error: Object 0xa768945bf1f4faf4d6ee9237d64a652875b6f650940c28ea8ca0774f82a2c948 is owned by object 0x93da53cf8adc59c6dd800f54b6ca7e3cb4c17d3dacf75eae21d61ec9354a55ff. Objects owned by other objects cannot be used as input arguments.

task 6 'view-object'. lines 37-37:
Owner: Object ID: ( fake(108) )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(110)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(111)}}
