processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-21:
created: object(105)
written: object(104)

task 2 'run'. lines 23-23:
created: object(107)
written: object(106)

task 3 'view-object'. lines 25-25:
Owner: Shared
Contents: test::m::S {info: sui::object::Info {id: sui::object::ID {bytes: fake(107)}, version: 1u64}}

task 4 'transfer-object'. lines 27-27:
Error: Transaction Effects Status: Invalid Transfer Object Transaction. Possibly not address-owned or possibly does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None } }

task 5 'view-object'. lines 29-29:
Owner: Shared
Contents: test::m::S {info: sui::object::Info {id: sui::object::ID {bytes: fake(107)}, version: 2u64}}
