processed 6 tasks

init:
A: object(100), B: object(101)

task 1 'publish'. lines 8-21:
created: object(106)
written: object(105)

task 2 'run'. lines 23-23:
created: object(108)
written: object(107)

task 3 'view-object'. lines 25-25:
Owner: Shared
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}

task 4 'transfer-object'. lines 27-27:
Error: Attempt to transfer object 0x745ea5d547883aa753c1f9ad61290dafd7a462cc162ae5ddf2ede94917e3bf49 that does not have public transfer. Object transfer must be done instead using a distinct Move function call.

task 5 'view-object'. lines 29-29:
Owner: Shared
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(108)}}}
