processed 4 tasks

init:
A: object(103), B: object(104)

task 1 'view-object'. lines 8-8:
Owner: Account Address ( A )
Version: 1
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(103)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 300000000000000u64}}

task 2 'transfer-object'. lines 10-10:
mutated: object(103), object(105)

task 3 'view-object'. lines 12-12:
Owner: Account Address ( B )
Version: 2
Contents: sui::coin::Coin<sui::sui::SUI> {id: sui::object::UID {id: sui::object::ID {bytes: fake(103)}}, balance: sui::balance::Balance<sui::sui::SUI> {value: 300000000000000u64}}
