processed 8 tasks

init:
A: object(103)

task 1 'publish'. lines 8-41:
created: object(105)
mutated: object(104)

task 2 'run'. lines 43-43:
created: object(107)
mutated: object(106)

task 3 'view-object'. lines 45-45:
Owner: Account Address ( A )
Version: 2
Contents: a::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}

task 4 'run'. lines 47-47:
created: object(109)
mutated: object(108)
wrapped: object(107)

task 5 'view-object'. lines 49-49:
Owner: Account Address ( A )
Version: 3
Contents: a::m::T {id: sui::object::UID {id: sui::object::ID {bytes: fake(109)}}, s: a::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}}

task 6 'run'. lines 51-51:
mutated: object(110)
unwrapped: object(107)
deleted: object(109)

task 7 'view-object'. lines 53-53:
Owner: Account Address ( A )
Version: 4
Contents: a::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(107)}}}
