processed 11 tasks

init:
C: object(0,0)

task 1 'create-checkpoint'. lines 8-8:
Checkpoint created: 1

task 2 'advance-epoch'. lines 10-10:
Epoch advanced: 0

task 3 'programmable'. lines 12-14:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 16-18:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [20, 171, 88, 59, 18, 151, 242, 229, 142, 36, 193, 119, 148, 28, 227, 11, 134, 170, 62, 215, 228, 54, 63, 18, 195, 205, 109, 79, 189, 189, 52, 35, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 5 'create-checkpoint'. lines 19-19:
Checkpoint created: 3

task 6 'advance-epoch'. lines 21-23:
Epoch advanced: 1

task 7 'programmable'. lines 24-28:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 29-29:
Checkpoint created: 5

task 9 'advance-epoch'. lines 31-32:
Epoch advanced: 2

task 10 'run-graphql'. lines 33-62:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "totalStake": "20000010002000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        },
        "validatorCandidatesSize": 0,
        "inactivePoolsId": "0xb729110f0024cf2afe694b505915eac3beb9910db7c502ece66ddfeefaa868ab"
      },
      "totalGasFees": "1000000",
      "totalStakeRewards": "1000000",
      "totalStakeSubsidies": "0",
      "fundSize": "15098160",
      "fundInflow": "1976000",
      "fundOutflow": "978120",
      "netInflow": "997880",
      "transactionBlocks": {
        "nodes": [
          {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            },
            "digest": "AAdVVPcgxTk9Jiqqdd5QFhP1HyUbaFjoenE7jB43gtGW"
          },
          {
            "kind": {
              "__typename": "EndOfEpochTransaction"
            },
            "digest": "FBQng23bTYgzLqYNj8jLwzGVvtsYLC9CZZ4hoMaWFZu2"
          }
        ]
      }
    }
  }
}
