processed 11 tasks

init:
C: object(0,0)

task 1 'create-checkpoint'. lines 8-8:
Checkpoint created: 1

task 2 'advance-epoch'. lines 10-10:
Epoch advanced: 0

task 3 'programmable'. lines 12-14:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 16-18:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [205, 194, 213, 73, 180, 73, 66, 247, 47, 26, 252, 245, 47, 78, 73, 151, 248, 107, 13, 176, 55, 9, 53, 252, 244, 197, 180, 96, 178, 157, 125, 125, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 5 'create-checkpoint'. lines 19-19:
Checkpoint created: 3

task 6 'advance-epoch'. lines 21-23:
Epoch advanced: 1

task 7 'programmable'. lines 24-28:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 29-29:
Checkpoint created: 5

task 9 'advance-epoch'. lines 31-32:
Epoch advanced: 2

task 10 'run-graphql'. lines 33-62:
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "totalStake": "20000010002000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        },
        "validatorCandidatesSize": 0,
        "inactivePoolsId": "0x31e0922de50b6ff1ab63f1cc3ce487c2ed28bf08559be3f288bdae6a99c2c2d2"
      },
      "totalGasFees": "1000000",
      "totalStakeRewards": "1000000",
      "totalStakeSubsidies": "0",
      "fundSize": "15098160",
      "fundInflow": "1976000",
      "fundOutflow": "978120",
      "netInflow": "997880",
      "transactionBlocks": {
        "nodes": [
          {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            },
            "digest": "BMUnsrAQPgqze3n4UBzjULPiw8wF48GXJ5sjYHynSqnA"
          },
          {
            "kind": {
              "__typename": "EndOfEpochTransaction"
            },
            "digest": "3iNPYEuuCFVfAKXTzxkfZqPPCmfs4fSLVZ6SukLfrZqn"
          }
        ]
      }
    }
  }
}
