processed 23 tasks

init:
C: object(0,0), validator_0: object(0,1)

task 1 'create-checkpoint'. lines 7-7:
Checkpoint created: 1

task 2 'advance-epoch'. lines 9-9:
Epoch advanced: 0

task 3 'programmable'. lines 11-13:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 15-15:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [114, 30, 247, 189, 168, 209, 171, 154, 241, 98, 233, 65, 28, 120, 226, 176, 43, 28, 109, 213, 204, 114, 40, 244, 54, 128, 202, 180, 113, 211, 86, 207, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 5 'create-checkpoint'. lines 17-17:
Checkpoint created: 3

task 6 'advance-epoch'. lines 19-19:
Epoch advanced: 1

task 7 'create-checkpoint'. lines 21-21:
Checkpoint created: 5

task 8 'advance-epoch'. lines 23-23:
Epoch advanced: 2

task 9 'programmable'. lines 25-27:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 29-29:
Checkpoint created: 7

task 11 'advance-epoch'. lines 31-31:
Epoch advanced: 3

task 12 'run'. lines 33-33:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("UnstakingRequestEvent"), type_params: [] }, contents: [114, 30, 247, 189, 168, 209, 171, 154, 241, 98, 233, 65, 28, 120, 226, 176, 43, 28, 109, 213, 204, 114, 40, 244, 54, 128, 202, 180, 113, 211, 86, 207, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 2, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
created: object(12,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 14774400,  storage_rebate: 14927616, non_refundable_storage_fee: 150784

task 13 'create-checkpoint'. lines 35-35:
Checkpoint created: 9

task 14 'advance-epoch'. lines 37-37:
Epoch advanced: 4

task 15 'programmable'. lines 39-41:
created: object(15,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 16 'create-checkpoint'. lines 43-43:
Checkpoint created: 11

task 17 'advance-epoch'. lines 45-45:
Epoch advanced: 5

task 18 'run-graphql'. lines 47-57:
Response: {
  "data": {
    "epoch": {
      "epochId": 4,
      "systemStateVersion": "2",
      "storageFund": {
        "totalObjectStorageRebates": "15762400",
        "nonRefundableBalance": "180424"
      }
    }
  }
}

task 19 'run-graphql'. lines 59-69:
Response: {
  "data": {
    "epoch": {
      "epochId": 3,
      "systemStateVersion": "2",
      "storageFund": {
        "totalObjectStorageRebates": "16066400",
        "nonRefundableBalance": "29640"
      }
    }
  }
}

task 20 'run-graphql'. lines 70-80:
Response: {
  "data": {
    "epoch": {
      "epochId": 2,
      "systemStateVersion": "2",
      "storageFund": {
        "totalObjectStorageRebates": "15078400",
        "nonRefundableBalance": "19760"
      }
    }
  }
}

task 21 'run-graphql'. lines 82-92:
Response: {
  "data": {
    "epoch": {
      "epochId": 1,
      "systemStateVersion": "2",
      "storageFund": {
        "totalObjectStorageRebates": "15078400",
        "nonRefundableBalance": "19760"
      }
    }
  }
}

task 22 'run-graphql'. lines 94-104:
Response: {
  "data": {
    "epoch": {
      "epochId": 4,
      "systemStateVersion": "2",
      "storageFund": {
        "totalObjectStorageRebates": "15762400",
        "nonRefundableBalance": "180424"
      }
    }
  }
}
