processed 23 tasks

init:
C: object(0,0), validator_0: object(0,1)

task 1 'create-checkpoint'. lines 10-10:
Checkpoint created: 1

task 2 'advance-epoch'. lines 12-12:
Epoch advanced: 0

task 3 'programmable'. lines 14-16:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 18-18:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [22, 54, 190, 32, 71, 100, 246, 236, 70, 118, 228, 155, 57, 192, 159, 217, 116, 164, 239, 124, 239, 63, 214, 193, 228, 128, 21, 217, 44, 112, 23, 192, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 5 'create-checkpoint'. lines 20-20:
Checkpoint created: 3

task 6 'advance-epoch'. lines 22-22:
Epoch advanced: 1

task 7 'create-checkpoint'. lines 24-24:
Checkpoint created: 5

task 8 'advance-epoch'. lines 26-26:
Epoch advanced: 2

task 9 'programmable'. lines 28-30:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 32-32:
Checkpoint created: 7

task 11 'advance-epoch'. lines 34-34:
Epoch advanced: 3

task 12 'run'. lines 36-36:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("UnstakingRequestEvent"), type_params: [] }, contents: [22, 54, 190, 32, 71, 100, 246, 236, 70, 118, 228, 155, 57, 192, 159, 217, 116, 164, 239, 124, 239, 63, 214, 193, 228, 128, 21, 217, 44, 112, 23, 192, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 2, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
created: object(12,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 14774400,  storage_rebate: 14927616, non_refundable_storage_fee: 150784

task 13 'create-checkpoint'. lines 38-38:
Checkpoint created: 9

task 14 'advance-epoch'. lines 40-40:
Epoch advanced: 4

task 15 'programmable'. lines 42-44:
created: object(15,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 16 'create-checkpoint'. lines 46-46:
Checkpoint created: 11

task 17 'advance-epoch'. lines 48-48:
Epoch advanced: 5

task 18 'run-graphql'. lines 50-60:
Response: {
  "data": {
    "epoch": {
      "epochId": 4,
      "systemStateVersion": 2,
      "storageFund": {
        "totalObjectStorageRebates": "15762400",
        "nonRefundableBalance": "180424"
      }
    }
  }
}

task 19 'run-graphql'. lines 62-72:
Response: {
  "data": {
    "epoch": {
      "epochId": 3,
      "systemStateVersion": 2,
      "storageFund": {
        "totalObjectStorageRebates": "16066400",
        "nonRefundableBalance": "29640"
      }
    }
  }
}

task 20 'run-graphql'. lines 74-84:
Response: {
  "data": {
    "epoch": {
      "epochId": 2,
      "systemStateVersion": 2,
      "storageFund": {
        "totalObjectStorageRebates": "15078400",
        "nonRefundableBalance": "19760"
      }
    }
  }
}

task 21 'run-graphql'. lines 86-96:
Response: {
  "data": {
    "epoch": {
      "epochId": 1,
      "systemStateVersion": 2,
      "storageFund": {
        "totalObjectStorageRebates": "15078400",
        "nonRefundableBalance": "19760"
      }
    }
  }
}

task 22 'run-graphql'. lines 98-108:
Response: {
  "data": {
    "epoch": {
      "epochId": 4,
      "systemStateVersion": 2,
      "storageFund": {
        "totalObjectStorageRebates": "15762400",
        "nonRefundableBalance": "180424"
      }
    }
  }
}
