processed 2 tasks

task 0 'run'. lines 1-13:
Error: Function execution failed with VMError: {
    major_status: VECTOR_OPERATION_ERROR,
    sub_status: Some(2),
    location: 0x1::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 1 'run'. lines 14-27:
Error: Function execution failed with VMError: {
    major_status: VECTOR_OPERATION_ERROR,
    sub_status: Some(2),
    location: 0x2::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 7)],
}
