processed 3 tasks

task 0 'run'. lines 1-13:
Error: Function execution failed with VMError: {
    major_status: VECTOR_OPERATION_ERROR,
    sub_status: Some(3),
    location: 0x1::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}

task 1 'run'. lines 14-26:
Error: Function execution failed with VMError: {
    major_status: VECTOR_OPERATION_ERROR,
    sub_status: Some(3),
    location: 0x2::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 5)],
}

task 2 'run'. lines 27-40:
Error: Function execution failed with VMError: {
    major_status: VECTOR_OPERATION_ERROR,
    sub_status: Some(3),
    location: 0x3::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 7)],
}
