processed 8 tasks

task 1 'publish'. lines 6-21:
created: object(103)
written: object(102)

task 2 'publish'. lines 23-52:
created: object(105)
written: object(104)

task 3 'publish'. lines 55-82:
created: object(107)
written: object(106)

task 4 'run'. lines 84-84:
created: object(109)
written: object(108)

task 5 'run'. lines 86-88:
created: object(111)
written: object(109), object(110)

task 6 'run'. lines 89-89:
Error: Transaction Effects Status: Invalid Shared Child Object Usage. When a child object (either direct or indirect) of a shared object is passed by-value to an entry function, either the child object's type or the shared object's type must be defined in the same module as the called function. This is violated by object fake(109), whose ancestor fake(111) is a shared object, and neither are defined in this module..
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidSharedChildUse(InvalidSharedChildUse { child: fake(109), ancestor: fake(111) }), source: Some("When a child object (either direct or indirect) of a shared object is passed by-value to an entry function, either the child object's type or the shared object's type must be defined in the same module as the called function. This is violated by object fake(109) (defined in module 'T3::O3'), whose ancestor fake(111) is a shared object (defined in module 'T2::O2'), and neither are defined in this module 'T1::O1'") } }

task 7 'run'. lines 91-91:
written: object(109), object(111), object(113)
