processed 8 tasks

task 1 'publish'. lines 6-21:
created: object(103)
written: object(102)

task 2 'publish'. lines 23-52:
created: object(105)
written: object(104)

task 3 'publish'. lines 55-82:
created: object(107)
written: object(106)

task 4 'run'. lines 84-84:
created: object(109)
written: object(108)

task 5 'run'. lines 86-88:
created: object(111), object(112)
written: object(109), object(110)

task 6 'run'. lines 89-89:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type t2::o2::Obj2, but found type sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID>") } }

task 7 'run'. lines 91-91:
Error: Transaction Effects Status: Entry Argument Type Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Expected argument of type t2::o2::Obj2, but found type sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID>") } }
