error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_store.move:9:9
   │
 8 │     public fun t1(s: other::S) {
   │                      -------- The type 'a::other::S' is not declared in the current module
 9 │         transfer::transfer(s, @0x100);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::transfer' is restricted to being called in the object's module, 'a::other'
   ·
22 │     struct S has key, store {
   │                       ----- The object has 'store' so 'sui::transfer::public_transfer' can be called instead

error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_store.move:13:9
   │
12 │     public fun t2(s: other::S) {
   │                      -------- The type 'a::other::S' is not declared in the current module
13 │         transfer::freeze_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::freeze_object' is restricted to being called in the object's module, 'a::other'
   ·
22 │     struct S has key, store {
   │                       ----- The object has 'store' so 'sui::transfer::public_freeze_object' can be called instead

error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_store.move:17:9
   │
16 │     public fun t3(s: other::S) {
   │                      -------- The type 'a::other::S' is not declared in the current module
17 │         transfer::share_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::share_object' is restricted to being called in the object's module, 'a::other'
   ·
22 │     struct S has key, store {
   │                       ----- The object has 'store' so 'sui::transfer::public_share_object' can be called instead

