error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_store_generic.move:10:9
   │
 9 │     public fun t1<T: key + store>(s: T) {
   │                            -----     - The type 'T' is not declared in the current module
   │                            │          
   │                            The object has 'store' so 'sui::transfer::public_transfer' can be called instead
10 │         transfer::transfer(s, @0x100);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::transfer' is restricted to being called in the object's module

error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_store_generic.move:14:9
   │
13 │     public fun t2<T: key + store>(s: T) {
   │                            -----     - The type 'T' is not declared in the current module
   │                            │          
   │                            The object has 'store' so 'sui::transfer::public_freeze_object' can be called instead
14 │         transfer::freeze_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::freeze_object' is restricted to being called in the object's module

error[Sui E02009]: invalid private transfer call
   ┌─ tests/sui_mode/private_generics/no_public_transfer_store_generic.move:18:9
   │
17 │     public fun t3<T: key + store>(s: T) {
   │                            -----     - The type 'T' is not declared in the current module
   │                            │          
   │                            The object has 'store' so 'sui::transfer::public_share_object' can be called instead
18 │         transfer::share_object(s);
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid private transfer. The function 'sui::transfer::share_object' is restricted to being called in the object's module

