processed 3 tasks

task 0 'run'. lines 1-8:
Error: Function execution failed with VMError: {
    major_status: NUMBER_OF_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}

task 1 'run'. lines 10-17:
Error: Function execution failed with VMError: {
    major_status: NUMBER_OF_ARGUMENTS_MISMATCH,
    sub_status: None,
    location: undefined,
    indices: [],
    offsets: [],
}
