processed 6 tasks

init:
A: object(100)

task 1 'publish'. lines 6-28:
created: object(105)
written: object(104)

task 2 'run'. lines 30-33:
written: object(106)

task 3 'run'. lines 35-38:
written: object(107)

task 4 'run'. lines 40-48:
written: object(108)

task 5 'run'. lines 50-50:
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: Some("Function expects std::ascii::String but provided argument's value does not match"), command: Some(0) } }
