processed 6 tasks

init:
A: object(100)

task 1 'publish'. lines 6-27:
created: object(104)
written: object(103)

task 2 'run'. lines 29-32:
written: object(105)

task 3 'run'. lines 34-37:
written: object(106)

task 4 'run'. lines 39-47:
written: object(107)

task 5 'run'. lines 49-49:
Error: Transaction Effects Status: Entry Argument Error. Error for argument at index 0: Type mismatch.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: EntryArgumentError(EntryArgumentError { argument_idx: 0, kind: TypeMismatch }), source: Some("Unexpected non-ASCII value (outside of ASCII character range) in argument 0") } }
