processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-11:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: &T0\"), command: None } }" }

task 2 'publish'. lines 13-16:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: &mut T0\"), command: None } }" }

task 3 'publish'. lines 18-21:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: &T0\"), command: None } }" }

task 4 'publish'. lines 23-26:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"Invalid entry point parameter type. Expected primitive or object type. Got: &mut T0\"), command: None } }" }
