processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-15:
created: object(1,0)
mutated: object(0,1)

task 2 'run'. lines 17-17:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: test, name: Identifier(\"x\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(0) } }

task 3 'run'. lines 19-19:
Error: Transaction Effects Status: Error for type argument at index 0: A type was not found in the module specified.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: TypeArgumentError { argument_idx: 0, kind: TypeNotFound }, source: None, command: Some(0) } }

task 4 'run'. lines 21-21:
Error: Transaction Effects Status: Type arity mismatch for Move function. Mismatch between the number of actual versus expected type arguments.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: TypeArityMismatch, source: None, command: Some(0) } }

task 5 'run'. lines 23-23:
Error: Transaction Effects Status: Type arity mismatch for Move function. Mismatch between the number of actual versus expected type arguments.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: TypeArityMismatch, source: None, command: Some(0) } }

task 6 'run'. lines 25-25:
Error: Transaction Effects Status: Error for type argument at index 0: A type provided did not match the specified constraints.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: TypeArgumentError { argument_idx: 0, kind: ConstraintNotSatisfied }, source: None, command: Some(0) } }
