processed 6 tasks

task 1 'publish'. lines 8-28:
created: object(1,0)
mutated: object(0,0)

task 2 'run'. lines 30-30:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Can only call `entry` or `public` functions"), command: Some(0) } }

task 3 'run'. lines 32-32:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Can only call `entry` or `public` functions"), command: Some(0) } }

task 4 'run'. lines 34-34:
Error: Transaction Effects Status: Invalid public Move function signature. Unsupported return type for return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidPublicFunctionReturnType { idx: 0 }, source: None, command: Some(0) } }

task 5 'run'. lines 36-36:
Error: Transaction Effects Status: Invalid public Move function signature. Unsupported return type for return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidPublicFunctionReturnType { idx: 0 }, source: None, command: Some(0) } }
