processed 5 tasks

task 1 'publish'. lines 8-24:
created: object(103)
written: object(102)

task 2 'run'. lines 26-26:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidNonEntryFunction, source: Some("Can only call `entry` functions") } }

task 3 'run'. lines 28-28:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidNonEntryFunction, source: Some("Can only call `entry` functions") } }

task 4 'run'. lines 30-30:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidNonEntryFunction, source: Some("Can only call `entry` functions") } }
