error[Sui E02007]: invalid object declaration
  ┌─ tests/sui_mode/struct_with_key/key_struct_second_field_id.move:6:9
  │
5 │     struct S has key {
  │                  --- The 'key' ability is used to declare objects in Sui
6 │         flag: bool,
  │         ^^^^ Invalid object 'S'. Structs with the 'key' ability must have 'id: sui::object::UID' as their first field

error[Sui E02007]: invalid object declaration
   ┌─ tests/sui_mode/struct_with_key/key_struct_second_field_id.move:11:9
   │
10 │     struct R has key {
   │                  --- The 'key' ability is used to declare objects in Sui
11 │         flag: bool,
   │         ^^^^ Invalid object 'R'. Structs with the 'key' ability must have 'id: sui::object::UID' as their first field

error[Sui E02007]: invalid object declaration
   ┌─ tests/sui_mode/struct_with_key/key_struct_second_field_id.move:12:9
   │
10 │     struct R has key {
   │                  --- The 'key' ability is used to declare objects in Sui
11 │         flag: bool,
12 │         id: address,
   │         ^^  ------- But found type: 'address'
   │         │    
   │         Invalid object. Expected the 'id' field to have type 'sui::object::UID'

