error[Sui E02007]: invalid object declaration
  ┌─ tests/sui_mode/struct_with_key/key_struct_id_field_incorrect_type.move:4:9
  │
3 │     struct S has key {
  │                  --- The 'key' ability is used to declare objects in Sui
4 │         id: bool
  │         ^^  ---- But found type: 'bool'
  │         │    
  │         Invalid object. Expected the 'id' field to have type 'sui::object::UID'

