error[Sui E02007]: invalid object declaration
  ┌─ tests/sui_mode/struct_with_key/key_struct_id_field_incorrect_struct_name.move:5:9
  │
4 │     struct S has key {
  │                  --- The 'key' ability is used to declare objects in Sui
5 │         id: object::ID
  │         ^^  ---------- But found type: '(sui=0x2)::object::ID'
  │         │    
  │         Invalid object. Expected the 'id' field to have type 'sui::object::UID'

