processed 9 tasks

task 1 'run'. lines 19-26:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x1::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 2 'run'. lines 28-35:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x2::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 3 'run'. lines 37-44:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x3::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 4 'run'. lines 46-53:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x4::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 5 'run'. lines 55-62:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x5::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 6 'run'. lines 64-71:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x6::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 7 'run'. lines 73-80:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x7::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 8 'run'. lines 82-89:
Error: Function execution failed with VMError: {
    major_status: ABORTED,
    sub_status: Some(0),
    location: 0x8::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}
