processed 5 tasks

task 0 'publish'. lines 1-13:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::M'. Got VMError: {
    major_status: INVALID_SIGNATURE_TOKEN,
    sub_status: None,
    location: 0x1::M,
    indices: [],
    offsets: [],
}

task 1 'publish'. lines 15-29:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::M'. Got VMError: {
    major_status: INVALID_SIGNATURE_TOKEN,
    sub_status: None,
    location: 0x1::M,
    indices: [(Signature, 2), (FunctionDefinition, 0)],
    offsets: [],
}

task 2 'publish'. lines 31-43:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::M'. Got VMError: {
    major_status: INVALID_SIGNATURE_TOKEN,
    sub_status: None,
    location: 0x1::M,
    indices: [(Signature, 2), (FunctionDefinition, 0)],
    offsets: [],
}

task 3 'publish'. lines 45-54:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::M'. Got VMError: {
    major_status: INVALID_SIGNATURE_TOKEN,
    sub_status: None,
    location: 0x1::M,
    indices: [],
    offsets: [],
}

task 4 'publish'. lines 56-65:
Error: Unable to publish module '0000000000000000000000000000000000000000000000000000000000000001::M'. Got VMError: {
    major_status: INVALID_SIGNATURE_TOKEN,
    sub_status: None,
    location: 0x1::M,
    indices: [],
    offsets: [],
}
