processed 4 tasks

init:
A: object(0,0)

task 1 'programmable'. lines 7-9:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 11-11:
Checkpoint created: 1

task 3 'run-graphql'. lines 13-22:
Response: {
  "data": {
    "sender": {
      "asObject": null
    },
    "coin": {
      "asObject": {
        "digest": "7ZZ3AJ2m7exxq7qNLvPBVy3kTevhKQeGZippu5UtRokQ"
      }
    }
  }
}
