processed 17 tasks

init:
A: object(0,0)

task 1, lines 6-86:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 10586800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 88-89:
//# run P0::M::new_o
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2264800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3, lines 91-92:
//# run P0::M::new_w
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2257200,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4, lines 94-95:
//# run P0::M::new_dof
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5, lines 97-98:
//# run P0::M::new_dof
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6, lines 101-104:
//# run P0::M::connect --args object(2,0) object(3,0) object(4,0) object(5,0)
created: object(6,0), object(6,1)
mutated: object(0,1), object(2,0), object(4,0), object(5,0)
wrapped: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 9940800,  storage_rebate: 6041772, non_refundable_storage_fee: 61028

task 7, lines 106-108:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 7
Contents: P0::M::O {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: sui::object::UID {
                    id: sui::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 0u64,
            },
        ],
    },
}

task 8, lines 110-111:
//# run P0::M::touch_root --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2568800,  storage_rebate: 2543112, non_refundable_storage_fee: 25688

task 9, lines 113-114:
//# run P0::M::touch_wrapped --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2568800,  storage_rebate: 2543112, non_refundable_storage_fee: 25688

task 10, lines 116-117:
//# run P0::M::touch_inner --args object(2,0)
mutated: object(0,1), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 3853200,  storage_rebate: 3814668, non_refundable_storage_fee: 38532

task 11, lines 119-120:
//# run P0::M::touch_outer --args object(2,0)
mutated: object(0,1), object(2,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3853200,  storage_rebate: 3814668, non_refundable_storage_fee: 38532

task 12, line 122:
//# view-object 2,0
Owner: Account Address ( _ )
Version: 11
Contents: P0::M::O {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: sui::object::UID {
                    id: sui::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 1u64,
            },
        ],
    },
}

task 13, line 124:
//# create-checkpoint
Checkpoint created: 1

task 14, lines 126-141:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "asObject": {
        "asMoveObject": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0x90dc651cc4aef34057af8c944f0ab8a0150295ad088edd4407a1bd4c225e18b8",
              "count": "1",
              "wrapped": {
                "id": "0x3330add01caca066f647d3a3df92917d0191ba9b9aaaa8d2da4d726bb3c330cf",
                "count": "1"
              }
            }
          }
        }
      }
    },
    "versioned": {
      "asObject": {
        "asMoveObject": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0x90dc651cc4aef34057af8c944f0ab8a0150295ad088edd4407a1bd4c225e18b8",
              "count": "1",
              "wrapped": {
                "id": "0x3330add01caca066f647d3a3df92917d0191ba9b9aaaa8d2da4d726bb3c330cf",
                "count": "1"
              }
            }
          }
        }
      }
    },
    "beforeWrappedBump": {
      "asObject": {
        "asMoveObject": {
          "version": 8,
          "contents": {
            "json": {
              "id": "0x90dc651cc4aef34057af8c944f0ab8a0150295ad088edd4407a1bd4c225e18b8",
              "count": "1",
              "wrapped": {
                "id": "0x3330add01caca066f647d3a3df92917d0191ba9b9aaaa8d2da4d726bb3c330cf",
                "count": "0"
              }
            }
          }
        }
      }
    },
    "beforeBump": {
      "asObject": {
        "asMoveObject": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x90dc651cc4aef34057af8c944f0ab8a0150295ad088edd4407a1bd4c225e18b8",
              "count": "0",
              "wrapped": {
                "id": "0x3330add01caca066f647d3a3df92917d0191ba9b9aaaa8d2da4d726bb3c330cf",
                "count": "0"
              }
            }
          }
        }
      }
    }
  }
}

task 15, lines 143-171:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xd38f2f2e8c369c5ec08b8852fac5834c2bcc25308f0205763528364354dc0369",
              "count": "0"
            }
          }
        }
      }
    },
    "latest": {
      "dynamicObjectField": {
        "value": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0xd38f2f2e8c369c5ec08b8852fac5834c2bcc25308f0205763528364354dc0369",
              "count": "1"
            }
          }
        }
      }
    },
    "afterFirstInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0xd38f2f2e8c369c5ec08b8852fac5834c2bcc25308f0205763528364354dc0369",
              "count": "1"
            }
          }
        }
      }
    },
    "beforeFirstInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xd38f2f2e8c369c5ec08b8852fac5834c2bcc25308f0205763528364354dc0369",
              "count": "0"
            }
          }
        }
      }
    },
    "beforeBumps": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xd38f2f2e8c369c5ec08b8852fac5834c2bcc25308f0205763528364354dc0369",
              "count": "0"
            }
          }
        }
      }
    }
  }
}

task 16, lines 173-194:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xab491044d75a8be613bd6fdc2215a0847c740b8774bc6feb9188f4b7233a37d5",
              "count": "0"
            }
          }
        }
      }
    },
    "latest": {
      "dynamicObjectField": {
        "value": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0xab491044d75a8be613bd6fdc2215a0847c740b8774bc6feb9188f4b7233a37d5",
              "count": "1"
            }
          }
        }
      }
    },
    "beforeInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xab491044d75a8be613bd6fdc2215a0847c740b8774bc6feb9188f4b7233a37d5",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
