processed 2 tasks

task 0 'publish'. lines 4-20:
Error: Failed to verify the Move module, reason: "Access to Move global storage is not allowed. Found in function no: [MoveFrom(StructDefinitionIndex(0))]".

task 1 'publish'. lines 22-38:
Error: Failed to verify the Move module, reason: "Access to Move global storage is not allowed. Found in function no: [MoveFromGeneric(StructDefInstantiationIndex(0))]".
