// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct ErrorLog {
    pub id: i64,
    pub error_type: String,
    pub error: String,
    pub error_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct EventLog {
    pub id: i32,
    pub next_cursor_tx_seq: Option<i64>,
    pub next_cursor_event_seq: Option<i64>,
}

#[derive(Queryable, Debug)]
pub struct Event {
    pub id: i64,
    pub transaction_digest: Option<String>,
    pub transaction_sequence: i64,
    pub event_sequence: i64,
    pub event_time: Option<NaiveDateTime>,
    pub event_type: String,
    pub event_content: String,
}

#[derive(Queryable, Debug)]
pub struct TransactionLog {
    pub id: i32,
    pub next_cursor_tx_digest: Option<String>,
}

#[derive(Queryable, Debug)]
pub struct Transaction {
    pub id: i64,
    pub transaction_digest: String,
    pub sender: String,
    pub transaction_time: Option<NaiveDateTime>,
    pub transaction_kinds: Option<Vec<String>>,
    pub created: Option<Vec<String>>,
    pub mutated: Option<Vec<String>>,
    pub deleted: Option<Vec<String>>,
    pub unwrapped: Option<Vec<String>>,
    pub wrapped: Option<Vec<String>>,
    pub gas_object_id: String,
    pub gas_object_sequence: i64,
    pub gas_object_digest: String,
    pub gas_budget: i64,
    pub total_gas_cost: i64,
    pub computation_cost: i64,
    pub storage_cost: i64,
    pub storage_rebate: i64,
}

