warning[W00001]: DEPRECATED. will be removed
  ┌─ tests/move_check/expansion/use_spec_schema.move:3:5
  │  
3 │ ╭     spec schema Foo<T> {
4 │ │         ensures true;
5 │ │     }
  │ ╰─────^ Specification blocks are deprecated

warning[W00001]: DEPRECATED. will be removed
  ┌─ tests/move_check/expansion/use_spec_schema.move:7:5
  │  
7 │ ╭     spec schema Bar<T> {
8 │ │         ensures true;
9 │ │     }
  │ ╰─────^ Specification blocks are deprecated

warning[W09001]: unused alias
   ┌─ tests/move_check/expansion/use_spec_schema.move:13:18
   │
13 │     use 0x2::X::{Foo, Bar as Baz};
   │                  ^^^ Unused 'use' of alias 'Foo'. Consider removing it
   │
   = This warning can be suppressed with '#[allow(unused_use)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W09001]: unused alias
   ┌─ tests/move_check/expansion/use_spec_schema.move:13:30
   │
13 │     use 0x2::X::{Foo, Bar as Baz};
   │                              ^^^ Unused 'use' of alias 'Baz'. Consider removing it
   │
   = This warning can be suppressed with '#[allow(unused_use)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W00001]: DEPRECATED. will be removed
   ┌─ tests/move_check/expansion/use_spec_schema.move:18:5
   │  
18 │ ╭     spec t {
19 │ │         apply Foo<S> to t;
20 │ │         apply Baz<S> to t;
21 │ │     }
   │ ╰─────^ Specification blocks are deprecated

