processed 2 tasks

task 1 'publish'. lines 8-20:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"one-time witness type candidate 0000000000000000000000000000000000000000000000000000000000000000::m::M must have a single ability: drop\"), command: None } }" }
