processed 2 tasks

task 1 'publish'. lines 8-15:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"init function of a module containing one-time witness type candidate must have 0000000000000000000000000000000000000000000000000000000000000000::m::M as the first parameter (a struct which has no fields or a single field of type bool)\"), command: None } }" }
