processed 14 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-18:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7166800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 21-33:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 7166800,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 3 'publish'. lines 36-47:
created: object(3,0), object(3,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6908400,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'upgrade'. lines 49-60:
created: object(4,0)
mutated: object(0,0), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 6908400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'upgrade'. lines 62-73:
created: object(5,0)
mutated: object(0,0), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 6908400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 6 'run'. lines 76-76:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2325600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7 'view-object'. lines 78-80:
Owner: Shared
Version: 2
Contents: Test_DepV1::DepM1::DepObj {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}, v: 42u64}

task 8 'programmable'. lines 81-83:
mutated: object(0,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2325600,  storage_rebate: 2302344, non_refundable_storage_fee: 23256

task 9 'view-object'. lines 85-88:
Owner: Shared
Version: 7
Contents: Test_DepV1::DepM1::DepObj {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}, v: 39u64}

task 10 'programmable'. lines 89-91:
mutated: object(0,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2325600,  storage_rebate: 2302344, non_refundable_storage_fee: 23256

task 11 'view-object'. lines 93-96:
Owner: Shared
Version: 8
Contents: Test_DepV1::DepM1::DepObj {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}, v: 37u64}

task 12 'programmable'. lines 97-99:
mutated: object(0,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2325600,  storage_rebate: 2302344, non_refundable_storage_fee: 23256

task 13 'view-object'. lines 101-101:
Owner: Shared
Version: 9
Contents: Test_DepV1::DepM1::DepObj {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}, v: 34u64}
