processed 10 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-9:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5038800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 11-14:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5054000,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 3 'upgrade'. lines 16-19:
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 4 'upgrade'. lines 21-24:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'upgrade'. lines 26-29:
created: object(5,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 6 'upgrade'. lines 31-33:
created: object(6,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 4856400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 7 'upgrade'. lines 35-38:
created: object(7,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 8 'upgrade'. lines 40-43:
created: object(8,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 5122400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 9 'upgrade'. lines 45-48:
Error: Transaction Effects Status: Invalid package upgrade. New package is incompatible with previous version
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: IncompatibleUpgrade }, source: Some(PartialVMError { major_status: BACKWARD_INCOMPATIBLE_MODULE_UPDATE, sub_status: None, message: None, exec_state: None, indices: [], offsets: [] }), command: Some(1) } }
