erlang_application(
    name = "buck2_shell_utils",
    srcs = glob(["src/*.erl"]),
    applications = [
        "kernel",
        "stdlib",
    ],
    erl_opts = [
        "+debug_info",
        "+warnings_as_errors",
    ],
    included_applications = [
        "prelude//erlang/common_test/test_exec:test_exec",
        "prelude//erlang/toolchain:resources[jsone]",
    ],
    shell_libs = [],
    visibility = ["PUBLIC"],
)
