Command `build -v -p ./C`:
BUILDING Foo
External Command `mv ./C/sources/Foo.move ./C/sources/Foo.move_old`:
External Command `rm -rf ./C/build/Foo/sources`:
Command `build -v -p ./B`:
INCLUDING DEPENDENCY Foo
BUILDING Bar
Error: Unable to deserialize module at '/private/var/folders/gw/732jkstx1j3fxgsqnlxg35c80000gn/T/.tmpDkeDrJ/0/1/C/build/Foo/bytecode_modules/Foo.mv': PartialVMError with status BAD_MAGIC
External Command `mv ./B/sources/Bar.move ./C/sources/Bar.move_old`:
External Command `rm -rf ./B/build/Bar/sources`:
Command `build -v`:
INCLUDING DEPENDENCY Bar
INCLUDING DEPENDENCY Foo
BUILDING A
Error: Unable to deserialize module at '/private/var/folders/gw/732jkstx1j3fxgsqnlxg35c80000gn/T/.tmpDkeDrJ/0/1/C/build/Foo/bytecode_modules/Foo.mv': PartialVMError with status BAD_MAGIC
