warning[W09002]: unused variable
   ┌─ tests/linter/move_2024/unneeded_return_okay.move:12:9
   │
12 │     let y = &mut x;
   │         ^ Unused local variable 'y'. Consider removing or prefixing with an underscore: '_y'
   │
   = This warning can be suppressed with '#[allow(unused_variable)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

error[E04007]: incompatible types
   ┌─ tests/linter/move_2024/unneeded_return_okay.move:13:14
   │
11 │     let mut x = 0;
   │         ----- Given: integer
12 │     let y = &mut x;
13 │     return (*x = 1)
   │              ^
   │              │
   │              Invalid mutation. Expected a mutable reference
   │              Expected: '&mut _'

error[E04007]: incompatible types
   ┌─ tests/linter/move_2024/unneeded_return_okay.move:16:12
   │
16 │ fun t3() { 'a: { return { return 'a 0 } } }
   │     --     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │     │      │
   │     │      Invalid return expression
   │     │      Given: integer
   │     Expected: '()'

error[E04014]: invalid loop control
   ┌─ tests/linter/move_2024/unneeded_return_okay.move:18:19
   │
18 │ fun t4() { return continue }
   │                   ^^^^^^^^ Invalid usage of 'continue'. 'continue' can only be used inside a loop body or lambda

error[E04014]: invalid loop control
   ┌─ tests/linter/move_2024/unneeded_return_okay.move:20:19
   │
20 │ fun t5() { return break }
   │                   ^^^^^ Invalid usage of 'break'. 'break' can only be used inside a loop body or lambda

error[E04014]: invalid loop control
   ┌─ tests/linter/move_2024/unneeded_return_okay.move:22:20
   │
22 │ fun t6() { return (break + 5) }
   │                    ^^^^^ Invalid usage of 'break'. 'break' can only be used inside a loop body or lambda

error[E03005]: unbound unscoped name
   ┌─ tests/linter/move_2024/unneeded_return_okay.move:24:19
   │
24 │ fun t7() { return unnamed_fun() }
   │                   ^^^^^^^^^^^ Unbound function 'unnamed_fun' in current scope

