processed 8 tasks

task 1 'publish'. lines 8-11:
created: object(103)
written: object(102)

task 2 'publish'. lines 13-18:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("_::m::t. Invalid call to 'sui::transfer::transfer' on an object of type 'a::m::S'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }

task 3 'publish'. lines 20-29:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("_::m::t. Invalid call to 'sui::transfer::transfer_to_object_id' on an object of type 'a::m::S'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }

task 4 'publish'. lines 31-36:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("_::m::t. Invalid call to 'sui::transfer::freeze_object' on an object of type 'a::m::S'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }

task 5 'publish'. lines 38-43:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("_::m::t. Invalid call to 'sui::transfer::share_object' on an object of type 'a::m::S'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }

task 6 'publish'. lines 45-51:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("_::m::t. Invalid call to 'sui::transfer::transfer_to_object' on an object of type 'a::m::S'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }

task 7 'publish'. lines 53-59:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("_::m::t. Invalid call to 'sui::transfer::transfer_to_object' on an object of type 'a::m::S'. The transferred object's type must be defined in the current module, or must have the 'store' type ability") } }
