processed 3 tasks

task 0 'publish'. lines 7-17:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4461200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 19-29:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4187600,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 2 'publish'. lines 31-41:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4180000,  storage_rebate: 978120, non_refundable_storage_fee: 9880
