processed 17 tasks

task 1, lines 20-29:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x2::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2, lines 30-39:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x3::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 4, lines 60-69:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x5::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 5, lines 70-79:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x42::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 7, lines 98-107:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x7::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 8, lines 108-117:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x8::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 10, lines 138-147:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x10::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 11, lines 148-157:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x11::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 12, lines 158-167:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x12::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 14, lines 188-197:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x14::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 15, lines 198-207:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x15::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 16, lines 208-217:
//# run
Error: Function execution failed with VMError: {
    major_status: ARITHMETIC_ERROR,
    sub_status: None,
    location: 0x16::m,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}
