// Auto-generated by Move decompiler

module 370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft;

// -- structs -- 

public struct CatNFT
has key, store {
    id: 0x2::object::UID,
    name: 0x1::string::String,
    description: 0x1::string::String,
    url: 0x2::url::Url,
}

public struct CAT_NFT has drop { dummy_field: bool }

public struct NFTMinted has copy, drop { object_id: 0x2::object::ID, creator: address, name: 0x1::string::String }

// -- constants -- 

const C0: u64 = 50000u64;

const C1: u64 = 0u64;

const C2: vector<u8> = vec![110u8, 97u8, 109u8, 101u8];

const C3: vector<u8> = vec![105u8, 109u8, 97u8, 103u8, 101u8, 95u8, 117u8, 114u8, 108u8];

const C4: vector<u8> = vec![100u8, 101u8, 115u8, 99u8, 114u8, 105u8, 112u8, 116u8, 105u8, 111u8, 110u8];

const C5: vector<u8> = vec![112u8, 114u8, 111u8, 106u8, 101u8, 99u8, 116u8, 95u8, 117u8, 114u8, 108u8];

const C6: vector<u8> = vec![99u8, 114u8, 101u8, 97u8, 116u8, 111u8, 114u8];

const C7: vector<u8> = vec![123u8, 110u8, 97u8, 109u8, 101u8, 125u8];

const C8: vector<u8> = vec![123u8, 117u8, 114u8, 108u8, 125u8];

const C9: vector<u8> = vec![123u8, 100u8, 101u8, 115u8, 99u8, 114u8, 105u8, 112u8, 116u8, 105u8, 111u8, 110u8, 125u8];

const C10: vector<u8> = vec![104u8, 116u8, 116u8, 112u8, 115u8, 58u8, 47u8, 47u8];

const C11: vector<u8> = vec![99u8, 97u8, 116u8];

// -- functions -- 

public entry fun burn(l0: 0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT, l1: &mut 0x2::tx_context::TxContext) {
    {
        0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT { id: reg_1, name: reg_2, description: reg_3, url: reg_4 } = l0;
        0x2::object::delete(reg_1 : 0x2::object::UID);
        return
    }
}

public fun description(l0: &0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT): &0x1::string::String {
    return &l0.description
}

fun init(l0: 0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CAT_NFT, l1: &mut 0x2::tx_context::TxContext) {
    {
        let l3 = vec![0x1::string::utf8(C2), 0x1::string::utf8(C3), 0x1::string::utf8(C4), 0x1::string::utf8(C5), 0x1::string::utf8(C6)];
        let l5 = vec![0x1::string::utf8(C7), 0x1::string::utf8(C8), 0x1::string::utf8(C9), 0x1::string::utf8(C10), 0x1::string::utf8(C11)];
        let l4 = 0x2::package::claim(l0, l1);
        let l2 = 0x2::display::new_with_fields(&l4, l3, l5, l1);
        0x2::display::update_version(&mut l2);
        0x2::transfer::public_transfer(l4, 0x2::tx_context::sender(freeze(l1)));
        0x2::transfer::public_transfer(l2, 0x2::tx_context::sender(freeze(l1)));
        return
    }
}

public fun mint(l0: vector<u8>, l1: vector<u8>, l2: vector<u8>, l3: &mut 0x2::tx_context::TxContext): 0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT {
    {
        let l5 = 0x2::tx_context::sender(freeze(l3));
        let l4 = CatNFT { id: 0x2::object::new(l3), name: 0x1::string::utf8(l0), description: 0x1::string::utf8(l1), url: 0x2::url::new_unsafe_from_bytes(l2) };
        0x2::event::emit(NFTMinted { object_id: 0x2::object::id(&l4), creator: l5, name: *(&(&l4).name) });
        return l4
    }
}

public entry fun mint_to_cat(l0: vector<u8>, l1: vector<u8>, l2: vector<u8>, l3: address, l4: &mut 0x2::tx_context::TxContext) {
    {
        0x2::transfer::public_transfer(0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::mint(l0, l1, l2, l4), l3);
        return
    }
}

public fun name(l0: &0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT): &0x1::string::String {
    return &l0.name
}

public entry fun transfer(l0: 0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT, l1: address, l2: &mut 0x2::tx_context::TxContext) {
    {
        0x2::transfer::public_transfer(l0, l1);
        return
    }
}

public entry fun update_description(l0: &mut 0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT, l1: vector<u8>, l2: &mut 0x2::tx_context::TxContext) {
    {
        *(&mut l0.description) = 0x1::string::utf8(l1);
        return
    }
}

public fun url(l0: &0x370092bfce3c986971f00a4f54bc2a6cc98dfcdacc48cd48626c6bc66d685f71::cat_nft::CatNFT): &0x2::url::Url {
    return &l0.url
}

