processed 4 tasks

task 0 'run'. lines 1-9:
Error: Script execution failed with VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 1)],
}

task 1 'run'. lines 12-22:
Error: Script execution failed with VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 2)],
}

task 2 'run'. lines 25-32:
Error: Script execution failed with VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 3)],
}

task 3 'run'. lines 35-43:
Error: Script execution failed with VMError: {
    major_status: TYPE_MISMATCH,
    sub_status: None,
    location: script,
    indices: [],
    offsets: [(FunctionDefinitionIndex(0), 4)],
}
