warnings:
  <none>
current frame stack:
  function: test (m.move:3)
    scope 0 :
warnings:
  Source debug info for 0x1::m::bad_source_map references a source file that is unavailable; showing disassembly for this frame.
current frame stack:
  function: test (m.move:3)
    scope 0 :
  function: bad_source_map (m.mvb:5)
    scope 0 :
warnings:
  <none>
current frame stack:
  function: test (m.move:4)
    scope 0 :
