current frame stack:
  function: test (m.move:21)
    scope 0 :
      ctx : (0x2::tx_context::TxContext) {
        sender : 0000000000000000000000000000000000000000000000000000000000000000
        tx_hash : [
          0 : 58
          1 : 152
          2 : 93
          3 : 167
          4 : 79
          5 : 226
          6 : 37
          7 : 178
          8 : 4
          9 : 92
          10 : 23
          11 : 45
          12 : 107
          13 : 211
          14 : 144
          15 : 189
          16 : 133
          17 : 95
          18 : 8
          19 : 110
          20 : 62
          21 : 157
          22 : 82
          23 : 91
          24 : 70
          25 : 191
          26 : 226
          27 : 69
          28 : 17
          29 : 67
          30 : 21
          31 : 50
        ]
        epoch : 0
        epoch_timestamp_ms : 0
        ids_created : 1
      }
      type: 0x2::tx_context::TxContext

