processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-36:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 3 'run-graphql'. lines 40-90:
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IC/ODiKvEk37J2+SHdOXOh0tj3+kKyMTQRJIm4g7eZSB",
          "node": {
            "balance": "300000000000000",
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        },
        {
          "cursor": "IIUF8I/vAPTSS4QFLI2mNoFN4DnGALfzAwuahN/pVrxb",
          "node": {
            "balance": "299999983336400",
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        },
        {
          "cursor": "IMuoUJrAqPQolyrJOQDQP8MtinwxMmIaikWg2Um7ZZSU",
          "node": {
            "balance": "30000000000000000",
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IF1ymdLegVciBXLBI6Y6HdJ/5hQguKpAgAKnTCcgbvhv",
          "node": {
            "balance": "2",
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x16a27647dbea2f51123790b792d4688e21aa0fc716405210ceebb0a2dc70d9f0::fake::FAKE>"
                }
              }
            }
          }
        },
        {
          "cursor": "IIoI4sKegbEz05/HKKtUr5Jh5xsjZNdTBMhXLyAvY0x8",
          "node": {
            "balance": "1",
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x16a27647dbea2f51123790b792d4688e21aa0fc716405210ceebb0a2dc70d9f0::fake::FAKE>"
                }
              }
            }
          }
        },
        {
          "cursor": "IP3OtufdP1lIpko4Gdw3YAOc+hhMq2YIBWFuGKP3luxj",
          "node": {
            "balance": "3",
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x16a27647dbea2f51123790b792d4688e21aa0fc716405210ceebb0a2dc70d9f0::fake::FAKE>"
                }
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IIUF8I/vAPTSS4QFLI2mNoFN4DnGALfzAwuahN/pVrxb",
            "node": {
              "balance": "299999983336400",
              "asMoveObject": {
                "contents": {
                  "type": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                  }
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjo6c3VpOjpTVUki",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "IjB4MTZhMjc2NDdkYmVhMmY1MTEyMzc5MGI3OTJkNDY4OGUyMWFhMGZjNzE2NDA1MjEwY2VlYmIwYTJkYzcwZDlmMDo6ZmFrZTo6RkFLRSI",
            "node": {
              "coinType": {
                "repr": "0x16a27647dbea2f51123790b792d4688e21aa0fc716405210ceebb0a2dc70d9f0::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "IjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjo6c3VpOjpTVUki"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "IjB4MTZhMjc2NDdkYmVhMmY1MTEyMzc5MGI3OTJkNDY4OGUyMWFhMGZjNzE2NDA1MjEwY2VlYmIwYTJkYzcwZDlmMDo6ZmFrZTo6RkFLRSI"
          }
        ]
      }
    }
  }
}
