processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-33:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 3 'run-graphql'. lines 37-85:
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IClom2+MZGKbURWMYEM3EmwOGvUOqbz43IJfrr1pWitPAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IIMyo6vA6Hrv5364cft1EcOM2I/BonVTbAQL8hYX8cxTAQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "II6zPlYVCHu/tOn5DrrgZdWNnyI3tTZ75oyVkL3iLACRAQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983336400",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IC+Ik+mnjZReZaqko4lIbtEZXFs9AOPlspxc8Nmm+zaVAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xafec835920a355ec756ac03ff68ea1fc6e8d3386cf155b40912b16f0e7ef7269::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IGH2IDqkPemt1+GLgrrwTXezk3Hjo4hgARH046r5GLp9AQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xafec835920a355ec756ac03ff68ea1fc6e8d3386cf155b40912b16f0e7ef7269::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "INTIikjZ/j04BRudHPVHjrzwdkWhvey0vzMfod4CEFUvAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xafec835920a355ec756ac03ff68ea1fc6e8d3386cf155b40912b16f0e7ef7269::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "II6zPlYVCHu/tOn5DrrgZdWNnyI3tTZ75oyVkL3iLACRAQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983336400",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "eyJ0IjoiMHhhZmVjODM1OTIwYTM1NWVjNzU2YWMwM2ZmNjhlYTFmYzZlOGQzMzg2Y2YxNTViNDA5MTJiMTZmMGU3ZWY3MjY5OjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0xafec835920a355ec756ac03ff68ea1fc6e8d3386cf155b40912b16f0e7ef7269::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHhhZmVjODM1OTIwYTM1NWVjNzU2YWMwM2ZmNjhlYTFmYzZlOGQzMzg2Y2YxNTViNDA5MTJiMTZmMGU3ZWY3MjY5OjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
