processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 44-46:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 48-48:
Checkpoint created: 1

task 4 'run-graphql'. lines 50-71:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x25a94fd43f61713b1a9aec3961b54a2147b014b610811d780e67d158aafec10f::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  62,
                                  177,
                                  3,
                                  130,
                                  238,
                                  145,
                                  195,
                                  72,
                                  57,
                                  235,
                                  48,
                                  204,
                                  123,
                                  244,
                                  62,
                                  4,
                                  61,
                                  220,
                                  153,
                                  194,
                                  229,
                                  171,
                                  13,
                                  18,
                                  121,
                                  31,
                                  13,
                                  167,
                                  89,
                                  169,
                                  193,
                                  79
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  62,
                                  177,
                                  3,
                                  130,
                                  238,
                                  145,
                                  195,
                                  72,
                                  57,
                                  235,
                                  48,
                                  204,
                                  123,
                                  244,
                                  62,
                                  4,
                                  61,
                                  220,
                                  153,
                                  194,
                                  229,
                                  171,
                                  13,
                                  18,
                                  121,
                                  31,
                                  13,
                                  167,
                                  89,
                                  169,
                                  193,
                                  79
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      62,
                                      177,
                                      3,
                                      130,
                                      238,
                                      145,
                                      195,
                                      72,
                                      57,
                                      235,
                                      48,
                                      204,
                                      123,
                                      244,
                                      62,
                                      4,
                                      61,
                                      220,
                                      153,
                                      194,
                                      229,
                                      171,
                                      13,
                                      18,
                                      121,
                                      31,
                                      13,
                                      167,
                                      89,
                                      169,
                                      193,
                                      79
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x3eb10382ee91c34839eb30cc7bf43e043ddc99c2e5ab0d12791f0da759a9c14f",
                          "f0": "0x3eb10382ee91c34839eb30cc7bf43e043ddc99c2e5ab0d12791f0da759a9c14f",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x3eb10382ee91c34839eb30cc7bf43e043ddc99c2e5ab0d12791f0da759a9c14f"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  186,
                                  33,
                                  129,
                                  78,
                                  49,
                                  186,
                                  14,
                                  108,
                                  212,
                                  36,
                                  147,
                                  166,
                                  144,
                                  84,
                                  179,
                                  102,
                                  38,
                                  68,
                                  120,
                                  5,
                                  121,
                                  134,
                                  135,
                                  250,
                                  198,
                                  51,
                                  97,
                                  254,
                                  217,
                                  37,
                                  93,
                                  24
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988444520"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xba21814e31ba0e6cd42493a69054b36626447805798687fac63361fed9255d18",
                          "balance": {
                            "value": "299999988444520"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
