processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 44-46:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 48-48:
Checkpoint created: 1

task 4 'run-graphql'. lines 50-69:
Response: {
  "data": {
    "transactionBlockConnection": {
      "nodes": [
        {
          "effects": {
            "objectChanges": [
              {
                "outputState": {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "data": {
                        "Struct": [
                          {
                            "name": "id",
                            "value": {
                              "UID": [
                                6,
                                11,
                                127,
                                79,
                                38,
                                115,
                                152,
                                197,
                                224,
                                172,
                                154,
                                149,
                                176,
                                206,
                                73,
                                161,
                                77,
                                118,
                                52,
                                174,
                                157,
                                127,
                                31,
                                98,
                                124,
                                100,
                                241,
                                167,
                                77,
                                60,
                                197,
                                144
                              ]
                            }
                          },
                          {
                            "name": "balance",
                            "value": {
                              "Struct": [
                                {
                                  "name": "value",
                                  "value": {
                                    "Number": "299999988444520"
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      },
                      "json": {
                        "id": "0x060b7f4f267398c5e0ac9a95b0ce49a14d7634ae9d7f1f627c64f1a74d3cc590",
                        "balance": {
                          "value": "299999988444520"
                        }
                      }
                    }
                  }
                }
              },
              {
                "outputState": {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0b6d8b045dee986d51237909b0b903b19f9167d2953f3eb149948d365d485b21::m::Foo"
                      },
                      "data": {
                        "Struct": [
                          {
                            "name": "id",
                            "value": {
                              "UID": [
                                135,
                                170,
                                102,
                                195,
                                48,
                                55,
                                227,
                                86,
                                82,
                                123,
                                88,
                                51,
                                117,
                                239,
                                195,
                                183,
                                92,
                                49,
                                141,
                                91,
                                64,
                                63,
                                226,
                                133,
                                79,
                                45,
                                229,
                                130,
                                145,
                                147,
                                80,
                                93
                              ]
                            }
                          },
                          {
                            "name": "f0",
                            "value": {
                              "ID": [
                                135,
                                170,
                                102,
                                195,
                                48,
                                55,
                                227,
                                86,
                                82,
                                123,
                                88,
                                51,
                                117,
                                239,
                                195,
                                183,
                                92,
                                49,
                                141,
                                91,
                                64,
                                63,
                                226,
                                133,
                                79,
                                45,
                                229,
                                130,
                                145,
                                147,
                                80,
                                93
                              ]
                            }
                          },
                          {
                            "name": "f1",
                            "value": {
                              "Bool": true
                            }
                          },
                          {
                            "name": "f2",
                            "value": {
                              "Number": "42"
                            }
                          },
                          {
                            "name": "f3",
                            "value": {
                              "Number": "43"
                            }
                          },
                          {
                            "name": "f4",
                            "value": {
                              "String": "hello"
                            }
                          },
                          {
                            "name": "f5",
                            "value": {
                              "String": "world"
                            }
                          },
                          {
                            "name": "f6",
                            "value": {
                              "Vector": [
                                {
                                  "Address": [
                                    135,
                                    170,
                                    102,
                                    195,
                                    48,
                                    55,
                                    227,
                                    86,
                                    82,
                                    123,
                                    88,
                                    51,
                                    117,
                                    239,
                                    195,
                                    183,
                                    92,
                                    49,
                                    141,
                                    91,
                                    64,
                                    63,
                                    226,
                                    133,
                                    79,
                                    45,
                                    229,
                                    130,
                                    145,
                                    147,
                                    80,
                                    93
                                  ]
                                }
                              ]
                            }
                          },
                          {
                            "name": "f7",
                            "value": {
                              "Option": {
                                "Number": "44"
                              }
                            }
                          }
                        ]
                      },
                      "json": {
                        "id": "0x87aa66c33037e356527b583375efc3b75c318d5b403fe2854f2de5829193505d",
                        "f0": "0x87aa66c33037e356527b583375efc3b75c318d5b403fe2854f2de5829193505d",
                        "f1": true,
                        "f2": 42,
                        "f3": "43",
                        "f4": "hello",
                        "f5": "world",
                        "f6": [
                          "0x87aa66c33037e356527b583375efc3b75c318d5b403fe2854f2de5829193505d"
                        ],
                        "f7": 44
                      }
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
