processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-54:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 56-58:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 60-60:
Checkpoint created: 1

task 4 'run-graphql'. lines 62-83:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x2b27451fe08307117ecc1d172f7bb24b81bfdb774592d8d11ba196a76edaddd6::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  56,
                                  223,
                                  62,
                                  4,
                                  221,
                                  43,
                                  163,
                                  179,
                                  9,
                                  17,
                                  185,
                                  146,
                                  193,
                                  146,
                                  56,
                                  28,
                                  179,
                                  90,
                                  243,
                                  178,
                                  100,
                                  107,
                                  65,
                                  162,
                                  152,
                                  189,
                                  57,
                                  216,
                                  209,
                                  61,
                                  42,
                                  215
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  56,
                                  223,
                                  62,
                                  4,
                                  221,
                                  43,
                                  163,
                                  179,
                                  9,
                                  17,
                                  185,
                                  146,
                                  193,
                                  146,
                                  56,
                                  28,
                                  179,
                                  90,
                                  243,
                                  178,
                                  100,
                                  107,
                                  65,
                                  162,
                                  152,
                                  189,
                                  57,
                                  216,
                                  209,
                                  61,
                                  42,
                                  215
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      56,
                                      223,
                                      62,
                                      4,
                                      221,
                                      43,
                                      163,
                                      179,
                                      9,
                                      17,
                                      185,
                                      146,
                                      193,
                                      146,
                                      56,
                                      28,
                                      179,
                                      90,
                                      243,
                                      178,
                                      100,
                                      107,
                                      65,
                                      162,
                                      152,
                                      189,
                                      57,
                                      216,
                                      209,
                                      61,
                                      42,
                                      215
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x38df3e04dd2ba3b30911b992c192381cb35af3b2646b41a298bd39d8d13d2ad7",
                          "f0": "0x38df3e04dd2ba3b30911b992c192381cb35af3b2646b41a298bd39d8d13d2ad7",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x38df3e04dd2ba3b30911b992c192381cb35af3b2646b41a298bd39d8d13d2ad7"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  74,
                                  63,
                                  69,
                                  149,
                                  223,
                                  0,
                                  225,
                                  254,
                                  133,
                                  114,
                                  233,
                                  29,
                                  11,
                                  223,
                                  12,
                                  229,
                                  83,
                                  83,
                                  236,
                                  108,
                                  28,
                                  82,
                                  187,
                                  116,
                                  23,
                                  108,
                                  228,
                                  45,
                                  4,
                                  45,
                                  150,
                                  20
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x4a3f4595df00e1fe8572e91d0bdf0ce55353ec6c1c52bb74176ce42d042d9614",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
