processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-54:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 56-58:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 60-60:
Checkpoint created: 1

task 4 'run-graphql'. lines 62-83:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xc6c3c93403b514bc534bb5eb5f18ad994caa414f6d178d3c71ef677f343fed7f::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  38,
                                  208,
                                  191,
                                  88,
                                  204,
                                  210,
                                  143,
                                  164,
                                  241,
                                  178,
                                  35,
                                  61,
                                  136,
                                  222,
                                  125,
                                  75,
                                  118,
                                  15,
                                  229,
                                  217,
                                  229,
                                  13,
                                  97,
                                  94,
                                  19,
                                  200,
                                  52,
                                  115,
                                  126,
                                  208,
                                  219,
                                  38
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  38,
                                  208,
                                  191,
                                  88,
                                  204,
                                  210,
                                  143,
                                  164,
                                  241,
                                  178,
                                  35,
                                  61,
                                  136,
                                  222,
                                  125,
                                  75,
                                  118,
                                  15,
                                  229,
                                  217,
                                  229,
                                  13,
                                  97,
                                  94,
                                  19,
                                  200,
                                  52,
                                  115,
                                  126,
                                  208,
                                  219,
                                  38
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      38,
                                      208,
                                      191,
                                      88,
                                      204,
                                      210,
                                      143,
                                      164,
                                      241,
                                      178,
                                      35,
                                      61,
                                      136,
                                      222,
                                      125,
                                      75,
                                      118,
                                      15,
                                      229,
                                      217,
                                      229,
                                      13,
                                      97,
                                      94,
                                      19,
                                      200,
                                      52,
                                      115,
                                      126,
                                      208,
                                      219,
                                      38
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x26d0bf58ccd28fa4f1b2233d88de7d4b760fe5d9e50d615e13c834737ed0db26",
                          "f0": "0x26d0bf58ccd28fa4f1b2233d88de7d4b760fe5d9e50d615e13c834737ed0db26",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x26d0bf58ccd28fa4f1b2233d88de7d4b760fe5d9e50d615e13c834737ed0db26"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  242,
                                  188,
                                  8,
                                  146,
                                  91,
                                  93,
                                  199,
                                  88,
                                  48,
                                  87,
                                  226,
                                  103,
                                  228,
                                  118,
                                  197,
                                  119,
                                  77,
                                  235,
                                  253,
                                  112,
                                  65,
                                  28,
                                  187,
                                  56,
                                  82,
                                  102,
                                  118,
                                  60,
                                  147,
                                  142,
                                  46,
                                  97
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xf2bc08925b5dc7583057e267e476c5774debfd70411cbb385266763c938e2e61",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
