processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-54:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10510800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 56-58:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3032400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 60-60:
Checkpoint created: 1

task 4 'run-graphql'. lines 62-83:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  26,
                                  81,
                                  115,
                                  93,
                                  169,
                                  35,
                                  41,
                                  133,
                                  14,
                                  27,
                                  79,
                                  142,
                                  163,
                                  22,
                                  195,
                                  52,
                                  250,
                                  101,
                                  183,
                                  195,
                                  178,
                                  66,
                                  100,
                                  67,
                                  178,
                                  248,
                                  49,
                                  160,
                                  240,
                                  34,
                                  83,
                                  232
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995967600"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x1a51735da92329850e1b4f8ea316c334fa65b7c3b2426443b2f831a0f02253e8",
                          "balance": {
                            "value": "299999995967600"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x72e81da69722659259d5c5f16bbc054e22b79cbac6d37ee5e5cb2daee5c8fb09::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  157,
                                  173,
                                  112,
                                  54,
                                  108,
                                  35,
                                  60,
                                  245,
                                  185,
                                  230,
                                  102,
                                  44,
                                  146,
                                  218,
                                  239,
                                  145,
                                  206,
                                  199,
                                  56,
                                  163,
                                  234,
                                  212,
                                  215,
                                  238,
                                  138,
                                  204,
                                  11,
                                  227,
                                  124,
                                  231,
                                  239,
                                  231
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  157,
                                  173,
                                  112,
                                  54,
                                  108,
                                  35,
                                  60,
                                  245,
                                  185,
                                  230,
                                  102,
                                  44,
                                  146,
                                  218,
                                  239,
                                  145,
                                  206,
                                  199,
                                  56,
                                  163,
                                  234,
                                  212,
                                  215,
                                  238,
                                  138,
                                  204,
                                  11,
                                  227,
                                  124,
                                  231,
                                  239,
                                  231
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      157,
                                      173,
                                      112,
                                      54,
                                      108,
                                      35,
                                      60,
                                      245,
                                      185,
                                      230,
                                      102,
                                      44,
                                      146,
                                      218,
                                      239,
                                      145,
                                      206,
                                      199,
                                      56,
                                      163,
                                      234,
                                      212,
                                      215,
                                      238,
                                      138,
                                      204,
                                      11,
                                      227,
                                      124,
                                      231,
                                      239,
                                      231
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x9dad70366c233cf5b9e6662c92daef91cec738a3ead4d7ee8acc0be37ce7efe7",
                          "f0": "0x9dad70366c233cf5b9e6662c92daef91cec738a3ead4d7ee8acc0be37ce7efe7",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x9dad70366c233cf5b9e6662c92daef91cec738a3ead4d7ee8acc0be37ce7efe7"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
