processed 13 tasks

init:
C: object(0,0)

task 1 'create-checkpoint'. lines 7-7:
Checkpoint created: 1

task 2 'advance-epoch'. lines 9-9:
Epoch advanced: 0

task 3 'programmable'. lines 11-13:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'run'. lines 15-17:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [238, 200, 46, 64, 19, 251, 166, 48, 169, 106, 19, 152, 17, 73, 253, 13, 104, 253, 255, 233, 100, 45, 194, 20, 146, 117, 157, 165, 47, 29, 161, 135, 251, 197, 26, 138, 207, 9, 111, 134, 25, 141, 95, 164, 112, 98, 14, 214, 162, 10, 188, 9, 185, 78, 168, 145, 239, 2, 154, 93, 227, 243, 151, 19, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 5 'create-checkpoint'. lines 18-18:
Checkpoint created: 3

task 6 'advance-epoch'. lines 20-20:
Epoch advanced: 1

task 7 'run-graphql'. lines 22-37:
Response: {
  "data": {
    "objectConnection": {
      "edges": [
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                }
              }
            }
          }
        },
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                }
              }
            }
          }
        },
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::staking_pool::StakedSui"
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 8 'run-graphql'. lines 39-54:
Response: {
  "data": {
    "objectConnection": {
      "edges": [
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        },
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        },
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 9 'run-graphql'. lines 56-72:
Response: {
  "data": {
    "objectConnection": {
      "edges": [
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        },
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        },
        {
          "node": {
            "asMoveObject": {
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 10 'run-graphql'. lines 74-90:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Invalid type provided as filter: Invalid struct type: 0x2::coin::Coin<ye>. Got error: expected token ::, got >",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "objectConnection"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 11 'run-graphql'. lines 92-108:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Invalid type provided as filter: Invalid struct type: 0x2::coin::Coin<. Got error: unexpected end of tokens",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "objectConnection"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 12 'run-graphql'. lines 110-126:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Invalid type provided as filter: Invalid struct type: 0x2::a%::B&. Got error: unrecognized token: %::B&",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "objectConnection"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
