processed 19 tasks

init:
A: object(0,0)

task 1 'publish'. lines 11-52:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7014800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 54-54:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 56-56:
Checkpoint created: 1

task 4 'run-graphql'. lines 58-71:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x05ae1c920990bf9e03e2c243b2d25a910aca03a3978c582dd64ecb1bbd1e1d5e",
            "value": "0"
          }
        }
      }
    }
  }
}

task 5 'run'. lines 73-73:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 6 'create-checkpoint'. lines 75-75:
Checkpoint created: 2

task 7 'run-graphql'. lines 77-103:
Response: {
  "data": {
    "latest_version": {
      "status": "HISTORICAL",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x05ae1c920990bf9e03e2c243b2d25a910aca03a3978c582dd64ecb1bbd1e1d5e",
            "value": "1"
          }
        }
      }
    },
    "previous_version": {
      "status": "HISTORICAL",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x05ae1c920990bf9e03e2c243b2d25a910aca03a3978c582dd64ecb1bbd1e1d5e",
            "value": "0"
          }
        }
      }
    }
  }
}

task 8 'run'. lines 105-105:
created: object(8,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 9 'create-checkpoint'. lines 107-107:
Checkpoint created: 3

task 10 'run-graphql'. lines 109-135:
Response: {
  "data": {
    "latest_wrapped": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "previous_version": {
      "status": "HISTORICAL",
      "version": 4,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x05ae1c920990bf9e03e2c243b2d25a910aca03a3978c582dd64ecb1bbd1e1d5e",
            "value": "1"
          }
        }
      }
    }
  }
}

task 11 'run'. lines 137-137:
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(0) } }

task 12 'create-checkpoint'. lines 139-139:
Checkpoint created: 4

task 13 'run-graphql'. lines 141-179:
Response: {
  "data": {
    "latest_unwrapped": {
      "status": "HISTORICAL",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x05ae1c920990bf9e03e2c243b2d25a910aca03a3978c582dd64ecb1bbd1e1d5e",
            "value": "1"
          }
        }
      }
    },
    "previous_version": {
      "status": "WRAPPED_OR_DELETED",
      "version": 5,
      "asMoveObject": null
    },
    "first_version": {
      "status": "HISTORICAL",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x05ae1c920990bf9e03e2c243b2d25a910aca03a3978c582dd64ecb1bbd1e1d5e",
            "value": "0"
          }
        }
      }
    }
  }
}

task 14 'run'. lines 181-181:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 15 'create-checkpoint'. lines 183-183:
Checkpoint created: 5

task 16 'run-graphql'. lines 185-211:
Response: {
  "data": {
    "latest_deleted": {
      "status": "WRAPPED_OR_DELETED",
      "version": 7,
      "asMoveObject": null
    },
    "version_specified": {
      "status": "WRAPPED_OR_DELETED",
      "version": 7,
      "asMoveObject": null
    }
  }
}

task 17 'force-object-snapshot-catchup'. lines 213-213:
Objects snapshot updated to [0 to 5)

task 18 'run-graphql'. lines 215-241:
Response: {
  "data": {
    "object_within_available_range": {
      "status": "HISTORICAL",
      "version": 6,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0x05ae1c920990bf9e03e2c243b2d25a910aca03a3978c582dd64ecb1bbd1e1d5e",
            "value": "1"
          }
        }
      }
    },
    "object_outside_available_range": null
  }
}
