processed 14 tasks

task 1 'publish'. lines 6-19:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 21-21:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 23-23:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 25-25:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 27-27:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 29-29:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'create-checkpoint'. lines 31-31:
Checkpoint created: 1

task 8 'run-graphql'. lines 33-43:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IBhMDZiGp6kLWJkkamAXfLYMLEzymv79v9Ln0gRHmxA1AQAAAAAAAAA="
          },
          {
            "cursor": "IGo2LF0uWBWev+G+hSmLww6rXmgJQEJ4LfFxqnhZYDReAQAAAAAAAAA="
          },
          {
            "cursor": "IIOUWmWoubxXbnMHfwFcdQWza7EdEUhLiw2NWDKMZT5AAQAAAAAAAAA="
          },
          {
            "cursor": "IMYcoQ7AWOYZT6WLrASYCF1Csj24o6N4XhfVz6MxLGK6AQAAAAAAAAA="
          },
          {
            "cursor": "IPLZxNQHzRLDTkk6wNlVvSFvT31q5DGf07odbAHgMWntAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9 'run-graphql'. lines 45-55:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IBhMDZiGp6kLWJkkamAXfLYMLEzymv79v9Ln0gRHmxA1AQAAAAAAAAA="
          },
          {
            "cursor": "IGo2LF0uWBWev+G+hSmLww6rXmgJQEJ4LfFxqnhZYDReAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 57-69:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IGo2LF0uWBWev+G+hSmLww6rXmgJQEJ4LfFxqnhZYDReAQAAAAAAAAA="
          },
          {
            "cursor": "IIOUWmWoubxXbnMHfwFcdQWza7EdEUhLiw2NWDKMZT5AAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 71-81:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IMYcoQ7AWOYZT6WLrASYCF1Csj24o6N4XhfVz6MxLGK6AQAAAAAAAAA="
          },
          {
            "cursor": "IPLZxNQHzRLDTkk6wNlVvSFvT31q5DGf07odbAHgMWntAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 83-93:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IGo2LF0uWBWev+G+hSmLww6rXmgJQEJ4LfFxqnhZYDReAQAAAAAAAAA="
          },
          {
            "cursor": "IIOUWmWoubxXbnMHfwFcdQWza7EdEUhLiw2NWDKMZT5AAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 13 'run-graphql'. lines 95-104:
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IMYcoQ7AWOYZT6WLrASYCF1Csj24o6N4XhfVz6MxLGK6AQAAAAAAAAA="
          },
          {
            "cursor": "IPLZxNQHzRLDTkk6wNlVvSFvT31q5DGf07odbAHgMWntAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}
