processed 13 tasks

task 1 'publish'. lines 6-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 25-25:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 27-27:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 29-29:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 31-31:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 33-33:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 8 'run-graphql'. lines 37-47:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x1a7608bbb2287049af7277beb03675da855f91f1e576bf85955be7bcf1a00dee"
          },
          {
            "cursor": "0x2d5bd25ebb5bd55a8f3cdcf3e9a2840e4ecd21cf783f3af27241bbc7484a4f67"
          },
          {
            "cursor": "0x767a20e24e00708b5134771a7897f5278107ce8544f03cab44628d84be11164f"
          },
          {
            "cursor": "0x925fbd4db2688a5f5cdf953f8c3522668922305d6f5510b6e0ccf9d3bb92d8fa"
          },
          {
            "cursor": "0x9cc539daaa3fc1684ab3cb0cf7f74a4a8339982d2f30458c05469189eece758b"
          }
        ]
      }
    }
  }
}

task 9 'run-graphql'. lines 49-59:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x1a7608bbb2287049af7277beb03675da855f91f1e576bf85955be7bcf1a00dee"
          },
          {
            "cursor": "0x2d5bd25ebb5bd55a8f3cdcf3e9a2840e4ecd21cf783f3af27241bbc7484a4f67"
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 61-73:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x2d5bd25ebb5bd55a8f3cdcf3e9a2840e4ecd21cf783f3af27241bbc7484a4f67"
          },
          {
            "cursor": "0x767a20e24e00708b5134771a7897f5278107ce8544f03cab44628d84be11164f"
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 75-85:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x925fbd4db2688a5f5cdf953f8c3522668922305d6f5510b6e0ccf9d3bb92d8fa"
          },
          {
            "cursor": "0x9cc539daaa3fc1684ab3cb0cf7f74a4a8339982d2f30458c05469189eece758b"
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 87-97:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x2d5bd25ebb5bd55a8f3cdcf3e9a2840e4ecd21cf783f3af27241bbc7484a4f67"
          },
          {
            "cursor": "0x767a20e24e00708b5134771a7897f5278107ce8544f03cab44628d84be11164f"
          }
        ]
      }
    }
  }
}
