processed 14 tasks

task 1 'publish'. lines 6-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 25-25:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'run'. lines 27-27:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 29-29:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 31-31:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 33-33:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 7 'create-checkpoint'. lines 35-35:
Checkpoint created: 1

task 8 'run-graphql'. lines 37-47:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x31c5584342708f66248126f6e91bab1c902b156e2a1932e54f45c24a55447467"
          },
          {
            "cursor": "0xc135cf8f3fb276342b6928427001820b10a09fcfc2382d7ce29edc96ab800309"
          },
          {
            "cursor": "0xe0e6c0fe3656026c675036246aba0ea041a184c2c2d9b1954c6cf12fe53a1b61"
          },
          {
            "cursor": "0xf369d64ba238703025d640128683c92af93f067d9b273d9318945c9e6521e967"
          },
          {
            "cursor": "0xf7f373fd2d4f3eb17ba7525f635364c0ec41337509bb8df9c578d2013eab83cb"
          }
        ]
      }
    }
  }
}

task 9 'run-graphql'. lines 49-59:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0x31c5584342708f66248126f6e91bab1c902b156e2a1932e54f45c24a55447467"
          },
          {
            "cursor": "0xc135cf8f3fb276342b6928427001820b10a09fcfc2382d7ce29edc96ab800309"
          }
        ]
      }
    }
  }
}

task 10 'run-graphql'. lines 61-73:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xf7f373fd2d4f3eb17ba7525f635364c0ec41337509bb8df9c578d2013eab83cb"
          }
        ]
      }
    }
  }
}

task 11 'run-graphql'. lines 75-85:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xe0e6c0fe3656026c675036246aba0ea041a184c2c2d9b1954c6cf12fe53a1b61"
          },
          {
            "cursor": "0xf369d64ba238703025d640128683c92af93f067d9b273d9318945c9e6521e967"
          }
        ]
      }
    }
  }
}

task 12 'run-graphql'. lines 87-97:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xe0e6c0fe3656026c675036246aba0ea041a184c2c2d9b1954c6cf12fe53a1b61"
          },
          {
            "cursor": "0xf369d64ba238703025d640128683c92af93f067d9b273d9318945c9e6521e967"
          }
        ]
      }
    }
  }
}

task 13 'run-graphql'. lines 99-108:
Response: {
  "data": {
    "address": {
      "objectConnection": {
        "edges": [
          {
            "cursor": "0xf369d64ba238703025d640128683c92af93f067d9b273d9318945c9e6521e967"
          },
          {
            "cursor": "0xf7f373fd2d4f3eb17ba7525f635364c0ec41337509bb8df9c578d2013eab83cb"
          }
        ]
      }
    }
  }
}
