processed 15 tasks

init:
A: object(0,0)

task 1 'publish'. lines 16-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6171200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 44-44:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 46-46:
Checkpoint created: 1

task 4 'run-graphql'. lines 48-61:
Response: {
  "data": {
    "object": {
      "status": "LIVE",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xcf27391f83c42a323595be23151f6ede95a083f451a388ff2e3e25fbbf31a7c3",
            "value": "0"
          }
        }
      }
    }
  }
}

task 5 'run-graphql'. lines 64-78:
Response: {
  "data": {
    "object": {
      "status": "HISTORICAL",
      "version": 3,
      "asMoveObject": {
        "contents": {
          "json": {
            "id": "0xcf27391f83c42a323595be23151f6ede95a083f451a388ff2e3e25fbbf31a7c3",
            "value": "0"
          }
        }
      }
    }
  }
}

task 6 'run'. lines 80-80:
created: object(6,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 7 'create-checkpoint'. lines 82-82:
Checkpoint created: 2

task 9 'create-checkpoint'. lines 86-86:
Checkpoint created: 3

task 11 'create-checkpoint'. lines 90-90:
Checkpoint created: 4

task 12 'run-graphql'. lines 92-106:
Response: {
  "data": {
    "object": null
  }
}

task 13 'run-graphql'. lines 109-124:
Response: {
  "data": {
    "object": {
      "status": "WRAPPED_OR_DELETED",
      "version": 4,
      "asMoveObject": null
    }
  }
}

task 14 'run-graphql'. lines 126-141:
Response: {
  "data": {
    "object": {
      "status": "OUTSIDE_AVAILABLE_RANGE",
      "version": null,
      "asMoveObject": null
    }
  }
}
