processed 7 tasks

init:
C: object(0,0)

task 1 'run-graphql'. lines 6-31:
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IN25CRYXkoExgo4197TsRBf9zreO410TAzzeVneOW16hAAAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "20000000000000000"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedSuis": {
        "edges": []
      }
    }
  }
}

task 2 'programmable'. lines 33-35:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 37-37:
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [222, 174, 238, 46, 128, 159, 154, 49, 183, 125, 217, 242, 75, 183, 191, 49, 231, 163, 206, 58, 121, 155, 254, 118, 101, 145, 25, 19, 113, 34, 85, 220, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0), object(3,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 15078400,  storage_rebate: 1956240, non_refundable_storage_fee: 19760

task 4 'create-checkpoint'. lines 39-39:
Checkpoint created: 1

task 5 'advance-epoch'. lines 41-41:
Epoch advanced: 0

task 6 'run-graphql'. lines 43-69:
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IDAYWv+0huufclH7Tw3WRvoR2AQ4CHwn65hicoktlq3SAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "10000000000",
                "poolId": "0xdeaeee2e809f9a31b77dd9f24bb7bf31e7a3ce3a799bfe7665911913712255dc"
              }
            }
          }
        },
        {
          "cursor": "ILl23ZhuMrjV3pz8CoyNOhThbfin9Fl04ys5Fq4grKcDAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "40000",
                "poolId": "0xdeaeee2e809f9a31b77dd9f24bb7bf31e7a3ce3a799bfe7665911913712255dc"
              }
            }
          }
        },
        {
          "cursor": "IN25CRYXkoExgo4197TsRBf9zreO410TAzzeVneOW16hAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "20000000000000000",
                "poolId": "0xdeaeee2e809f9a31b77dd9f24bb7bf31e7a3ce3a799bfe7665911913712255dc"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedSuis": {
        "edges": [
          {
            "cursor": "IDAYWv+0huufclH7Tw3WRvoR2AQ4CHwn65hicoktlq3SAgAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}
