// Auto-generated by Move decompiler

module 0xa32574713e612fa6d9eb439723cb7d69f06ae55117d8c9a028330cea98c5f391::marketplace;

// -- uses -- 

use 0x1::ascii;
use 0x1::debug;
use 0x1::option;
use 0x1::string;
use 0x1::type_name;
use 0x1::vector;
use 0x2::balance as x2_balance;
use 0x2::clock;
use 0x2::coin;
use 0x2::dynamic_object_field;
use 0x2::event;
use 0x2::kiosk;
use 0x2::linked_table;
use 0x2::object;
use 0x2::transfer;
use 0x2::tx_context;
use 0x434b5bd8f6a7b05fede0ff46c6e511d71ea326ed38056e3bcd681d2d7c2a7879::royalty_rule;
use 0xa32574713e612fa6d9eb439723cb7d69f06ae55117d8c9a028330cea98c5f391::helpers;
use 0xa32574713e612fa6d9eb439723cb7d69f06ae55117d8c9a028330cea98c5f391::marketplace;
use 0xb2f3f2134577e6cd3ef312b099f05e48964301262a1158416143e57358d2e455::ions;
use 0xb2f3f2134577e6cd3ef312b099f05e48964301262a1158416143e57358d2e455::math;
use 0x1::ascii::String;
use 0x1::option::Option;
use 0x2::balance::Balance;
use 0x2::clock::Clock;
use 0x2::coin::Coin;
use 0x2::kiosk::Kiosk;
use 0x2::kiosk::KioskOwnerCap;
use 0x2::kiosk::PurchaseCap;
use 0x2::linked_table::LinkedTable;
use 0x2::object::ID;
use 0x2::object::UID;
use 0x2::sui::SUI;
use 0x2::transfer_policy::TransferPolicy;
use 0x2::transfer_policy::TransferRequest;
use 0x2::tx_context::TxContext;
use 0xb2f3f2134577e6cd3ef312b099f05e48964301262a1158416143e57358d2e455::ions::AnimaChef;
use 0xb2f3f2134577e6cd3ef312b099f05e48964301262a1158416143e57358d2e455::ions::AnimaIONs;
use 0xb2f3f2134577e6cd3ef312b099f05e48964301262a1158416143e57358d2e455::ions::PointsAdminCap;

// -- structs -- 

public struct CollectorCap has key, store { id: UID }

public struct AdminCap has key, store { id: UID }

public struct LaunchpadCap has key, store { id: UID }

public struct TraitBidsAdminCap has key, store { id: UID }

public struct TraitBidsPotato { id: ID }

public struct MarketPlaceStore
has key {
    id: UID,
    points_admin_cap: PointsAdminCap,
    is_permissionless: bool,
    new_collection_fee: u64,
    commission_pct: u64,
    available_sui: Balance<SUI>,
    user_activity: LinkedTable<address, UserInfo>,
    active_collections: LinkedTable<String, bool>,
    referrals: LinkedTable<address, u64>,
    kiosk_id: ID,
    escrow_kiosk_cap: KioskOwnerCap,
    pending_claims: LinkedTable<address, PendingClaims>,
    version: u64,
}

public struct PendingClaims has store { pending_claims: LinkedTable<ID, PendingClaim> }

public struct PendingClaim has store { buyer: address, nft_type: String, price: u64 }

public struct UserInfo
has key, store {
    id: UID,
    listings: LinkedTable<ID, ListingInfo>,
    bids: LinkedTable<ID, BidInfo>,
    collection_bids: LinkedTable<String, vector<BidInfo>>,
    trait_bids: LinkedTable<String, vector<TraitBidInfo>>,
    claimable_points: u64,
}

public struct ListingInfo has drop, store { nft_type: String, price: u64, listed_at: u64, last_points_claimed_at: u64 }

public struct BidInfo
has drop, store {
    bid_id: ID,
    nft_type: String,
    bid_price: u64,
    is_collection_bid: bool,
    bid_at: u64,
    last_points_claimed_at: u64,
}

public struct TraitBidInfo
has drop, store {
    bid_id: ID,
    nft_type: String,
    bid_price: u64,
    trait_key1: Option<String>,
    trait_value1: Option<vector<String>>,
    trait_key2: Option<String>,
    trait_value2: Option<vector<String>>,
    trait_key3: Option<String>,
    trait_value3: Option<vector<String>>,
    bid_at: u64,
    last_points_claimed_at: u64,
}

public struct CollectionMarketPlace<phantom T0: key + store>
has key, store {
    id: UID,
    listings: LinkedTable<ID, Listing<T0>>,
    bids: LinkedTable<ID, ActiveBids>,
    collection_bids: LinkedTable<address, vector<ActiveBid>>,
    sui_trait_bids_pool: Balance<SUI>,
    are_trait_bids_enabled: bool,
    lifetime_volume: u128,
    ion_points_enabled: bool,
    ion_collection_multiplier: u64,
    avg_sale_price: u64,
    recent_sale_prices: vector<u64>,
}

public struct Listing<phantom T0: key + store>
has store {
    seller: address,
    kiosk_id: ID,
    nft_id: ID,
    cap: PurchaseCap<T0>,
    price: u64,
    commission: u64,
    listed_at: u64,
}

public struct ActiveBids has key, store { id: UID, bids: LinkedTable<address, ActiveBid> }

public struct ActiveBid has key, store { id: UID, bidder: address, bid_price: u64, balance: Balance<SUI>, bid_at: u64 }

public struct ActiveTraitBid
has key, store {
    id: UID,
    bidder: address,
    bid_price: u64,
    bid_at: u64,
    trait_key1: Option<String>,
    trait_value1: Option<vector<String>>,
    trait_key2: Option<String>,
    trait_value2: Option<vector<String>>,
    trait_key3: Option<String>,
    trait_value3: Option<vector<String>>,
}

public struct UpdateActiveCollectionsEvent has copy, drop { nft_type: String, boolean: bool }

public struct CollectCommissionsEvent has copy, drop { recepient: address, amount: u64 }

public struct UpdateIONMultiplierEvent has copy, drop { nft_type: String, is_ion_points_enabled: bool, ion_collection_multiplier: u64 }

public struct UpdatePermissionlessStatusEvent has copy, drop { is_permissionless: bool }

public struct ListEvent
has copy, drop { nft_type: String, seller: address, kiosk_id: ID, nft_id: ID, price: u64, listed_at: u64 }

public struct UnlistEvent
has copy, drop {
    nft_type: String,
    seller: address,
    nft_id: ID,
    kiosk_id: ID,
    price: u64,
    unlisted_at: u64,
    ion_points_awarded: u64,
}

public struct MakeBidEvent
has copy, drop {
    bid_id: ID,
    nft_type: String,
    buyer: address,
    nft_id: Option<ID>,
    price: u64,
    is_collection_bid: bool,
    bid_at: u64,
}

public struct CancelBidEvent
has copy, drop {
    bid_id: ID,
    nft_type: String,
    bidder: address,
    nft_id: Option<ID>,
    is_collection_bid: bool,
    cancelled_at: u64,
    ion_points_awarded: u64,
}

public struct BuyEvent
has copy, drop {
    nft_type: String,
    nft_id: ID,
    buyer: address,
    seller: address,
    seller_kiosk: ID,
    price: u64,
    commission: u64,
    buyer_ion_points: u64,
    seller_ion_points: u64,
}

public struct AwardIonPointsEvent
has copy, drop {
    user_address: address,
    points_earned: u64,
    referrer_address: Option<address>,
    referral_points: u64,
    bonus_points: u64,
    total_points: u64,
}

public struct ReferralPointsClaimedEvent
has copy, drop {
    user_address: address,
    claimable_points: u64,
    referral_points: u64,
    bonus_points: u64,
    total_points: u64,
}

public struct TraitBidMadeEvent
has copy, drop {
    nft_type: String,
    bidder: address,
    bid_id: ID,
    bid_amount: u64,
    trait_key1: Option<String>,
    trait_value1: Option<vector<String>>,
    trait_key2: Option<String>,
    trait_value2: Option<vector<String>>,
    trait_key3: Option<String>,
    trait_value3: Option<vector<String>>,
    bid_at: u64,
}

public struct TraitBidAcceptedEvent
has copy, drop {
    nft_type: String,
    nft_id: ID,
    seller: address,
    buyer: address,
    price: u64,
    commission: u64,
    buyer_ion_points: u64,
    seller_ion_points: u64,
}

public struct TraitBidCancelledEvent
has copy, drop {
    nft_type: String,
    bidder: address,
    bid_id: ID,
    refund_amount: u64,
    ion_points_awarded: u64,
    cancelled_at: u64,
}

public struct BidAcceptedEvent
has copy, drop {
    nft_type: String,
    nft_id: ID,
    seller: address,
    buyer: address,
    is_collection_bid: bool,
    price: u64,
    commission: u64,
    escrow_kiosk: ID,
    buyer_ion_points: u64,
    seller_ion_points: u64,
}

public struct NFTClaimedEvent has copy, drop { nft_type: String, nft_id: ID, buyer: address, buyer_kiosk: ID, claimed_at: u64 }

public struct UpdateTraitBiddingSupportEvent has copy, drop { nft_type: String, are_trait_bids_enabled: bool }

// -- constants -- 

const C0: u64 = 0u64;

const C1: vector<u8> = vector[116u8, 114u8, 97u8, 105u8, 116u8, 95u8, 98u8, 105u8, 100u8, 115u8];

const C2: vector<u8> = vector[];

const C3: u64 = 10u64;

const C4: u64 = 10000u64;

const C5: u64 = 1000u64;

const C6: u64 = 15u64;

const C7: u64 = 100000000000u64;

const C8: u64 = 2u64;

const C9: u64 = 7684u64;

const C10: u64 = 769u64;

const C11: u64 = 770u64;

const C12: u64 = 771u64;

const C13: u64 = 772u64;

const C14: u64 = 773u64;

const C15: u64 = 774u64;

const C16: u64 = 775u64;

const C17: u64 = 776u64;

const C18: u64 = 777u64;

const C19: u64 = 778u64;

const C20: u64 = 779u64;

const C21: u64 = 780u64;

const C22: u64 = 781u64;

const C23: u64 = 782u64;

const C24: u64 = 783u64;

const C25: u64 = 784u64;

const C26: u64 = 785u64;

const C27: u64 = 786u64;

const C28: u64 = 787u64;

const C29: u64 = 788u64;

const C30: u64 = 789u64;

const C31: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 76u8, 73u8, 83u8, 84u8, 73u8, 78u8, 71u8, 32u8, 78u8, 70u8, 84u8, 32u8, 61u8, 61u8, 61u8];

const C32: vector<u8> = vector[78u8, 70u8, 84u8, 32u8, 108u8, 105u8, 115u8, 116u8, 101u8, 100u8, 32u8, 115u8, 117u8, 99u8, 99u8, 101u8, 115u8, 115u8, 102u8, 117u8, 108u8, 108u8, 121u8];

const C33: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 85u8, 78u8, 76u8, 73u8, 83u8, 84u8, 73u8, 78u8, 71u8, 32u8, 78u8, 70u8, 84u8, 32u8, 61u8, 61u8, 61u8];

const C34: vector<u8> = vector[84u8, 105u8, 109u8, 101u8, 32u8, 97u8, 99u8, 116u8, 105u8, 118u8, 101u8, 58u8];

const C35: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 73u8, 79u8, 78u8, 32u8, 80u8, 79u8, 73u8, 78u8, 84u8, 83u8, 32u8, 61u8, 61u8, 61u8];

const C36: vector<u8> = vector[84u8, 105u8, 109u8, 101u8, 32u8, 109u8, 117u8, 108u8, 116u8, 105u8, 112u8, 108u8, 105u8, 101u8, 114u8, 58u8];

const C37: vector<u8> = vector[80u8, 114u8, 111u8, 120u8, 105u8, 109u8, 105u8, 116u8, 121u8, 32u8, 109u8, 117u8, 108u8, 116u8, 105u8, 112u8, 108u8, 105u8, 101u8, 114u8, 58u8];

const C38: vector<u8> = vector[67u8, 111u8, 108u8, 108u8, 101u8, 99u8, 116u8, 105u8, 111u8, 110u8, 32u8, 109u8, 117u8, 108u8, 116u8, 105u8, 112u8, 108u8, 105u8, 101u8, 114u8, 58u8];

const C39: vector<u8> = vector[80u8, 111u8, 105u8, 110u8, 116u8, 115u8, 58u8];

const C40: vector<u8> = vector[73u8, 79u8, 78u8, 32u8, 112u8, 111u8, 105u8, 110u8, 116u8, 115u8, 32u8, 97u8, 119u8, 97u8, 114u8, 100u8, 101u8, 100u8, 32u8, 102u8, 111u8, 114u8, 32u8, 117u8, 110u8, 108u8, 105u8, 115u8, 116u8, 105u8, 110u8, 103u8, 58u8];

const C41: vector<u8> = vector[78u8, 70u8, 84u8, 32u8, 117u8, 110u8, 108u8, 105u8, 115u8, 116u8, 101u8, 100u8, 32u8, 115u8, 117u8, 99u8, 99u8, 101u8, 115u8, 115u8, 102u8, 117u8, 108u8, 108u8, 121u8];

const C42: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 77u8, 65u8, 75u8, 73u8, 78u8, 71u8, 32u8, 66u8, 73u8, 68u8, 32u8, 61u8, 61u8, 61u8];

const C43: vector<u8> = vector[67u8, 114u8, 101u8, 97u8, 116u8, 101u8, 100u8, 32u8, 98u8, 105u8, 100u8, 32u8, 119u8, 105u8, 116u8, 104u8, 32u8, 73u8, 68u8, 58u8];

const C44: vector<u8> = vector[66u8, 105u8, 100u8, 32u8, 99u8, 114u8, 101u8, 97u8, 116u8, 101u8, 100u8, 32u8, 115u8, 117u8, 99u8, 99u8, 101u8, 115u8, 115u8, 102u8, 117u8, 108u8, 108u8, 121u8];

const C45: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 67u8, 65u8, 78u8, 67u8, 69u8, 76u8, 73u8, 78u8, 71u8, 32u8, 66u8, 73u8, 68u8, 32u8, 61u8, 61u8, 61u8];

const C46: vector<u8> = vector[82u8, 101u8, 102u8, 117u8, 110u8, 100u8, 105u8, 110u8, 103u8, 32u8, 97u8, 109u8, 111u8, 117u8, 110u8, 116u8, 58u8];

const C47: vector<u8> = vector[73u8, 79u8, 78u8, 32u8, 112u8, 111u8, 105u8, 110u8, 116u8, 115u8, 32u8, 97u8, 119u8, 97u8, 114u8, 100u8, 101u8, 100u8, 32u8, 102u8, 111u8, 114u8, 32u8, 99u8, 97u8, 110u8, 99u8, 101u8, 108u8, 105u8, 110u8, 103u8, 58u8];

const C48: vector<u8> = vector[66u8, 105u8, 100u8, 32u8, 99u8, 97u8, 110u8, 99u8, 101u8, 108u8, 101u8, 100u8, 32u8, 115u8, 117u8, 99u8, 99u8, 101u8, 115u8, 115u8, 102u8, 117u8, 108u8, 108u8, 121u8];

const C49: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 66u8, 85u8, 89u8, 73u8, 78u8, 71u8, 32u8, 78u8, 70u8, 84u8, 32u8, 61u8, 61u8, 61u8];

const C50: vector<u8> = vector[84u8, 114u8, 97u8, 110u8, 115u8, 97u8, 99u8, 116u8, 105u8, 111u8, 110u8, 32u8, 112u8, 114u8, 105u8, 99u8, 101u8, 58u8];

const C51: vector<u8> = vector[67u8, 111u8, 109u8, 109u8, 105u8, 115u8, 115u8, 105u8, 111u8, 110u8, 58u8];

const C52: vector<u8> = vector[83u8, 81u8, 82u8, 84u8, 32u8, 112u8, 114u8, 105u8, 99u8, 101u8, 58u8];

const C53: vector<u8> = vector[73u8, 79u8, 78u8, 32u8, 112u8, 111u8, 105u8, 110u8, 116u8, 115u8, 32u8, 97u8, 119u8, 97u8, 114u8, 100u8, 101u8, 100u8, 32u8, 45u8, 32u8, 66u8, 117u8, 121u8, 101u8, 114u8, 58u8];

const C54: vector<u8> = vector[73u8, 79u8, 78u8, 32u8, 112u8, 111u8, 105u8, 110u8, 116u8, 115u8, 32u8, 97u8, 119u8, 97u8, 114u8, 100u8, 101u8, 100u8, 32u8, 45u8, 32u8, 83u8, 101u8, 108u8, 108u8, 101u8, 114u8, 58u8];

const C55: vector<u8> = vector[78u8, 70u8, 84u8, 32u8, 112u8, 117u8, 114u8, 99u8, 104u8, 97u8, 115u8, 101u8, 100u8, 32u8, 115u8, 117u8, 99u8, 99u8, 101u8, 115u8, 115u8, 102u8, 117u8, 108u8, 108u8, 121u8];

const C56: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 65u8, 67u8, 67u8, 69u8, 80u8, 84u8, 73u8, 78u8, 71u8, 32u8, 66u8, 73u8, 68u8, 32u8, 61u8, 61u8, 61u8];

const C57: vector<u8> = vector[80u8, 117u8, 114u8, 99u8, 104u8, 97u8, 115u8, 101u8, 32u8, 97u8, 109u8, 111u8, 117u8, 110u8, 116u8, 58u8];

const C58: vector<u8> = vector[67u8, 111u8, 109u8, 109u8, 105u8, 115u8, 115u8, 105u8, 111u8, 110u8, 32u8, 97u8, 109u8, 111u8, 117u8, 110u8, 116u8, 58u8];

const C59: vector<u8> = vector[66u8, 105u8, 100u8, 32u8, 97u8, 99u8, 99u8, 101u8, 112u8, 116u8, 101u8, 100u8, 32u8, 115u8, 117u8, 99u8, 99u8, 101u8, 115u8, 115u8, 102u8, 117u8, 108u8, 108u8, 121u8];

const C60: vector<u8> = vector[61u8, 61u8, 61u8, 32u8, 80u8, 82u8, 79u8, 67u8, 69u8, 83u8, 83u8, 73u8, 78u8, 71u8, 32u8, 80u8, 69u8, 78u8, 68u8, 73u8, 78u8, 71u8, 32u8, 67u8, 76u8, 65u8, 73u8, 77u8, 32u8, 61u8, 61u8, 61u8];

const C61: vector<u8> = vector[80u8, 101u8, 110u8, 100u8, 105u8, 110u8, 103u8, 32u8, 99u8, 108u8, 97u8, 105u8, 109u8, 32u8, 118u8, 101u8, 114u8, 105u8, 102u8, 105u8, 101u8, 100u8, 32u8, 102u8, 111u8, 114u8, 32u8, 98u8, 117u8, 121u8, 101u8, 114u8];

const C62: vector<u8> = vector[78u8, 70u8, 84u8, 32u8, 115u8, 117u8, 99u8, 99u8, 101u8, 115u8, 115u8, 102u8, 117u8, 108u8, 108u8, 121u8, 32u8, 116u8, 114u8, 97u8, 110u8, 115u8, 102u8, 101u8, 114u8, 114u8, 101u8, 100u8, 32u8, 116u8, 111u8, 32u8, 98u8, 117u8, 121u8, 101u8, 114u8, 39u8, 115u8, 32u8, 107u8, 105u8, 111u8, 115u8, 107u8];

const C63: vector<u8> = vector[44u8];

// -- functions -- 

public fun accept_bid<T0: key + store>(l0: &Clock, l1: &mut MarketPlaceStore, l2: &mut Kiosk, l3: &KioskOwnerCap, l4: &mut Kiosk, l5: ID, l6: ID, l7: address, l8: bool, l9: &TransferPolicy<T0>, l10: &mut AnimaIONs, l11: &mut AnimaChef, l12: &mut TxContext) {
    marketplace::validation_check(freeze(l1));
    let l55 = clock::timestamp_ms(l0);
    let l51 = tx_context::sender(freeze(l12));
    let l45 = type_name::into_string(type_name::get());
    debug::print(&string::utf8(C56));
    debug::print(&l51);
    debug::print(&l5);
    debug::print(&l6);
    debug::print(&l8);
    debug::print(&l45);
    assert!(linked_table::contains(&l1.user_activity, l51), C20);
    let l53 = *(&(&linked_table::remove(&mut (linked_table::borrow_mut(&mut l1.user_activity, l51)).listings, l5)).last_points_claimed_at);
    assert!(linked_table::contains(&l1.user_activity, l7), C21);
    let l29 = linked_table::borrow_mut(&mut l1.user_activity, l7);
    let l32 = 0u64;
    if (l8) {
        assert!(linked_table::contains(&l29.collection_bids, l45), C17);
        let l34 = linked_table::borrow_mut(&mut l29.collection_bids, l45);
        let l39 = 0u64;
        loop {
            if (l39 < freeze(l34).len()) {
                if (*(&(&(freeze(l34))[l39]).bid_id) != l6) {
                    l39 = l39 + 1u64;
                    continue
                };
                l32 = *(&(&vector::remove(l34, l39)).last_points_claimed_at);
            };
            break
        };
        if (freeze(l34).len() == 0u64) {
            
        }
    } else {
        assert!(linked_table::contains(&l29.bids, l5), C17);
        l32 = *(&(&linked_table::remove(&mut l29.bids, l5)).last_points_claimed_at);
        unstructured {
            goto 'label_217;
        }
    };
    /* block 217 */;
    let l36 = dynamic_object_field::borrow_mut(&mut l1.id, l45);
    assert!(linked_table::contains(&l36.listings, l5), C11);
    let (reg_158, reg_159);
    (reg_158, reg_159, reg_160, reg_161) = marketplace::destroy_listing(linked_table::remove(&mut l36.listings, l5));
    let l41 = reg_159;
    let l49 = reg_158;
    assert!(l41 == object::id(freeze(l2)), C19);
    let l24 = x2_balance::zero();
    if (l8) {
        let l35 = linked_table::borrow_mut(&mut l36.collection_bids, l7);
        let l40 = 0u64;
        loop {
            if (l40 < freeze(l35).len()) {
                if (object::uid_to_inner(&(&(freeze(l35))[l40]).id) != l6) {
                    l40 = l40 + 1u64;
                    continue
                };
                let l22 = vector::remove(l35, l40);
            };
            break
        };
        if (freeze(l35).len() == 0u64) {
            std::vector::destroy_empty(linked_table::remove(&mut l36.collection_bids, l7))
        }
    } else {
        assert!(object::uid_to_inner(&(&linked_table::remove(&mut (linked_table::borrow_mut(&mut l36.bids, l5)).bids, l7)).id) == l6, C26);
        unstructured {
            goto 'label_383;
        }
    };
    let (l38, l48);
    /* block 383 */;
    l48 = x2_balance::value(&l24);
    debug::print(&string::utf8(C57));
    debug::print(&l48);
    *(&mut l36.lifetime_volume) = *(&l36.lifetime_volume) + x2_balance::value(&l24)as u128;
    marketplace::update_collection_avg_price(l36, x2_balance::value(&l24));
    l38 = x2_balance::value(&l24) * *(&l1.commission_pct) / 100u64;
    debug::print(&string::utf8(C58));
    debug::print(&l38);
    kiosk::return_purchase_cap(l2, l49);
    ions::destroy_or_transfer_balance(l24, l51, l12);
    let l44 = kiosk::take(l2, l3, l5);
    kiosk::lock(l4, &l1.escrow_kiosk_cap, l9, l44);
    let l46 = PendingClaim { buyer: l7, nft_type: l45, price: l48 - l38 };
    if (linked_table::contains(&l1.pending_claims, l7)) {
        linked_table::push_back(&mut (linked_table::borrow_mut(&mut l1.pending_claims, l7)).pending_claims, l5, l46);
        unstructured {
            goto 'label_485;
        }
    } else {
        let l47 = PendingClaims { pending_claims: linked_table::new(l12) };
        linked_table::push_back(&mut (&mut l47).pending_claims, l5, l46);
        linked_table::push_back(&mut l1.pending_claims, l7, l47);
        unstructured {
            goto 'label_485;
        }
    };
    let (l17, l18);
    /* block 485 */;
    if (*(&l36.ion_points_enabled)) {
        let l16;
        if (*(&l36.ion_collection_multiplier) == 0u64) {
            l16 = C5;
            unstructured {
                goto 'label_502;
            }
        } else {
            l16 = *(&l36.ion_collection_multiplier);
            unstructured {
                goto 'label_502;
            }
        };
        /* block 502 */;
        let l37 = l16;
        let l27 = helpers::calculate_bid_proximity_multiplier(l48, *(&l36.avg_sale_price));
        let l42 = helpers::calculate_listing_proximity_multiplier(l48, *(&l36.avg_sale_price));
        let l28 = helpers::calculate_time_multiplier(l55 - l32, true);
        let l43 = helpers::calculate_time_multiplier(l55 - l53, true);
        let l54 = helpers::calculate_ion_points(l48, l37, l42, l43);
        marketplace::award_ion_points_with_referral(l51, l1, l10, l54, l0, l11);
        let l33 = helpers::calculate_ion_points(l48, l37, l27, l28);
        let l30 = linked_table::borrow_mut(&mut l1.user_activity, l7);
        *(&mut l30.claimable_points) = *(&l30.claimable_points) + l33;
        l18 = l54;
        l17 = l33;
        unstructured {
            goto 'label_579;
        }
    } else {
        l18 = 0u64;
        l17 = 0u64;
        unstructured {
            goto 'label_579;
        }
    };
    /* block 579 */;
    let l52 = l18;
    let l31 = l17;
    debug::print(&string::utf8(C53));
    debug::print(&l31);
    debug::print(&string::utf8(C54));
    debug::print(&l52);
    debug::print(&string::utf8(C59));
    event::emit(BidAcceptedEvent { nft_type: l45, nft_id: l5, seller: l51, buyer: l7, is_collection_bid: l8, price: l48, commission: l38, escrow_kiosk: object::id(freeze(l4)), buyer_ion_points: l31, seller_ion_points: l52 })
}

public fun accept_trait_bid<T0: key + store, T1: key + store>(l0: &mut MarketPlaceStore, l1: ID, l2: &mut Kiosk, l3: &KioskOwnerCap, l4: &mut TxContext): ( T0, T1, TraitBidsPotato) {
    marketplace::validation_check(freeze(l0));
    let l11 = tx_context::sender(freeze(l4));
    let l9 = type_name::into_string(type_name::get());
    marketplace::validate_collection_exists(freeze(l0));
    let l5 = dynamic_object_field::borrow_mut(&mut l0.id, l9);
    assert!(dynamic_object_field::exists_(&l5.id, C1), C15);
    assert!(*(&l5.are_trait_bids_enabled), C30);
    let l13 = dynamic_object_field::remove(&mut l5.id, C1);
    let l7 = TraitBidsPotato { id: object::id(&l13) };
    if (linked_table::contains(&(dynamic_object_field::borrow(&l0.id, l9)).listings, l1)) {
        assert!(linked_table::contains(&l0.user_activity, l11), C20);
        assert!(linked_table::contains(&(linked_table::borrow_mut(&mut l0.user_activity, l11)).listings, l1), C11);
        let l6 = dynamic_object_field::borrow_mut(&mut l0.id, l9);
        assert!(linked_table::contains(&l6.listings, l1), C18);
        let (reg_85, reg_86);
        (reg_85, reg_86, reg_87, reg_88) = marketplace::destroy_listing(linked_table::remove(&mut l6.listings, l1));
        let l8 = reg_86;
        let l10 = reg_85;
        assert!(l8 == object::id(freeze(l2)), C19);
        kiosk::return_purchase_cap(l2, l10);
        unstructured {
            goto 'label_153;
        }
    } else {
        unstructured {
            goto 'label_153;
        }
    };
    /* block 153 */;
    return (kiosk::take(l2, l3, l1), l13, l7)
}

public fun accept_trait_bid_settle<T0: key + store, T1: key + store>(l0: &mut MarketPlaceStore, l1: T1, l2: TraitBidsPotato, l3: &mut Kiosk, l4: &TransferPolicy<T0>, l5: ActiveTraitBid, l6: T0, l7: &mut AnimaIONs, l8: &Clock, l9: &mut AnimaChef, l10: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let TraitBidsPotato { id: reg_3 } = l2;
    assert!(object::id(&l1) == reg_3 : 0x2::object::ID, C24);
    let l37 = tx_context::sender(freeze(l10));
    let l33 = type_name::into_string(type_name::get());
    let l41 = clock::timestamp_ms(l8);
    let l22 = *(&(&l5).bidder);
    let l36 = *(&(&l5).bid_price);
    let l18 = object::id(&l5);
    let l17 = *(&(&l5).bid_at);
    let l32 = object::id(&l6);
    assert!(linked_table::contains(&l0.user_activity, l22), C21);
    let l23 = linked_table::borrow_mut(&mut l0.user_activity, l22);
    let l26 = 0u64;
    let l43 = linked_table::borrow_mut(&mut l23.trait_bids, l33);
    let l31 = 0u64;
    loop {
        if (l31 < freeze(l43).len()) {
            if (*(&(&(freeze(l43))[l31]).bid_id) != l18) {
                l31 = l31 + 1u64;
                continue
            };
            l26 = *(&(&vector::remove(l43, l31)).last_points_claimed_at);
        };
        assert!(l26 != 0u64, C29);
        let l27 = dynamic_object_field::borrow_mut(&mut l0.id, l33);
        dynamic_object_field::add(&mut l27.id, C1, l1);
        let l29 = l36 * *(&l0.commission_pct) / 100u64;
        let l16 = marketplace::destroy_active_trait_bid(l5);
        helpers::destroy_or_transfer_balance(x2_balance::split(&mut l27.sui_trait_bids_pool, l16), l37, l10);
        kiosk::lock(l3, &l0.escrow_kiosk_cap, l4, l6);
        let l34 = PendingClaim { buyer: l22, nft_type: l33, price: l36 - l29 };
        if (linked_table::contains(&l0.pending_claims, l22)) {
            linked_table::push_back(&mut (linked_table::borrow_mut(&mut l0.pending_claims, l22)).pending_claims, l32, l34)
        } else {
            let l35 = PendingClaims { pending_claims: linked_table::new(l10) };
            linked_table::push_back(&mut (&mut l35).pending_claims, l32, l34);
            linked_table::push_back(&mut l0.pending_claims, l22, l35)
        };
        let (l14, l15);
        *(&mut l27.lifetime_volume) = *(&l27.lifetime_volume) + l36as u128;
        marketplace::update_collection_avg_price(l27, l36);
        l14 = if (*(&l27.ion_points_enabled)) {
            let l28 = if (*(&l27.ion_collection_multiplier) == 0u64) {
                C5
            } else {
                *(&l27.ion_collection_multiplier)
            };
            let l19 = helpers::calculate_bid_proximity_multiplier(l36, *(&l27.avg_sale_price));
            let l20 = helpers::calculate_time_multiplier(l41 - l26, true);
            let l39 = helpers::calculate_ion_points(l36, l28, l19, l20);
            let l12 = if (l26 == 0u64) {
                l17
            } else {
                l26
            };
            let l40 = helpers::calculate_time_multiplier(l41 - l12, true);
            l15 = l39;
            helpers::calculate_ion_points(l36, l28, l19, l40)
        } else {
            l15 = 0u64;
            0u64
        };
        let l38 = l15;
        let l25 = l14;
        if (l38 > 0u64) {
            marketplace::award_ion_points_with_referral(l37, l0, l7, l38, l8, l9);
            break
        };
        break;
        let l24 = linked_table::borrow_mut(&mut l0.user_activity, l22);
        *(&mut l24.claimable_points) = *(&l24.claimable_points) + l25;
        event::emit(TraitBidAcceptedEvent { nft_type: l33, nft_id: l32, seller: l37, buyer: l22, price: l36, commission: l29, buyer_ion_points: l25, seller_ion_points: l38 });
        return
    }
}

public fun accept_unlisted_bid<T0: key + store>(l0: &Clock, l1: &mut MarketPlaceStore, l2: &mut Kiosk, l3: &mut Kiosk, l4: &KioskOwnerCap, l5: ID, l6: address, l7: ID, l8: u64, l9: bool, l10: &mut TransferPolicy<T0>, l11: &mut AnimaIONs, l12: &mut AnimaChef, l13: &mut TxContext): TransferRequest<T0> {
    marketplace::validation_check(freeze(l1));
    let l46 = clock::timestamp_ms(l0);
    let l43 = tx_context::sender(freeze(l13));
    let l39 = type_name::into_string(type_name::get());
    assert!(kiosk::has_item_with_type(freeze(l2), l5), C19);
    assert!(linked_table::contains(&l1.user_activity, l6), C21);
    let l26 = linked_table::borrow_mut(&mut l1.user_activity, l6);
    let l29 = 0u64;
    if (l9) {
        assert!(linked_table::contains(&l26.collection_bids, l39), C17);
        let l31 = linked_table::borrow_mut(&mut l26.collection_bids, l39);
        let l36 = 0u64;
        loop {
            if (l36 < freeze(l31).len()) {
                if (*(&(&(freeze(l31))[l36]).bid_id) != l7) {
                    l36 = l36 + 1u64;
                    continue
                };
                l29 = *(&(&vector::remove(l31, l36)).last_points_claimed_at);
            };
            break
        };
        if (freeze(l31).len() == 0u64) {
            
        }
    } else {
        assert!(linked_table::contains(&l26.bids, l5), C17);
        l29 = *(&(&linked_table::remove(&mut l26.bids, l5)).last_points_claimed_at);
        unstructured {
            goto 'label_190;
        }
    };
    let (l21, l33);
    /* block 190 */;
    l33 = dynamic_object_field::borrow_mut(&mut l1.id, l39);
    l21 = x2_balance::zero();
    if (l9) {
        let l32 = linked_table::borrow_mut(&mut l33.collection_bids, l6);
        let l37 = 0u64;
        loop {
            if (l37 < freeze(l32).len()) {
                if (object::uid_to_inner(&(&(freeze(l32))[l37]).id) != l7) {
                    l37 = l37 + 1u64;
                    continue
                };
                let l18 = vector::remove(l32, l37);
            };
            break
        };
        if (freeze(l32).len() == 0u64) {
            std::vector::destroy_empty(linked_table::remove(&mut l33.collection_bids, l6))
        }
    } else {
        assert!(linked_table::contains(&l33.bids, l5), C17);
        let l19 = linked_table::borrow_mut(&mut l33.bids, l5);
        assert!(linked_table::contains(&l19.bids, l6), C17);
        let l20 = linked_table::remove(&mut l19.bids, l6);
        unstructured {
            goto 'label_321;
        }
    };
    let (l35, l42, l47);
    /* block 321 */;
    *(&mut l33.lifetime_volume) = *(&l33.lifetime_volume) + x2_balance::value(&l21)as u128;
    marketplace::update_collection_avg_price(l33, x2_balance::value(&l21));
    l35 = x2_balance::value(&l21) * *(&l1.commission_pct) / 100u64;
    let l17 = x2_balance::value(&l21) - l8;
    kiosk::list(l2, l4, l5, l17);
    let (reg_244, reg_245) = kiosk::purchase(l2, l5, coin::from_balance(x2_balance::split(&mut l21, l17), l13));
    l47 = reg_245;
    royalty_rule::pay(l10, &mut l47, coin::from_balance(x2_balance::split(&mut l21, l8), l13));
    l42 = x2_balance::value(&l21);
    helpers::destroy_or_transfer_balance(l21, l43, l13);
    kiosk::lock(l3, &l1.escrow_kiosk_cap, freeze(l10), reg_244);
    let l40 = PendingClaim { buyer: l6, nft_type: l39, price: l42 - l35 };
    if (linked_table::contains(&l1.pending_claims, l6)) {
        linked_table::push_back(&mut (linked_table::borrow_mut(&mut l1.pending_claims, l6)).pending_claims, l5, l40);
        unstructured {
            goto 'label_430;
        }
    } else {
        let l41 = PendingClaims { pending_claims: linked_table::new(l13) };
        linked_table::push_back(&mut (&mut l41).pending_claims, l5, l40);
        linked_table::push_back(&mut l1.pending_claims, l6, l41);
        unstructured {
            goto 'label_430;
        }
    };
    let (l15, l16);
    /* block 430 */;
    if (*(&l33.ion_points_enabled)) {
        let l14;
        if (*(&l33.ion_collection_multiplier) == 0u64) {
            l14 = C5;
            unstructured {
                goto 'label_447;
            }
        } else {
            l14 = *(&l33.ion_collection_multiplier);
            unstructured {
                goto 'label_447;
            }
        };
        /* block 447 */;
        let l34 = l14;
        let l24 = helpers::calculate_bid_proximity_multiplier(l42, *(&l33.avg_sale_price));
        let l25 = helpers::calculate_time_multiplier(l46 - l29, true);
        let l45 = helpers::calculate_ion_points(l42, l34, l24, l25);
        marketplace::award_ion_points_with_referral(l43, l1, l11, l45, l0, l12);
        let l30 = helpers::calculate_ion_points(l42, l34, l24, l25);
        let l27 = linked_table::borrow_mut(&mut l1.user_activity, l6);
        *(&mut l27.claimable_points) = *(&l27.claimable_points) + l30;
        l16 = l45;
        l15 = l30;
        unstructured {
            goto 'label_512;
        }
    } else {
        l16 = 0u64;
        l15 = 0u64;
        unstructured {
            goto 'label_512;
        }
    };
    /* block 512 */;
    let l44 = l16;
    let l28 = l15;
    event::emit(BidAcceptedEvent { nft_type: l39, nft_id: l5, seller: l43, buyer: l6, is_collection_bid: l9, price: l42, commission: l35, escrow_kiosk: object::id(freeze(l3)), buyer_ion_points: l28, seller_ion_points: l44 });
    return l47
}

public fun add_trait_bidding_support<T0: key + store, T1: key + store>(l0: &mut MarketPlaceStore, l1: &TraitBidsAdminCap, l2: T1, l3: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let l5 = type_name::into_string(type_name::get());
    assert!(linked_table::contains(&l0.active_collections, l5), C15);
    assert!(dynamic_object_field::exists_(&l0.id, l5), C15);
    let l4 = dynamic_object_field::borrow_mut(&mut l0.id, l5);
    dynamic_object_field::add(&mut l4.id, C1, l2);
    *(&mut l4.are_trait_bids_enabled) = true;
    event::emit(UpdateTraitBiddingSupportEvent { nft_type: l5, are_trait_bids_enabled: true })
}

public fun award_bid_ion_points<T0: key + store>(l0: &mut MarketPlaceStore, l1: address, l2: ID, l3: &mut AnimaIONs, l4: &Clock, l5: &mut AnimaChef) {
    marketplace::validation_check(freeze(l0));
    let l15 = type_name::into_string(type_name::get());
    let l13 = clock::timestamp_ms(l4);
    assert!(linked_table::contains(&l0.user_activity, l1), C10);
    let l23 = linked_table::borrow_mut(&mut l0.user_activity, l1);
    assert!(linked_table::contains(&l23.bids, l2), C17);
    let l6;
    let l9 = linked_table::borrow_mut(&mut l23.bids, l2);
    if (*(&l9.last_points_claimed_at) == 0u64) {
        l6 = *(&l9.bid_at);
        unstructured {
            goto 'label_68;
        }
    } else {
        l6 = *(&l9.last_points_claimed_at);
        unstructured {
            goto 'label_68;
        }
    };
    let (l10, l21, l7);
    /* block 68 */;
    let l14 = l6;
    l21 = l13 - l14;
    l10 = dynamic_object_field::borrow(&l0.id, l15);
    if (*(&l10.ion_points_enabled)) {
        l7 = l21 > 0u64;
        unstructured {
            goto 'label_90;
        }
    } else {
        l7 = false;
        unstructured {
            goto 'label_90;
        }
    };
    /* block 90 */;
    if (l7) {
        let l22 = helpers::calculate_time_multiplier(l21, false);
        if (l22 > 0u64) {
            let l8;
            let l17 = helpers::calculate_bid_proximity_multiplier(*(&l9.bid_price), *(&l10.avg_sale_price));
            if (*(&l10.ion_collection_multiplier) == 0u64) {
                l8 = C5;
                unstructured {
                    goto 'label_123;
                }
            } else {
                l8 = *(&l10.ion_collection_multiplier);
                unstructured {
                    goto 'label_123;
                }
            };
            /* block 123 */;
            let l11 = l8;
            let l16 = helpers::calculate_ion_points(*(&l9.bid_price), l11, l17, l22);
            *(&mut l9.last_points_claimed_at) = l13;
            marketplace::award_ion_points_with_referral(l1, l0, l3, l16, l4, l5);
            if (ions::has_referrer(freeze(l3))) {
                let l20 = ions::get_referrer(freeze(l3));
                if (option::is_some(&l20)) {
                    let l19 = *(option::borrow(&l20));
                    let l18 = l16 * C6 / 100u64;
                    if (linked_table::contains(&l0.referrals, l19)) {
                        let l12 = linked_table::borrow_mut(&mut l0.referrals, l19);
                        *l12 = *l12 + l18;
                        unstructured {
                            goto 'label_221;
                        }
                    } else {
                        linked_table::push_back(&mut l0.referrals, l19, l18);
                        unstructured {
                            goto 'label_221;
                        }
                    }
                } else {
                    unstructured {
                        goto 'label_221;
                    }
                }
            } else {
                unstructured {
                    goto 'label_221;
                }
            }
        } else {
            unstructured {
                goto 'label_221;
            }
        }
    } else {
        unstructured {
            goto 'label_221;
        }
    };
    /* block 221 */
}

fun award_ion_points_with_referral(l0: address, l1: &mut MarketPlaceStore, l2: &mut AnimaIONs, l3: u64, l4: &Clock, l5: &mut AnimaChef) {
    let l9 = option::none();
    let l8 = 0u64;
    let l6 = 0u64;
    if (ions::has_referrer(freeze(l2))) {
        let l10 = ions::get_referrer(freeze(l2));
        if (option::is_some(&l10)) {
            option::fill(&mut l9, *(option::borrow(&l10)));
            l8 = math::mul_div_u128(l3as u128, C6as u128, 100u128);
            l6 = math::mul_div_u128(l3as u128, C3as u128, 100u128);
            if (linked_table::contains(&l1.referrals, *(option::borrow(&l9)))) {
                let l7 = linked_table::borrow_mut(&mut l1.referrals, *(option::borrow(&l9)));
                *l7 = *l7 + l8;
                unstructured {
                    goto 'label_64;
                }
            } else {
                linked_table::push_back(&mut l1.referrals, *(option::borrow(&l9)), l8);
                unstructured {
                    goto 'label_64;
                }
            }
        } else {
            unstructured {
                goto 'label_64;
            }
        }
    } else {
        unstructured {
            goto 'label_64;
        }
    };
    /* block 64 */;
    ions::award_ion_points(&l1.points_admin_cap, l4, l5, l2, l3 + l6);
    event::emit(AwardIonPointsEvent { user_address: l0, points_earned: l3 + l6, referrer_address: l9, referral_points: l8, bonus_points: l6, total_points: l3 + l6 })
}

public fun award_listing_ion_points<T0: key + store>(l0: &mut MarketPlaceStore, l1: address, l2: ID, l3: &mut AnimaIONs, l4: &Clock, l5: &mut AnimaChef) {
    marketplace::validation_check(freeze(l0));
    let l14 = type_name::into_string(type_name::get());
    let l11 = clock::timestamp_ms(l4);
    assert!(linked_table::contains(&l0.user_activity, l1), C10);
    let l19 = linked_table::borrow_mut(&mut l0.user_activity, l1);
    assert!(linked_table::contains(&l19.listings, l2), C11);
    let l6;
    let l13 = linked_table::borrow_mut(&mut l19.listings, l2);
    if (*(&l13.last_points_claimed_at) == 0u64) {
        l6 = *(&l13.listed_at);
        unstructured {
            goto 'label_68;
        }
    } else {
        l6 = *(&l13.last_points_claimed_at);
        unstructured {
            goto 'label_68;
        }
    };
    let (l17, l7, l9);
    /* block 68 */;
    let l12 = l6;
    l17 = l11 - l12;
    l9 = dynamic_object_field::borrow(&l0.id, l14);
    if (*(&l9.ion_points_enabled)) {
        l7 = l17 > 0u64;
        unstructured {
            goto 'label_90;
        }
    } else {
        l7 = false;
        unstructured {
            goto 'label_90;
        }
    };
    /* block 90 */;
    if (l7) {
        let l18 = helpers::calculate_time_multiplier(l17, false);
        if (l18 > 0u64) {
            let l8;
            let l16 = helpers::calculate_listing_proximity_multiplier(*(&l13.price), *(&l9.avg_sale_price));
            if (*(&l9.ion_collection_multiplier) == 0u64) {
                l8 = C5;
                unstructured {
                    goto 'label_123;
                }
            } else {
                l8 = *(&l9.ion_collection_multiplier);
                unstructured {
                    goto 'label_123;
                }
            };
            /* block 123 */;
            let l10 = l8;
            let l15 = helpers::calculate_ion_points(*(&l13.price), l10, l16, l18);
            marketplace::award_ion_points_with_referral(l1, l0, l3, l15, l4, l5);
            unstructured {
                goto 'label_168;
            }
        } else {
            unstructured {
                goto 'label_168;
            }
        }
    } else {
        unstructured {
            goto 'label_168;
        }
    };
    /* block 168 */
}

public fun buy<T0: key + store>(l0: &Clock, l1: &mut MarketPlaceStore, l2: &mut Kiosk, l3: ID, l4: Coin<SUI>, l5: &mut AnimaIONs, l6: &mut AnimaChef, l7: &mut TxContext): ( T0, TransferRequest<T0>, u64) {
    marketplace::validation_check(freeze(l1));
    let l46 = clock::timestamp_ms(l0);
    let l22 = tx_context::sender(freeze(l7));
    let l37 = kiosk::owner(freeze(l2));
    let l33 = type_name::into_string(type_name::get());
    debug::print(&string::utf8(C49));
    assert!(linked_table::contains(&l1.user_activity, l37), C10);
    let l39 = linked_table::borrow_mut(&mut l1.user_activity, l37);
    assert!(linked_table::contains(&l39.listings, l3), C11);
    let l29 = *(&(&linked_table::remove(&mut l39.listings, l3)).last_points_claimed_at);
    let l25 = dynamic_object_field::borrow_mut(&mut l1.id, l33);
    assert!(linked_table::contains(&l25.listings, l3), C18);
    let l30 = linked_table::remove(&mut l25.listings, l3);
    let l48 = *(&(&l30).price);
    let l47 = *(&(&l30).commission);
    debug::print(&string::utf8(C50));
    debug::print(&l48);
    debug::print(&string::utf8(C51));
    debug::print(&l47);
    *(&mut l25.lifetime_volume) = *(&l25.lifetime_volume) + l48as u128;
    marketplace::update_collection_avg_price(l25, l48);
    assert!(coin::value(&l4) >= l48, C13);
    let l43 = coin::into_balance(l4);
    let (reg_116, reg_117, reg_118, reg_119) = marketplace::destroy_listing(l30);
    let l27 = reg_119;
    let l34 = reg_118;
    assert!(reg_117 == object::id(freeze(l2)), C19);
    let (l10, l9);
    let l38 = l34 - l27;
    let l44 = x2_balance::split(&mut l43, l38);
    let (reg_145, reg_146) = kiosk::purchase_with_cap(l2, reg_116, coin::from_balance(l44, l7));
    let l32 = reg_145;
    if (*(&l25.ion_points_enabled)) {
        let l16;
        if (*(&l25.ion_collection_multiplier) == 0u64) {
            l16 = C5;
            unstructured {
                goto 'label_244;
            }
        } else {
            l16 = *(&l25.ion_collection_multiplier);
            unstructured {
                goto 'label_244;
            }
        };
        /* block 244 */;
        let l26 = l16;
        let l35 = helpers::calculate_listing_proximity_multiplier(l48, *(&l25.avg_sale_price));
        let l45 = helpers::calculate_time_multiplier(l46 - l29, true);
        let l42 = helpers::integer_sqrt(l34);
        debug::print(&string::utf8(C35));
        debug::print(&string::utf8(C38));
        debug::print(&l26);
        debug::print(&string::utf8(C37));
        debug::print(&l35);
        debug::print(&string::utf8(C36));
        debug::print(&l45);
        debug::print(&string::utf8(C52));
        debug::print(&l42);
        let l41 = helpers::calculate_ion_points(l42, l26, l35, l45);
        *(&mut l39.claimable_points) = *(&l39.claimable_points) + l41;
        let l24 = helpers::calculate_ion_points(l42, l26, l35, C5);
        marketplace::award_ion_points_with_referral(l22, l1, l5, l24, l0, l6);
        l10 = l41;
        l9 = l24;
        unstructured {
            goto 'label_342;
        }
    } else {
        l10 = 0u64;
        l9 = 0u64;
        unstructured {
            goto 'label_342;
        }
    };
    /* block 342 */;
    let l40 = l10;
    let l23 = l9;
    debug::print(&string::utf8(C53));
    debug::print(&l23);
    debug::print(&string::utf8(C54));
    debug::print(&l40);
    event::emit(BuyEvent { nft_type: l33, nft_id: object::id(&l32), buyer: l22, seller: l37, seller_kiosk: object::id(freeze(l2)), price: l34, commission: l27, buyer_ion_points: l23, seller_ion_points: l40 });
    debug::print(&string::utf8(C55));
    helpers::destroy_or_transfer_balance(l43, l22, l7);
    return (l32, reg_146, l34 - l27)
}

public fun cancel_bid<T0: key + store>(l0: &mut MarketPlaceStore, l1: Option<ID>, l2: ID, l3: &mut AnimaIONs, l4: &Clock, l5: &mut AnimaChef, l6: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let l27 = tx_context::sender(freeze(l6));
    let l37 = type_name::into_string(type_name::get());
    let l33 = !(option::is_some(&l1));
    let l43 = clock::timestamp_ms(l4);
    debug::print(&string::utf8(C45));
    debug::print(&l27);
    debug::print(&l1);
    debug::print(&l2);
    debug::print(&l33);
    debug::print(&l37);
    assert!(linked_table::contains(&l0.active_collections, l37), C15);
    let l28 = dynamic_object_field::borrow_mut(&mut l0.id, l37);
    let l40 = x2_balance::zero();
    if (!(l33)) {
        let l35 = *(option::borrow(&l1));
        assert!(linked_table::contains(&l28.bids, l35), C17);
        let l21 = linked_table::remove(&mut (linked_table::borrow_mut(&mut l28.bids, l35)).bids, l27);
        unstructured {
            goto 'label_166;
        }
    } else {
        assert!(linked_table::contains(&l28.collection_bids, l27), C17);
        let l20 = linked_table::borrow_mut(&mut l28.collection_bids, l27);
        let l30 = 0u64;
        loop {
            if (l30 < freeze(l20).len()) {
                if (object::uid_to_inner(&(&(freeze(l20))[l30]).id) != l2) {
                    l30 = l30 + 1u64;
                    continue
                };
                let l22 = vector::remove(l20, l30);
            };
            break
        };
        if (freeze(l20).len() == 0u64) {
            std::vector::destroy_empty(linked_table::remove(&mut l28.collection_bids, l27))
        }
    };
    /* block 166 */;
    debug::print(&string::utf8(C46));
    debug::print(&x2_balance::value(&l40));
    helpers::destroy_or_transfer_balance(l40, l27, l6);
    assert!(linked_table::contains(&l0.user_activity, l27), C10);
    let l44 = linked_table::borrow_mut(&mut l0.user_activity, l27);
    let l26 = 0u64;
    let l34 = 0u64;
    if (l33) {
        assert!(linked_table::contains(&l44.collection_bids, l37), C17);
        let l25 = linked_table::borrow_mut(&mut l44.collection_bids, l37);
        let l31 = 0u64;
        loop {
            if (l31 < freeze(l25).len()) {
                if (*(&(&(freeze(l25))[l31]).bid_id) != l2) {
                    l31 = l31 + 1u64;
                    continue
                };
                let l23 = vector::remove(l25, l31);
                l26 = *(&(&l23).bid_price);
                l34 = *(&(&l23).last_points_claimed_at);
            };
            break
        };
        if (freeze(l25).len() == 0u64) {
            
        }
    } else {
        let l36 = *(option::borrow(&l1));
        assert!(linked_table::contains(&l44.bids, l36), C17);
        let l24 = linked_table::remove(&mut l44.bids, l36);
        l26 = *(&(&l24).bid_price);
        l34 = *(&(&l24).last_points_claimed_at);
        unstructured {
            goto 'label_321;
        }
    };
    let l9;
    /* block 321 */;
    let l41 = l43 - l34;
    if (*(&l28.ion_points_enabled)) {
        let l14;
        let l42 = helpers::calculate_time_multiplier(l41, false);
        let l39 = helpers::calculate_bid_proximity_multiplier(l26, *(&l28.avg_sale_price));
        if (*(&l28.ion_collection_multiplier) == 0u64) {
            l14 = C5;
            unstructured {
                goto 'label_354;
            }
        } else {
            l14 = *(&l28.ion_collection_multiplier);
            unstructured {
                goto 'label_354;
            }
        };
        /* block 354 */;
        let l29 = l14;
        let l38 = helpers::calculate_ion_points(l26, l29, l39, l42);
        debug::print(&string::utf8(C35));
        debug::print(&string::utf8(C34));
        debug::print(&l41);
        debug::print(&string::utf8(C36));
        debug::print(&l42);
        debug::print(&string::utf8(C37));
        debug::print(&l39);
        debug::print(&string::utf8(C38));
        debug::print(&l29);
        debug::print(&string::utf8(C39));
        debug::print(&l38);
        marketplace::award_ion_points_with_referral(l27, l0, l3, l38, l4, l5);
        l9 = l38;
        unstructured {
            goto 'label_424;
        }
    } else {
        l9 = 0u64;
        unstructured {
            goto 'label_424;
        }
    };
    /* block 424 */;
    let l32 = l9;
    debug::print(&string::utf8(C47));
    debug::print(&l32);
    debug::print(&string::utf8(C48));
    event::emit(CancelBidEvent { bid_id: l2, nft_type: l37, bidder: l27, nft_id: l1, is_collection_bid: l33, cancelled_at: l43, ion_points_awarded: l32 })
}

public fun cancel_trait_bid<T0: key + store, T1: key + store>(l0: &mut MarketPlaceStore, l1: &mut TxContext): ( T1, TraitBidsPotato) {
    marketplace::validation_check(freeze(l0));
    let l4 = type_name::into_string(type_name::get());
    marketplace::validate_collection_exists(freeze(l0));
    let l2 = dynamic_object_field::borrow_mut(&mut l0.id, l4);
    assert!(dynamic_object_field::exists_(&l2.id, C1), C15);
    let l5 = dynamic_object_field::remove(&mut l2.id, C1);
    let l3 = TraitBidsPotato { id: object::id(&l5) };
    return (l5, l3)
}

public fun cancel_trait_bid_settle<T0: key + store, T1: key + store>(l0: &Clock, l1: &mut MarketPlaceStore, l2: ActiveTraitBid, l3: T1, l4: TraitBidsPotato, l5: &mut AnimaIONs, l6: &mut AnimaChef, l7: &mut TxContext) {
    marketplace::validation_check(freeze(l1));
    let TraitBidsPotato { id: reg_3 } = l4;
    assert!(object::id(&l3) == reg_3 : 0x2::object::ID, C24);
    let l23 = type_name::into_string(type_name::get());
    let l27 = clock::timestamp_ms(l0);
    let l15 = *(&(&l2).bidder);
    let l13 = *(&(&l2).bid_at);
    let l14 = object::id(&l2);
    assert!(linked_table::contains(&l1.user_activity, l15), C10);
    let l30 = linked_table::borrow_mut(&mut l1.user_activity, l15);
    let l22 = 0u64;
    if (linked_table::contains(&l30.trait_bids, l23)) {
        let l29 = linked_table::borrow_mut(&mut l30.trait_bids, l23);
        let l20 = 0u64;
        while (l20 < freeze(l29).len()) {
            if (*(&(&(freeze(l29))[l20]).bid_id) == l14) {
                l22 = *(&(&vector::remove(l29, l20)).last_points_claimed_at);
                break
            };
            l20 = l20 + 1u64;
        }
    } else {
        unstructured {
            goto 'label_109;
        }
    };
    let (l12, l25);
    /* block 109 */;
    let l16 = dynamic_object_field::borrow_mut(&mut l1.id, l23);
    dynamic_object_field::add(&mut l16.id, C1, l3);
    l25 = marketplace::destroy_active_trait_bid(l2);
    helpers::destroy_or_transfer_balance(x2_balance::split(&mut l16.sui_trait_bids_pool, l25), l15, l7);
    let l17 = dynamic_object_field::borrow(&l1.id, l23);
    if (*(&l17.ion_points_enabled)) {
        let l8;
        if (l22 == 0u64) {
            l8 = l13;
            unstructured {
                goto 'label_149;
            }
        } else {
            l8 = l22;
            unstructured {
                goto 'label_149;
            }
        };
        let l11;
        /* block 149 */;
        let l26 = helpers::calculate_time_multiplier(l27 - l8, false);
        if (l26 > 0u64) {
            let l10;
            let l24 = helpers::calculate_bid_proximity_multiplier(l25, *(&l17.avg_sale_price));
            if (*(&l17.ion_collection_multiplier) == 0u64) {
                l10 = C5;
                unstructured {
                    goto 'label_180;
                }
            } else {
                l10 = *(&l17.ion_collection_multiplier);
                unstructured {
                    goto 'label_180;
                }
            };
            /* block 180 */;
            let l18 = l10;
            l11 = helpers::calculate_ion_points(l25, l18, l24, l26);
            unstructured {
                goto 'label_193;
            }
        } else {
            l11 = 0u64;
            unstructured {
                goto 'label_193;
            }
        };
        /* block 193 */;
        l12 = l11;
        unstructured {
            goto 'label_200;
        }
    } else {
        l12 = 0u64;
        unstructured {
            goto 'label_200;
        }
    };
    let l21;
    /* block 200 */;
    l21 = l12;
    if (l21 > 0u64) {
        marketplace::award_ion_points_with_referral(l15, l1, l5, l21, l0, l6);
        unstructured {
            goto 'label_222;
        }
    } else {
        unstructured {
            goto 'label_222;
        }
    };
    /* block 222 */;
    event::emit(TraitBidCancelledEvent { nft_type: l23, bidder: l15, bid_id: l14, refund_amount: l25, ion_points_awarded: l21, cancelled_at: l27 })
}

public fun claim_referral_points(l0: &Clock, l1: &mut AnimaChef, l2: &mut MarketPlaceStore, l3: &mut AnimaIONs, l4: &mut TxContext) {
    marketplace::validation_check(freeze(l2));
    let l7 = tx_context::sender(freeze(l4));
    let l10 = option::none();
    let l9 = 0u64;
    let l5 = 0u64;
    assert!(linked_table::contains(&l2.referrals, l7), C10);
    let l6 = *(linked_table::borrow(&l2.referrals, l7));
    *(linked_table::borrow_mut(&mut l2.referrals, l7)) = 0u64;
    if (ions::has_referrer(freeze(l3))) {
        let l11 = ions::get_referrer(freeze(l3));
        if (option::is_some(&l11)) {
            option::fill(&mut l10, *(option::borrow(&l11)));
            l9 = math::mul_div_u128(l6as u128, C6as u128, 100u128);
            l5 = math::mul_div_u128(l6as u128, C3as u128, 100u128);
            if (linked_table::contains(&l2.referrals, *(option::borrow(&l10)))) {
                let l8 = linked_table::borrow_mut(&mut l2.referrals, *(option::borrow(&l10)));
                *l8 = *l8 + l9;
                unstructured {
                    goto 'label_99;
                }
            } else {
                linked_table::push_back(&mut l2.referrals, *(option::borrow(&l10)), l9);
                unstructured {
                    goto 'label_99;
                }
            }
        } else {
            unstructured {
                goto 'label_99;
            }
        }
    } else {
        unstructured {
            goto 'label_99;
        }
    };
    /* block 99 */;
    let l12 = l9 + l5;
    ions::award_ion_points(&l2.points_admin_cap, l0, l1, l3, l12);
    event::emit(ReferralPointsClaimedEvent { user_address: l7, claimable_points: l6, referral_points: l9, bonus_points: l5, total_points: l12 })
}

public fun collect_commissions(l0: &mut MarketPlaceStore, l1: &CollectorCap, l2: address, l3: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    event::emit(CollectCommissionsEvent { recepient: l2, amount: x2_balance::value(&l0.available_sui) });
    helpers::destroy_or_transfer_balance(x2_balance::withdraw_all(&mut l0.available_sui), l2, l3)
}

public fun complete_trait_bid<T0: key + store, T1: key + store>(l0: &mut MarketPlaceStore, l1: T1, l2: TraitBidsPotato, l3: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let TraitBidsPotato { id: reg_3 } = l2;
    assert!(object::id(&l1) == reg_3 : 0x2::object::ID, C24);
    let l5 = type_name::into_string(type_name::get());
    dynamic_object_field::add(&mut (dynamic_object_field::borrow_mut(&mut l0.id, l5)).id, C1, l1)
}

fun create_trait_summary(l0: Option<String>, l1: Option<String>, l2: Option<String>): String {
    let l4 = ascii::string(C2);
    let l3 = true;
    if (option::is_some(&l0)) {
        if (!(l3)) {
            ascii::append(&mut l4, ascii::string(C63));
            unstructured {
                goto 'label_15;
            }
        } else {
            unstructured {
                goto 'label_15;
            }
        };
        /* block 15 */;
        ascii::append(&mut l4, *(option::borrow(&l0)));
        l3 = false;
        unstructured {
            goto 'label_22;
        }
    } else {
        unstructured {
            goto 'label_22;
        }
    };
    /* block 22 */;
    if (option::is_some(&l1)) {
        if (!(l3)) {
            ascii::append(&mut l4, ascii::string(C63));
            unstructured {
                goto 'label_32;
            }
        } else {
            unstructured {
                goto 'label_32;
            }
        };
        /* block 32 */;
        ascii::append(&mut l4, *(option::borrow(&l1)));
        l3 = false;
        unstructured {
            goto 'label_39;
        }
    } else {
        unstructured {
            goto 'label_39;
        }
    };
    /* block 39 */;
    if (option::is_some(&l2)) {
        if (!(l3)) {
            ascii::append(&mut l4, ascii::string(C63));
            unstructured {
                goto 'label_49;
            }
        } else {
            unstructured {
                goto 'label_49;
            }
        };
        /* block 49 */;
        ascii::append(&mut l4, *(option::borrow(&l2)));
        unstructured {
            goto 'label_54;
        }
    } else {
        unstructured {
            goto 'label_54;
        }
    };
    /* block 54 */;
    return l4
}

fun destroy_active_bid(l0: ActiveBid): Balance<SUI> {
    let ActiveBid { id: reg_1, bidder: reg_2, bid_price: reg_3, balance: reg_4, bid_at: reg_5 } = l0;
    object::delete(reg_1 : 0x2::object::UID);
    return reg_4 : 0x2::balance::Balance<0x2::sui::SUI>
}

fun destroy_active_trait_bid(l0: ActiveTraitBid): u64 {
    let ActiveTraitBid { id: reg_1, bidder: reg_2, bid_price: reg_3, bid_at: reg_4, trait_key1: reg_5, trait_value1: reg_6, trait_key2: reg_7, trait_value2: reg_8, trait_key3: reg_9, trait_value3: reg_10 } = l0;
    object::delete(reg_1 : 0x2::object::UID);
    return reg_3 : u64
}

fun destroy_listing<T0: key + store>(l0: Listing<T0>): ( PurchaseCap<T0>, ID, u64, u64) {
    let Listing { seller: reg_1, kiosk_id: reg_2, nft_id: reg_3, cap: reg_4, price: reg_5, commission: reg_6, listed_at: reg_7 } = l0;
    return (reg_4 : 0x2::kiosk::PurchaseCap<T0>, reg_2 : 0x2::object::ID, reg_5 : u64, reg_6 : u64)
}

fun ensure_user_activity_exists(l0: &mut LinkedTable<address, UserInfo>, l1: address, l2: &mut TxContext) {
    if (!(linked_table::contains(freeze(l0), l1))) {
        let l3 = UserInfo { id: object::new(l2), listings: linked_table::new(l2), bids: linked_table::new(l2), collection_bids: linked_table::new(l2), trait_bids: linked_table::new(l2), claimable_points: 0u64 };
        linked_table::push_back(l0, l1, l3);
        unstructured {
            goto 'label_28;
        }
    } else {
        unstructured {
            goto 'label_28;
        }
    };
    /* block 28 */
}

public fun get_active_bid_balance(l0: &ActiveBid): u64 {
    return x2_balance::value(&l0.balance)
}

public fun get_active_bid_info(l0: &ActiveTraitBid): (
    address,
    u64,
    u64,
    Option<String>,
    Option<vector<String>>, Option<String>, Option<vector<String>>, Option<String>, Option<vector<String>>) {
    return (*(&l0.bidder), *(&l0.bid_price), *(&l0.bid_at), *(&l0.trait_key1), *(&l0.trait_value1), *(&l0.trait_key2), *(&l0.trait_value2), *(&l0.trait_key3), *(&l0.trait_value3))
}

public fun get_bids_for_any_nft<T0: key + store>(l0: &MarketPlaceStore, l1: ID, l2: Option<address>, l3: u64): ( vector<address>, vector<ID>, vector<u64>, vector<u64>, u64, bool) {
    let l16 = type_name::into_string(type_name::get());
    let l11 = vector[];
    let l9 = vector[];
    let l10 = vector[];
    let l7 = vector[];
    if (!(dynamic_object_field::exists_(&l0.id, l16))) {
        return (l11, l9, l10, l7, 0u64, false)
    };
    let l12 = dynamic_object_field::borrow(&l0.id, l16);
    let l15 = linked_table::contains(&l12.listings, l1);
    if (!(linked_table::contains(&l12.bids, l1))) {
        return (l11, l9, l10, l7, 0u64, l15)
    };
    let l4;
    let l6 = linked_table::borrow(&l12.bids, l1);
    if (option::is_some(&l2)) {
        l4 = l2;
        unstructured {
            goto 'label_67;
        }
    } else {
        l4 = *(linked_table::front(&l6.bids));
        unstructured {
            goto 'label_67;
        }
    };
    let (l13, l14);
    /* block 67 */;
    l13 = l4;
    l14 = 0u64;
    while (option::is_some(&l13) && l14 < l3) {
        let l17 = option::borrow(&l13);
        let l8 = linked_table::borrow(&l6.bids, *l17);
        (&mut l11).push_back(*l17);
        (&mut l9).push_back(object::uid_to_inner(&l8.id));
        (&mut l10).push_back(*(&l8.bid_price));
        (&mut l7).push_back(x2_balance::value(&l8.balance));
        l13 = *(linked_table::next(&l6.bids, *l17));
        l14 = l14 + 1u64;
    };
    return (l11, l9, l10, l7, linked_table::length(&l6.bids), l15)
}

public fun get_bids_for_listing<T0: key + store>(l0: &MarketPlaceStore, l1: ID, l2: Option<address>, l3: u64): ( vector<address>, vector<ID>, vector<u64>, vector<u64>, u64) {
    let l15 = type_name::into_string(type_name::get());
    let l11 = vector[];
    let l9 = vector[];
    let l10 = vector[];
    let l7 = vector[];
    if (!(dynamic_object_field::exists_(&l0.id, l15))) {
        return (l11, l9, l10, l7, 0u64)
    };
    let l12 = dynamic_object_field::borrow(&l0.id, l15);
    if (!(linked_table::contains(&l12.bids, l1))) {
        return (l11, l9, l10, l7, 0u64)
    };
    let l4;
    let l6 = linked_table::borrow(&l12.bids, l1);
    if (option::is_some(&l2)) {
        l4 = l2;
        unstructured {
            goto 'label_60;
        }
    } else {
        l4 = *(linked_table::front(&l6.bids));
        unstructured {
            goto 'label_60;
        }
    };
    let (l13, l14);
    /* block 60 */;
    l13 = l4;
    l14 = 0u64;
    while (option::is_some(&l13) && l14 < l3) {
        let l16 = option::borrow(&l13);
        let l8 = linked_table::borrow(&l6.bids, *l16);
        (&mut l11).push_back(*l16);
        (&mut l9).push_back(object::uid_to_inner(&l8.id));
        (&mut l10).push_back(*(&l8.bid_price));
        (&mut l7).push_back(x2_balance::value(&l8.balance));
        l13 = *(linked_table::next(&l6.bids, *l16));
        l14 = l14 + 1u64;
    };
    return (l11, l9, l10, l7, linked_table::length(&l6.bids))
}

public fun get_collection_bidders_for_collection<T0: key + store>(l0: &MarketPlaceStore, l1: Option<address>, l2: u64): ( vector<address>, vector<u64>, u64) {
    let l11 = type_name::into_string(type_name::get());
    let l5 = vector[];
    let l6 = vector[];
    if (!(dynamic_object_field::exists_(&l0.id, l11))) {
        return (l5, l6, 0u64)
    };
    let l3;
    let l8 = dynamic_object_field::borrow(&l0.id, l11);
    if (option::is_some(&l1)) {
        l3 = l1;
        unstructured {
            goto 'label_35;
        }
    } else {
        l3 = *(linked_table::front(&l8.collection_bids));
        unstructured {
            goto 'label_35;
        }
    };
    let (l10, l9);
    /* block 35 */;
    l9 = l3;
    l10 = 0u64;
    while (option::is_some(&l9) && l10 < l2) {
        let l12 = option::borrow(&l9);
        let l7 = linked_table::borrow(&l8.collection_bids, *l12);
        (&mut l5).push_back(*l12);
        (&mut l6).push_back(l7.len());
        l9 = *(linked_table::next(&l8.collection_bids, *l12));
        l10 = l10 + 1u64;
    };
    return (l5, l6, linked_table::length(&l8.collection_bids))
}

public fun get_collection_bids_by_user_for_collection<T0: key + store>(l0: &MarketPlaceStore, l1: address, l2: u64, l3: u64): ( vector<ID>, vector<u64>, vector<u64>, vector<u64>, u64) {
    let l13 = type_name::into_string(type_name::get());
    let l9 = vector[];
    let l10 = vector[];
    let l7 = vector[];
    let l8 = vector[];
    if (!(dynamic_object_field::exists_(&l0.id, l13))) {
        return (l9, l10, l7, l8, 0u64)
    };
    let l11 = dynamic_object_field::borrow(&l0.id, l13);
    if (!(linked_table::contains(&l11.collection_bids, l1))) {
        return (l9, l10, l7, l8, 0u64)
    };
    let l6 = linked_table::borrow(&l11.collection_bids, l1);
    let l12 = l2;
    while (l12 < l6.len() && l12 < l3) {
        let l5 = &l6[l12];
        (&mut l9).push_back(object::uid_to_inner(&l5.id));
        (&mut l10).push_back(*(&l5.bid_price));
        (&mut l7).push_back(x2_balance::value(&l5.balance));
        (&mut l8).push_back(*(&l5.bid_at));
        l12 = l12 + 1u64;
    };
    return (l9, l10, l7, l8, l6.len())
}

public fun get_collection_fee(l0: &MarketPlaceStore): u64 {
    return *(&l0.new_collection_fee)
}

public fun get_collection_marketplace_info<T0: key + store>(l0: &MarketPlaceStore): ( u64, u64, u64, u128, bool, u64, u64) {
    let l2 = type_name::into_string(type_name::get());
    if (!(dynamic_object_field::exists_(&l0.id, l2))) {
        return (0u64, 0u64, 0u64, 0u128, false, 0u64, 0u64)
    };
    let l1 = dynamic_object_field::borrow(&l0.id, l2);
    return (linked_table::length(&l1.listings), linked_table::length(&l1.bids), linked_table::length(&l1.collection_bids), *(&l1.lifetime_volume), *(&l1.ion_points_enabled), *(&l1.ion_collection_multiplier), *(&l1.avg_sale_price))
}

public fun get_listings_for_marketplace<T0: key + store>(l0: &MarketPlaceStore, l1: Option<ID>, l2: u64): ( vector<address>, vector<ID>, vector<ID>, vector<u64>, vector<u64>, u64) {
    let l13 = type_name::into_string(type_name::get());
    let l15 = vector[];
    let l9 = vector[];
    let l12 = vector[];
    let l14 = vector[];
    let l6 = vector[];
    if (!(dynamic_object_field::exists_(&l0.id, l13))) {
        return (l15, l9, l12, l14, l6, 0u64)
    };
    let l3;
    let l5 = dynamic_object_field::borrow(&l0.id, l13);
    if (option::is_some(&l1)) {
        l3 = l1;
        unstructured {
            goto 'label_44;
        }
    } else {
        l3 = *(linked_table::front(&l5.listings));
        unstructured {
            goto 'label_44;
        }
    };
    let (l7, l8);
    /* block 44 */;
    l7 = l3;
    l8 = 0u64;
    while (option::is_some(&l7) && l8 < l2) {
        let l11 = option::borrow(&l7);
        let l10 = linked_table::borrow(&l5.listings, *l11);
        (&mut l12).push_back(*l11);
        (&mut l15).push_back(*(&l10.seller));
        (&mut l9).push_back(*(&l10.kiosk_id));
        (&mut l14).push_back(*(&l10.price));
        (&mut l6).push_back(*(&l10.commission));
        l7 = *(linked_table::next(&l5.listings, *l11));
        l8 = l8 + 1u64;
    };
    return (l15, l9, l12, l14, l6, linked_table::length(&l5.listings))
}

public fun get_marketplace_info(l0: &MarketPlaceStore): ( address, bool, u64, u64, u64, u64, u64, ID, u64, u64) {
    return (object::uid_to_address(&l0.id), *(&l0.is_permissionless), *(&l0.new_collection_fee), *(&l0.commission_pct), x2_balance::value(&l0.available_sui), linked_table::length(&l0.user_activity), linked_table::length(&l0.active_collections), *(&l0.kiosk_id), linked_table::length(&l0.referrals), *(&l0.version))
}

public fun get_referral_points_balance(l0: &MarketPlaceStore, l1: address): u64 {
    let l2;
    if (linked_table::contains(&l0.referrals, l1)) {
        l2 = *(linked_table::borrow(&l0.referrals, l1));
        unstructured {
            goto 'label_16;
        }
    } else {
        l2 = 0u64;
        unstructured {
            goto 'label_16;
        }
    };
    /* block 16 */;
    return l2
}

public fun get_trait_bid_details(l0: &MarketPlaceStore, l1: address, l2: ID): (
    String,
    u64,
    Option<String>,
    Option<vector<String>>, Option<String>, Option<vector<String>>, Option<String>, Option<vector<String>>, u64, u64) {
    if (!(linked_table::contains(&l0.user_activity, l1))) {
        return (ascii::string(C2), 0u64, option::none(), option::none(), option::none(), option::none(), option::none(), option::none(), 0u64, 0u64)
    };
    let l8 = linked_table::borrow(&l0.user_activity, l1);
    let l3 = *(linked_table::front(&l8.trait_bids));
    loop {
        if (!(option::is_some(&l3))) {
            return (ascii::string(C2), 0u64, option::none(), option::none(), option::none(), option::none(), option::none(), option::none(), 0u64, 0u64)
        };
        let l5 = option::borrow(&l3);
        let l7 = linked_table::borrow(&l8.trait_bids, *l5);
        let l4 = 0u64;
        loop {
            if (l4 >= l7.len()) {
                l3 = *(linked_table::next(&l8.trait_bids, *l5));
                break
            };
            let l6 = &l7[l4];
            if (*(&l6.bid_id) == l2) {
                
            } else {
                l4 = l4 + 1u64;
                continue
            };
            return (*(&l6.nft_type), *(&l6.bid_price), *(&l6.trait_key1), *(&l6.trait_value1), *(&l6.trait_key2), *(&l6.trait_value2), *(&l6.trait_key3), *(&l6.trait_value3), *(&l6.bid_at), *(&l6.last_points_claimed_at))
        }
    }
}

public fun get_user_activity_overview(l0: &MarketPlaceStore, l1: address): ( u64, u64, u64, u64, u64) {
    let (l2, l3, l4, l5, l6);
    if (!(linked_table::contains(&l0.user_activity, l1))) {
        l6 = 0u64;
        l5 = 0u64;
        l4 = 0u64;
        l3 = 0u64;
        l2 = 0u64;
        unstructured {
            goto 'label_44;
        }
    } else {
        let l7 = linked_table::borrow(&l0.user_activity, l1);
        l6 = *(&l7.claimable_points);
        l5 = linked_table::length(&l7.trait_bids);
        l4 = linked_table::length(&l7.collection_bids);
        l3 = linked_table::length(&l7.bids);
        l2 = linked_table::length(&l7.listings);
        unstructured {
            goto 'label_44;
        }
    };
    /* block 44 */;
    return (l2, l3, l4, l5, l6)
}

public fun get_user_addresses_list(l0: &MarketPlaceStore, l1: Option<address>, l2: u64): ( vector<address>, u64) {
    let l3;
    let l8 = vector[];
    if (option::is_some(&l1)) {
        l3 = l1;
        unstructured {
            goto 'label_13;
        }
    } else {
        l3 = *(linked_table::front(&l0.user_activity));
        unstructured {
            goto 'label_13;
        }
    };
    let (l5, l6);
    /* block 13 */;
    l5 = l3;
    l6 = 0u64;
    while (option::is_some(&l5) && l6 < l2) {
        let l7 = option::borrow(&l5);
        (&mut l8).push_back(*l7);
        l5 = *(linked_table::next(&l0.user_activity, *l7));
        l6 = l6 + 1u64;
    };
    return (l8, linked_table::length(&l0.user_activity))
}

public fun get_user_bids_info(l0: &MarketPlaceStore, l1: address, l2: Option<ID>, l3: u64): ( vector<ID>, vector<String>, vector<ID>, vector<u64>, vector<u64>, vector<u64>, u64) {
    let l14 = vector[];
    let l15 = vector[];
    let l7 = vector[];
    let l9 = vector[];
    let l6 = vector[];
    let l12 = vector[];
    if (!(linked_table::contains(&l0.user_activity, l1))) {
        return (l14, l15, l7, l9, l6, l12, 0u64)
    };
    let l4;
    let l16 = linked_table::borrow(&l0.user_activity, l1);
    if (option::is_some(&l2)) {
        l4 = l2;
        unstructured {
            goto 'label_44;
        }
    } else {
        l4 = *(linked_table::front(&l16.bids));
        unstructured {
            goto 'label_44;
        }
    };
    let (l10, l11);
    /* block 44 */;
    l10 = l4;
    l11 = 0u64;
    while (option::is_some(&l10) && l11 < l3) {
        let l13 = option::borrow(&l10);
        let l8 = linked_table::borrow(&l16.bids, *l13);
        (&mut l14).push_back(*l13);
        (&mut l15).push_back(*(&l8.nft_type));
        (&mut l7).push_back(*(&l8.bid_id));
        (&mut l9).push_back(*(&l8.bid_price));
        (&mut l6).push_back(*(&l8.bid_at));
        (&mut l12).push_back(*(&l8.last_points_claimed_at));
        l10 = *(linked_table::next(&l16.bids, *l13));
        l11 = l11 + 1u64;
    };
    return (l14, l15, l7, l9, l6, l12, linked_table::length(&l16.bids))
}

public fun get_user_collection_bids_for_type(l0: &MarketPlaceStore, l1: address, l2: String, l3: u64, l4: u64): ( vector<ID>, vector<u64>, vector<u64>, vector<u64>, u64) {
    let l7 = vector[];
    let l9 = vector[];
    let l6 = vector[];
    let l12 = vector[];
    if (!(linked_table::contains(&l0.user_activity, l1))) {
        return (l7, l9, l6, l12, 0u64)
    };
    let l14 = linked_table::borrow(&l0.user_activity, l1);
    if (!(linked_table::contains(&l14.collection_bids, l2))) {
        return (l7, l9, l6, l12, 0u64)
    };
    let l10 = linked_table::borrow(&l14.collection_bids, l2);
    let l11 = l3;
    let l13 = l10.len();
    while (l11 < l13 && l11 < l4) {
        let l8 = &l10[l11];
        (&mut l7).push_back(*(&l8.bid_id));
        (&mut l9).push_back(*(&l8.bid_price));
        (&mut l6).push_back(*(&l8.bid_at));
        (&mut l12).push_back(*(&l8.last_points_claimed_at));
        l11 = l11 + 1u64;
    };
    return (l7, l9, l6, l12, l13)
}

public fun get_user_collection_bids_info(l0: &MarketPlaceStore, l1: address, l2: Option<String>, l3: u64): ( vector<String>, vector<u64>, u64) {
    let l11 = vector[];
    let l6 = vector[];
    if (!(linked_table::contains(&l0.user_activity, l1))) {
        return (l11, l6, 0u64)
    };
    let l4;
    let l12 = linked_table::borrow(&l0.user_activity, l1);
    if (option::is_some(&l2)) {
        l4 = l2;
        unstructured {
            goto 'label_32;
        }
    } else {
        l4 = *(linked_table::front(&l12.collection_bids));
        unstructured {
            goto 'label_32;
        }
    };
    let (l8, l9);
    /* block 32 */;
    l8 = l4;
    l9 = 0u64;
    while (option::is_some(&l8) && l9 < l3) {
        let l10 = option::borrow(&l8);
        let l7 = linked_table::borrow(&l12.collection_bids, *l10);
        (&mut l11).push_back(*l10);
        (&mut l6).push_back(l7.len());
        l8 = *(linked_table::next(&l12.collection_bids, *l10));
        l9 = l9 + 1u64;
    };
    return (l11, l6, linked_table::length(&l12.collection_bids))
}

public fun get_user_listings_info(l0: &MarketPlaceStore, l1: address, l2: Option<ID>, l3: u64): ( vector<ID>, vector<String>, vector<u64>, vector<u64>, u64) {
    let l11 = vector[];
    let l13 = vector[];
    let l12 = vector[];
    let l8 = vector[];
    if (!(linked_table::contains(&l0.user_activity, l1))) {
        return (l11, l13, l12, l8, 0u64)
    };
    let l4;
    let l14 = linked_table::borrow(&l0.user_activity, l1);
    if (option::is_some(&l2)) {
        l4 = l2;
        unstructured {
            goto 'label_38;
        }
    } else {
        l4 = *(linked_table::front(&l14.listings));
        unstructured {
            goto 'label_38;
        }
    };
    let (l6, l7);
    /* block 38 */;
    l6 = l4;
    l7 = 0u64;
    while (option::is_some(&l6) && l7 < l3) {
        let l10 = option::borrow(&l6);
        let l9 = linked_table::borrow(&l14.listings, *l10);
        (&mut l11).push_back(*l10);
        (&mut l13).push_back(*(&l9.nft_type));
        (&mut l12).push_back(*(&l9.price));
        (&mut l8).push_back(*(&l9.last_points_claimed_at));
        l6 = *(linked_table::next(&l14.listings, *l10));
        l7 = l7 + 1u64;
    };
    return (l11, l13, l12, l8, linked_table::length(&l14.listings))
}

public fun get_user_pending_claims(l0: &MarketPlaceStore, l1: address, l2: Option<ID>, l3: u64): ( vector<ID>, vector<String>, u64) {
    let l12 = vector[];
    let l11 = vector[];
    let l13 = vector[];
    if (!(linked_table::contains(&l0.pending_claims, l1))) {
        return (vector[], vector[], 0u64)
    };
    let l4;
    let l10 = linked_table::borrow(&l0.pending_claims, l1);
    if (option::is_some(&l2)) {
        l4 = l2;
        unstructured {
            goto 'label_34;
        }
    } else {
        l4 = *(linked_table::front(&l10.pending_claims));
        unstructured {
            goto 'label_34;
        }
    };
    let (l6, l8);
    /* block 34 */;
    l6 = l4;
    l8 = 0u64;
    while (option::is_some(&l6) && l8 < l3) {
        let l7 = option::borrow(&l6);
        let l9 = linked_table::borrow(&l10.pending_claims, *l7);
        (&mut l12).push_back(*l7);
        (&mut l11).push_back(*(&l9.nft_type));
        (&mut l13).push_back(*(&l9.price));
        l6 = *(linked_table::next(&l10.pending_claims, *l7));
        l8 = l8 + 1u64;
    };
    return (l12, l11, l8)
}

public fun get_user_trait_bids_info(l0: &MarketPlaceStore, l1: address, l2: Option<String>, l3: u64): ( vector<ID>, vector<String>, vector<u64>, vector<String>, u64) {
    let l7 = vector[];
    let l15 = vector[];
    let l8 = vector[];
    let l22 = vector[];
    let l17 = 0u64;
    if (!(linked_table::contains(&l0.user_activity, l1))) {
        return (l7, l15, l8, l22, 0u64)
    };
    let l4;
    let l24 = linked_table::borrow(&l0.user_activity, l1);
    if (option::is_some(&l2)) {
        l4 = l2;
        unstructured {
            goto 'label_40;
        }
    } else {
        l4 = *(linked_table::front(&l24.trait_bids));
        unstructured {
            goto 'label_40;
        }
    };
    let (l11, l9);
    /* block 40 */;
    l11 = l4;
    l9 = 0u64;
    while (option::is_some(&l11) && l9 < l3) {
        let l12 = option::borrow(&l11);
        let l20 = linked_table::borrow(&l24.trait_bids, *l12);
        let l13 = 0u64;
        while (l13 < l20.len() && l9 < l3) {
            let l19 = &l20[l13];
            (&mut l7).push_back(*(&l19.bid_id));
            (&mut l15).push_back(*(&l19.nft_type));
            (&mut l8).push_back(*(&l19.bid_price));
            let l23 = marketplace::create_trait_summary(*(&l19.trait_key1), *(&l19.trait_key2), *(&l19.trait_key3));
            (&mut l22).push_back(l23);
            l13 = l13 + 1u64;
            l9 = l9 + 1u64;
            l17 = l17 + 1u64;
        };
        l11 = *(linked_table::next(&l24.trait_bids, *l12));
    };
    let l16 = 0u64;
    let l10 = *(linked_table::front(&l24.trait_bids));
    while (option::is_some(&l10)) {
        let l14 = option::borrow(&l10);
        let l21 = linked_table::borrow(&l24.trait_bids, *l14);
        l16 = l16 + l21.len();
        l10 = *(linked_table::next(&l24.trait_bids, *l14));
    };
    let l18 = l16;
    return (l7, l15, l8, l22, l18)
}

fun init(l0: &mut TxContext) {
    transfer::public_transfer(CollectorCap { id: object::new(l0) }, tx_context::sender(freeze(l0)));
    transfer::public_transfer(AdminCap { id: object::new(l0) }, tx_context::sender(freeze(l0)));
    transfer::public_transfer(LaunchpadCap { id: object::new(l0) }, tx_context::sender(freeze(l0)));
    transfer::public_transfer(TraitBidsAdminCap { id: object::new(l0) }, tx_context::sender(freeze(l0)))
}

public fun init_marketplace(l0: &AdminCap, l1: PointsAdminCap, l2: &mut TxContext) {
    let (reg_1, reg_2) = kiosk::new(l2);
    let l13 = reg_2;
    let l14 = kiosk::kiosk_owner_cap_for(&l13);
    transfer::public_share_object(reg_1);
    let l3 = object::new(l2);
    let l8 = x2_balance::zero();
    let l9 = linked_table::new(l2);
    let l10 = linked_table::new(l2);
    let l11 = linked_table::new(l2);
    let l6 = linked_table::new(l2);
    transfer::share_object(MarketPlaceStore { id: l3, points_admin_cap: l1, is_permissionless: false, new_collection_fee: C7, commission_pct: C8, available_sui: l8, user_activity: l9, active_collections: l10, referrals: l11, kiosk_id: l14, escrow_kiosk_cap: l13, pending_claims: l6, version: C0 })
}

public fun is_permissionless(l0: &MarketPlaceStore): bool {
    return *(&l0.is_permissionless)
}

public fun launchpad_add_collection<T0: key + store>(l0: &mut MarketPlaceStore, l1: &LaunchpadCap, l2: bool, l3: u64, l4: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    assert!(l3 <= C4, C22);
    let l6 = type_name::into_string(type_name::get());
    assert!(!(linked_table::contains(&l0.active_collections, l6)), C15);
    linked_table::push_back(&mut l0.active_collections, l6, true);
    let l5 = CollectionMarketPlace { id: object::new(l4), listings: linked_table::new(l4), bids: linked_table::new(l4), collection_bids: linked_table::new(l4), sui_trait_bids_pool: x2_balance::zero(), are_trait_bids_enabled: false, lifetime_volume: 0u128, ion_points_enabled: l2, ion_collection_multiplier: l3, avg_sale_price: 0u64, recent_sale_prices: vector[] };
    dynamic_object_field::add(&mut l0.id, l6, l5);
    event::emit(UpdateActiveCollectionsEvent { nft_type: l6, boolean: true });
    event::emit(UpdateIONMultiplierEvent { nft_type: l6, is_ion_points_enabled: l2, ion_collection_multiplier: l3 })
}

public entry fun list<T0: key + store>(l0: &mut MarketPlaceStore, l1: &mut Kiosk, l2: &KioskOwnerCap, l3: ID, l4: u64, l5: &Clock, l6: &mut TxContext) {
    debug::print(&string::utf8(C31));
    marketplace::validation_check(freeze(l0));
    let l19 = tx_context::sender(freeze(l6));
    let l16 = object::id(freeze(l1));
    let l18 = type_name::into_string(type_name::get());
    let l20 = clock::timestamp_ms(l5);
    marketplace::validate_collection_exists(freeze(l0));
    let l15 = l4 * *(&l0.commission_pct) / 100u64;
    let l17 = Listing { seller: l19, kiosk_id: l16, nft_id: l3, cap: kiosk::list_with_purchase_cap(l1, l2, l3, l4 - l15, l6), price: l4, commission: l15, listed_at: l20 };
    linked_table::push_back(&mut (dynamic_object_field::borrow_mut(&mut l0.id, l18)).listings, l3, l17);
    marketplace::ensure_user_activity_exists(&mut l0.user_activity, l19, l6);
    linked_table::push_back(&mut (linked_table::borrow_mut(&mut l0.user_activity, l19)).listings, l3, ListingInfo { nft_type: l18, price: l4, listed_at: l20, last_points_claimed_at: l20 });
    debug::print(&string::utf8(C32));
    event::emit(ListEvent { nft_type: l18, seller: l19, kiosk_id: l16, nft_id: l3, price: l4, listed_at: l20 })
}

public entry fun make_bid<T0: key + store>(l0: &mut MarketPlaceStore, l1: Option<ID>, l2: u64, l3: Coin<SUI>, l4: &Clock, l5: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let l16 = tx_context::sender(freeze(l5));
    let l21 = type_name::into_string(type_name::get());
    let l18 = !(option::is_some(&l1));
    let l23 = clock::timestamp_ms(l4);
    debug::print(&string::utf8(C42));
    debug::print(&l16);
    debug::print(&l1);
    debug::print(&l2);
    debug::print(&l18);
    debug::print(&l21);
    marketplace::validate_collection_exists(freeze(l0));
    let l17 = dynamic_object_field::borrow_mut(&mut l0.id, l21);
    let l22 = coin::into_balance(l3);
    let l9 = ActiveBid { id: object::new(l5), bidder: l16, bid_price: l2, balance: x2_balance::split(&mut l22, l2), bid_at: l23 };
    let l14 = object::id(&l9);
    debug::print(&string::utf8(C43));
    debug::print(&l14);
    if (!(l18)) {
        let l19 = *(option::borrow(&l1));
        if (linked_table::contains(&l17.bids, l19)) {
            let l10 = linked_table::borrow_mut(&mut l17.bids, l19);
            assert!(!(linked_table::contains(&l10.bids, l16)), C16);
            linked_table::push_back(&mut l10.bids, l16, l9);
            unstructured {
                goto 'label_140;
            }
        } else {
            let l11 = ActiveBids { id: object::new(l5), bids: linked_table::new(l5) };
            linked_table::push_back(&mut (&mut l11).bids, l16, l9);
            linked_table::push_back(&mut l17.bids, l19, l11);
            unstructured {
                goto 'label_140;
            }
        }
    } else {
        if (linked_table::contains(&l17.collection_bids, l16)) {
            (linked_table::borrow_mut(&mut l17.collection_bids, l16)).push_back(l9);
            unstructured {
                goto 'label_140;
            }
        } else {
            let l12 = vector[];
            (&mut l12).push_back(l9);
            linked_table::push_back(&mut l17.collection_bids, l16, l12);
            unstructured {
                goto 'label_140;
            }
        }
    };
    /* block 140 */;
    let l15 = BidInfo { bid_id: l14, nft_type: l21, bid_price: l2, is_collection_bid: l18, bid_at: l23, last_points_claimed_at: l23 };
    marketplace::ensure_user_activity_exists(&mut l0.user_activity, l16, l5);
    let l24 = linked_table::borrow_mut(&mut l0.user_activity, l16);
    if (l18) {
        if (linked_table::contains(&l24.collection_bids, l21)) {
            (linked_table::borrow_mut(&mut l24.collection_bids, l21)).push_back(l15);
            unstructured {
                goto 'label_205;
            }
        } else {
            let l13 = vector[];
            (&mut l13).push_back(l15);
            linked_table::push_back(&mut l24.collection_bids, l21, l13);
            unstructured {
                goto 'label_205;
            }
        }
    } else {
        let l20 = *(option::borrow(&l1));
        assert!(!(linked_table::contains(&l24.bids, l20)), C16);
        linked_table::push_back(&mut l24.bids, l20, l15);
        unstructured {
            goto 'label_205;
        }
    };
    /* block 205 */;
    debug::print(&string::utf8(C44));
    event::emit(MakeBidEvent { bid_id: l14, nft_type: l21, buyer: l16, nft_id: l1, price: l2, is_collection_bid: l18, bid_at: l23 });
    helpers::destroy_or_transfer_balance(l22, l16, l5)
}

public fun make_trait_bid<T0: key + store, T1: key + store>(l0: &Clock, l1: &mut MarketPlaceStore, l2: Coin<SUI>, l3: Option<String>, l4: Option<vector<String>>, l5: Option<String>, l6: Option<vector<String>>, l7: Option<String>, l8: Option<vector<String>>, l9: &mut TxContext): ( ActiveTraitBid, T1, TraitBidsPotato) {
    marketplace::validation_check(freeze(l1));
    let l14 = tx_context::sender(freeze(l9));
    let l17 = type_name::into_string(type_name::get());
    let l18 = clock::timestamp_ms(l0);
    marketplace::validate_collection_exists(freeze(l1));
    let l15 = dynamic_object_field::borrow_mut(&mut l1.id, l17);
    assert!(dynamic_object_field::exists_(&l15.id, C1), C23);
    assert!(*(&l15.are_trait_bids_enabled), C30);
    let l11 = coin::value(&l2);
    let l12 = coin::into_balance(l2);
    let l10 = ActiveTraitBid { id: object::new(l9), bidder: l14, bid_price: l11, bid_at: l18, trait_key1: l3, trait_value1: l4, trait_key2: l5, trait_value2: l6, trait_key3: l7, trait_value3: l8 };
    let l13 = object::id(&l10);
    marketplace::ensure_user_activity_exists(&mut l1.user_activity, l14, l9);
    let l22 = linked_table::borrow_mut(&mut l1.user_activity, l14);
    let l19 = TraitBidInfo { bid_id: l13, nft_type: l17, bid_price: l11, trait_key1: l3, trait_value1: l4, trait_key2: l5, trait_value2: l6, trait_key3: l7, trait_value3: l8, bid_at: l18, last_points_claimed_at: l18 };
    if (linked_table::contains(&l22.trait_bids, l17)) {
        (linked_table::borrow_mut(&mut l22.trait_bids, l17)).push_back(l19);
        unstructured {
            goto 'label_122;
        }
    } else {
        let l20 = vector[];
        (&mut l20).push_back(l19);
        linked_table::push_back(&mut l22.trait_bids, l17, l20);
        unstructured {
            goto 'label_122;
        }
    };
    /* block 122 */;
    let l21 = dynamic_object_field::remove(&mut l15.id, C1);
    let l16 = TraitBidsPotato { id: object::id(&l21) };
    helpers::destroy_or_transfer_balance(l12, l14, l9);
    event::emit(TraitBidMadeEvent { nft_type: l17, bidder: l14, bid_id: l13, bid_amount: l11, trait_key1: l3, trait_value1: l4, trait_key2: l5, trait_value2: l6, trait_key3: l7, trait_value3: l8, bid_at: l18 });
    return (l10, l21, l16)
}

public fun permissionless_add_collection<T0: key + store>(l0: &mut MarketPlaceStore, l1: Coin<SUI>, l2: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    assert!(*(&l0.is_permissionless), C15);
    let l4 = type_name::into_string(type_name::get());
    assert!(!(linked_table::contains(&l0.active_collections, l4)), C15);
    assert!(coin::value(&l1) >= *(&l0.new_collection_fee), C13);
    let l5 = coin::into_balance(l1);
    let l6 = tx_context::sender(freeze(l2));
    helpers::destroy_or_transfer_balance(l5, l6, l2);
    linked_table::push_back(&mut l0.active_collections, l4, true);
    let l3 = CollectionMarketPlace { id: object::new(l2), listings: linked_table::new(l2), bids: linked_table::new(l2), collection_bids: linked_table::new(l2), sui_trait_bids_pool: x2_balance::zero(), are_trait_bids_enabled: false, lifetime_volume: 0u128, ion_points_enabled: false, ion_collection_multiplier: 0u64, avg_sale_price: 0u64, recent_sale_prices: vector[] };
    dynamic_object_field::add(&mut l0.id, l4, l3);
    event::emit(UpdateActiveCollectionsEvent { nft_type: l4, boolean: true })
}

public fun process_pending_claim<T0: key + store>(l0: &Clock, l1: &mut MarketPlaceStore, l2: &mut Kiosk, l3: &mut Kiosk, l4: &KioskOwnerCap, l5: ID, l6: &mut TxContext): TransferRequest<T0> {
    marketplace::validation_check(freeze(l1));
    let l10 = tx_context::sender(freeze(l6));
    let l16 = clock::timestamp_ms(l0);
    debug::print(&string::utf8(C60));
    debug::print(&l10);
    debug::print(&l5);
    assert!(linked_table::contains(&l1.pending_claims, l10), C27);
    let l14 = linked_table::borrow_mut(&mut l1.pending_claims, l10);
    assert!(linked_table::contains(&l14.pending_claims, l5), C28);
    let l13 = linked_table::remove(&mut l14.pending_claims, l5);
    assert!(*(&(&l13).buyer) == l10, C25);
    let PendingClaim { buyer: reg_53, nft_type: reg_54, price: reg_55 } = l13;
    debug::print(&string::utf8(C61));
    debug::print(&l10);
    assert!(kiosk::kiosk_owner_cap_for(l4) == object::id(freeze(l3)), C19);
    let l15 = kiosk::list_with_purchase_cap(l2, &l1.escrow_kiosk_cap, l5, 0u64, l6);
    let (reg_84, reg_85) = kiosk::purchase_with_cap(l2, l15, coin::from_balance(x2_balance::zero(), l6));
    kiosk::place(l3, l4, reg_84);
    debug::print(&string::utf8(C62));
    event::emit(NFTClaimedEvent { nft_type: reg_54 : 0x1::ascii::String, nft_id: l5, buyer: l10, buyer_kiosk: object::id(freeze(l3)), claimed_at: l16 });
    return reg_85
}

public fun remove_trait_bidding_support<T0: key + store, T1: key + store>(l0: &mut MarketPlaceStore, l1: &TraitBidsAdminCap, l2: &mut TxContext): T1 {
    marketplace::validation_check(freeze(l0));
    let l4 = type_name::into_string(type_name::get());
    assert!(linked_table::contains(&l0.active_collections, l4), C15);
    assert!(dynamic_object_field::exists_(&l0.id, l4), C15);
    let l3 = dynamic_object_field::borrow_mut(&mut l0.id, l4);
    *(&mut l3.are_trait_bids_enabled) = false;
    event::emit(UpdateTraitBiddingSupportEvent { nft_type: l4, are_trait_bids_enabled: false });
    return dynamic_object_field::remove(&mut l3.id, C1)
}

public fun switch_trait_bidding_support<T0: key + store>(l0: &mut MarketPlaceStore, l1: &TraitBidsAdminCap, l2: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let l4 = type_name::into_string(type_name::get());
    assert!(linked_table::contains(&l0.active_collections, l4), C15);
    assert!(dynamic_object_field::exists_(&l0.id, l4), C15);
    let l3 = dynamic_object_field::borrow_mut(&mut l0.id, l4);
    *(&mut l3.are_trait_bids_enabled) = !(*(&l3.are_trait_bids_enabled));
    event::emit(UpdateTraitBiddingSupportEvent { nft_type: l4, are_trait_bids_enabled: *(&l3.are_trait_bids_enabled) })
}

public fun unlist<T0: key + store>(l0: &mut MarketPlaceStore, l1: &mut Kiosk, l2: ID, l3: &mut AnimaIONs, l4: &Clock, l5: &mut AnimaChef, l6: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let l28 = tx_context::sender(freeze(l6));
    let l24 = type_name::into_string(type_name::get());
    let l31 = clock::timestamp_ms(l4);
    debug::print(&string::utf8(C33));
    assert!(linked_table::contains(&l0.user_activity, l28), C10);
    let l21 = linked_table::borrow_mut(&mut l0.user_activity, l28);
    assert!(linked_table::contains(&l21.listings, l2), C11);
    let l23 = linked_table::remove(&mut l21.listings, l2);
    let l18 = dynamic_object_field::borrow_mut(&mut l0.id, l24);
    assert!(linked_table::contains(&l18.listings, l2), C11);
    let l17;
    let l22 = linked_table::remove(&mut l18.listings, l2);
    let l29 = l31 - *(&(&l23).last_points_claimed_at);
    debug::print(&string::utf8(C34));
    debug::print(&l29);
    if (*(&l18.ion_points_enabled)) {
        let l11;
        let l30 = helpers::calculate_time_multiplier(l29, false);
        let l26 = helpers::calculate_listing_proximity_multiplier(*(&(&l22).price), *(&l18.avg_sale_price));
        if (*(&l18.ion_collection_multiplier) == 0u64) {
            l11 = C5;
            unstructured {
                goto 'label_140;
            }
        } else {
            l11 = *(&l18.ion_collection_multiplier);
            unstructured {
                goto 'label_140;
            }
        };
        /* block 140 */;
        let l19 = l11;
        let l25 = helpers::calculate_ion_points(*(&(&l22).price), l19, l26, l30);
        debug::print(&string::utf8(C35));
        debug::print(&string::utf8(C36));
        debug::print(&l30);
        debug::print(&string::utf8(C37));
        debug::print(&l26);
        debug::print(&string::utf8(C38));
        debug::print(&l19);
        debug::print(&string::utf8(C39));
        debug::print(&l25);
        marketplace::award_ion_points_with_referral(l28, l0, l3, l25, l4, l5);
        l17 = l25;
        unstructured {
            goto 'label_205;
        }
    } else {
        l17 = 0u64;
        unstructured {
            goto 'label_205;
        }
    };
    /* block 205 */;
    let l20 = l17;
    debug::print(&string::utf8(C40));
    debug::print(&l20);
    event::emit(UnlistEvent { nft_type: l24, seller: l28, nft_id: l2, kiosk_id: object::id(freeze(l1)), price: *(&(&l22).price), unlisted_at: l31, ion_points_awarded: l20 });
    let Listing { seller: reg_150, kiosk_id: reg_151, nft_id: reg_152, cap: reg_153, price: reg_154, commission: reg_155, listed_at: reg_156 } = l22;
    kiosk::return_purchase_cap(l1, reg_153 : 0x2::kiosk::PurchaseCap<T0>);
    debug::print(&string::utf8(C41))
}

public fun update_active_collections<T0: key + store>(l0: &mut MarketPlaceStore, l1: &AdminCap, l2: bool, l3: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    let l7 = type_name::into_string(type_name::get());
    if (l2) {
        if (!(linked_table::contains(&l0.active_collections, l7))) {
            linked_table::push_back(&mut l0.active_collections, l7, true);
            unstructured {
                goto 'label_28;
            }
        } else {
            *(linked_table::borrow_mut(&mut l0.active_collections, l7)) = true;
            unstructured {
                goto 'label_28;
            }
        };
        /* block 28 */;
        if (!(dynamic_object_field::exists_(&l0.id, l7))) {
            let l6 = CollectionMarketPlace { id: object::new(l3), listings: linked_table::new(l3), bids: linked_table::new(l3), collection_bids: linked_table::new(l3), sui_trait_bids_pool: x2_balance::zero(), are_trait_bids_enabled: false, lifetime_volume: 0u128, ion_points_enabled: false, ion_collection_multiplier: 0u64, avg_sale_price: 0u64, recent_sale_prices: vector[] };
            dynamic_object_field::add(&mut l0.id, l7, l6);
            unstructured {
                goto 'label_72;
            }
        } else {
            unstructured {
                goto 'label_72;
            }
        }
    } else {
        *(linked_table::borrow_mut(&mut l0.active_collections, l7)) = false;
        unstructured {
            goto 'label_72;
        }
    };
    /* block 72 */;
    event::emit(UpdateActiveCollectionsEvent { nft_type: l7, boolean: l2 })
}

fun update_collection_avg_price<T0: key + store>(l0: &mut CollectionMarketPlace<T0>, l1: u64) {
    if (&l0.recent_sale_prices.len() >= C3) {
        unstructured {
            goto 'label_11;
        }
    } else {
        unstructured {
            goto 'label_11;
        }
    };
    let (l2, l3);
    /* block 11 */;
    (&mut l0.recent_sale_prices).push_back(l1);
    l3 = 0u64;
    l2 = 0u64;
    while (l2 < &l0.recent_sale_prices.len()) {
        l3 = l3 + *(&(&l0.recent_sale_prices)[l2]);
        l2 = l2 + 1u64;
    };
    *(&mut l0.avg_sale_price) = l3 / &l0.recent_sale_prices.len()
}

public fun update_collection_fee(l0: &mut MarketPlaceStore, l1: &AdminCap, l2: u64) {
    marketplace::validation_check(freeze(l0));
    *(&mut l0.new_collection_fee) = l2
}

public fun update_commission_pct(l0: &mut MarketPlaceStore, l1: &AdminCap, l2: u64) {
    marketplace::validation_check(freeze(l0));
    assert!(l2 <= C3, C12);
    *(&mut l0.commission_pct) = l2
}

public fun update_ion_point_multiplier<T0: key + store>(l0: &mut MarketPlaceStore, l1: &AdminCap, l2: bool, l3: u64) {
    marketplace::validation_check(freeze(l0));
    assert!(l3 <= C4, C22);
    let l5 = type_name::into_string(type_name::get());
    let l4 = dynamic_object_field::borrow_mut(&mut l0.id, l5);
    *(&mut l4.ion_points_enabled) = l2;
    *(&mut l4.ion_collection_multiplier) = l3;
    event::emit(UpdateIONMultiplierEvent { nft_type: l5, is_ion_points_enabled: l2, ion_collection_multiplier: l3 })
}

public fun update_module_version(l0: &mut MarketPlaceStore) {
    assert!(*(&l0.version) < C0, C14);
    *(&mut l0.version) = C0
}

public fun update_permissionless_status(l0: &mut MarketPlaceStore, l1: &AdminCap, l2: bool, l3: &mut TxContext) {
    marketplace::validation_check(freeze(l0));
    *(&mut l0.is_permissionless) = l2;
    event::emit(UpdatePermissionlessStatusEvent { is_permissionless: l2 })
}

fun validate_collection_exists<T0: key + store>(l0: &MarketPlaceStore) {
    let l1 = type_name::into_string(type_name::get());
    assert!(linked_table::contains(&l0.active_collections, l1), C15);
    assert!(*(linked_table::borrow(&l0.active_collections, l1)), C15);
    assert!(dynamic_object_field::exists_(&l0.id, l1), C15)
}

fun validation_check(l0: &MarketPlaceStore) {
    assert!(*(&l0.version) == C0, C9)
}

