Command `build -v -p ./C`:
BUILDING Foo
External Command `mv ./C/sources/Foo.move ./C/sources/Foo.move_old`:
External Command `rm -rf ./C/build/Foo/sources`:
Command `build -v -p ./B`:
INCLUDING DEPENDENCY Foo
BUILDING Bar
External Command `mv ./B/sources/Bar.move ./B/sources/Bar.move_old`:
External Command `rm -rf ./B/build/Bar/sources`:
Command `test`:
INCLUDING DEPENDENCY Bar
INCLUDING DEPENDENCY Foo
INCLUDING DEPENDENCY MoveStdlib
BUILDING A
Running Move unit tests
[ PASS    ] 0x2::A::foo_test
Test result: OK. Total tests: 1; passed: 1; failed: 0
