Command `build`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Command `disassemble --package MoveStdlib --name address`:
// Move bytecode v6
module 1.address {

public length(): u64 {
B0:
	0: LdU64(32)
	1: Ret
}

}

Command `info`:
PackageBasics
├── std:0x1
└── MoveStdlib
    └── std:0x1

Command `test double_two`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Running Move unit tests
[ PASS    ] std::AModule::double_two
Test result: OK. Total tests: 1; passed: 1; failed: 0
Command `test one_one`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Running Move unit tests
[ PASS    ] std::AModuleTests::double_one_one
Test result: OK. Total tests: 1; passed: 1; failed: 0
