Command `build`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Command `test --coverage --threads 1`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Running Move unit tests
[ PASS    ] std::AModule::double_three
[ PASS    ] std::AModule::double_two
[ PASS    ] std::AModuleTests::double_one_one
[ PASS    ] std::AModuleTests::double_three
[ PASS    ] std::AModuleTests::double_zero_zero
[ PASS    ] std::AModuleTests::double_zero_zero_wrong
Test result: OK. Total tests: 6; passed: 6; failed: 0
Command `coverage summary --summarize-functions`:
+-------------------------+
| Move Coverage Summary   |
+-------------------------+
Module 0000000000000000000000000000000000000000000000000000000000000001::AModule
	fun double_except_three
		total: 11
		covered: 11
		% coverage: 100.00
>>> % Module coverage: 100.00
+-------------------------+
| % Move Coverage: 100.00  |
+-------------------------+
Command `coverage source --module AModule`:
module std::AModule {

    /// x was three
    const E_IS_THREE: u64 = 0;

    public fun double_except_three(x: u64): u64 {
        assert!(x != 3, E_IS_THREE);
        x * x
    }

    #[test]
    fun double_two() {
        assert!(double_except_three(4) == 16, 0)
    }

    #[test]
    #[expected_failure]
    fun double_three() {
        double_except_three(3);
    }
}
Command `coverage bytecode --module AModule`:
// Move bytecode v6
module 1.AModule {

public double_except_three(x#0#0: u64): u64 {
B0:
[32m[6]	0: CopyLoc[0](x#0#0: u64)[39m
[32m[6]	1: LdU64(3)[39m
[32m[6]	2: Neq[39m
[32m[6]	3: BrFalse(5)[39m
B1:
[32m[4]	4: Branch(7)[39m
B2:
[32m[2]	5: LdConst[0](u64: 0)[39m
[32m[2]	6: Abort[39m
B3:
[32m[4]	7: CopyLoc[0](x#0#0: u64)[39m
[32m[4]	8: MoveLoc[0](x#0#0: u64)[39m
[32m[4]	9: Mul[39m
[32m[4]	10: Ret[39m
}

Constants [
	0 => u64: 0
]
}

Command `disassemble --package MoveStdlib --name address`:
// Move bytecode v6
module 1.address {

public length(): u64 {
B0:
	0: LdU64(32)
	1: Ret
}

}

Command `info`:
PackageBasics
├── std:0x1
└── MoveStdlib
    └── std:0x1

Command `test double_two`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Running Move unit tests
[ PASS    ] std::AModule::double_two
Test result: OK. Total tests: 1; passed: 1; failed: 0
Command `test one_one`:
INCLUDING DEPENDENCY MoveStdlib
BUILDING PackageBasics
Running Move unit tests
[ PASS    ] std::AModuleTests::double_one_one
Test result: OK. Total tests: 1; passed: 1; failed: 0
