processed 1 task

task 0 'publish'. lines 4-17:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"0000000000000000000000000000000000000000000000000000000000000000::m::init at offset 1. Cannot call a module's 'init' function from another Move function\"), command: None } }" }
