processed 2 tasks

task 0 'publish'. lines 4-11:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("Expected exactly one parameter for _::m::init  of type &mut sui::tx_context::TxContext") } }

task 1 'publish'. lines 14-21:
Error: Transaction Effects Status: MiscellaneousError
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: ModuleVerificationFailure, source: Some("Expected exactly one parameter for _::m::init  of type &mut sui::tx_context::TxContext") } }
