processed 3 tasks

task 0 'publish'. lines 4-11:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"0000000000000000000000000000000000000000000000000000000000000000::m. 'init' function must be private\"), command: None } }" }

task 1 'publish'. lines 13-20:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"0000000000000000000000000000000000000000000000000000000000000000::m. 'init' function must be private\"), command: None } }" }

task 2 'publish'. lines 22-29:
Error: Error checking transaction input objects: PackageVerificationTimedout { err: "Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some(\"0000000000000000000000000000000000000000000000000000000000000000::m. 'init' function must be private\"), command: None } }" }
