Command `migrate`:
Package toml does not specify an edition. As of 2024, Move requires all packages to define a language edition.

Please select one of the following editions:

1) 2024.beta
2) legacy

Selection (default=1): 

Would you like the Move compiler to migrate your code to Move 2024? (Y/n) 
Generated changes . . .
INCLUDING DEPENDENCY MoveStdlib
BUILDING A
Unable to generate migration patch due to compilation errors.
Please fix the errors in your current edition before attempting to migrate.
error[E00003]: unable to migrate
  ┌─ sources/mod_friend.move:3:5
  │  
3 │ ╭     friend // why
4 │ │     A::n;
  │ ╰─────────^ Unable to migrate. Cannot remove 'friend' that spans multiple lines

error[E00003]: unable to migrate
  ┌─ sources/mod_pub_friend.move:2:5
  │  
2 │ ╭     public( // why folks, why
3 │ │         friend
4 │ │     ) fun t() {}
  │ ╰─────^ Unable to migrate 'public(friend)' that spans multiple lines

Error: Compilation error
External Command `diff Move.toml Move.toml.expected`:
5a6
> edition = "2024.beta"
