processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 14-87:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 11263200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 89-89:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 91-91:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 4 'run'. lines 93-93:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("Object"), type_params: [] })] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'run'. lines 95-95:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 97-97:
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'run'. lines 99-99:
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M2"), name: Identifier("Object"), type_params: [] })] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 8 'create-checkpoint'. lines 101-101:
Checkpoint created: 1

task 9 'run-graphql'. lines 103-123:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventB<0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::Object>"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NiwiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M2::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NywiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M2::EventB<0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M2::Object>"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "3"
            },
            "bcs": "AwAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 10 'run-graphql'. lines 125-145:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventB<0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::Object>"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NiwiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M2::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NywiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M2"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M2::EventB<0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M2::Object>"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "3"
            },
            "bcs": "AwAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 147-167:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventB<0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::Object>"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 12 'run-graphql'. lines 169-189:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 13 'run-graphql'. lines 191-211:
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MH0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::EventB<0x7bb8e3ce9fdeded7ea1520cd10cd0f9b615a6d5fbf8e06796963ea94672ca613::M1::Object>"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 213-233:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}

task 15 'run-graphql'. lines 235-255:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}

task 16 'run-graphql'. lines 257-277:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Failed to parse \"String\": Invalid filter, expected: package[::module[::type[<type_params>]]] or primitive type (occurred while parsing \"EventFilter\")",
      "locations": [
        {
          "line": 2,
          "column": 18
        }
      ],
      "path": [
        "events"
      ]
    }
  ]
}
