processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 14-87:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 11263200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 89-89:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 91-91:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 4 'run'. lines 93-93:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("Object"), type_params: [] })] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'run'. lines 95-95:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'run'. lines 97-97:
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'run'. lines 99-99:
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventB"), type_params: [Struct(StructTag { address: Test, module: Identifier("M2"), name: Identifier("Object"), type_params: [] })] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 8 'create-checkpoint'. lines 101-101:
Checkpoint created: 1

task 9 'run-graphql'. lines 103-122:
Response: {
  "data": {
    "eventConnection": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventA"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "0"
          },
          "bcs": "AAAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventB<0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::Object>"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "1"
          },
          "bcs": "AQAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M2::EventA"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "2"
          },
          "bcs": "AgAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M2::EventB<0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M2::Object>"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "3"
          },
          "bcs": "AwAAAAAAAAA="
        }
      ]
    }
  }
}

task 10 'run-graphql'. lines 124-143:
Response: {
  "data": {
    "eventConnection": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventA"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "0"
          },
          "bcs": "AAAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventB<0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::Object>"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "1"
          },
          "bcs": "AQAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M2::EventA"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "2"
          },
          "bcs": "AgAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M2::EventB<0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M2::Object>"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "3"
          },
          "bcs": "AwAAAAAAAAA="
        }
      ]
    }
  }
}

task 11 'run-graphql'. lines 145-164:
Response: {
  "data": {
    "eventConnection": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventA"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "0"
          },
          "bcs": "AAAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventB<0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::Object>"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "1"
          },
          "bcs": "AQAAAAAAAAA="
        }
      ]
    }
  }
}

task 12 'run-graphql'. lines 166-185:
Response: {
  "data": {
    "eventConnection": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventA"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "0"
          },
          "bcs": "AAAAAAAAAAA="
        }
      ]
    }
  }
}

task 13 'run-graphql'. lines 187-206:
Response: {
  "data": {
    "eventConnection": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M1"
          },
          "type": {
            "repr": "0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventB<0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::Object>"
          },
          "senders": [
            {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "json": {
            "new_value": "1"
          },
          "bcs": "AQAAAAAAAAA="
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 208-227:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Invalid type provided as filter: Invalid struct type: 0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::M1::EventB<. Got error: unexpected end of tokens",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "eventConnection"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 15 'run-graphql'. lines 229-248:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Invalid type provided as filter: Invalid format in '::M1' - if '::' is present, there must be a non-empty string on both sides. Expected format like 'package[::module[::type[<type_params>]]]'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "eventConnection"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 16 'run-graphql'. lines 250-269:
Response: {
  "data": null,
  "errors": [
    {
      "message": "Invalid type provided as filter: Invalid format in '0xc6d87e1b811586a8f918c4da6008004b6b3fc6479236a8047c9b0dfab4f68ebd::' - if '::' is present, there must be a non-empty string on both sides. Expected format like 'package[::module[::type[<type_params>]]]'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "eventConnection"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
