processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-22:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4818400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 24-24:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 26-26:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'create-checkpoint'. lines 28-28:
Checkpoint created: 1

task 5 'run-graphql'. lines 30-50:
Response: {
  "data": {
    "eventConnection": {
      "edges": [
        {
          "cursor": "2:0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "3:0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "3:1",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 6 'run-graphql'. lines 52-72:
Response: {
  "data": {
    "eventConnection": {
      "edges": [
        {
          "cursor": "3:0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "3:1",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 7 'run-graphql'. lines 74-94:
Response: {
  "data": {
    "eventConnection": {
      "edges": [
        {
          "cursor": "2:0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "3:0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 8 'run-graphql'. lines 96-116:
Response: {
  "data": {
    "eventConnection": {
      "edges": [
        {
          "cursor": "3:0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "3:1",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0xa1b4b5e41ec2fd82f4c4f67a3e5212aa3a3e6e30c3a74c4ed45bef3e3b20387d::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}
