processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-22:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4818400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 24-24:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 26-26:
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [1, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'create-checkpoint'. lines 28-28:
Checkpoint created: 1

task 5 'run-graphql'. lines 30-54:
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 6 'run-graphql'. lines 56-80:
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 7 'run-graphql'. lines 82-106:
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": false,
        "hasNextPage": true
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MiwiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "0"
            },
            "bcs": "AAAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        }
      ]
    }
  }
}

task 8 'run-graphql'. lines 108-132:
Response: {
  "data": {
    "events": {
      "pageInfo": {
        "hasPreviousPage": true,
        "hasNextPage": false
      },
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "1"
            },
            "bcs": "AQAAAAAAAAA="
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "sendingModule": {
              "name": "M1"
            },
            "type": {
              "repr": "0x7667d0acecb78e05aa09ae8fb02a292da56f0c67cf445b7b4fd8950a60b17ea6::M1::EventA"
            },
            "sender": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "json": {
              "new_value": "2"
            },
            "bcs": "AgAAAAAAAAA="
          }
        }
      ]
    }
  }
}
