processed 17 tasks

init:
A: object(0,0)

task 1, lines 10-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4795600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::no_emit --sender A --args 0
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::emit_2 --sender A --args 2
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4, line 32:
//# run Test::M1::emit_2 --sender A --args 4
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [4, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [5, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5, line 34:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 36-43:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "4U25VGAB2VkWrQVcYHmhcJ1auBMoR6wGJ1XkAVWThvRR"
        },
        {
          "digest": "8f5zsvxPTNvfW9HoQReViqMC8aWKfwQvP2UFt2uWxQs3"
        },
        {
          "digest": "5qVugAqZ6ANMTadHevvJaUyU2c65paKm1n6UGCJHTAbD"
        },
        {
          "digest": "Ar4ascrErFfQAEPEcNxhMfJok8FvkhSocVjPBm9vUQa2"
        },
        {
          "digest": "5bEKPHKVsqMpFrsjQXnkZc8R8naYjoKs9oErx8rc4CdC"
        }
      ]
    }
  }
}

task 7, lines 45-55:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "2"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "3"
            }
          }
        }
      ]
    }
  }
}

task 8, lines 57-68:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 9, lines 70-83:
//# run-graphql --cursors {"tx":1,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 10, lines 86-96:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "4"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "5"
            }
          }
        }
      ]
    }
  }
}

task 11, lines 98-108:
//# run-graphql --cursors {"tx":4,"e":0,"c":1}
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "5"
            }
          }
        }
      ]
    }
  }
}

task 12, lines 111-121:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "2"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6MywiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "3"
            }
          }
        }
      ]
    }
  }
}

task 13, lines 123-134:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6MywiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "2"
            }
          }
        }
      ]
    }
  }
}

task 14, lines 136-149:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 15, lines 152-162:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "4"
            }
          }
        },
        {
          "cursor": "eyJ0eCI6NCwiZSI6MSwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "5"
            }
          }
        }
      ]
    }
  }
}

task 16, lines 164-174:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": [
        {
          "cursor": "eyJ0eCI6NCwiZSI6MCwiYyI6MX0",
          "node": {
            "json": {
              "new_value": "4"
            }
          }
        }
      ]
    }
  }
}
