processed 12 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-37:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 6604400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 39:
//# run Test::M2::emit_emit_a --sender A --args 20
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [20, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 41:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 43-60:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M1::EventA"
          },
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "json": {
            "new_value": "20"
          },
          "bcs": "FAAAAAAAAAA="
        }
      ]
    }
  }
}

task 5, line 62:
//# run Test::M2::emit_b --sender A --args 42
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: A, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventB"), type_params: [] }, contents: [42, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6, line 64:
//# run Test::M2::emit_b --sender B --args 43
events: Event { package_id: Test, transaction_module: Identifier("M2"), sender: B, type_: StructTag { address: Test, module: Identifier("M2"), name: Identifier("EventB"), type_params: [] }, contents: [43, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7, line 66:
//# create-checkpoint
Checkpoint created: 2

task 8, lines 68-85:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M1::EventA"
          },
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "json": {
            "new_value": "20"
          },
          "bcs": "FAAAAAAAAAA="
        }
      ]
    }
  }
}

task 9, lines 87-104:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M2::EventB"
          },
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "json": {
            "new_value": "42"
          },
          "bcs": "KgAAAAAAAAA="
        }
      ]
    }
  }
}

task 10, lines 106-123:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M1::EventA"
          },
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "json": {
            "new_value": "20"
          },
          "bcs": "FAAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M2::EventB"
          },
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "json": {
            "new_value": "42"
          },
          "bcs": "KgAAAAAAAAA="
        }
      ]
    }
  }
}

task 11, lines 125-142:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M1::EventA"
          },
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "json": {
            "new_value": "20"
          },
          "bcs": "FAAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M2::EventB"
          },
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "json": {
            "new_value": "42"
          },
          "bcs": "KgAAAAAAAAA="
        },
        {
          "sendingModule": {
            "name": "M2"
          },
          "type": {
            "repr": "0x6edb181eb03cea19a3c4b09d2d6b5de8d0a741df186d072d18b2030eb36faee1::M2::EventB"
          },
          "sender": {
            "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
          },
          "json": {
            "new_value": "43"
          },
          "bcs": "KwAAAAAAAAA="
        }
      ]
    }
  }
}
